# N1 compound-noun batch sourced from japanesetest4you.com's "JLPT N1
# Vocabulary List" (https://japanesetest4you.com/jlpt-n1-vocabulary-list/)
# - jlptsensei.com's own dedicated N1 noun/verb/adjective sublists turned
# out to be too sparse (11-17 entries each) to be useful, unlike their N3
# lists, so this source was used instead for N1. Cross-checked against the
# existing 1380-word dataset: 24 of the ~147 raw candidates gathered were
# already present, 123 were genuinely new 2-3 pure-kanji compounds. No
# example sentences in the source either, so every one was hand-authored,
# same as the N3 web batch.
#
# Each entry: (kanji, reading, meaning_id, category, example_ja,
#              example_romaji, example_id)
N1_WORDS = [
    ("悪事", "あくじ", "kejahatan/perbuatan jahat", "konsep_umum",
     "悪事を働きました。", "Akuji o hatarakimashita.", "Melakukan kejahatan."),
    ("圧倒", "あっとう", "mengalahkan telak/menguasai", "konsep_umum",
     "相手を圧倒しました。", "Aite o attou shimashita.", "Mengalahkan lawan secara telak."),
    ("圧力", "あつりょく", "tekanan", "konsep_umum",
     "圧力をかけます。", "Atsuryoku o kakemasu.", "Memberikan tekanan."),
    ("買収", "ばいしゅう", "akuisisi/pengambilalihan", "pekerjaan_kantor",
     "会社を買収しました。", "Kaisha o baishuu shimashita.", "Mengakuisisi perusahaan."),
    ("爆弾", "ばくだん", "bom", "konsep_umum",
     "爆弾が見つかりました。", "Bakudan ga mitsukarimashita.", "Bom ditemukan."),
    ("弁護", "べんご", "pembelaan (hukum)", "pekerjaan_kantor",
     "弁護士が弁護します。", "Bengoshi ga bengo shimasu.", "Pengacara melakukan pembelaan."),
    ("弁解", "べんかい", "pembelaan diri/dalih", "konsep_umum",
     "弁解する必要はありません。", "Benkai suru hitsuyou wa arimasen.", "Tidak perlu membela diri."),
    ("弁明", "べんめい", "penjelasan/pembelaan", "konsep_umum",
     "弁明の機会を与えます。", "Benmei no kikai o ataemasu.", "Memberikan kesempatan untuk menjelaskan diri."),
    ("貧乏", "びんぼう", "kemiskinan", "konsep_umum",
     "貧乏な生活をしています。", "Binbou na seikatsu o shite imasu.", "Menjalani hidup miskin."),
    ("敏感", "びんかん", "sensitif", "perasaan_emosi",
     "肌が敏感です。", "Hada ga binkan desu.", "Kulitnya sensitif."),
    ("微笑", "びしょう", "senyuman", "ekspresi_wajah",
     "微笑を浮かべました。", "Bishou o ukabemashita.", "Menampilkan senyuman."),
    ("膨張", "ぼうちょう", "pemuaian/ekspansi", "konsep_umum",
     "経済が膨張しています。", "Keizai ga bouchou shite imasu.", "Ekonomi berekspansi."),
    ("防衛", "ぼうえい", "pertahanan", "konsep_umum",
     "国を防衛します。", "Kuni o bouei shimasu.", "Mempertahankan negara."),
    ("暴力", "ぼうりょく", "kekerasan", "konsep_umum",
     "暴力は許されません。", "Bouryoku wa yurusaremasen.", "Kekerasan tidak diperbolehkan."),
    ("侮辱", "ぶじょく", "penghinaan", "perasaan_emosi",
     "侮辱された気がします。", "Bujoku sareta ki ga shimasu.", "Merasa dihina."),
    ("分配", "ぶんぱい", "pembagian", "konsep_umum",
     "利益を分配します。", "Rieki o bunpai shimasu.", "Membagi keuntungan."),
    ("分散", "ぶんさん", "penyebaran/dispersi", "konsep_umum",
     "リスクを分散します。", "Risuku o bunsan shimasu.", "Menyebarkan risiko."),
    ("文書", "ぶんしょ", "dokumen", "pekerjaan_kantor",
     "文書を作成します。", "Bunsho o sakusei shimasu.", "Membuat dokumen."),
    ("無礼", "ぶれい", "tidak sopan", "perasaan_emosi",
     "無礼な態度でした。", "Burei na taido deshita.", "Sikapnya tidak sopan."),
    ("武装", "ぶそう", "persenjataan", "konsep_umum",
     "武装した兵士がいます。", "Busou shita heishi ga imasu.", "Ada tentara bersenjata."),
    ("着手", "ちゃくしゅ", "mulai mengerjakan", "pekerjaan_kantor",
     "計画に着手します。", "Keikaku ni chakushu shimasu.", "Mulai mengerjakan rencana."),
    ("蓄積", "ちくせき", "akumulasi/penumpukan", "konsep_umum",
     "経験を蓄積します。", "Keiken o chikuseki shimasu.", "Mengakumulasi pengalaman."),
    ("賃金", "ちんぎん", "upah", "pekerjaan_kantor",
     "賃金が上がりました。", "Chingin ga agarimashita.", "Upah naik."),
    ("沈黙", "ちんもく", "keheningan/diam", "konsep_umum",
     "沈黙を守ります。", "Chinmoku o mamorimasu.", "Menjaga kediaman."),
    ("知性", "ちせい", "kecerdasan intelek", "konsep_umum",
     "彼は知性があります。", "Kare wa chisei ga arimasu.", "Dia memiliki kecerdasan."),
    ("秩序", "ちつじょ", "ketertiban", "konsep_umum",
     "秩序を守ります。", "Chitsujo o mamorimasu.", "Menjaga ketertiban."),
    ("直面", "ちょくめん", "berhadapan (dengan masalah)", "konsep_umum",
     "困難に直面しています。", "Konnan ni chokumen shite imasu.", "Menghadapi kesulitan."),
    ("挑戦", "ちょうせん", "tantangan", "hobi_aktivitas",
     "新しいことに挑戦します。", "Atarashii koto ni chousen shimasu.", "Menantang diri dengan hal baru."),
    ("調達", "ちょうたつ", "pengadaan (dana/barang)", "pekerjaan_kantor",
     "資金を調達します。", "Shikin o choutatsu shimasu.", "Mengumpulkan dana."),
    ("中断", "ちゅうだん", "terhenti sementara", "konsep_umum",
     "会議が中断しました。", "Kaigi ga chuudan shimashita.", "Rapat terhenti sementara."),
    ("忠実", "ちゅうじつ", "setia/loyal", "keluarga_hubungan",
     "忠実な部下です。", "Chuujitsu na buka desu.", "Bawahan yang loyal."),
    ("忠告", "ちゅうこく", "nasihat/peringatan", "konsep_umum",
     "忠告を聞きます。", "Chuukoku o kikimasu.", "Mendengarkan nasihat."),
    ("打撃", "だげき", "pukulan (dampak)", "konsep_umum",
     "経済に打撃を与えました。", "Keizai ni dageki o ataemashita.", "Memberikan dampak pada ekonomi."),
    ("大胆", "だいたん", "berani/nekat", "perasaan_emosi",
     "大胆な決断をしました。", "Daitan na ketsudan o shimashita.", "Membuat keputusan yang berani."),
    ("団結", "だんけつ", "persatuan", "konsep_umum",
     "みんなで団結します。", "Minna de danketsu shimasu.", "Kita semua bersatu."),
    ("脱出", "だっしゅつ", "melarikan diri/lolos", "konsep_umum",
     "火事から脱出しました。", "Kaji kara dasshutsu shimashita.", "Melarikan diri dari kebakaran."),
    ("土台", "どだい", "landasan/fondasi", "konsep_umum",
     "土台を作ります。", "Dodai o tsukurimasu.", "Membuat fondasi."),
    ("独裁", "どくさい", "kediktatoran", "negara_kota",
     "独裁政権が続いています。", "Dokusai seiken ga tsuzuite imasu.", "Rezim diktator masih berlanjut."),
    ("独占", "どくせん", "monopoli", "pekerjaan_kantor",
     "市場を独占しています。", "Shijou o dokusen shite imasu.", "Memonopoli pasar."),
    ("度胸", "どきょう", "keberanian/nyali", "perasaan_emosi",
     "度胸がありますね。", "Dokyou ga arimasu ne.", "Kamu punya nyali ya."),
    ("同情", "どうじょう", "simpati/rasa kasihan", "perasaan_emosi",
     "彼に同情します。", "Kare ni doujou shimasu.", "Saya bersimpati padanya."),
    ("動機", "どうき", "motif", "konsep_umum",
     "犯罪の動機を調べます。", "Hanzai no douki o shirabemasu.", "Menyelidiki motif kejahatan."),
    ("同盟", "どうめい", "aliansi", "negara_kota",
     "同盟を結びます。", "Doumei o musubimasu.", "Membentuk aliansi."),
    ("同類", "どうるい", "jenis yang sama/sejenis", "konsep_umum",
     "これは同類の問題です。", "Kore wa dourui no mondai desu.", "Ini masalah yang sejenis."),
    ("同士", "どうし", "sesama/rekan", "keluarga_hubungan",
     "友人同士で話します。", "Yuujin doushi de hanashimasu.", "Berbicara sesama teman."),
    ("同等", "どうとう", "setara", "konsep_umum",
     "同等の権利があります。", "Doutou no kenri ga arimasu.", "Memiliki hak yang setara."),
    ("腐敗", "ふはい", "korupsi/pembusukan", "negara_kota",
     "政治の腐敗を批判します。", "Seiji no fuhai o hihan shimasu.", "Mengkritik korupsi politik."),
    ("復讐", "ふくしゅう", "balas dendam", "perasaan_emosi",
     "復讐を計画しています。", "Fukushuu o keikaku shite imasu.", "Merencanakan balas dendam."),
    ("紛争", "ふんそう", "konflik/perselisihan", "negara_kota",
     "国際紛争が続いています。", "Kokusai funsou ga tsuzuite imasu.", "Konflik internasional masih berlanjut."),
    ("負傷", "ふしょう", "luka/cedera", "penyakit_gejala",
     "事故で負傷しました。", "Jiko de fushou shimashita.", "Terluka karena kecelakaan."),
    ("負担", "ふたん", "beban", "konsep_umum",
     "経済的な負担があります。", "Keizaiteki na futan ga arimasu.", "Ada beban ekonomi."),
    ("不当", "ふとう", "tidak adil", "konsep_umum",
     "不当な扱いを受けました。", "Futou na atsukai o ukemashita.", "Menerima perlakuan yang tidak adil."),
    ("封鎖", "ふうさ", "blokade/penutupan", "negara_kota",
     "道路を封鎖します。", "Douro o fuusa shimasu.", "Menutup jalan."),
    ("現地", "げんち", "lokasi setempat", "arah_lokasi",
     "現地に到着しました。", "Genchi ni touchaku shimashita.", "Tiba di lokasi setempat."),
    ("厳密", "げんみつ", "ketat/teliti", "konsep_umum",
     "厳密に調査します。", "Genmitsu ni chousa shimasu.", "Menyelidiki secara teliti."),
    ("原則", "げんそく", "prinsip", "konsep_umum",
     "原則として禁止です。", "Gensoku to shite kinshi desu.", "Pada prinsipnya dilarang."),
    ("幻想", "げんそう", "ilusi/khayalan", "konsep_umum",
     "それは幻想です。", "Sore wa gensou desu.", "Itu hanyalah ilusi."),
    ("犠牲", "ぎせい", "korban/pengorbanan", "konsep_umum",
     "多くの犠牲を払いました。", "Ooku no gisei o haraimashita.", "Membayar banyak pengorbanan."),
    ("合成", "ごうせい", "sintesis/gabungan", "teknologi_gadget",
     "合成写真を作ります。", "Gousei shashin o tsukurimasu.", "Membuat foto hasil gabungan (edit)."),
    ("軍事", "ぐんじ", "urusan militer", "negara_kota",
     "軍事力を強化します。", "Gunjiryoku o kyouka shimasu.", "Memperkuat kekuatan militer."),
    ("業務", "ぎょうむ", "urusan bisnis/tugas kerja", "pekerjaan_kantor",
     "業務を分担します。", "Gyoumu o buntan shimasu.", "Membagi tugas kerja."),
    ("把握", "はあく", "pemahaman/penguasaan (situasi)", "konsep_umum",
     "状況を把握します。", "Joukyou o haaku shimasu.", "Memahami situasi."),
    ("配置", "はいち", "penempatan", "pekerjaan_kantor",
     "社員を配置します。", "Shain o haichi shimasu.", "Menempatkan karyawan."),
    ("背後", "はいご", "di balik/belakang", "arah_lokasi",
     "背後に隠れます。", "Haigo ni kakuremasu.", "Bersembunyi di belakang."),
    ("配慮", "はいりょ", "pertimbangan/perhatian", "perasaan_emosi",
     "相手に配慮します。", "Aite ni hairyo shimasu.", "Memberikan perhatian kepada lawan bicara."),
    ("廃止", "はいし", "penghapusan (aturan)", "negara_kota",
     "制度を廃止します。", "Seido o haishi shimasu.", "Menghapus sistem."),
    ("破壊", "はかい", "kehancuran", "konsep_umum",
     "建物が破壊されました。", "Tatemono ga hakai saremashita.", "Bangunan dihancurkan."),
    ("派遣", "はけん", "pengiriman/penugasan (staf)", "pekerjaan_kantor",
     "社員を派遣します。", "Shain o haken shimasu.", "Mengirim karyawan (ke lokasi tugas)."),
    ("白状", "はくじょう", "pengakuan (bersalah)", "konsep_umum",
     "罪を白状しました。", "Tsumi o hakujou shimashita.", "Mengakui kesalahan."),
    ("繁栄", "はんえい", "kemakmuran", "negara_kota",
     "国が繁栄しています。", "Kuni ga han'ei shite imasu.", "Negara berkembang makmur."),
    ("反応", "はんのう", "reaksi", "konsep_umum",
     "すぐに反応します。", "Sugu ni hannou shimasu.", "Bereaksi dengan cepat."),
    ("反乱", "はんらん", "pemberontakan", "negara_kota",
     "反乱が起こりました。", "Hanran ga okorimashita.", "Pemberontakan terjadi."),
    ("兵器", "へいき", "senjata (militer)", "konsep_umum",
     "新しい兵器を開発します。", "Atarashii heiki o kaihatsu shimasu.", "Mengembangkan senjata baru."),
    ("閉鎖", "へいさ", "penutupan (tempat)", "bangunan_fasilitas",
     "工場が閉鎖されました。", "Koujou ga heisa saremashita.", "Pabrik ditutup."),
    ("兵士", "へいし", "tentara/prajurit", "profesi",
     "兵士が行進します。", "Heishi ga koushin shimasu.", "Prajurit berbaris."),
    ("変動", "へんどう", "fluktuasi", "konsep_umum",
     "価格が変動します。", "Kakaku ga hendou shimasu.", "Harga berfluktuasi."),
    ("偏見", "へんけん", "prasangka", "perasaan_emosi",
     "偏見を持たないでください。", "Henken o motanaide kudasai.", "Jangan berprasangka."),
    ("悲鳴", "ひめい", "jeritan/pekikan", "perasaan_emosi",
     "悲鳴が聞こえました。", "Himei ga kikoemashita.", "Terdengar jeritan."),
    ("非難", "ひなん", "kritik/celaan", "perasaan_emosi",
     "非難を受けました。", "Hinan o ukemashita.", "Menerima kritik."),
    ("貧困", "ひんこん", "kemiskinan", "konsep_umum",
     "貧困問題を解決します。", "Hinkon mondai o kaiketsu shimasu.", "Menyelesaikan masalah kemiskinan."),
    ("頻繁", "ひんぱん", "sering/kerap", "konsep_umum",
     "頻繁に会います。", "Hinpan ni aimasu.", "Sering bertemu."),
    ("疲労", "ひろう", "kelelahan", "penyakit_gejala",
     "疲労がたまっています。", "Hirou ga tamatte imasu.", "Kelelahan menumpuk."),
    ("悲惨", "ひさん", "tragis/menyedihkan", "perasaan_emosi",
     "悲惨な事故でした。", "Hisan na jiko deshita.", "Kecelakaan yang tragis."),
    ("匹敵", "ひってき", "setanding/sebanding", "olahraga",
     "彼の実力に匹敵します。", "Kare no jitsuryoku ni hitteki shimasu.", "Setanding dengan kemampuannya."),
    ("必然", "ひつぜん", "keniscayaan", "konsep_umum",
     "必然の結果です。", "Hitsuzen no kekka desu.", "Ini adalah hasil yang tak terelakkan."),
    ("保険", "ほけん", "asuransi", "pekerjaan_kantor",
     "保険に入ります。", "Hoken ni hairimasu.", "Mengikuti asuransi."),
    ("本心", "ほんしん", "perasaan sebenarnya", "perasaan_emosi",
     "本心を話してください。", "Honshin o hanashite kudasai.", "Tolong bicarakan perasaan sebenarnya."),
    ("本質", "ほんしつ", "esensi/sifat dasar", "konsep_umum",
     "問題の本質を考えます。", "Mondai no honshitsu o kangaemasu.", "Memikirkan esensi masalah."),
    ("放棄", "ほうき", "meninggalkan/melepaskan (hak)", "konsep_umum",
     "権利を放棄します。", "Kenri o houki shimasu.", "Melepaskan hak."),
    ("方策", "ほうさく", "kebijakan/strategi", "pekerjaan_kantor",
     "新しい方策を考えます。", "Atarashii housaku o kangaemasu.", "Memikirkan strategi baru."),
    ("報酬", "ほうしゅう", "imbalan/upah", "pekerjaan_kantor",
     "報酬をもらいます。", "Houshuu o moraimasu.", "Menerima imbalan."),
    ("法廷", "ほうてい", "ruang sidang pengadilan", "bangunan_fasilitas",
     "法廷で証言します。", "Houtei de shougen shimasu.", "Bersaksi di ruang sidang."),
    ("一部", "いちぶ", "sebagian", "konsep_umum",
     "一部の人が反対します。", "Ichibu no hito ga hantai shimasu.", "Sebagian orang menentang."),
    ("一刻", "いっこく", "sesaat/sejenak", "hari_bulan",
     "一刻も早く来てください。", "Ikkoku mo hayaku kite kudasai.", "Tolong datang secepatnya."),
    ("移民", "いみん", "imigran/imigrasi", "negara_kota",
     "移民が増えています。", "Imin ga fuete imasu.", "Jumlah imigran bertambah."),
    ("依然", "いぜん", "masih (seperti sebelumnya)", "konsep_umum",
     "依然として問題があります。", "Izen to shite mondai ga arimasu.", "Masih ada masalah seperti sebelumnya."),
    ("依存", "いぞん", "ketergantungan", "konsep_umum",
     "スマホに依存しています。", "Sumaho ni izon shite imasu.", "Ketergantungan pada HP."),
    ("地獄", "じごく", "neraka", "agama_budaya",
     "地獄という考え方があります。", "Jigoku to iu kangaekata ga arimasu.", "Ada konsep tentang neraka."),
    ("事業", "じぎょう", "usaha/bisnis", "pekerjaan_kantor",
     "新しい事業を始めます。", "Atarashii jigyou o hajimemasu.", "Memulai usaha baru."),
    ("自覚", "じかく", "kesadaran diri", "perasaan_emosi",
     "責任を自覚します。", "Sekinin o jikaku shimasu.", "Menyadari tanggung jawab."),
    ("地元", "じもと", "daerah asal/setempat", "arah_lokasi",
     "地元に帰ります。", "Jimoto ni kaerimasu.", "Pulang ke daerah asal."),
    ("迅速", "じんそく", "cepat/segera", "konsep_umum",
     "迅速に対応します。", "Jinsoku ni taiou shimasu.", "Menanggapi dengan cepat."),
    ("実践", "じっせん", "praktik (penerapan nyata)", "mata_pelajaran",
     "理論を実践します。", "Riron o jissen shimasu.", "Mempraktikkan teori."),
    ("実質", "じっしつ", "substansi/hakikat", "konsep_umum",
     "実質的な効果があります。", "Jisshitsuteki na kouka ga arimasu.", "Memiliki efek yang substansial."),
    ("事前", "じぜん", "sebelumnya/di muka", "hari_bulan",
     "事前に予約します。", "Jizen ni yoyaku shimasu.", "Memesan sebelumnya (di muka)."),
    ("助言", "じょげん", "nasihat", "konsep_umum",
     "助言をいただきました。", "Jogen o itadakimashita.", "Menerima nasihat."),
    ("譲歩", "じょうほ", "kompromi/mengalah", "konsep_umum",
     "譲歩しました。", "Jouho shimashita.", "Kami mengalah (berkompromi)."),
    ("情熱", "じょうねつ", "semangat/passion", "perasaan_emosi",
     "仕事に情熱を持っています。", "Shigoto ni jounetsu o motte imasu.", "Memiliki passion dalam pekerjaan."),
    ("上陸", "じょうりく", "pendaratan (di darat)", "kendaraan",
     "台風が上陸しました。", "Taifuu ga jouriku shimashita.", "Topan mendarat di daratan."),
    ("情勢", "じょうせい", "keadaan/situasi", "negara_kota",
     "政治情勢が不安定です。", "Seiji jousei ga fuantei desu.", "Situasi politik tidak stabil."),
    ("従業員", "じゅうぎょういん", "karyawan", "profesi",
     "従業員を採用します。", "Juugyouin o saiyou shimasu.", "Merekrut karyawan."),
    ("柔軟", "じゅうなん", "fleksibel/lentur", "konsep_umum",
     "柔軟に対応します。", "Juunan ni taiou shimasu.", "Menanggapi secara fleksibel."),
    ("株式", "かぶしき", "saham", "pekerjaan_kantor",
     "株式を購入します。", "Kabushiki o kounyuu shimasu.", "Membeli saham."),
    ("課題", "かだい", "tugas/isu", "mata_pelajaran",
     "課題を提出します。", "Kadai o teishutsu shimasu.", "Menyerahkan tugas."),
    ("開発", "かいはつ", "pengembangan", "teknologi_gadget",
     "新製品を開発します。", "Shin seihin o kaihatsu shimasu.", "Mengembangkan produk baru."),
    ("回避", "かいひ", "penghindaran", "konsep_umum",
     "危険を回避します。", "Kiken o kaihi shimasu.", "Menghindari bahaya."),
    ("解除", "かいじょ", "pembatalan/pelepasan", "konsep_umum",
     "契約を解除します。", "Keiyaku o kaijo shimasu.", "Membatalkan kontrak."),
    ("階級", "かいきゅう", "kelas sosial/pangkat", "konsep_umum",
     "社会階級があります。", "Shakai kaikyuu ga arimasu.", "Ada kelas sosial."),
    ("介入", "かいにゅう", "intervensi", "negara_kota",
     "政府が介入します。", "Seifu ga kainyuu shimasu.", "Pemerintah melakukan intervensi."),
    ("確保", "かくほ", "penjaminan/pengamanan", "konsep_umum",
     "安全を確保します。", "Anzen o kakuho shimasu.", "Menjamin keamanan."),
    ("確信", "かくしん", "keyakinan penuh", "perasaan_emosi",
     "成功を確信しています。", "Seikou o kakushin shite imasu.", "Yakin akan kesuksesan."),
    ("肝心", "かんじん", "penting/esensial", "konsep_umum",
     "肝心な点を説明します。", "Kanjin na ten o setsumei shimasu.", "Menjelaskan poin penting."),
    ("完璧", "かんぺき", "sempurna", "konsep_umum",
     "完璧な計画です。", "Kanpeki na keikaku desu.", "Rencana yang sempurna."),
]
