# N2 (jlptsensei.com "JLPT N2 Nouns Vocabulary List", 83 words, single
# page) and N4 (jlptsensei.com "JLPT N4 Nouns Vocabulary List", 363 words
# across 4 pages) compound-noun batches. Cross-checked against the
# existing 1503-word dataset: 63 N2 and 118 N4 words were genuinely new
# 2-3 pure-kanji compounds. No example sentences in either source, so
# every one was hand-authored, same discipline as the N3/N1 web batches.
#
# Each entry: (kanji, reading, meaning_id, level, category, example_ja,
#              example_romaji, example_id)
N2_N4_WORDS = [
    ("足跡", "あしあと", "jejak kaki", "N2", "anggota_tubuh",
     "雪の上に足跡があります。", "Yuki no ue ni ashiato ga arimasu.", "Ada jejak kaki di atas salju."),
    ("売買", "ばいばい", "jual beli", "N2", "pekerjaan_kantor",
     "株を売買します。", "Kabu o baibai shimasu.", "Jual beli saham."),
    ("長男", "ちょうなん", "anak laki-laki tertua", "N2", "keluarga_hubungan",
     "彼は長男です。", "Kare wa chounan desu.", "Dia anak laki-laki tertua."),
    ("楕円", "だえん", "elips", "N2", "bentuk",
     "これは楕円の形です。", "Kore wa daen no katachi desu.", "Ini bentuk elips."),
    ("出入口", "でいりぐち", "pintu keluar masuk", "N2", "bangunan_fasilitas",
     "出入口はこちらです。", "Deiriguchi wa kochira desu.", "Pintu keluar masuk ada di sini."),
    ("宴会", "えんかい", "pesta/jamuan", "N2", "perayaan_haribesar",
     "宴会に参加します。", "Enkai ni sanka shimasu.", "Ikut pesta jamuan."),
    ("円周", "えんしゅう", "keliling lingkaran", "N2", "bentuk",
     "円周を計算します。", "Enshuu o keisan shimasu.", "Menghitung keliling lingkaran."),
    ("遠足", "えんそく", "tamasya sekolah", "N2", "mata_pelajaran",
     "遠足に行きます。", "Ensoku ni ikimasu.", "Pergi tamasya sekolah."),
    ("父母", "ふぼ", "ayah dan ibu", "N2", "keluarga_hubungan",
     "父母に感謝します。", "Fubo ni kansha shimasu.", "Berterima kasih pada orang tua."),
    ("学科", "がっか", "jurusan/mata kuliah", "N2", "mata_pelajaran",
     "学科を選びます。", "Gakka o erabimasu.", "Memilih jurusan."),
    ("学会", "がっかい", "himpunan akademik", "N2", "mata_pelajaran",
     "学会に出席します。", "Gakkai ni shusseki shimasu.", "Menghadiri konferensi akademik."),
    ("学力", "がくりょく", "kemampuan akademik", "N2", "mata_pelajaran",
     "学力を伸ばします。", "Gakuryoku o nobashimasu.", "Meningkatkan kemampuan akademik."),
    ("外科", "げか", "bedah (bidang medis)", "N2", "obat_obatan",
     "外科で手術します。", "Geka de shujutsu shimasu.", "Operasi di bagian bedah."),
    ("半径", "はんけい", "radius", "N2", "bentuk",
     "円の半径を測ります。", "En no hankei o hakarimasu.", "Mengukur radius lingkaran."),
    ("半島", "はんとう", "semenanjung", "N2", "arah_lokasi",
     "半島を旅行します。", "Hantou o ryokou shimasu.", "Bepergian ke semenanjung."),
    ("早口", "はやくち", "bicara cepat", "N2", "konsep_umum",
     "早口で話します。", "Hayaguchi de hanashimasu.", "Berbicara dengan cepat."),
    ("昼寝", "ひるね", "tidur siang", "N2", "konsep_umum",
     "昼寝をします。", "Hirune o shimasu.", "Tidur siang."),
    ("意地悪", "いじわる", "jahat/usil", "N2", "perasaan_emosi",
     "意地悪なことを言わないでください。", "Ijiwaru na koto o iwanaide kudasai.", "Jangan mengatakan hal yang usil."),
    ("移転", "いてん", "pindah (kantor/toko)", "N2", "pekerjaan_kantor",
     "事務所を移転します。", "Jimusho o iten shimasu.", "Memindahkan kantor."),
    ("寺院", "じいん", "kuil (Buddha)", "N2", "agama_budaya",
     "寺院を訪れます。", "Jiin o otozuremasu.", "Mengunjungi kuil."),
    ("自習", "じしゅう", "belajar mandiri", "N2", "mata_pelajaran",
     "図書館で自習します。", "Toshokan de jishuu shimasu.", "Belajar mandiri di perpustakaan."),
    ("時速", "じそく", "kecepatan per jam", "N2", "kendaraan",
     "時速80キロで走ります。", "Jisoku hachijuu kiro de hashirimasu.", "Melaju dengan kecepatan 80 km/jam."),
    ("実習", "じっしゅう", "praktik/pelatihan", "N2", "mata_pelajaran",
     "実習を行います。", "Jisshuu o okonaimasu.", "Melakukan praktik."),
    ("過半数", "かはんすう", "lebih dari separuh", "N2", "angka_satuan",
     "過半数の賛成が必要です。", "Kahansuu no sansei ga hitsuyou desu.", "Diperlukan persetujuan lebih dari separuh."),
    ("開会", "かいかい", "pembukaan acara", "N2", "perayaan_haribesar",
     "開会のあいさつをします。", "Kaikai no aisatsu o shimasu.", "Menyampaikan sambutan pembukaan."),
    ("会館", "かいかん", "gedung pertemuan", "N2", "bangunan_fasilitas",
     "会館で結婚式をします。", "Kaikan de kekkonshiki o shimasu.", "Mengadakan pernikahan di gedung pertemuan."),
    ("回転", "かいてん", "putaran/rotasi", "N2", "konsep_umum",
     "車輪が回転します。", "Sharin ga kaiten shimasu.", "Roda berputar."),
    ("加速", "かそく", "akselerasi", "N2", "kendaraan",
     "車が加速します。", "Kuruma ga kasoku shimasu.", "Mobil berakselerasi."),
    ("加速度", "かそくど", "tingkat akselerasi", "N2", "kendaraan",
     "加速度を計算します。", "Kasokudo o keisan shimasu.", "Menghitung tingkat akselerasi."),
    ("見学", "けんがく", "kunjungan observasi", "N2", "mata_pelajaran",
     "工場を見学します。", "Koujou o kengaku shimasu.", "Mengunjungi pabrik untuk observasi."),
    ("国王", "こくおう", "raja", "N2", "negara_kota",
     "国王が訪問します。", "Kokuou ga houmon shimasu.", "Raja berkunjung."),
    ("国立", "こくりつ", "negeri (nasional)", "N2", "negara_kota",
     "国立大学に入学します。", "Kokuritsu daigaku ni nyuugaku shimasu.", "Masuk universitas negeri."),
    ("国籍", "こくせき", "kewarganegaraan", "N2", "negara_kota",
     "国籍を取得します。", "Kokuseki o shutoku shimasu.", "Memperoleh kewarganegaraan."),
    ("校舎", "こうしゃ", "gedung sekolah", "N2", "bangunan_fasilitas",
     "新しい校舎ができました。", "Atarashii kousha ga dekimashita.", "Gedung sekolah baru sudah jadi."),
    ("校庭", "こうてい", "halaman sekolah", "N2", "bangunan_fasilitas",
     "校庭で遊びます。", "Koutei de asobimasu.", "Bermain di halaman sekolah."),
    ("待合室", "まちあいしつ", "ruang tunggu", "N2", "bangunan_fasilitas",
     "待合室で待ちます。", "Machiaishitsu de machimasu.", "Menunggu di ruang tunggu."),
    ("毎度", "まいど", "setiap kali", "N2", "konsep_umum",
     "毎度ありがとうございます。", "Maido arigatou gozaimasu.", "Terima kasih setiap kali (ucapan toko)."),
    ("店屋", "みせや", "toko/kedai", "N2", "bangunan_fasilitas",
     "店屋で買い物します。", "Miseya de kaimono shimasu.", "Berbelanja di toko."),
    ("木材", "もくざい", "kayu (material)", "N2", "konsep_umum",
     "木材で家を建てます。", "Mokuzai de ie o tatemasu.", "Membangun rumah dari kayu."),
    ("内科", "ないか", "penyakit dalam (bidang medis)", "N2", "obat_obatan",
     "内科に行きます。", "Naika ni ikimasu.", "Pergi ke dokter penyakit dalam."),
    ("並木", "なみき", "deretan pohon", "N2", "arah_lokasi",
     "並木道を歩きます。", "Namikimichi o arukimasu.", "Berjalan di jalan berderet pohon."),
    ("入社", "にゅうしゃ", "masuk perusahaan", "N2", "pekerjaan_kantor",
     "会社に入社します。", "Kaisha ni nyuusha shimasu.", "Masuk bekerja di perusahaan."),
    ("領収", "りょうしゅう", "penerimaan (uang)", "N2", "pekerjaan_kantor",
     "領収書をもらいます。", "Ryoushuusho o moraimasu.", "Menerima kuitansi."),
    ("青少年", "せいしょうねん", "remaja/pemuda", "N2", "keluarga_hubungan",
     "青少年の教育が大切です。", "Seishounen no kyouiku ga taisetsu desu.", "Pendidikan remaja itu penting."),
    ("赤道", "せきどう", "garis khatulistiwa", "N2", "arah_lokasi",
     "赤道を通過します。", "Sekidou o tsuuka shimasu.", "Melintasi garis khatulistiwa."),
    ("社説", "しゃせつ", "editorial (koran)", "N2", "media_hiburan",
     "社説を読みます。", "Shasetsu o yomimasu.", "Membaca editorial."),
    ("司会", "しかい", "pembawa acara/MC", "N2", "profesi",
     "司会を務めます。", "Shikai o tsutomemasu.", "Menjadi pembawa acara."),
    ("白髪", "しらが", "rambut putih", "N2", "anggota_tubuh",
     "白髪が増えました。", "Shiraga ga fuemashita.", "Rambut putih bertambah."),
    ("書店", "しょてん", "toko buku", "N2", "bangunan_fasilitas",
     "書店で本を買います。", "Shoten de hon o kaimasu.", "Membeli buku di toko buku."),
    ("商社", "しょうしゃ", "perusahaan dagang", "N2", "pekerjaan_kantor",
     "商社で働いています。", "Shousha de hataraite imasu.", "Bekerja di perusahaan dagang."),
    ("商店", "しょうてん", "toko", "N2", "bangunan_fasilitas",
     "商店で働きます。", "Shouten de hatarakimasu.", "Bekerja di toko."),
    ("集合", "しゅうごう", "berkumpul", "N2", "konsep_umum",
     "8時に集合します。", "Hachiji ni shuugou shimasu.", "Berkumpul jam 8."),
    ("習字", "しゅうじ", "kaligrafi", "N2", "hobi_aktivitas",
     "習字を習っています。", "Shuuji o naratte imasu.", "Belajar kaligrafi."),
    ("集会", "しゅうかい", "rapat umum/pertemuan", "N2", "pekerjaan_kantor",
     "集会に参加します。", "Shuukai ni sanka shimasu.", "Menghadiri pertemuan."),
    ("速力", "そくりょく", "kecepatan", "N2", "kendaraan",
     "速力を上げます。", "Sokuryoku o agemasu.", "Menambah kecepatan."),
    ("速達", "そくたつ", "pos kilat", "N2", "bangunan_fasilitas",
     "速達で送ります。", "Sokutatsu de okurimasu.", "Mengirim dengan pos kilat."),
    ("特売", "とくばい", "penjualan khusus/diskon", "N2", "konsep_umum",
     "特売セールがあります。", "Tokubai seeru ga arimasu.", "Ada obral khusus."),
    ("透明", "とうめい", "transparan", "N2", "konsep_umum",
     "透明なガラスです。", "Toumei na garasu desu.", "Kaca yang transparan."),
    ("東洋", "とうよう", "Timur (Asia)", "N2", "negara_kota",
     "東洋の文化を学びます。", "Touyou no bunka o manabimasu.", "Belajar budaya Timur."),
    ("売上", "うりあげ", "hasil penjualan", "N2", "pekerjaan_kantor",
     "売上が伸びました。", "Uriage ga nobimashita.", "Hasil penjualan meningkat."),
    ("輸血", "ゆけつ", "transfusi darah", "N2", "obat_obatan",
     "輸血を受けます。", "Yuketsu o ukemasu.", "Menerima transfusi darah."),
    ("輸送", "ゆそう", "pengangkutan barang", "N2", "kendaraan",
     "荷物を輸送します。", "Nimotsu o yusou shimasu.", "Mengangkut barang."),
    ("材木", "ざいもく", "bahan kayu", "N2", "konsep_umum",
     "材木を切ります。", "Zaimoku o kirimasu.", "Memotong bahan kayu."),
    # --- N4 below ---
    ("挨拶", "あいさつ", "salam/sapaan", "N4", "konsep_umum",
     "挨拶をします。", "Aisatsu o shimasu.", "Memberi salam."),
    ("案内", "あんない", "pemanduan/petunjuk", "N4", "bangunan_fasilitas",
     "案内をお願いします。", "Annai o onegai shimasu.", "Tolong berikan petunjuk."),
    ("番組", "ばんぐみ", "acara (TV/radio)", "N4", "media_hiburan",
     "テレビ番組を見ます。", "Terebi bangumi o mimasu.", "Menonton acara TV."),
    ("場所", "ばしょ", "tempat/lokasi", "N4", "arah_lokasi",
     "集合場所を確認します。", "Shuugou basho o kakunin shimasu.", "Memeriksa tempat berkumpul."),
    ("部長", "ぶちょう", "kepala departemen", "N4", "profesi",
     "部長に報告します。", "Buchou ni houkoku shimasu.", "Melapor ke kepala departemen."),
    ("文学", "ぶんがく", "sastra", "N4", "mata_pelajaran",
     "文学を勉強します。", "Bungaku o benkyou shimasu.", "Belajar sastra."),
    ("文法", "ぶんぽう", "tata bahasa", "N4", "mata_pelajaran",
     "文法を勉強します。", "Bunpou o benkyou shimasu.", "Belajar tata bahasa."),
    ("中学校", "ちゅうがっこう", "SMP", "N4", "bangunan_fasilitas",
     "中学校に通っています。", "Chuugakkou ni kayotte imasu.", "Sekolah di SMP."),
    ("注意", "ちゅうい", "perhatian/kehati-hatian", "N4", "konsep_umum",
     "注意してください。", "Chuui shite kudasai.", "Tolong berhati-hati."),
    ("駐車場", "ちゅうしゃじょう", "tempat parkir", "N4", "bangunan_fasilitas",
     "駐車場に車を止めます。", "Chuushajou ni kuruma o tomemasu.", "Memarkir mobil di tempat parkir."),
    ("大学生", "だいがくせい", "mahasiswa", "N4", "mata_pelajaran",
     "大学生になりました。", "Daigakusei ni narimashita.", "Menjadi mahasiswa."),
    ("男性", "だんせい", "laki-laki (formal)", "N4", "keluarga_hubungan",
     "男性用のトイレです。", "Dansei-you no toire desu.", "Ini toilet untuk laki-laki."),
    ("電報", "でんぽう", "telegram", "N4", "teknologi_gadget",
     "電報を送ります。", "Denpou o okurimasu.", "Mengirim telegram."),
    ("電灯", "でんとう", "lampu listrik", "N4", "perabot_rumah",
     "電灯をつけます。", "Dentou o tsukemasu.", "Menyalakan lampu listrik."),
    ("泥棒", "どろぼう", "pencuri", "N4", "profesi",
     "泥棒に気をつけてください。", "Dorobou ni ki o tsukete kudasai.", "Waspada terhadap pencuri."),
    ("道具", "どうぐ", "alat/perkakas", "N4", "konsep_umum",
     "大工道具を使います。", "Daiku dougu o tsukaimasu.", "Menggunakan alat tukang."),
    ("不便", "ふべん", "tidak praktis", "N4", "konsep_umum",
     "不便な場所です。", "Fuben na basho desu.", "Tempat yang tidak praktis."),
    ("復習", "ふくしゅう", "mengulang pelajaran", "N4", "mata_pelajaran",
     "授業の復習をします。", "Jugyou no fukushuu o shimasu.", "Mengulang materi pelajaran."),
    ("複雑", "ふくざつ", "kompleks/rumit", "N4", "konsep_umum",
     "複雑な問題です。", "Fukuzatsu na mondai desu.", "Masalah yang rumit."),
    ("布団", "ふとん", "kasur lipat Jepang", "N4", "perabot_rumah",
     "布団を敷きます。", "Futon o shikimasu.", "Menghamparkan futon."),
    ("普通", "ふつう", "biasa/umum", "N4", "konsep_umum",
     "普通の生活をしています。", "Futsuu no seikatsu o shite imasu.", "Menjalani kehidupan yang biasa."),
    ("下宿", "げしゅく", "kos/indekos", "N4", "ruangan_rumah",
     "下宿に住んでいます。", "Geshuku ni sunde imasu.", "Tinggal di tempat kos."),
    ("具合", "ぐあい", "kondisi (kesehatan)", "N4", "penyakit_gejala",
     "具合が悪いです。", "Guai ga warui desu.", "Kondisinya tidak baik (sakit)."),
    ("拝見", "はいけん", "melihat (bentuk sopan)", "N4", "konsep_umum",
     "拝見します。", "Haiken shimasu.", "Saya akan melihatnya (sopan)."),
    ("歯医者", "はいしゃ", "dokter gigi", "N4", "profesi",
     "歯医者に行きます。", "Haisha ni ikimasu.", "Pergi ke dokter gigi."),
    ("花見", "はなみ", "melihat bunga sakura", "N4", "hobi_aktivitas",
     "花見に行きます。", "Hanami ni ikimasu.", "Pergi melihat bunga sakura."),
    ("反対", "はんたい", "menentang/berlawanan", "N4", "konsep_umum",
     "反対の意見です。", "Hantai no iken desu.", "Pendapat yang berlawanan."),
    ("返事", "へんじ", "balasan/jawaban", "N4", "konsep_umum",
     "返事をください。", "Henji o kudasai.", "Tolong berikan balasan."),
    ("飛行場", "ひこうじょう", "bandara/lapangan udara", "N4", "bangunan_fasilitas",
     "飛行場に着きました。", "Hikoujou ni tsukimashita.", "Tiba di bandara."),
    ("翻訳", "ほんやく", "terjemahan", "N4", "mata_pelajaran",
     "本を翻訳します。", "Hon o honyaku shimasu.", "Menerjemahkan buku."),
    ("医学", "いがく", "ilmu kedokteran", "N4", "mata_pelajaran",
     "医学を学びます。", "Igaku o manabimasu.", "Belajar ilmu kedokteran."),
    ("以上", "いじょう", "lebih dari", "N4", "angka_satuan",
     "20歳以上です。", "Nijussai ijou desu.", "Usia 20 tahun ke atas."),
    ("以下", "いか", "kurang dari/di bawah", "N4", "angka_satuan",
     "10人以下です。", "Juunin ika desu.", "Kurang dari 10 orang."),
    ("意見", "いけん", "pendapat", "N4", "konsep_umum",
     "意見を言います。", "Iken o iimasu.", "Menyampaikan pendapat."),
    ("事故", "じこ", "kecelakaan", "N4", "konsep_umum",
     "事故が起きました。", "Jiko ga okimashita.", "Terjadi kecelakaan."),
    ("人口", "じんこう", "populasi", "N4", "negara_kota",
     "人口が増えています。", "Jinkou ga fuete imasu.", "Populasi bertambah."),
    ("辞典", "じてん", "kamus", "N4", "alat_tulis_sekolah",
     "辞典で調べます。", "Jiten de shirabemasu.", "Mencari di kamus."),
    ("自由", "じゆう", "kebebasan", "N4", "konsep_umum",
     "自由な時間があります。", "Jiyuu na jikan ga arimasu.", "Ada waktu bebas."),
    ("十分", "じゅうぶん", "cukup", "N4", "konsep_umum",
     "十分です。", "Juubun desu.", "Sudah cukup."),
    ("住所", "じゅうしょ", "alamat", "N4", "konsep_umum",
     "住所を書きます。", "Juusho o kakimasu.", "Menulis alamat."),
    # teknologi_gadget (not mata_pelajaran): 化学 (kagaku, "kimia") already
    # lives there from an earlier batch - genuine homophone, moved to
    # avoid an identical-reading quiz collision.
    ("科学", "かがく", "sains", "N4", "teknologi_gadget",
     "科学を勉強します。", "Kagaku o benkyou shimasu.", "Belajar sains."),
    ("海岸", "かいがん", "pantai", "N4", "arah_lokasi",
     "海岸を歩きます。", "Kaigan o arukimasu.", "Berjalan di pantai."),
    ("会議室", "かいぎしつ", "ruang rapat", "N4", "bangunan_fasilitas",
     "会議室で話します。", "Kaigishitsu de hanashimasu.", "Berbicara di ruang rapat."),
    # arah_lokasi (not bangunan_fasilitas): 開場 (kaijou, "pembukaan
    # tempat") already lives there from the TANGO batch - genuine
    # homophone, moved to avoid an identical-reading quiz collision.
    ("会場", "かいじょう", "tempat acara", "N4", "arah_lokasi",
     "会場に到着しました。", "Kaijou ni touchaku shimashita.", "Tiba di tempat acara."),
    ("会話", "かいわ", "percakapan", "N4", "mata_pelajaran",
     "会話を練習します。", "Kaiwa o renshuu shimasu.", "Berlatih percakapan."),
    ("格好", "かっこう", "penampilan", "N4", "pakaian_aksesori",
     "格好がいいですね。", "Kakkou ga ii desu ne.", "Penampilannya bagus ya."),
    ("家内", "かない", "istri saya", "N4", "keluarga_hubungan",
     "家内と話します。", "Kanai to hanashimasu.", "Berbicara dengan istri saya."),
    ("看護婦", "かんごふ", "perawat (perempuan)", "N4", "profesi",
     "看護婦さんが優しいです。", "Kangofu-san ga yasashii desu.", "Perawatnya baik hati."),
    ("簡単", "かんたん", "mudah/simpel", "N4", "konsep_umum",
     "簡単な問題です。", "Kantan na mondai desu.", "Soal yang mudah."),
    ("見物", "けんぶつ", "melihat-lihat (wisata)", "N4", "hobi_aktivitas",
     "お祭りを見物します。", "Omatsuri o kenbutsu shimasu.", "Melihat-lihat festival."),
    ("喧嘩", "けんか", "bertengkar", "N4", "perasaan_emosi",
     "喧嘩をしました。", "Kenka o shimashita.", "Bertengkar."),
    ("研究", "けんきゅう", "penelitian", "N4", "mata_pelajaran",
     "研究をしています。", "Kenkyuu o shite imasu.", "Melakukan penelitian."),
    ("研究室", "けんきゅうしつ", "ruang penelitian/lab", "N4", "bangunan_fasilitas",
     "研究室で実験します。", "Kenkyuushitsu de jikken shimasu.", "Melakukan eksperimen di lab."),
    ("気分", "きぶん", "perasaan/mood", "N4", "perasaan_emosi",
     "気分がいいです。", "Kibun ga ii desu.", "Perasaan saya baik."),
    ("機会", "きかい", "kesempatan", "N4", "konsep_umum",
     "いい機会です。", "Ii kikai desu.", "Ini kesempatan yang baik."),
    ("危険", "きけん", "berbahaya", "N4", "konsep_umum",
     "危険な場所です。", "Kiken na basho desu.", "Tempat yang berbahaya."),
    ("汽車", "きしゃ", "kereta (uap, lama)", "N4", "kendaraan",
     "汽車に乗ります。", "Kisha ni norimasu.", "Naik kereta."),
    ("今度", "こんど", "kali ini/lain kali", "N4", "hari_bulan",
     "今度会いましょう。", "Kondo aimashou.", "Mari bertemu lain kali."),
    ("今夜", "こんや", "malam ini", "N4", "hari_bulan",
     "今夜は寒いです。", "Kon'ya wa samui desu.", "Malam ini dingin."),
    ("故障", "こしょう", "kerusakan (mesin)", "N4", "teknologi_gadget",
     "車が故障しました。", "Kuruma ga koshou shimashita.", "Mobil rusak."),
    ("小鳥", "こどり", "burung kecil", "N4", "burung",
     "小鳥が鳴いています。", "Kotori ga naite imasu.", "Burung kecil berkicau."),
    ("校長", "こうちょう", "kepala sekolah", "N4", "profesi",
     "校長先生に会います。", "Kouchou sensei ni aimasu.", "Bertemu kepala sekolah."),
    ("講堂", "こうどう", "aula", "N4", "bangunan_fasilitas",
     "講堂で式をします。", "Koudou de shiki o shimasu.", "Mengadakan upacara di aula."),
    ("郊外", "こうがい", "pinggiran kota", "N4", "arah_lokasi",
     "郊外に住んでいます。", "Kougai ni sunde imasu.", "Tinggal di pinggiran kota."),
    ("高校", "こうこう", "SMA", "N4", "bangunan_fasilitas",
     "高校に通っています。", "Koukou ni kayotte imasu.", "Sekolah di SMA."),
    ("空気", "くうき", "udara", "N4", "cuaca",
     "空気がきれいです。", "Kuuki ga kirei desu.", "Udaranya bersih."),
    ("教育", "きょういく", "pendidikan", "N4", "mata_pelajaran",
     "教育を受けます。", "Kyouiku o ukemasu.", "Menerima pendidikan."),
    ("教会", "きょうかい", "gereja", "N4", "agama_budaya",
     "教会に行きます。", "Kyoukai ni ikimasu.", "Pergi ke gereja."),
    ("急行", "きゅうこう", "kereta cepat", "N4", "kendaraan",
     "急行に乗ります。", "Kyuukou ni norimasu.", "Naik kereta cepat."),
    ("木綿", "もめん", "katun", "N4", "pakaian_aksesori",
     "木綿のシャツです。", "Momen no shatsu desu.", "Kemeja katun."),
    ("無理", "むり", "mustahil/memaksakan", "N4", "konsep_umum",
     "それは無理です。", "Sore wa muri desu.", "Itu mustahil."),
    ("人形", "にんぎょう", "boneka", "N4", "hobi_aktivitas",
     "人形で遊びます。", "Ningyou de asobimasu.", "Bermain boneka."),
    ("入学", "にゅうがく", "masuk sekolah", "N4", "mata_pelajaran",
     "大学に入学します。", "Daigaku ni nyuugaku shimasu.", "Masuk universitas."),
    ("入院", "にゅういん", "dirawat di RS", "N4", "obat_obatan",
     "入院しました。", "Nyuuin shimashita.", "Dirawat di rumah sakit."),
    ("屋上", "おくじょう", "atap gedung (rooftop)", "N4", "bangunan_fasilitas",
     "屋上に上がります。", "Okujou ni agarimasu.", "Naik ke atap gedung."),
    ("利用", "りよう", "penggunaan", "N4", "konsep_umum",
     "図書館を利用します。", "Toshokan o riyou shimasu.", "Menggunakan perpustakaan."),
    ("理由", "りゆう", "alasan", "N4", "konsep_umum",
     "理由を説明します。", "Riyuu o setsumei shimasu.", "Menjelaskan alasan."),
    ("両方", "りょうほう", "kedua-duanya", "N4", "konsep_umum",
     "両方とも好きです。", "Ryouhou tomo suki desu.", "Suka keduanya."),
    ("最後", "さいご", "yang terakhir", "N4", "konsep_umum",
     "これが最後です。", "Kore ga saigo desu.", "Ini yang terakhir."),
    ("最近", "さいきん", "belakangan ini", "N4", "hari_bulan",
     "最近忙しいです。", "Saikin isogashii desu.", "Belakangan ini sibuk."),
    ("産業", "さんぎょう", "industri", "N4", "pekerjaan_kantor",
     "産業が発展しています。", "Sangyou ga hatten shite imasu.", "Industri berkembang."),
    ("再来月", "さらいげつ", "bulan depan setelah bulan depan", "N4", "hari_bulan",
     "再来月旅行します。", "Saraigetsu ryokou shimasu.", "Bepergian dua bulan lagi."),
    ("再来週", "さらいしゅう", "minggu setelah minggu depan", "N4", "hari_bulan",
     "再来週会います。", "Saraishuu aimasu.", "Bertemu dua minggu lagi."),
    ("政治", "せいじ", "politik", "N4", "negara_kota",
     "政治に興味があります。", "Seiji ni kyoumi ga arimasu.", "Tertarik pada politik."),
    ("生活", "せいかつ", "kehidupan (sehari-hari)", "N4", "konsep_umum",
     "楽しい生活です。", "Tanoshii seikatsu desu.", "Kehidupan yang menyenangkan."),
    ("生命", "せいめい", "nyawa/kehidupan", "N4", "konsep_umum",
     "生命を守ります。", "Seimei o mamorimasu.", "Melindungi nyawa."),
    ("生産", "せいさん", "produksi", "N4", "pekerjaan_kantor",
     "製品を生産します。", "Seihin o seisan shimasu.", "Memproduksi barang."),
    ("西洋", "せいよう", "Barat (dunia)", "N4", "negara_kota",
     "西洋の文化を学びます。", "Seiyou no bunka o manabimasu.", "Belajar budaya Barat."),
    ("世界", "せかい", "dunia", "N4", "negara_kota",
     "世界を旅行します。", "Sekai o ryokou shimasu.", "Bepergian keliling dunia."),
    ("戦争", "せんそう", "perang", "N4", "negara_kota",
     "戦争が終わりました。", "Sensou ga owarimashita.", "Perang telah berakhir."),
    ("社長", "しゃちょう", "presiden direktur", "N4", "profesi",
     "社長に会います。", "Shachou ni aimasu.", "Bertemu presiden direktur."),
    ("仕方", "しかた", "cara/metode", "N4", "konsep_umum",
     "仕方がありません。", "Shikata ga arimasen.", "Tidak ada cara lain (apa boleh buat)."),
    ("品物", "しなもの", "barang", "N4", "pekerjaan_kantor",
     "品物を確認します。", "Shinamono o kakunin shimasu.", "Memeriksa barang."),
    ("新聞社", "しんぶんしゃ", "perusahaan koran", "N4", "pekerjaan_kantor",
     "新聞社で働いています。", "Shinbunsha de hataraite imasu.", "Bekerja di perusahaan koran."),
    ("親切", "しんせつ", "ramah/baik hati", "N4", "perasaan_emosi",
     "彼は親切です。", "Kare wa shinsetsu desu.", "Dia baik hati."),
    ("下着", "したぎ", "pakaian dalam", "N4", "pakaian_aksesori",
     "下着を洗います。", "Shitagi o araimasu.", "Mencuci pakaian dalam."),
    ("食料品", "しょくりょうひん", "bahan makanan", "N4", "konsep_umum",
     "食料品を買います。", "Shokuryouhin o kaimasu.", "Membeli bahan makanan."),
    ("小学校", "しょうがっこう", "SD", "N4", "bangunan_fasilitas",
     "小学校に通っています。", "Shougakkou ni kayotte imasu.", "Sekolah di SD."),
    ("小説", "しょうせつ", "novel", "N4", "media_hiburan",
     "小説を読みます。", "Shousetsu o yomimasu.", "Membaca novel."),
    ("卒業", "そつぎょう", "kelulusan", "N4", "mata_pelajaran",
     "大学を卒業します。", "Daigaku o sotsugyou shimasu.", "Lulus dari universitas."),
    ("相談", "そうだん", "konsultasi/berdiskusi", "N4", "konsep_umum",
     "先生に相談します。", "Sensei ni soudan shimasu.", "Berkonsultasi dengan guru."),
    ("水道", "すいどう", "saluran air (PAM)", "N4", "ruangan_rumah",
     "水道を使います。", "Suidou o tsukaimasu.", "Menggunakan air ledeng."),
    ("丁寧", "ていねい", "sopan", "N4", "perasaan_emosi",
     "丁寧に話します。", "Teinei ni hanashimasu.", "Berbicara dengan sopan."),
    ("適当", "てきとう", "sesuai/pas", "N4", "konsep_umum",
     "適当な言葉を選びます。", "Tekitou na kotoba o erabimasu.", "Memilih kata yang sesuai."),
    ("店員", "てんいん", "pegawai toko", "N4", "profesi",
     "店員に聞きます。", "Ten'in ni kikimasu.", "Bertanya kepada pegawai toko."),
    ("展覧会", "てんらんかい", "pameran", "N4", "hobi_aktivitas",
     "展覧会を見ます。", "Tenrankai o mimasu.", "Melihat pameran."),
    ("特急", "とっきゅう", "kereta ekspres", "N4", "kendaraan",
     "特急に乗ります。", "Tokkyuu ni norimasu.", "Naik kereta ekspres."),
    ("床屋", "とこや", "tukang cukur", "N4", "profesi",
     "床屋で髪を切ります。", "Tokoya de kami o kirimasu.", "Memotong rambut di tukang cukur."),
    ("特別", "とくべつ", "istimewa/khusus", "N4", "konsep_umum",
     "特別な日です。", "Tokubetsu na hi desu.", "Hari yang istimewa."),
    ("受付", "うけつけ", "penerimaan/resepsionis", "N4", "bangunan_fasilitas",
     "受付で聞きます。", "Uketsuke de kikimasu.", "Bertanya di resepsionis."),
    ("約束", "やくそく", "janji", "N4", "konsep_umum",
     "約束を守ります。", "Yakusoku o mamorimasu.", "Menepati janji."),
    ("予習", "よしゅう", "belajar sebelum kelas", "N4", "mata_pelajaran",
     "予習をします。", "Yoshuu o shimasu.", "Belajar sebelum kelas (pra-belajar)."),
    ("用意", "ようい", "persiapan", "N4", "konsep_umum",
     "用意ができました。", "Youi ga dekimashita.", "Persiapan sudah selesai."),
    ("用事", "ようじ", "keperluan/urusan", "N4", "konsep_umum",
     "用事があります。", "Youji ga arimasu.", "Ada keperluan."),
    ("予約", "よやく", "reservasi", "N4", "bangunan_fasilitas",
     "レストランを予約します。", "Resutoran o yoyaku shimasu.", "Memesan (reservasi) restoran."),
    ("残念", "ざんねん", "sayang/menyesal", "N4", "perasaan_emosi",
     "残念です。", "Zannen desu.", "Sayang sekali."),
]
