# N3 compound-noun batch sourced from jlptsensei.com's "JLPT N3 Nouns
# Vocabulary List" (https://jlptsensei.com/jlpt-n3-nouns-vocabulary-list/,
# both pages, 160 words total) - cross-checked against the existing
# 1288-word dataset (93 were genuinely new 2-3 pure-kanji compounds; one
# of those 93, 木曜 "Thursday without 日", was dropped as a near-duplicate
# of the already-present 木曜日). Unlike the TANGO N2 PDF batch, this
# source only gives kanji/reading/English meaning - no example sentences -
# so every (kanji, reading, meaning_id, example_ja, example_romaji,
# example_id) tuple below was authored by hand, same as batches 1-13.
#
# Each entry: (kanji, reading, meaning_id, category, example_ja,
#              example_romaji, example_id)
N3_WORDS = [
    ("悪魔", "あくま", "setan/iblis", "konsep_umum",
     "悪魔のような性格です。", "Akuma no you na seikaku desu.", "Kepribadiannya seperti setan."),
    ("暗記", "あんき", "menghafal", "mata_pelajaran",
     "単語を暗記します。", "Tango o anki shimasu.", "Saya menghafal kosakata."),
    ("文明", "ぶんめい", "peradaban", "konsep_umum",
     "古代文明を研究します。", "Kodai bunmei o kenkyuu shimasu.", "Saya meneliti peradaban kuno."),
    ("分野", "ぶんや", "bidang/ranah", "konsep_umum",
     "専門の分野で働いています。", "Senmon no bunya de hataraite imasu.", "Saya bekerja di bidang keahlian saya."),
    ("父親", "ちちおや", "ayah (istilah umum)", "keluarga_hubungan",
     "父親と話します。", "Chichioya to hanashimasu.", "Saya berbicara dengan ayah."),
    ("地平線", "ちへいせん", "garis horizon", "arah_lokasi",
     "地平線に夕日が見えます。", "Chiheisen ni yuuhi ga miemasu.", "Matahari terbenam terlihat di garis horizon."),
    ("地位", "ちい", "posisi/status", "konsep_umum",
     "高い地位に就きました。", "Takai chii ni tsukimashita.", "Saya menduduki posisi tinggi."),
    ("長期", "ちょうき", "jangka panjang", "konsep_umum",
     "長期の計画を立てます。", "Chouki no keikaku o tatemasu.", "Saya membuat rencana jangka panjang."),
    ("中学", "ちゅうがく", "SMP", "mata_pelajaran",
     "中学に入学します。", "Chuugaku ni nyuugaku shimasu.", "Saya masuk SMP."),
    ("昼食", "ちゅうしょく", "makan siang", "konsep_umum",
     "昼食を食べます。", "Chuushoku o tabemasu.", "Saya makan siang."),
    ("大部分", "だいぶぶん", "sebagian besar", "konsep_umum",
     "大部分は賛成です。", "Daibubun wa sansei desu.", "Sebagian besar setuju."),
    ("男子", "だんし", "anak laki-laki/pria muda", "keluarga_hubungan",
     "男子校に通っています。", "Danshi kou ni kayotte imasu.", "Saya sekolah di sekolah khusus laki-laki."),
    ("不利", "ふり", "tidak menguntungkan", "konsep_umum",
     "この条件は不利です。", "Kono jouken wa furi desu.", "Kondisi ini tidak menguntungkan."),
    ("外交", "がいこう", "diplomasi", "negara_kota",
     "外交関係を築きます。", "Gaikou kankei o kizukimasu.", "Membangun hubungan diplomatik."),
    ("学問", "がくもん", "ilmu pengetahuan", "mata_pelajaran",
     "学問を深めます。", "Gakumon o fukamemasu.", "Saya memperdalam ilmu pengetahuan."),
    ("学者", "がくしゃ", "sarjana/cendekiawan", "profesi",
     "有名な学者です。", "Yuumei na gakusha desu.", "Dia sarjana terkenal."),
    ("学習", "がくしゅう", "pembelajaran", "mata_pelajaran",
     "日本語を学習します。", "Nihongo o gakushuu shimasu.", "Saya belajar bahasa Jepang."),
    ("議長", "ぎちょう", "ketua rapat/pimpinan sidang", "pekerjaan_kantor",
     "議長が発言します。", "Gichou ga hatsugen shimasu.", "Ketua rapat berbicara."),
    ("議会", "ぎかい", "parlemen/dewan", "negara_kota",
     "議会で審議します。", "Gikai de shingi shimasu.", "Dibahas di parlemen."),
    ("語学", "ごがく", "studi bahasa asing", "mata_pelajaran",
     "語学が得意です。", "Gogaku ga tokui desu.", "Saya mahir dalam bahasa asing."),
    ("母親", "ははおや", "ibu (istilah umum)", "keluarga_hubungan",
     "母親に会います。", "Hahaoya ni aimasu.", "Saya bertemu ibu."),
    ("販売", "はんばい", "penjualan", "pekerjaan_kantor",
     "商品を販売します。", "Shouhin o hanbai shimasu.", "Menjual barang dagangan."),
    ("発明", "はつめい", "penemuan (inovasi)", "teknologi_gadget",
     "新しい機械を発明しました。", "Atarashii kikai o hatsumei shimashita.", "Menemukan mesin baru."),
    ("一言", "ひとこと", "sepatah kata", "konsep_umum",
     "一言お願いします。", "Hitokoto onegai shimasu.", "Tolong berikan sepatah kata."),
    ("本物", "ほんもの", "barang asli", "konsep_umum",
     "これは本物です。", "Kore wa honmono desu.", "Ini barang asli."),
    ("本人", "ほんにん", "orang yang bersangkutan", "konsep_umum",
     "本人に確認します。", "Honnin ni kakunin shimasu.", "Saya konfirmasi ke orang yang bersangkutan."),
    ("一致", "いっち", "kesepakatan/kecocokan", "konsep_umum",
     "意見が一致しました。", "Iken ga icchi shimashita.", "Pendapat kami sepakat."),
    ("一時", "いちじ", "sementara/jam satu", "hari_bulan",
     "一時的な問題です。", "Ichijiteki na mondai desu.", "Ini masalah sementara."),
    ("一家", "いっか", "satu keluarga", "keluarga_hubungan",
     "一家で旅行します。", "Ikka de ryokou shimasu.", "Bepergian sekeluarga."),
    ("一方", "いっぽう", "di sisi lain", "konsep_umum",
     "一方で反対もあります。", "Ippou de hantai mo arimasu.", "Di sisi lain, ada juga penentangan."),
    ("一生", "いっしょう", "seumur hidup", "konsep_umum",
     "一生忘れません。", "Isshou wasuremasen.", "Tidak akan lupa seumur hidup."),
    ("一種", "いっしゅ", "satu macam/jenis", "konsep_umum",
     "これは一種の芸術です。", "Kore wa isshu no geijutsu desu.", "Ini adalah semacam seni."),
    ("一瞬", "いっしゅん", "sekejap", "hari_bulan",
     "一瞬で終わりました。", "Isshun de owarimashita.", "Selesai dalam sekejap."),
    ("一層", "いっそう", "lebih lagi", "konsep_umum",
     "一層努力します。", "Issou doryoku shimasu.", "Berusaha lebih keras lagi."),
    ("一体", "いったい", "sebenarnya (penekanan tanya)", "konsep_umum",
     "一体何ですか。", "Ittai nan desu ka.", "Sebenarnya apa ini?"),
    ("邪魔", "じゃま", "gangguan/halangan", "konsep_umum",
     "お邪魔します。", "Ojama shimasu.", "Maaf mengganggu (ucapan saat masuk rumah orang)."),
    ("海外", "かいがい", "luar negeri", "negara_kota",
     "海外に住みたいです。", "Kaigai ni sumitai desu.", "Saya ingin tinggal di luar negeri."),
    ("会合", "かいごう", "pertemuan/rapat", "pekerjaan_kantor",
     "会合に出席します。", "Kaigou ni shusseki shimasu.", "Menghadiri pertemuan."),
    ("科目", "かもく", "mata pelajaran (kurikulum)", "mata_pelajaran",
     "好きな科目は何ですか。", "Sukina kamoku wa nan desu ka.", "Mata pelajaran favoritmu apa?"),
    ("気味", "きみ", "gejala/kecenderungan", "konsep_umum",
     "風邪の気味があります。", "Kaze no kimi ga arimasu.", "Ada gejala flu."),
    ("記入", "きにゅう", "mengisi (formulir)", "pekerjaan_kantor",
     "名前を記入します。", "Namae o kinyuu shimasu.", "Mengisi nama."),
    ("国家", "こっか", "negara (bangsa)", "negara_kota",
     "国家の代表です。", "Kokka no daihyou desu.", "Perwakilan negara."),
    ("国会", "こっかい", "parlemen nasional", "negara_kota",
     "国会で決定します。", "Kokkai de kettei shimasu.", "Diputuskan di parlemen."),
    ("国境", "こっきょう", "perbatasan negara", "negara_kota",
     "国境を越えます。", "Kokkyou o koemasu.", "Melintasi perbatasan negara."),
    ("国民", "こくみん", "rakyat/warga negara", "negara_kota",
     "国民の声を聞きます。", "Kokumin no koe o kikimasu.", "Mendengarkan suara rakyat."),
    ("今後", "こんご", "mulai sekarang/selanjutnya", "hari_bulan",
     "今後気をつけます。", "Kongo ki o tsukemasu.", "Akan lebih berhati-hati mulai sekarang."),
    ("今回", "こんかい", "kali ini", "hari_bulan",
     "今回は特別です。", "Konkai wa tokubetsu desu.", "Kali ini istimewa."),
    ("高速", "こうそく", "kecepatan tinggi", "kendaraan",
     "高速道路を走ります。", "Kousoku douro o hashirimasu.", "Melaju di jalan tol."),
    ("強力", "きょうりょく", "kuat/tangguh", "teknologi_gadget",
     "強力な機械です。", "Kyouryoku na kikai desu.", "Mesin yang kuat."),
    ("吸収", "きゅうしゅう", "penyerapan", "konsep_umum",
     "水を吸収します。", "Mizu o kyuushuu shimasu.", "Menyerap air."),
    ("急速", "きゅうそく", "pesat", "konsep_umum",
     "急速に成長しています。", "Kyuusoku ni seichou shite imasu.", "Berkembang dengan pesat."),
    ("万一", "まんいち", "jika terjadi (kemungkinan kecil)", "konsep_umum",
     "万一の場合に備えます。", "Man'ichi no baai ni sonaemasu.", "Bersiap untuk kemungkinan terburuk."),
    # "keluarga_hubungan" (not konsep_umum): 見方 (mikata, "cara pandang")
    # already lives in konsep_umum from an earlier batch - genuine
    # homophone, moved here to avoid two identical-reading quiz options.
    ("味方", "みかた", "sekutu/pendukung", "keluarga_hubungan",
     "彼は私の味方です。", "Kare wa watashi no mikata desu.", "Dia adalah sekutu saya."),
    ("魅力", "みりょく", "daya tarik/pesona", "perasaan_emosi",
     "彼女には魅力があります。", "Kanojo ni wa miryoku ga arimasu.", "Dia memiliki daya tarik."),
    ("熱心", "ねっしん", "antusias/tekun", "perasaan_emosi",
     "熱心に勉強します。", "Nesshin ni benkyou shimasu.", "Belajar dengan tekun."),
    ("能力", "のうりょく", "kemampuan", "konsep_umum",
     "彼には能力があります。", "Kare ni wa nouryoku ga arimasu.", "Dia memiliki kemampuan."),
    ("入場", "にゅうじょう", "masuk (ke tempat acara)", "bangunan_fasilitas",
     "入場は無料です。", "Nyuujou wa muryou desu.", "Masuk gratis."),
    ("連続", "れんぞく", "berkelanjutan/beruntun", "konsep_umum",
     "三日連続で雨です。", "Mikka renzoku de ame desu.", "Hujan tiga hari berturut-turut."),
    ("利益", "りえき", "keuntungan/laba", "pekerjaan_kantor",
     "利益が増えました。", "Rieki ga fuemashita.", "Keuntungan bertambah."),
    ("留学", "りゅうがく", "belajar di luar negeri", "mata_pelajaran",
     "アメリカに留学します。", "Amerika ni ryuugaku shimasu.", "Belajar ke Amerika."),
    ("左右", "さゆう", "kiri dan kanan", "arah_lokasi",
     "左右を確認します。", "Sayuu o kakunin shimasu.", "Memeriksa kiri dan kanan."),
    ("製品", "せいひん", "produk (hasil manufaktur)", "pekerjaan_kantor",
     "新しい製品を作ります。", "Atarashii seihin o tsukurimasu.", "Membuat produk baru."),
    ("青年", "せいねん", "pemuda", "keluarga_hubungan",
     "青年が集まっています。", "Seinen ga atsumatte imasu.", "Para pemuda berkumpul."),
    ("刺激", "しげき", "stimulus/rangsangan", "perasaan_emosi",
     "強い刺激を受けました。", "Tsuyoi shigeki o ukemashita.", "Menerima stimulus yang kuat."),
    ("資本", "しほん", "modal (dana)", "pekerjaan_kantor",
     "資本を集めます。", "Shihon o atsumemasu.", "Mengumpulkan modal."),
    ("身長", "しんちょう", "tinggi badan", "anggota_tubuh",
     "身長を測ります。", "Shinchou o hakarimasu.", "Mengukur tinggi badan."),
    ("食品", "しょくひん", "produk makanan", "konsep_umum",
     "食品を輸入します。", "Shokuhin o yunyuu shimasu.", "Mengimpor produk makanan."),
    ("書物", "しょもつ", "buku (istilah formal)", "alat_tulis_sekolah",
     "古い書物を読みます。", "Furui shomotsu o yomimasu.", "Membaca buku kuno."),
    ("書斎", "しょさい", "ruang kerja/studi pribadi", "ruangan_rumah",
     "書斎で本を読みます。", "Shosai de hon o yomimasu.", "Membaca buku di ruang kerja."),
    ("商売", "しょうばい", "perdagangan/bisnis", "pekerjaan_kantor",
     "商売を始めます。", "Shoubai o hajimemasu.", "Mulai berbisnis."),
    ("奨学金", "しょうがくきん", "beasiswa", "mata_pelajaran",
     "奨学金をもらいました。", "Shougakukin o moraimashita.", "Menerima beasiswa."),
    ("正午", "しょうご", "tengah hari", "hari_bulan",
     "正午に会いましょう。", "Shougo ni aimashou.", "Mari bertemu tengah hari."),
    ("少女", "しょうじょ", "gadis muda", "keluarga_hubungan",
     "少女が歌っています。", "Shoujo ga utatte imasu.", "Gadis muda sedang menyanyi."),
    ("少年", "しょうねん", "anak laki-laki/remaja", "keluarga_hubungan",
     "少年が野球をします。", "Shounen ga yakyuu o shimasu.", "Remaja laki-laki bermain bisbol."),
    ("集団", "しゅうだん", "kelompok/massa", "konsep_umum",
     "集団で行動します。", "Shuudan de koudou shimasu.", "Bertindak secara berkelompok."),
    ("収穫", "しゅうかく", "panen", "konsep_umum",
     "米を収穫します。", "Kome o shuukaku shimasu.", "Memanen beras."),
    ("週間", "しゅうかん", "seminggu (durasi)", "hari_bulan",
     "一週間旅行します。", "Isshuukan ryokou shimasu.", "Bepergian selama seminggu."),
    ("週刊", "しゅうかん", "terbitan mingguan", "media_hiburan",
     "週刊誌を読みます。", "Shuukanshi o yomimasu.", "Membaca majalah mingguan."),
    ("速度", "そくど", "kecepatan", "kendaraan",
     "速度を落としてください。", "Sokudo o otoshite kudasai.", "Tolong kurangi kecepatan."),
    ("大半", "たいはん", "sebagian besar", "konsep_umum",
     "大半の人が同意します。", "Taihan no hito ga doui shimasu.", "Sebagian besar orang setuju."),
    ("大会", "たいかい", "kompetisi/turnamen besar", "olahraga",
     "大会に出場します。", "Taikai ni shutsujou shimasu.", "Ikut kompetisi."),
    ("手品", "てじな", "sulap/trik sulap", "hobi_aktivitas",
     "手品を見せます。", "Tejina o misemasu.", "Menunjukkan sulap."),
    ("徹夜", "てつや", "semalaman tidak tidur", "konsep_umum",
     "徹夜で勉強しました。", "Tetsuya de benkyou shimashita.", "Belajar semalaman."),
    ("図書", "としょ", "buku-buku (koleksi, istilah formal)", "alat_tulis_sekolah",
     "図書を整理します。", "Tosho o seiri shimasu.", "Merapikan buku-buku."),
    ("運転", "うんてん", "mengemudi/mengoperasikan", "kendaraan",
     "車を運転します。", "Kuruma o unten shimasu.", "Mengemudikan mobil."),
    ("悪口", "わるぐち", "omongan jelek/fitnah", "perasaan_emosi",
     "悪口を言わないでください。", "Waruguchi o iwanaide kudasai.", "Jangan bicara buruk tentang orang."),
    ("余分", "よぶん", "kelebihan/ekstra", "konsep_umum",
     "余分な物を捨てます。", "Yobun na mono o sutemasu.", "Membuang barang yang berlebihan."),
    ("夜中", "よなか", "tengah malam", "hari_bulan",
     "夜中に起きました。", "Yonaka ni okimashita.", "Bangun tengah malam."),
    ("唯一", "ゆいいつ", "satu-satunya", "konsep_umum",
     "唯一の方法です。", "Yuiitsu no houhou desu.", "Ini satu-satunya cara."),
    ("輸出", "ゆしゅつ", "ekspor", "pekerjaan_kantor",
     "車を輸出します。", "Kuruma o yushutsu shimasu.", "Mengekspor mobil."),
    ("有利", "ゆうり", "menguntungkan", "konsep_umum",
     "この条件は有利です。", "Kono jouken wa yuuri desu.", "Kondisi ini menguntungkan."),
    ("全国", "ぜんこく", "seluruh negeri", "negara_kota",
     "全国で販売します。", "Zenkoku de hanbai shimasu.", "Dijual di seluruh negeri."),
]
