# Category assignment for the 377 new 2-3-kanji compound words mined from
# TANGO N2 (scripts/reference/tango_n2_source.json). Keyed by TANGO entry
# number for traceability back to the source book. Assigned by reading each
# entry's Indonesian meaning and picking the best-fitting existing Kotoba
# category; genuinely abstract concepts (no concrete real-world theme) fall
# to konsep_umum, same convention already established for that category.
CATEGORY_BY_NUMBER = {
    56: "konsep_umum", 57: "cuaca", 58: "konsep_umum", 59: "hari_bulan",
    60: "hari_bulan", 63: "hari_bulan", 64: "arah_lokasi", 65: "konsep_umum",
    66: "konsep_umum", 67: "konsep_umum", 68: "hari_bulan", 69: "negara_kota",
    70: "pekerjaan_kantor", 71: "perasaan_emosi", 72: "minuman",
    73: "arah_lokasi", 74: "konsep_umum", 76: "pekerjaan_kantor",
    77: "obat_obatan", 78: "ekspresi_wajah", 79: "pekerjaan_kantor",
    80: "hobi_aktivitas", 81: "konsep_umum", 82: "kendaraan",
    83: "pekerjaan_kantor", 85: "konsep_umum", 86: "keluarga_hubungan",
    87: "bangunan_fasilitas", 88: "konsep_umum", 89: "hobi_aktivitas",
    91: "pekerjaan_kantor", 92: "konsep_umum", 93: "konsep_umum",
    94: "konsep_umum", 95: "bangunan_fasilitas", 96: "konsep_umum",
    97: "konsep_umum", 99: "bangunan_fasilitas", 100: "konsep_umum",
    101: "negara_kota", 102: "konsep_umum", 103: "hari_bulan",
    104: "bencana_alam", 105: "ruangan_rumah", 107: "profesi",
    108: "negara_kota", 109: "hobi_aktivitas", 110: "keluarga_hubungan",
    111: "perabot_rumah", 112: "anggota_tubuh", 113: "konsep_umum",
    115: "konsep_umum", 116: "konsep_umum", 117: "perasaan_emosi",
    118: "hobi_aktivitas", 119: "obat_obatan", 122: "perasaan_emosi",
    123: "perasaan_emosi", 124: "konsep_umum", 125: "cuaca",
    126: "perasaan_emosi", 127: "perasaan_emosi", 128: "bangunan_fasilitas",
    129: "konsep_umum", 130: "hobi_aktivitas", 132: "mata_pelajaran",
    133: "mata_pelajaran", 134: "hobi_aktivitas", 135: "perasaan_emosi",
    136: "cuaca", 137: "teknologi_gadget", 138: "hari_bulan",
    139: "pekerjaan_kantor", 140: "pekerjaan_kantor", 141: "negara_kota",
    142: "media_hiburan", 143: "mata_pelajaran", 146: "arah_lokasi",
    147: "konsep_umum", 148: "kendaraan", 149: "perayaan_haribesar",
    150: "mata_pelajaran", 152: "konsep_umum", 153: "konsep_umum",
    155: "arah_lokasi", 156: "konsep_umum", 157: "arah_lokasi",
    158: "teknologi_gadget", 159: "bunga_tanaman", 160: "konsep_umum",
    161: "konsep_umum", 162: "perasaan_emosi", 163: "konsep_umum",
    164: "konsep_umum", 166: "konsep_umum", 167: "profesi",
    170: "profesi", 172: "kendaraan", 173: "arah_lokasi",
    174: "konsep_umum", 175: "konsep_umum", 176: "keluarga_hubungan",
    177: "konsep_umum", 178: "obat_obatan", 179: "obat_obatan",
    181: "bangunan_fasilitas", 182: "hobi_aktivitas", 184: "media_hiburan",
    185: "mata_pelajaran", 186: "konsep_umum", 187: "pekerjaan_kantor",
    188: "cuaca", 190: "konsep_umum", 191: "mata_pelajaran",
    192: "mata_pelajaran", 193: "konsep_umum", 194: "pekerjaan_kantor",
    195: "kendaraan", 197: "bangunan_fasilitas", 199: "kendaraan",
    200: "konsep_umum", 201: "olahraga", 202: "arah_lokasi",
    205: "negara_kota", 206: "konsep_umum", 207: "kendaraan",
    208: "mata_pelajaran", 209: "konsep_umum", 210: "konsep_umum",
    211: "konsep_umum", 213: "pekerjaan_kantor", 214: "profesi",
    215: "hobi_aktivitas", 216: "hari_bulan", 217: "profesi",
    218: "mata_pelajaran", 219: "konsep_umum", 220: "konsep_umum",
    222: "mata_pelajaran", 224: "pekerjaan_kantor", 225: "anggota_tubuh",
    226: "konsep_umum", 227: "profesi", 229: "konsep_umum",
    230: "pekerjaan_kantor", 231: "mata_pelajaran", 232: "kendaraan",
    233: "bunga_tanaman", 234: "negara_kota", 235: "konsep_umum",
    236: "kendaraan", 238: "pekerjaan_kantor", 239: "konsep_umum",
    240: "pekerjaan_kantor", 241: "konsep_umum", 242: "hari_bulan",
    243: "obat_obatan", 246: "pekerjaan_kantor", 247: "negara_kota",
    248: "konsep_umum", 249: "konsep_umum", 250: "konsep_umum",
    251: "perayaan_haribesar", 253: "pekerjaan_kantor", 255: "arah_lokasi",
    256: "konsep_umum", 257: "penyakit_gejala", 258: "peralatan_masak",
    259: "pekerjaan_kantor", 260: "pekerjaan_kantor", 262: "konsep_umum",
    263: "pekerjaan_kantor", 267: "konsep_umum", 268: "hari_bulan",
    269: "pekerjaan_kantor", 270: "konsep_umum", 271: "hari_bulan",
    272: "konsep_umum", 273: "konsep_umum", 274: "perasaan_emosi",
    275: "hari_bulan", 276: "bangunan_fasilitas", 277: "keluarga_hubungan",
    279: "konsep_umum", 280: "konsep_umum", 281: "konsep_umum",
    282: "perasaan_emosi", 283: "pekerjaan_kantor", 284: "kendaraan",
    285: "mata_pelajaran", 287: "konsep_umum", 290: "kendaraan",
    291: "konsep_umum", 292: "konsep_umum", 293: "konsep_umum",
    295: "konsep_umum", 296: "anggota_tubuh", 297: "penyakit_gejala",
    299: "angka_satuan", 300: "mata_pelajaran", 301: "konsep_umum",
    302: "pekerjaan_kantor", 303: "pakaian_aksesori", 304: "bangunan_fasilitas",
    305: "hari_bulan", 307: "media_hiburan", 308: "pekerjaan_kantor",
    309: "pekerjaan_kantor", 310: "konsep_umum", 311: "hari_bulan",
    312: "olahraga", 313: "bangunan_fasilitas", 315: "teknologi_gadget",
    317: "hari_bulan", 318: "konsep_umum", 319: "konsep_umum",
    320: "arah_lokasi", 321: "perasaan_emosi", 322: "konsep_umum",
    323: "negara_kota", 325: "konsep_umum", 326: "olahraga",
    327: "mata_pelajaran", 328: "keluarga_hubungan", 329: "konsep_umum",
    330: "pekerjaan_kantor", 331: "konsep_umum", 332: "arah_lokasi",
    333: "pekerjaan_kantor", 336: "hari_bulan", 337: "konsep_umum",
    338: "pekerjaan_kantor", 339: "konsep_umum", 340: "arah_lokasi",
    341: "mata_pelajaran", 342: "pekerjaan_kantor", 344: "bangunan_fasilitas",
    345: "bangunan_fasilitas", 346: "konsep_umum", 347: "kendaraan",
    349: "alat_tulis_sekolah", 350: "kendaraan", 352: "pekerjaan_kantor",
    353: "ruangan_rumah", 354: "profesi", 355: "perabot_rumah",
    356: "konsep_umum", 357: "hari_bulan", 358: "media_hiburan",
    359: "kendaraan", 360: "negara_kota", 362: "olahraga",
    363: "bangunan_fasilitas", 364: "arah_lokasi", 365: "kendaraan",
    366: "hari_bulan", 367: "konsep_umum", 368: "konsep_umum",
    369: "konsep_umum", 370: "keluarga_hubungan", 371: "konsep_umum",
    372: "perasaan_emosi", 373: "hari_bulan", 374: "hari_bulan",
    375: "cuaca", 376: "hari_bulan", 377: "konsep_umum",
    378: "mata_pelajaran", 379: "teknologi_gadget", 380: "konsep_umum",
    381: "konsep_umum", 382: "angka_satuan", 383: "konsep_umum",
    384: "konsep_umum", 385: "konsep_umum", 386: "profesi",
    387: "pekerjaan_kantor", 388: "mata_pelajaran", 389: "konsep_umum",
    391: "pekerjaan_kantor", 392: "bangunan_fasilitas", 394: "konsep_umum",
    395: "konsep_umum", 398: "konsep_umum", 399: "alat_tulis_sekolah",
    400: "konsep_umum", 401: "hari_bulan", 403: "angka_satuan",
    404: "pakaian_aksesori", 406: "konsep_umum", 407: "pakaian_aksesori",
    409: "teknologi_gadget", 410: "konsep_umum", 411: "konsep_umum",
    413: "makanan_jepang", 415: "pekerjaan_kantor", 417: "konsep_umum",
    418: "pekerjaan_kantor", 420: "arah_lokasi", 421: "hari_bulan",
    422: "perabot_rumah", 423: "konsep_umum", 424: "pekerjaan_kantor",
    426: "pekerjaan_kantor", 427: "bangunan_fasilitas", 428: "kendaraan",
    430: "konsep_umum", 431: "konsep_umum", 432: "penyakit_gejala",
    434: "konsep_umum", 436: "pekerjaan_kantor", 437: "kendaraan",
    438: "pekerjaan_kantor", 439: "konsep_umum", 440: "mata_pelajaran",
    441: "media_hiburan", 442: "perasaan_emosi", 443: "hari_bulan",
    445: "keluarga_hubungan", 446: "bangunan_fasilitas", 447: "ruangan_rumah",
    449: "keluarga_hubungan", 450: "keluarga_hubungan", 451: "bangunan_fasilitas",
    452: "konsep_umum", 453: "pekerjaan_kantor", 454: "peralatan_masak",
    455: "alat_tulis_sekolah", 456: "hari_bulan", 457: "konsep_umum",
    458: "pekerjaan_kantor", 459: "hobi_aktivitas", 460: "konsep_umum",
    462: "konsep_umum", 463: "ruangan_rumah", 464: "keluarga_hubungan",
    465: "makanan_jepang", 467: "konsep_umum", 473: "pakaian_aksesori",
    487: "kendaraan", 493: "obat_obatan", 507: "bangunan_fasilitas",
    508: "pekerjaan_kantor", 510: "mata_pelajaran", 512: "bangunan_fasilitas",
    513: "perabot_rumah", 515: "keluarga_hubungan", 517: "mata_pelajaran",
    520: "hari_bulan", 521: "bumbu_rempah", 525: "angka_satuan",
    530: "bangunan_fasilitas", 531: "pekerjaan_kantor", 532: "bangunan_fasilitas",
    798: "konsep_umum", 805: "konsep_umum", 808: "konsep_umum",
    811: "konsep_umum", 813: "konsep_umum", 980: "minuman",
    981: "keluarga_hubungan", 982: "perasaan_emosi", 983: "perasaan_emosi",
    984: "konsep_umum", 986: "perasaan_emosi", 987: "anggota_tubuh",
    988: "anggota_tubuh", 990: "konsep_umum", 991: "konsep_umum",
    992: "keluarga_hubungan", 993: "konsep_umum", 994: "perasaan_emosi",
    995: "perasaan_emosi", 997: "negara_kota", 998: "pakaian_aksesori",
    999: "konsep_umum", 1000: "bangunan_fasilitas",
}

# Category id -> which generate_kotoba_*.py script file owns it.
CATEGORY_TO_SCRIPT = {
    "cuaca": "generate_kotoba_alam.py", "bencana_alam": "generate_kotoba_alam.py",
    "bunga_tanaman": "generate_kotoba_alam.py",
    "minuman": "generate_kotoba_makanan_minuman.py",
    "makanan_jepang": "generate_kotoba_makanan_minuman.py",
    "bumbu_rempah": "generate_kotoba_makanan_minuman.py",
    "peralatan_masak": "generate_kotoba_makanan_minuman.py",
    "anggota_tubuh": "generate_kotoba_tubuh_kesehatan.py",
    "penyakit_gejala": "generate_kotoba_tubuh_kesehatan.py",
    "obat_obatan": "generate_kotoba_tubuh_kesehatan.py",
    "olahraga": "generate_kotoba_tubuh_kesehatan.py",
    "perasaan_emosi": "generate_kotoba_tubuh_kesehatan.py",
    "ekspresi_wajah": "generate_kotoba_tubuh_kesehatan.py",
    "ruangan_rumah": "generate_kotoba_tempat_transportasi.py",
    "perabot_rumah": "generate_kotoba_tempat_transportasi.py",
    "bangunan_fasilitas": "generate_kotoba_tempat_transportasi.py",
    "kendaraan": "generate_kotoba_tempat_transportasi.py",
    "arah_lokasi": "generate_kotoba_tempat_transportasi.py",
    "negara_kota": "generate_kotoba_tempat_transportasi.py",
    "profesi": "generate_kotoba_manusia_sosial.py",
    "keluarga_hubungan": "generate_kotoba_manusia_sosial.py",
    "pakaian_aksesori": "generate_kotoba_manusia_sosial.py",
    "hobi_aktivitas": "generate_kotoba_manusia_sosial.py",
    "agama_budaya": "generate_kotoba_manusia_sosial.py",
    "perayaan_haribesar": "generate_kotoba_manusia_sosial.py",
    "konsep_umum": "generate_kotoba_manusia_sosial.py",
    "alat_tulis_sekolah": "generate_kotoba_pendidikan_pekerjaan.py",
    "mata_pelajaran": "generate_kotoba_pendidikan_pekerjaan.py",
    "pekerjaan_kantor": "generate_kotoba_pendidikan_pekerjaan.py",
    "teknologi_gadget": "generate_kotoba_pendidikan_pekerjaan.py",
    "media_hiburan": "generate_kotoba_pendidikan_pekerjaan.py",
    "hari_bulan": "generate_kotoba_waktu_angka.py",
    "musim": "generate_kotoba_waktu_angka.py",
    "angka_satuan": "generate_kotoba_waktu_angka.py",
    "warna": "generate_kotoba_waktu_angka.py",
    "bentuk": "generate_kotoba_waktu_angka.py",
}
