# Hand-authored romaji for each TANGO N2 example sentence (keyed by TANGO
# entry number) - the source PDF only provides the Japanese sentence and
# the Indonesian translation, not a sentence-level romaji, and a mechanical
# kana->romaji converter can't handle kanji correctly, so these were
# transliterated by hand to match this project's existing sentenceExamples
# schema (japanese, romaji, translation) for every other Kotoba entry.
EXAMPLE_ROMAJI_BY_NUMBER = {
    56: "Aizu o shite kudasai.",
    57: "Aozora ga hirogatte imasu.",
    58: "Nichiyoubi igai hatarakimasu.",
    59: "Kyou igo ki o tsukemasu.",
    60: "Shichiji ikou wa hairemasen.",
    63: "Izen koko ni sunde imashita.",
    64: "Ichi o kakunin shimasu.",
    65: "Ichiryuu no kaisha desu.",
    66: "Ippan no hito mo sanka dekimasu.",
    67: "Heya o idou shimasu.",
    68: "Juppun inai ni kite kudasai.",
    69: "Inaka de sodachimashita.",
    70: "Shiryou o insatsu shimasu.",
    71: "Yoi inshou o ukemashita.",
    72: "Inryousui o youi shimasu.",
    73: "Doa no uchigawa ni tatte kudasai.",
    74: "Uchuu ni kyoumi ga arimasu.",
    76: "Kaisha wa kuji kara eigyou shimasu.",
    77: "Eiyou o shikkari torimasu.",
    78: "Egao de aisatsu shimasu.",
    79: "Kaigi wa enki ni narimashita.",
    80: "Piano o ensou shimasu.",
    81: "Enryo shinaide kudasai.",
    82: "Densha de oufuku shimasu.",
    83: "Shigoto ni oubo shimashita.",
    85: "Oozei no hito ga imasu.",
    86: "Oyako de kimashita.",
    87: "Onsen ni hairitai desu.",
    88: "Kaiin ni narimashita.",
    89: "Kaiga o mi ni ikimasu.",
    91: "Kaikei o onegai shimasu.",
    92: "Mondai o kaiketsu shimashita.",
    93: "Gomi o kaishuu shimasu.",
    94: "Sagyou o kaishi shimasu.",
    95: "Hachiji ni kaijou shimasu.",
    96: "Kaisuu ga fuemashita.",
    97: "Sensei ga kaisetsu shimasu.",
    99: "Mise wa juji ni kaiten shimasu.",
    100: "Kakaku ga takai desu.",
    101: "Kakuchi de jishin ga okite imasu.",
    102: "Mou ichido kakunin shite kudasai.",
    103: "Kako o wasuremasen.",
    104: "Kasai ni chuui shite kudasai.",
    105: "Kadan ni hana o uemasu.",
    107: "Kachou ni houkoku shimasu.",
    108: "Kakkoku no bunka o manabimasu.",
    109: "Borantia katsudou o shite iru.",
    110: "Katei o taisetsu ni shimasu.",
    111: "Kabin ni hana o iremasu.",
    112: "Kamigata o kaemashita.",
    113: "Kankyaku ga ooi desu.",
    115: "Shigoto ni kankei ga arimasu.",
    116: "Minasan o kangei shimasu.",
    117: "Totemo kangeki shimashita.",
    118: "Kyouto o kankou shimasu.",
    119: "Haha o kango shite imasu.",
    122: "Kare no doryoku ni kanshin shimashita.",
    123: "Nihon bunka ni kanshin ga arimasu.",
    124: "Repooto ga kansei shimashita.",
    125: "Sentakumono o kansou shimasu.",
    126: "Eiga no kansou o hanashimasu.",
    127: "Totemo kandou shimashita.",
    128: "Kannai de wa kin'en desu.",
    129: "Korekara gaishutsu shimasu.",
    130: "Kyou wa gaishoku shimasu.",
    132: "Keizai gakubu ni hairimasu.",
    133: "Atarashii gakki ga hajimarimasu.",
    134: "Gakki o renshuu shimasu.",
    135: "Sukoshi gaman shite kudasai.",
    136: "Kion ga sagarimashita.",
    137: "Kikai o sousa shimasu.",
    138: "Kikan wa sankagetsu desu.",
    139: "Nihon kigyou de hatarakitai desu.",
    140: "Kigen o mamotte kudasai.",
    141: "Rainen kikoku shimasu.",
    142: "Shinbun no kiji o yomimasu.",
    143: "Nihongo no kiso o benkyou shimasu.",
    146: "Kitagawa no heya wa samui desu.",
    147: "Juji ni kitaku shimashita.",
    148: "Kippu o kaimasu.",
    149: "Kinen shashin o torimasu.",
    150: "Kihon o oboete kudasai.",
    152: "Hageshii kyousou ga arimasu.",
    153: "Kyoutsuu no shumi ga arimasu.",
    155: "Kyori ga tooi desu.",
    156: "Kiroku o torimasu.",
    157: "Kinjo ni suupaa ga arimasu.",
    158: "Gijutsu o manabimasu.",
    159: "Kusabana o sodatete imasu.",
    160: "Sagyou o kufuu shimasu.",
    161: "Futatsu o kubetsu shite kudasai.",
    162: "Totemo kurou shimashita.",
    163: "Mainichi kunren shimasu.",
    164: "Guuzen aimashita.",
    166: "Keikaku o tatemasu.",
    167: "Keikan ni kikimashita.",
    170: "Keisatsu o yobimasu.",
    172: "Toukyou keiyu de ikimasu.",
    173: "Keshiki ga kirei desu.",
    174: "Kekkyoku ikimasen deshita.",
    175: "Sore de kekkou desu.",
    176: "Rainen kekkon shimasu.",
    177: "Kare no ketten o shitte imasu.",
    178: "Kenkou ga taisetsu desu.",
    179: "Nimotsu o kensa shimasu.",
    181: "Kenchiku o benkyou shite imasu.",
    182: "Geijutsu ni kyoumi ga arimasu.",
    184: "Genkou o kaite imasu.",
    185: "Gengo o manabimasu.",
    186: "Jinkou ga genshou shite imasu.",
    187: "Sensei ga kouen shimasu.",
    188: "Kouon ni chuui shite kudasai.",
    190: "Buhin o koukan shimasu.",
    191: "Kouki ga hajimarimashita.",
    192: "Daigaku de kougi o ukemasu.",
    193: "Koukyou no basho desu.",
    194: "Kougyou ga hatten shite imasu.",
    195: "Koukuu kaisha de hatarakitai desu.",
    197: "Douro o kouji shite imasu.",
    199: "Koutsuu ga benri desu.",
    200: "Sugu koudou shite kudasai.",
    201: "Shiai no kouhan ga hajimarimashita.",
    202: "Kouhou ni sagatte kudasai.",
    205: "Kokusai kaigi ni sanka shimasu.",
    206: "Kojin jouhou o mamorimasu.",
    207: "Densha ga konzatsu shite imasu.",
    208: "Shiken ni goukaku shimashita.",
    209: "Goukei o keisan shimasu.",
    210: "Saishuu densha ni norimasu.",
    211: "Saisho ni jiko shoukai shimasu.",
    213: "Sagyou o hajimemasu.",
    214: "Sakusha no namae o kakimasu.",
    215: "Kono sakuhin wa yuumei desu.",
    216: "Sakuya ame ga furimashita.",
    217: "Kare wa yuumei na sakka desu.",
    218: "Sansuu o benkyou shimasu.",
    219: "Watashi wa sansei desu.",
    220: "Zairyou o junbi shimasu.",
    222: "Ashita shiken ga arimasu.",
    224: "Joushi no shiji ni shitagaimasu.",
    225: "Shisei o tadashite kudasai.",
    226: "Shizen ga yutaka desu.",
    227: "Shichou ga kimashita.",
    229: "Jikan o shitei shite kudasai.",
    230: "Oosaka shiten de hataraite imasu.",
    231: "Sensei ga shidou shimasu.",
    232: "Shihatsu densha ni norimasu.",
    233: "Shibafu ni hairanaide kudasai.",
    234: "Shimin ga atsumatte imasu.",
    235: "Shimei o kaite kudasai.",
    236: "Shanai de wa shizuka ni shite kudasai.",
    238: "Nihon de shuushoku shitai desu.",
    239: "Benkyou ni shuuchuu shimasu.",
    240: "Shuunyuu ga fuemashita.",
    241: "Kaigi ga shuuryou shimashita.",
    242: "Kyou wa shukujitsu desu.",
    243: "Shujutsu o ukemashita.",
    246: "Mainichi hachiji ni shukkin shimasu.",
    247: "Watashi wa Indoneshia shusshin desu.",
    248: "Shurui ga ooi desu.",
    249: "Kono kikai o shiyou shimasu.",
    250: "Tomodachi o shoukai shimasu.",
    251: "Paatii ni shoutai saremashita.",
    253: "Shouhin o narabemasu.",
    255: "Shoumen kara haitte kudasai.",
    256: "Shourai Nihon de hatarakitai desu.",
    257: "Shokuyoku ga arimasu.",
    258: "Shokki o araimasu.",
    259: "Shorui o teishutsu shimasu.",
    260: "Shiryou o kubarimasu.",
    262: "Kaigi ga shinkou shite imasu.",
    263: "Biza o shinsei shimasu.",
    267: "Shinrin o mamorimashou.",
    268: "Ima wa isogashii jiki desu.",
    269: "Jikyuu wa senen desu.",
    270: "Ookina jiken ga arimashita.",
    271: "Shuppatsu jikoku o kakunin shimasu.",
    272: "Pasupooto o jisan shite kudasai.",
    273: "Jijou o setsumei shimasu.",
    274: "Jishin ga arimasu.",
    275: "Atarashii jidai ni narimashita.",
    276: "Jitaku de benkyou shimasu.",
    277: "Jikka ni kaerimasu.",
    279: "Keikaku o jikkou shimasu.",
    280: "Jitsuyouteki na dougu desu.",
    281: "Jitsuryoku o nobashimasu.",
    282: "Ryouri o jiman shimasu.",
    283: "Jimu no shigoto o shite imasu.",
    284: "Michi ga juutai shite imasu.",
    285: "JLPT o juken shimasu.",
    287: "Junban o mamotte kudasai.",
    290: "Densha ni jousha shimasu.",
    291: "Kikai no joutai o kakunin shimasu.",
    292: "Joudan desu yo.",
    293: "Josei ga ooi desu.",
    295: "Jinsei wa ichido dake desu.",
    296: "Jintai no benkyou o shimasu.",
    297: "Suimin ga taisetsu desu.",
    299: "Suuji o kaite kudasai.",
    300: "Seikai shimashita.",
    301: "Jikan o seigen shimasu.",
    302: "Maiasa seisou shimasu.",
    303: "Gakkou no seifuku o kimasu.",
    304: "Setsubi o kakunin shite kudasai.",
    305: "Senjitsu oai shimashita ne.",
    307: "Shin shouhin o senden shimasu.",
    308: "Senpai ni kikimasu.",
    309: "Nihongo ga senmon desu.",
    310: "Zen'in atsumatte kudasai.",
    311: "Juppun zengo kakarimasu.",
    312: "Zenhan wa kantan deshita.",
    313: "Souko ni nimotsu o okimasu.",
    315: "Meeru o soushin shimashita.",
    317: "Souchou ni shuppatsu shimasu.",
    318: "N2 no mojigoi wa soutou muzukashii desu.",
    319: "Souryou wa muryou desu.",
    320: "Sotogawa o mite kudasai.",
    321: "Sensei o sonkei shite imasu.",
    322: "Jinkou ga zouka shite imasu.",
    323: "Nihon ni sankagetsu taizai shimasu.",
    325: "Tairyou ni mizu o tsukaimasu.",
    326: "Tairyoku o tsuketai desu.",
    327: "Tango o oboemasu.",
    328: "Kodomo ga tanjou shimashita.",
    329: "Daikin o haraimasu.",
    330: "Watashi ga daihyou desu.",
    331: "Dantai de ryokou shimasu.",
    332: "Chika ni chuushajou ga arimasu.",
    333: "Chikoku shimashita.",
    336: "Kongetsu chuujun ni ikimasu.",
    337: "Ryouri o chuumon shimasu.",
    338: "Shijou o chousa shimasu.",
    339: "Choushi ga ii desu.",
    340: "Yama no choujou ni tsukimashita.",
    341: "Densha de tsuugaku shimasu.",
    342: "Basu de tsuukin shimasu.",
    344: "Tsuuro o aruite kudasai.",
    345: "Teiin wa sanjuunin desu.",
    346: "Kion ga teika shimashita.",
    347: "Teiki kaado o wasurete shimatta.",
    349: "Techou ni yotei o kakimasu.",
    350: "Kono machi ni wa atarashii tetsudou ga dekita.",
    352: "Raigetsu Oosaka e tenkin shimasu.",
    353: "Tenjou ga takai heya desu ne.",
    354: "Tenchou ni soudan shimashita.",
    355: "Denkyuu o koukan shimashita.",
    356: "Dengon o onegai shimasu.",
    357: "Toujitsu wa ame deshita.",
    358: "Sensei ga kyoushitsu ni toujou shimashita.",
    359: "Eki ni touchaku shimashita.",
    360: "Tokai de hatarakitai desu.",
    362: "Shuumatsu ni tozan shimasu.",
    363: "Kono tochi wa takai desu.",
    364: "Gakkou no tochuu de tomodachi ni atta.",
    365: "Eki made toho gofun desu.",
    366: "Futari wa douji ni hanashimashita.",
    367: "Shourai dokuritsu shitai desu.",
    368: "Goukaku no tame ni doryoku shimasu.",
    369: "Naiyou o kakunin shite kudasai.",
    370: "Nakama to kyouryoku shimasu.",
    371: "Hako no nakami wa nan desu ka.",
    372: "Kare no setsumei ni nattoku shimashita.",
    373: "Mensetsu no nichiji o oshiete kudasai.",
    374: "Nichijou seikatsu ga isogashii desu.",
    375: "Nikkou ga tsuyoi desu ne.",
    376: "Nittei o kakunin shite kudasai.",
    377: "Nimotsu o mochimasu.",
    378: "Nihongo o nyuumon shimashita.",
    379: "Pasuwaado o nyuuryoku shite kudasai.",
    380: "Kono mise wa ninki ga arimasu.",
    381: "Ningen wa kangaeru ikimono desu.",
    382: "Ninzuu o kazoemasu.",
    383: "Nedan ga takai desu.",
    384: "Kesa nebou shimashita.",
    385: "Nenrei o kaite kudasai.",
    386: "Sofu wa nougyou o shite imasu.",
    387: "Nimotsu o haitatsu shimasu.",
    388: "Hatsuon o renshuu shimasu.",
    389: "Jiko ga hassei shimashita.",
    391: "Shin shouhin ga hatsubai saremashita.",
    392: "Baiten de mizu o kaimashita.",
    394: "Hijou ni samui desu.",
    395: "Kare wa jijitsu o hitei shimashita.",
    398: "Kore wa himitsu desu.",
    399: "Hon no hyoushi ga kirei desu.",
    400: "Hyoumen o sawaranaide kudasai.",
    401: "Hiruma wa shigoto o shite imasu.",
    403: "Fukusuu no riyuu ga arimasu.",
    404: "Fukusou ni ki o tsukete kudasai.",
    406: "Mizu ga fusoku shite imasu.",
    407: "Furugi o kaimashita.",
    409: "Kono buhin wa hitsuyou desu.",
    410: "Kono bubun o naoshite kudasai.",
    411: "Gomi o bunrui shimasu.",
    413: "Mainichi bentou o motte ikimasu.",
    415: "Sensei ni houkoku shimasu.",
    417: "Ii houhou o kangaemasu.",
    418: "Kaisha o houmon shimashita.",
    420: "Hodou o aruite kudasai.",
    421: "Honjitsu wa yasumi desu.",
    422: "Hondana ni hon ga arimasu.",
    423: "Hontou desu ka.",
    424: "Nihon to Indo wa boueki o shite imasu.",
    426: "Atarashii shain o boshuu shite imasu.",
    427: "Madoguchi de moshikomimasu.",
    428: "Densha wa man'in desu.",
    430: "Kangaekata no mikata ga chigaimasu.",
    431: "Mihon o misete kudasai.",
    432: "Mushiba ga itai desu.",
    434: "Kono saabisu wa muryou desu.",
    436: "Joushi ga meirei shimashita.",
    437: "Unten menkyo o torimashita.",
    438: "Ashita kaisha no mensetsu ga arimasu.",
    439: "Mokuhyou o kimemashita.",
    440: "Kono moji wa muzukashii desu.",
    441: "Omoshiroi monogatari o yomimashita.",
    442: "Monku o iwanaide kudasai.",
    443: "Yakan ni hatarakimasu.",
    445: "Ryoushin no yakuwari wa taisetsu desu.",
    446: "Yachin o haraimashita.",
    447: "Yane o shuuri shimashita.",
    449: "Kare to no yuujou wa taisetsu desu.",
    450: "Yuujin ni aimashita.",
    451: "Shorui o yuusou shimasu.",
    452: "Koko kara saki wa yuuryou desu.",
    453: "Nihon wa ooku no shokuhin o yunyuu shite iru.",
    454: "Youki ni mizu o iremasu.",
    455: "Youshi ni namae o kaite kudasai.",
    456: "Yokujitsu, kekka ga demashita.",
    457: "Kekka o yosou shimasu.",
    458: "Ooku no okyakusama ga raiten shimashita.",
    459: "Kono fuku ga ryuukou shite imasu.",
    460: "Ryoukin o haratte kudasai.",
    462: "Ima, ie wa rusu desu.",
    463: "Rouka o hashiranaide kudasai.",
    464: "Wakamono ga fuete imasu.",
    465: "Washoku ga suki desu.",
    467: "Shouhin o waribiki shimasu.",
    473: "Udedokei o kaimashita.",
    487: "Kaisatsuguchi de matte imasu.",
    493: "Kurumaisu o oshimasu.",
    507: "Shiyakusho de tetsuzuki o shimasu.",
    508: "Shouhinmei o oshiete kudasai.",
    510: "Shin'nyuusei o kangei shimasu.",
    512: "Kore wa senmonten de kaimashita.",
    513: "Soujiki de heya o souji shimasu.",
    515: "Sofubo wa inaka ni sunde imasu.",
    517: "Kare wa daigakuin de benkyou shite imasu.",
    520: "Choujikan hatarakimashita.",
    521: "Choumiryou o irete kudasai.",
    525: "Ninzuubun no ryouri o youi shimasu.",
    530: "Biyouin de kami o kirimashita.",
    531: "Fudousan no shigoto o shite imasu.",
    532: "Kodomo o hoikuen ni azukemasu.",
    798: "Sassoku yatte mimasu.",
    805: "Tashou jikan ga arimasu.",
    808: "Touzen no kekka desu.",
    811: "Totsuzen ame ga furimashita.",
    813: "Fudan wa isogashii desu.",
    980: "Kare wa koohii o aiin shite imasu.",
    981: "Kono futari wa aishou ga ii.",
    982: "Haha wa kodomo ni aijou o motte imasu.",
    983: "Kono machi ni aichaku ga arimasu.",
    984: "Kono pen o nagaku aiyou shite imasu.",
    986: "Kare ni wa akui ga arimasen.",
    987: "Toshi o toru to ashikoshi ga yowaku naru.",
    988: "Ashimoto ni ki o tsukete kudasai.",
    990: "Seikatsu ga antei shite kimashita.",
    991: "Kono shigoto ni wa ookina igi ga aru.",
    992: "Kanojo wa ikuji ni isogashii.",
    993: "Atarashii seido ni ikou shimasu.",
    994: "Kare wa tsuyoi ishi o motte imasu.",
    995: "Jibun no ishi o tsutaete kudasai.",
    997: "Kare wa gaikoku ni ijuu shimashita.",
    998: "Matsuri no ishou o kimashita.",
    999: "Kikai ni ijou ga arimasu.",
    1000: "Sakana ichiba e ikimashita.",
}
