/**
 * Card Game Mode's authoritative scoring — Tahap 2 butir 7 in
 * NOTES_CARD_GAME_MODE.md. Triggered on every new
 * `battleMatches/{matchId}/answers/{round}` doc, re-validates the
 * answer independently of whatever the client's own "fast path" guess
 * was, and is the only writer of `officialScore`/`result`/`status` —
 * see BattleMatch's own doc comment (lib/data/models/battle_match.dart)
 * for why those three are never trusted from the client.
 *
 * **`RomajiConverter` is ported here, not reused** — this runs on
 * Node.js, the Flutter app runs on Dart, and there is no way to share
 * one implementation across both. Two copies is the honest cost of that
 * split; a bug fixed in one (like the youon/sokuon fixes documented in
 * romaji_converter.dart's own history) needs remembering to fix in the
 * other too.
 *
 * Data source: `functions/data/kana_data.json` and
 * `functions/data/kanji_word_readings.json`, both generated by
 * `scripts/generate_functions_battle_data.py` from the exact same
 * `assets/data/*.json` files the Flutter app bundles — never hand
 * typed, and must be regenerated whenever those source files change.
 */

const {onDocumentCreated} = require("firebase-functions/v2/firestore");
const {getFirestore} = require("firebase-admin/firestore");

const kanaData = require("./data/kana_data.json");
const kanjiWordReadings = require("./data/kanji_word_readings.json");

function db() {
  return getFirestore();
}

/**
 * Match length, mirroring `lib/core/constants/battle_rules.dart` — one
 * round is one card answered by one player, so these are twice the
 * per-player card counts. Ten cards each decide it; a level score plays
 * both decks out to the end.
 *
 * **Kept in step by hand**, like the RomajiConverter port below: this
 * runs on Node and the app runs on Dart, and there is no way to share
 * one definition. Changing either without the other is how a match ends
 * at a different card on the server than on the phone.
 */
const MAIN_PHASE_ROUNDS = 20;
const TOTAL_ROUNDS = 40;

// --- RomajiConverter port (see lib/core/services/romaji_converter.dart
// for the Dart original this must stay in step with) ---

const SOKUON = new Set(["っ", "ッ"]);

const CHAR_TO_ROMAJI = {};
for (const k of kanaData) {
  CHAR_TO_ROMAJI[k.character] = k.romaji;
}

/** The romaji [runes] would produce starting at [index] — a youon
 * two-character match if one exists there, otherwise the single
 * character's own entry, otherwise `null`. Mirrors `_romajiAt` in the
 * Dart original exactly. */
function romajiAt(runes, index) {
  if (index >= runes.length) return null;
  if (index + 1 < runes.length) {
    const twoChar = runes[index] + runes[index + 1];
    const combined = CHAR_TO_ROMAJI[twoChar];
    if (combined) return combined;
  }
  return CHAR_TO_ROMAJI[runes[index]] || null;
}

/** Kana -> romaji, handling youon (two-character lookup tried first at
 * every position) and sokuon (repeats the next mora's leading letter) —
 * mirrors `RomajiConverter.convert` exactly. Only ever called on the
 * player's typed hiragana for a kanji card; kana cards are already
 * typed as romaji and compared directly. */
function toRomaji(text) {
  const runes = Array.from(text);
  const buffer = [];
  let i = 0;
  while (i < runes.length) {
    const char = runes[i];
    if (SOKUON.has(char)) {
      const nextRomaji = romajiAt(runes, i + 1);
      if (nextRomaji) buffer.push(nextRomaji[0]);
      i++;
      continue;
    }
    if (i + 1 < runes.length) {
      const twoChar = runes[i] + runes[i + 1];
      const combined = CHAR_TO_ROMAJI[twoChar];
      if (combined) {
        buffer.push(combined);
        i += 2;
        continue;
      }
    }
    buffer.push(CHAR_TO_ROMAJI[char] || char);
    i++;
  }
  return buffer.join("");
}

// --- Card resolution (mirrors battle_deck_builder.dart's resolveCard)
// ---

/** Given a `TurnOrderEntry.cardId`, the correct romaji answer and
 * whether it's typed as hiragana (kanji cards) or romaji directly (kana
 * cards) — same "{kanjiId}|{word}" vs plain kana-id split
 * `resolveCard` uses on the Flutter side. Returns `null` if the id
 * doesn't resolve to anything real. */
function resolveCorrectRomaji(cardId) {
  if (cardId.includes("|")) {
    const reading = kanjiWordReadings[cardId];
    if (!reading) return null;
    return {correctRomaji: reading, answerInHiragana: true};
  }
  const kana = kanaData.find((k) => k.id === cardId);
  if (!kana) return null;
  return {correctRomaji: kana.romaji, answerInHiragana: false};
}

// --- Scoring ---

/**
 * **Corrects a real gap in the notes' own design, not just an
 * implementation detail**: `NOTES_CARD_GAME_MODE.md` describes checking
 * "is `officialScore.uidA + officialScore.uidB == round + 1`" to detect
 * whether every round from 0 through `round` has been processed (since
 * the fast path lets rounds be answered — and their Cloud Function
 * invocations complete — out of order). That check is unsound twice
 * over: (1) summing *scores* undercounts whenever any prior round was
 * answered wrong (a wrong answer processes a round but adds 0 to the
 * sum, indistinguishable from "not yet processed"), and (2) even a
 * plain *count* of processed rounds can accidentally match `round + 1`
 * while still missing an earlier round, if a later round's invocation
 * happened to complete first and made up the count. Both are real for
 * this design specifically, since Cloud Function invocation order is
 * never guaranteed to match creation order.
 *
 * Fixed here with an explicit per-round marker (`scoredRounds`, a map
 * of round-string -> `true`) and a genuine contiguity check — walk
 * every round from 0 through `round` and confirm each one is marked —
 * rather than trusting any single aggregate number to stand in for
 * that. `scoredRounds` doubles as the idempotency guard against
 * duplicate delivery of the same trigger (Cloud Functions v2 is
 * at-least-once, not exactly-once).
 *
 * [dbInstance] is accepted explicitly (defaulting to the real Firestore
 * client) so a test can pass a `FakeFirestore` instead and exercise this
 * exact function — the same "real logic takes its dependencies as
 * parameters" split `battle_abandonment_sweep.js`'s
 * `forfeitOneStaleRound` and `battle_stars.js`'s `applyToPlayer` already
 * use. Added specifically so out-of-order-trigger tests can call the
 * real conclusion logic directly instead of a hand-written mirror of it.
 */
async function scoreAnswer(matchId, round, answerText, dbInstance = db()) {
  const matchRef = dbInstance.collection("battleMatches").doc(matchId);

  await dbInstance.runTransaction(async (transaction) => {
    const matchSnap = await transaction.get(matchRef);
    const match = matchSnap.data();
    if (!match) return;
    if (match.result) return; // already concluded — nothing left to score

    const scoredRounds = match.scoredRounds || {};
    if (scoredRounds[String(round)]) return; // already processed (retry)

    const turnEntry = (match.turnOrder || []).find((e) => e.round === round);
    if (!turnEntry) return;

    // The card its owner chose, falling back to the one dealt to this
    // round when they let the choosing window run out. Mirrors
    // `BattleMatch.effectiveCardId` on the client — scoring the dealt
    // card instead would mark the answer against a card the player
    // never saw.
    const playedCards = match.playedCards || {};
    const cardId = playedCards[String(round)] || turnEntry.cardId;

    const resolved = resolveCorrectRomaji(cardId);
    if (!resolved) return;

    let typedRomaji = (answerText || "").trim();
    if (resolved.answerInHiragana) {
      typedRomaji = toRomaji(typedRomaji);
    }
    const correct = typedRomaji.length > 0 &&
      typedRomaji.toLowerCase() === resolved.correctRomaji.trim().toLowerCase();

    // Who answered is derived from turnOrder, never trusted from the
    // answer doc's own `byUid` — see firestore.rules' battleMatches
    // comment for why that field is client-writable by either player.
    const players = match.players || [];
    const deckOwner = turnEntry.deckOwnerUid;
    const answerer = players.find((p) => p !== deckOwner) || deckOwner;

    const officialScore = Object.assign({}, match.officialScore || {});
    if (correct) {
      officialScore[answerer] = (officialScore[answerer] || 0) + 1;
    }

    const newScoredRounds = Object.assign({}, scoredRounds, {
      [String(round)]: true,
    });

    const updates = {officialScore, scoredRounds: newScoredRounds};

    let allPriorRoundsProcessed = true;
    for (let r = 0; r <= round; r++) {
      if (!newScoredRounds[String(r)]) {
        allPriorRoundsProcessed = false;
        break;
      }
    }

    if (allPriorRoundsProcessed && round >= MAIN_PHASE_ROUNDS - 1) {
      const scores = players.map((p) => officialScore[p] || 0);
      if (scores.length === 2 && scores[0] !== scores[1]) {
        updates.result = scores[0] > scores[1] ? players[0] : players[1];
        updates.status = "finished";
      }
    }

    // Self-heal for out-of-order trigger completion — see
    // AUDIT_C2_STAGE2_TRIGGER_ORDERING_REVIEW.md. The block above only
    // ever looks at rounds `0..round`, so a tied match could previously
    // only ever be forced to `"draw"` by round `TOTAL_ROUNDS - 1`'s own
    // invocation (the one place `round === TOTAL_ROUNDS - 1` could be
    // true) — and nothing re-checks that once `onDocumentCreated` has
    // already fired for that document. If that specific round's trigger
    // happened to complete *before* every earlier round had (Stage 2's
    // sequential-but-bursty writes make this far likelier than ordinary
    // gameplay ever did), the match could sit fully scored — every round
    // genuinely marked in `scoredRounds`, `officialScore` entirely
    // correct — with `result`/`status` never written, forever.
    //
    // This checks contiguity across the *whole* deck (`0..TOTAL_ROUNDS -
    // 1`), independently of `round`, so whichever invocation happens to
    // be the one that completes that full set — not necessarily round
    // `TOTAL_ROUNDS - 1`'s own, and not necessarily the numerically last
    // one either (the same gap exists in principle for a round below
    // `MAIN_PHASE_ROUNDS` arriving last after a retry) — is the one that
    // notices and concludes. It reuses the identical winner/draw rule
    // the block above already applies, verbatim, against the same
    // `officialScore` this transaction already computed: no new scoring
    // rule, no new field, and `if (!updates.result)` means this can
    // never run after the block above has already decided — never a
    // second, conflicting write.
    if (!updates.result) {
      let allRoundsScored = true;
      for (let r = 0; r < TOTAL_ROUNDS; r++) {
        if (!newScoredRounds[String(r)]) {
          allRoundsScored = false;
          break;
        }
      }
      if (allRoundsScored) {
        const scores = players.map((p) => officialScore[p] || 0);
        if (scores.length === 2 && scores[0] !== scores[1]) {
          updates.result = scores[0] > scores[1] ? players[0] : players[1];
          updates.status = "finished";
        } else if (scores.length === 2) {
          updates.result = "draw";
          updates.status = "finished";
        }
      }
    }

    transaction.update(matchRef, updates);
  });
}

exports.onBattleAnswerCreated = onDocumentCreated(
    "battleMatches/{matchId}/answers/{round}",
    async (event) => {
      const matchId = event.params.matchId;
      const round = parseInt(event.params.round, 10);
      if (Number.isNaN(round)) return;
      const answer = event.data.data();
      await scoreAnswer(matchId, round, answer.text);
    },
);

// Exported for tests only.
exports._internal = {toRomaji, resolveCorrectRomaji, scoreAnswer};
