// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Generated from `android/app/google-services.json` and
/// `ios/Runner/GoogleService-Info.plist` (project teisou-kana-master).
/// Regenerate via `flutterfire configure` if the Firebase project changes.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'run flutterfire configure to add web support.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform. '
          'Run flutterfire configure to add support for it.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_oIrI5pP0_0ik2bDAwONqr2g1QhMsGH4',
    appId: '1:329692614759:android:cbca9fc670f162d60e44c2',
    messagingSenderId: '329692614759',
    projectId: 'teisou-kana-master',
    storageBucket: 'teisou-kana-master.firebasestorage.app',
    // Card Game Mode presence (NOTES_CARD_GAME_MODE.md) — the Realtime
    // Database instance, created 2026-08-13 via the Firebase Console
    // (asia-southeast1/Singapore, closest region to this app's user
    // base), not auto-generated by flutterfire configure the way the
    // rest of this file is — added by hand once the instance existed to
    // avoid, not to invent.
    databaseURL:
        'https://teisou-kana-master-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  /// Values copied verbatim from `ios/Runner/GoogleService-Info.plist`
  /// (API_KEY, GOOGLE_APP_ID, GCM_SENDER_ID, PROJECT_ID, STORAGE_BUCKET,
  /// BUNDLE_ID, CLIENT_ID respectively). Note the apiKey and appId are
  /// genuinely *different* from Android's — each platform gets its own
  /// from Firebase, so they are not interchangeable.
  ///
  /// [iosClientId] is what Google Sign-In needs; it must stay in step with
  /// the `REVERSED_CLIENT_ID` URL scheme registered in
  /// `ios/Runner/Info.plist`, or the sign-in sheet opens and then fails to
  /// hand control back to the app.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ5uLd-5BCIeElGuBiRb6skKSwF__itRw',
    appId: '1:329692614759:ios:e5675bc27b55ef8f0e44c2',
    messagingSenderId: '329692614759',
    projectId: 'teisou-kana-master',
    storageBucket: 'teisou-kana-master.firebasestorage.app',
    iosBundleId: 'com.teisou.kanamaster',
    iosClientId:
        '329692614759-kohqu6a6mvs39jg7fi9maj30usdiqdrl.apps.googleusercontent.com',
    // Same Realtime Database instance as android — see the comment
    // there. One project, one database, shared by both platforms.
    databaseURL:
        'https://teisou-kana-master-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
