# Canonical N5 grammar-point scope — the single source of truth
# generate_bunpou_seed.py imports to know which patterns to write full
# content for, mirroring how kanji_char_lists.py locks kanji_char scope
# for generate_kanji_seed.py.
#
# N5_GRAMMAR is sourced from jlptsensei.com's N5 grammar list
# (https://jlptsensei.com/jlpt-n5-grammar-list/, fetched across its 3
# paginated pages) — there's no official JLPT grammar list, so any single
# source is a community convention, not an authority; jlptsensei.com was
# used here since it's the same source already used for this project's
# N2/N1 kanji lists (Tanos' page was fine for grammar but jlptsensei was
# picked for consistency with the kanji pipeline's established source).
# The page states "JLPT N5 Grammar List total: (84)" and 84 rows were
# counted across all 3 pages, confirming nothing was missed.
#
# Each entry is kept exactly as the source row presents it, including
# rows that bundle a couple of closely-related variants together (e.g.
# "だ / です", "ちゃいけない・じゃいけない") or represent a grammar
# *category* rather than a single pattern (e.g. "い-adjectives",
# "な-adjectives") — splitting these into separate rows would produce a
# count that no longer matches the source's own stated total, so the
# 1:1 mapping to the source is kept intact. Content authoring (see
# generate_bunpou_seed.py's N5_GRAMMAR_ENTRIES) is free to explain both
# variants of a bundled row in one entry's formation/usageNotes text.

N5_GRAMMAR = [
    "ちゃいけない・じゃいけない",
    "だ / です",
    "だけ",
    "だろう",
    "で",
    "でも",
    "でしょう",
    "どんな",
    "どうして",
    "どうやって",
    "が",
    "があります",
    "がほしい",
    "がいます",
    "ほうがいい",
    "い-adjectives",
    "いちばん",
    "一緒に",
    "いつも",
    "じゃない・ではない",
    "か",
    "か～か",
    "から",
    "方",
    "けど",
    "けれども",
    "まだ",
    "まだ～ていません",
    "まで",
    "前に",
    "ませんか",
    "ましょう",
    "ましょうか",
    "も",
    "もう",
    "な-adjectives",
    "なあ",
    "ないで",
    "ないでください",
    "ないといけない",
    "なくてもいい",
    "なくちゃ",
    "なくてはいけない",
    "なくてはならない",
    "なる",
    "んです",
    "ね",
    "に",
    "に行く",
    "にする",
    "に/へ",
    "の",
    "のです",
    "のが下手",
    "のが上手",
    "のが好き",
    "の中で[A]が一番",
    "ので",
    "お / ご",
    "を",
    "をください",
    "しかし",
    "それから",
    "そして",
    "すぎる",
    "たことがある",
    "たい",
    "たり～たり",
    "てある",
    "ている",
    "てから",
    "てください",
    "てはいけない",
    "てもいいです",
    "と",
    "とき",
    "とても",
    "つもり",
    "は",
    "は〜より・・・です",
    "はどうですか",
    "や",
    "よ",
    "より～ほうが",
    # Added later (2026-08-03), not from jlptsensei.com's original list —
    # a deliberate fix for a real curriculum gap found while building the
    # Bab module: several existing N5 patterns (te_kudasai, te_iru, ...)
    # use the -te form but nothing taught how to conjugate to it.
    "て形（てけい）",
    # Added later still (2026-08-03), same day, also not from
    # jlptsensei.com — a second deliberate gap-fill, this time found by
    # comparing this dataset against the real Minna no Nihongo 1 lesson
    # sequence (see the "REORDER PASS" comment in scripts/bab_lists.py):
    # these four are core absolute-beginner patterns (Minna lessons
    # 2/3/6-7) that jlptsensei's N5 list simply doesn't carry as their own
    # numbered rows, but a real N5 curriculum cannot skip them.
    "これ／それ／あれ・この／その／あの",
    "ここ／そこ／あそこ",
    "ません",
    "あげます／もらいます",
]

assert len(N5_GRAMMAR) == 89, len(N5_GRAMMAR)
assert len(set(N5_GRAMMAR)) == 89, "duplicate pattern in N5_GRAMMAR"

# N4_GRAMMAR is sourced the same way (jlptsensei.com's N4 grammar list,
# https://jlptsensei.com/jlpt-n4-grammar-list/, fetched across its 4
# paginated pages). The page states "JLPT N4 Grammar List total: (132)"
# and 132 rows were counted across all 4 pages.
#
# Two pairs of rows render as literally identical plain text in the
# source's pattern column — のに (twice) and そうだ (twice) — because
# jlptsensei distinguishes two separate N4 grammar points per pair that
# happen to share the same base text: のに as the contrastive "even
# though" (逆接) vs. the purpose-marking "in order to/for ~ing" (目的);
# そうだ as hearsay "I heard that ~" (伝聞) vs. appearance "looks/seems
# like ~" (様態). Unlike N5's bundled rows (which stay exactly as the
# source presents them since they're genuinely one row each), leaving
# these as bare duplicate strings would both fail this file's own
# uniqueness assertion and make two list entries indistinguishable in
# the app UI, so each pair is disambiguated here with its standard
# grammatical qualifier in parentheses — content, not cosmetic, since
# the two members of each pair have different meaning/formation/usage
# notes when authored.
N4_GRAMMAR = [
    "間（あいだ）",
    "間に（あいだに）",
    "あまり～ない",
    "後で（あとで）",
    "ば",
    "場合は（ばあいは）",
    "ばかり",
    "だけで",
    "出す（だす）",
    "でございます",
    "でも",
    "ではないか",
    "が必要（がひつよう）",
    "がする",
    "がり",
    "がる / がっている",
    "ございます",
    "始める（はじめる）",
    "はずだ",
    "はずがない",
    "必要がある（ひつようがある）",
    "意向形（いこうけい）",
    "いらっしゃる",
    "いたします",
    "じゃないか",
    "かどうか",
    "かしら",
    "かい",
    "かもしれない",
    "かな",
    "から作る（からつくる）",
    "きっと",
    "頃（ころ / ごろ）",
    "こと",
    "ことがある",
    "ことができる",
    "ことになる",
    "ことにする",
    "くする",
    "急に（きゅうに）",
    "までに",
    "まま",
    "または",
    "みたいだ",
    "みたいな",
    "みたいに",
    "も",
    "な",
    "など",
    "ながら",
    "なかなか～ない",
    "なければいけない",
    "なければならない",
    "なら",
    "なさい",
    "なさる",
    "に気がつく",
    "に見える",
    "にする",
    "にくい",
    "の中で",
    "のに（逆接）",
    "のに（目的）",
    "のは〜だ",
    "お～ください",
    "お～になる",
    "おきに",
    "終わる（おわる）",
    "られる",
    "らしい",
    "さ",
    "さっき",
    "させられる",
    "させる",
    "させてください",
    "さすが",
    "し",
    "そんなに",
    "それでも",
    "それに",
    "そうだ（伝聞）",
    "そうだ（様態）",
    "そうに / そうな",
    "たばかり",
    "たところ",
    "他動詞 & 自動詞（たどうし & じどうし）",
    "たがる",
    "たら",
    "たらどう",
    "たらいいですか",
    "て / で",
    "てあげる",
    "てほしい",
    "ていく",
    "ていた",
    "ていただけませんか",
    "てくれる",
    "てくる",
    "てみる",
    "てもらう",
    "ておく",
    "てしまう / ちゃう",
    "てすみません",
    "てやる",
    "てよかった",
    "ているところ",
    "ても",
    "と",
    "と言ってもいい（といってもいい）",
    "という",
    "ということ",
    "と言われている（といわれている）",
    "と聞いた（ときいた）",
    "と思う（とおもう）",
    "とか～とか",
    "ところ",
    "続ける（つづける）",
    "って",
    "受身形（うけみけい）",
    "は〜が… は",
    "やすい",
    "やっと",
    "より",
    "予定だ（よていだ）",
    "ようだ",
    "ように / ような",
    "ようになる",
    "ようにする",
    "ようと思う（ようとおもう）",
    "ぜひ",
    "全然～ない（ぜんぜん～ない）",
    "づらい",
]

assert len(N4_GRAMMAR) == 132, len(N4_GRAMMAR)
assert len(set(N4_GRAMMAR)) == 132, "duplicate pattern in N4_GRAMMAR"

# N3_GRAMMAR is sourced the same way (jlptsensei.com's N3 grammar list,
# https://jlptsensei.com/jlpt-n3-grammar-list/, fetched across its 5
# paginated pages). The page states "JLPT N3 Grammar List total: (182)"
# and 182 rows were counted across all 5 pages.
N3_GRAMMAR = [
    "上げる（あげる）",
    "あまり",
    "あまりにも",
    "合う（あう）",
    "ばいい",
    "ばよかった",
    "ば～ほど",
    "ば～のに",
    "ばかりで",
    "ばかりでなく",
    "べきだ",
    "べきではない",
    "別に～ない（べつに～ない）",
    "ぶりに",
    "中（ちゅう）",
    "だけ",
    "だけでなく",
    "だけど",
    "だらけ",
    "どんなに～ても",
    "どうしても",
    "ふりをする",
    "ふと",
    "がち",
    "がたい",
    "気味（ぎみ）",
    "ごとに",
    "ほど",
    "ほど～ない",
    "一度に（いちどに）",
    "いくら～ても",
    "一方だ（いっぽうだ）",
    "一体（いったい）",
    "じゃない",
    "か何か（かなにか）",
    "かける",
    "から〜にかけて",
    "代わりに（かわりに）",
    "結果（けっか）",
    "結局（けっきょく）",
    "決して～ない（けっして～ない）",
    "切れない（きれない）",
    "きり",
    "切る（きる）",
    "っけ",
    "込む（こむ）",
    "こそ",
    "こと",
    "ことから",
    "ことになっている",
    "ことはない",
    "ことは～が",
    "くらい / ぐらい",
    "くせに",
    "まるで",
    "まさか",
    "めったに～ない",
    "も～ば～も",
    "もしかしたら",
    "もしも〜たら",
    "向け（むけ）",
    "向き（むき）",
    "むしろ",
    "ながらも",
    "ないことはない",
    "ないと",
    "なかなか",
    "なんか / なんて / など",
    "直す（なおす）",
    "なるべく",
    "なぜなら",
    "んだって",
    "に違いない（にちがいない）",
    "に反して（にはんして）",
    "にかけて",
    "に関する / に関して（にかんする / にかんして）",
    "にかわって / にかわり",
    "に比べて（にくらべて）",
    "に慣れる（になれる）",
    "において / における",
    "にしたがって",
    "にしても",
    "にしては",
    "に対して（にたいして）",
    "にとって",
    "について",
    "につれて",
    "には",
    "によると /によれば",
    "によって / による",
    "のでしょうか",
    "を中心に（をちゅうしんに）",
    "をはじめ",
    "を込めて（をこめて）",
    "を通じて / を通して（をつうじて / をとおして）",
    "おかげで",
    "っぱなし",
    "っぽい",
    "さえ",
    "さえ～ば",
    "際に（さいに）",
    "最中に（さいちゅうに）",
    "さらに",
    "さて",
    "せいで",
    "せいぜい",
    "しばらく",
    "しかない",
    "そのために",
    "それとも",
    "そうもない /そうにない",
    "すでに",
    "すなわち",
    "数量 + は（すうりょう + は）",
    "たものだ",
    "たとたん",
    "たびに",
    "ために",
    "確かに（たしかに）",
    "たて",
    "たとえ～ても",
    "例えば（たとえば）",
    "たって",
    "てばかりいる",
    "てごらん",
    "てはじめて",
    "てからでないと",
    "てしょうがない・てしかたがない",
    "て済む（てすむ）",
    "てはいけないから",
    "ている場合じゃない（ているばあいじゃない）",
    "的（てき）",
    "ても始まらない（てもはじまらない）",
    "ても構わない（てもかまわない）",
    "てもしょうがない / てもしかたがない",
    "と言えば（といえば）",
    "といい / たらいい",
    "といっても",
    "ということだ",
    "というのは",
    "と言うと（というと）",
    "というより",
    "とみえる / とみえて",
    "とすれば・としたら・とすると",
    "と共に（とともに）",
    "途中で/途中に（とちゅうで/とちゅうに）",
    "ところで",
    "ところが",
    "とおりに",
    "通す（とおす）",
    "として",
    "とても～ない",
    "とは限らない（とはかぎらない）",
    "つい",
    "ついに",
    "ついでに",
    "つまり",
    "つもりだった",
    "つもりで",
    "うちに",
    "上で（うえで）",
    "上に（うえに）",
    "は別として（はべつとして）",
    "はもちろん",
    "は～で有名（は～でゆうめい）",
    "わけだ",
    "わけではない",
    "わけがない",
    "わけにはいかない",
    "割に（わりに）",
    "わざと",
    "わざわざ",
    "よりも",
    "ようがない",
    "ような気がする（ようなきがする）",
    "ように",
    "ように見える（ようにみえる）",
    "ようとしない",
    "ようとする",
    "ずに",
    "ずにはいられない",
    "ずつ",
]

assert len(N3_GRAMMAR) == 182, len(N3_GRAMMAR)
assert len(set(N3_GRAMMAR)) == 182, "duplicate pattern in N3_GRAMMAR"

# N2_GRAMMAR is sourced the same way (jlptsensei.com's N2 grammar list,
# https://jlptsensei.com/jlpt-n2-grammar-list/, fetched across its 5
# paginated pages). The page states "JLPT N2 Grammar List total: (197)"
# and 197 rows were counted across all 5 pages.
#
# The source page marks its "より" row with a footnote-style bracket
# ("より [2]") — a site UI annotation, not part of the grammar text
# itself — dropped here, keeping just "より". Two rows in this list are
# exact-string repeats of an N4 pattern (ばかり, より): unlike N5/N4's
# bundled-variant rows or N4's のに/そうだ pairs (which are the source
# distinguishing two senses of the same surface text), these are the
# source re-listing the *same* grammar point because N2 usage adds a
# nuance beyond the N4 entry. Handled the same way as the six existing
# N5/N4-vs-N3/N4 cross-level reuses documented in CLAUDE.md: identical
# `pattern` text is fine, kept unique via an incremented `id` suffix at
# authoring time (bakari2, yori2), with the nuance difference recorded
# in usageNotes and cross-linked via similarPatterns.
N2_GRAMMAR = [
    "あげく",
    "あるいは",
    "ばかり",
    "ばかりだ",
    "ばかりか",
    "ばかりに",
    "ちなみに",
    "ちっとも～ない",
    "だけあって",
    "だけましだ",
    "だけに",
    "だけのことはある",
    "だけは",
    "だって",
    "でしかない",
    "どころではない",
    "どころか",
    "どうやら",
    "どうせ",
    "得ない（えない）",
    "得る（える / うる）",
    "再び（ふたたび）",
    "ふうに",
    "がきっかけで / をきっかけに",
    "げ",
    "逆に（ぎゃくに）",
    "反面（はんめん）",
    "果たして（はたして）",
    "一応（いちおう）",
    "以外（いがい）",
    "以上に（いじょうに）",
    "以上は（いじょうは）",
    "いきなり",
    "一気に（いっきに）",
    "一方で（いっぽうで）",
    "いわゆる",
    "いよいよ",
    "上（じょう）",
    "かのように",
    "かと思ったら（かとおもったら）",
    "か～ないかのうちに",
    "かえって",
    "限り（かぎり）",
    "甲斐がある（かいがある）",
    "かねない",
    "かねる",
    "から言うと（からいうと）",
    "からこそ",
    "から見ると（からみると）",
    "からには",
    "からして",
    "からすると / からすれば",
    "からと言って（からといって）",
    "っこない",
    "ことだ",
    "ことだから",
    "ことか",
    "ことなく",
    "ことに",
    "ことにはならない",
    "くせして",
    "まだしも",
    "まい",
    "ままに",
    "全く～ない（まったく～ない）",
    "もかまわず",
    "も当然だ（もとうぜんだ）",
    "もの / もん",
    "ものだ",
    "ものだから",
    "ものではない",
    "ものがある",
    "ものか / もんか",
    "ものなら",
    "ものの",
    "もっとも",
    "もう少しで（もうすこしで）",
    "ないではいられない",
    "ないことには～ない",
    "中を / 中では（なかを / なかでは）",
    "なくはない / なくもない",
    "なくて済む（なくてすむ）",
    "何も～ない（なにも～ない）",
    "なお",
    "ねばならない",
    "にあたって",
    "にほかならない",
    "に限らず（にかぎらず）",
    "に限る（にかぎる）",
    "に限って（にかぎって）",
    "に関わらず（にかかわらず）",
    "に関わる（にかかわる）",
    "に決まっている（にきまっている）",
    "に越したことはない（にこしたことはない）",
    "に応えて（にこたえて）",
    "に加えて（にくわえて）",
    "に基づいて（にもとづいて）",
    "に向かって（にむかって）",
    "に応じて（におうじて）",
    "に際して（にさいして）",
    "に先立ち（にさきだち）",
    "にせよ/ にしろ",
    "にしろ～にしろ",
    "にしたら / にすれば",
    "にしても～にしても",
    "に沿って（にそって）",
    "に相違ない（にそういない）",
    "に過ぎない（にすぎない）",
    "に伴って（にともなって）",
    "につけ",
    "につき",
    "にわたって",
    "にも関わらず（にもかかわらず）",
    "にて",
    "のももっともだ",
    "の下で（のもとで）",
    "の上では（のうえでは）",
    "のみ",
    "のみならず",
    "ぬ",
    "抜きにして / 抜きで（ぬきにして/ ぬきで）",
    "抜く（ぬく）",
    "を契機に（をけいきに）",
    "をめぐって",
    "をもとに",
    "を除いて（をのぞいて）",
    "を問わず（をとわず）",
    "お～願う（お～ねがう）",
    "おまけに",
    "恐らく（おそらく）",
    "恐れがある（おそれがある）",
    "及び（および）",
    "ろくに～ない",
    "幸いなことに（さいわいなことに）",
    "せいか",
    "せっかく",
    "せめて",
    "次第（しだい）",
    "次第で（しだいで）",
    "次第に（しだいに）",
    "しかも",
    "その上（そのうえ）",
    "それなのに",
    "それなら",
    "それにしても",
    "そう言えば（そういえば）",
    "そうすると",
    "末に（すえに）",
    "少しも～ない（すこしも～ない）",
    "少なくとも（すくなくとも）",
    "直ちに（ただちに）",
    "たまえ",
    "てばかりはいられない",
    "てでも",
    "て以来（ていらい）",
    "ていては",
    "てこそ",
    "てまで",
    "てならない",
    "てたまらない",
    "て当然だ",
    "ては / では",
    "てはいられない",
    "てはならない",
    "ては～ては",
    "と同時に",
    "といった",
    "というふうに",
    "ということは",
    "というものだ",
    "というものではない",
    "と考えられる",
    "とか（で）",
    "とっくに",
    "ところだった",
    "ところに",
    "ところを見ると",
    "とも",
    "として～ない",
    "としても",
    "つつ",
    "つつある",
    "上は",
    "はもとより",
    "はともかく",
    "わずかに",
    "やがて",
    "やら～やら",
    "よほど / よっぽど",
    "より",
    "よりほかない",
    "ようでは",
    "ようではないか",
    "ようか～まいか",
    "要するに",
    "ざるを得ない",
    "ずに済む",
]

assert len(N2_GRAMMAR) == 197, len(N2_GRAMMAR)
assert len(set(N2_GRAMMAR)) == 197, "duplicate pattern in N2_GRAMMAR"

# N1_GRAMMAR is sourced the same way (jlptsensei.com's N1 grammar list,
# https://jlptsensei.com/jlpt-n1-grammar-list/, fetched across its 7
# paginated pages). The page states "JLPT N1 Grammar List total: (253)"
# and 253 rows were counted across all 7 pages.
#
# Three rows are exact-string repeats of earlier-level patterns: bare
# "に" (page 3, repeats N5), bare "という" (page 6, repeats N4), and bare
# "さ" (page 5, repeats N4). Handled the same way as the eight existing
# cross-level reuses documented in CLAUDE.md — identical `pattern` text
# is fine, kept unique via an incremented `id` suffix at authoring time
# (`ni2`, `to_iu2`, `sa2`), with the different (advanced/literary/N1-only)
# nuance recorded in usageNotes and cross-linked via similarPatterns.
N1_GRAMMAR = [
    "敢えて（あえて）",
    "あくまでも",
    "案の定（あんのじょう）",
    "あらかじめ",
    "あっての",
    "ばこそ",
    "ばそれまでだ / たらそれまでだ",
    "べからず / べからざる",
    "べく",
    "べくもない",
    "べくして",
    "びる / びて / びた",
    "ぶり / っぷり",
    "ぶる / ぶって / ぶった",
    "だに / だにしない",
    "だの～だの",
    "だろうに",
    "であれ / であろうと",
    "であれ～であれ",
    "でもあり～でもある",
    "でも何でもない / くも何ともない（でもなんでもない / くもなんともない）",
    "でなくてなんだろう",
    "ではあるまいか",
    "ではあるまいし",
    "では済まない（ではすまない）",
    "どうにも～ない",
    "が早いか（がはやいか）",
    "が/も～なら、～も～だ",
    "がましい",
    "がてら",
    "ごとき / ごとく / ごとし",
    "ぐるみ",
    "羽目になる（はめになる）",
    "ほどのことではない",
    "ほうがましだ",
    "放題（ほうだい）",
    "いかんだ / いかんでは / いかんによっては",
    "いかんにかかわらず / いかんによらず / いかんをとわず",
    "いかなる",
    "いかに",
    "いかにも",
    "いずれにしても / いずれにしろ / いずれにせよ",
    "じみた",
    "か否か（かいなか）",
    "かと思いきや（かとおもいきや）",
    "限りだ（かぎりだ）",
    "甲斐もなく（かいもなく）",
    "可能性がある（かのうせいがある）",
    "からある / からする / からの",
    "かれ～かれ",
    "かたがた",
    "かたわら",
    "かつて",
    "嫌いがある（きらいがある）",
    "切りがない（きりがない）",
    "きっての",
    "極まる / 極まりない（きわまる / きわまりない）",
    "こそあれ",
    "こそすれ",
    "こそ「～が・けれど」",
    "ことごとく",
    "ことこの上ない / この上ない / この上なく（ことこのうえない / このうえない / このうえなく）",
    "こともあって",
    "ことなしに",
    "ことのないように",
    "こととて",
    "くらいなら",
    "くらいのものだ",
    "までだ / までのことだ",
    "までもない / までもなく",
    "まじき",
    "まくる",
    "まみれ",
    "まるっきり",
    "めく",
    "も同然だ（もどうぜんだ）",
    "もさることながら",
    "もしないで",
    "もはや",
    "もので",
    "ものを",
    "ものと思われる / ものと見られる（ものとおもわれる / ものとみられる）",
    "ものとする",
    "ものとして",
    "もしくは",
    "んばかりに",
    "んがために",
    "ながらに / ながらの",
    "ないまでも",
    "ないものでもない",
    "ないものか / ないものだろうか",
    "ないとも限らない（ないともかぎらない）",
    "なくしては",
    "並み（なみ）",
    "なんという / なんと / なんて",
    "何しろ（なにしろ）",
    "ならでは",
    "ならいざしらず / はいざしらず",
    "なり",
    "なりに / なりの",
    "なりとも",
    "なり～なり",
    "なしに / なしで",
    "に",
    "に値する（にあたいする）",
    "にあって",
    "に引き換え（にひきかえ）",
    "に至る / に至った（にいたる / にいたった）",
    "に至るまで（にいたるまで）",
    "に至っても（にいたっても）",
    "に至っては（にいたっては）",
    "に言わせれば（にいわせれば）",
    "に限ったことではない（にかぎったことではない）",
    "にかかっては / にかかったら / にかかると / かかれば",
    "にかかっている",
    "にかこつけて",
    "にかまけて",
    "に難くない（にかたくない）",
    "にまつわる",
    "に則って（にのっとって）",
    "に先駆けて（にさきがけて）",
    "に忍びない（にしのびない）",
    "にしたところで / としたところで",
    "にして",
    "に即して（にそくして）",
    "に耐える / に耐えない（にたえる / にたえない）",
    "に足らない / に足りない（にたらない / にたりない）",
    "に足る / に足りる（にたる / にたりる）",
    "に照らして（にてらして）",
    "にとどまらず",
    "には無理がある（にはむりがある）",
    "によらず",
    "に～を重ねて（に～をかさねて）",
    "にもほどがある",
    "にも増して（にもまして）",
    "には当たらない（にはあたらない）",
    "には及ばない（にはおよばない）",
    "の至り（のいたり）",
    "の極み（のきわみ）",
    "のなんのって",
    "のやら / ものやら / ことやら",
    "のやら～のやら",
    "を踏まえて（をふまえて）",
    "を経て（をへて）",
    "を控えて（をひかえて）",
    "をいいことに",
    "を顧みず / も顧みず（をかえりみず / もかえりみず）",
    "を限りに（をかぎりに）",
    "を兼ねて（をかねて）",
    "を皮切りに（をかわきりに）",
    "を機に（をきに）",
    "を禁じ得ない（をきんじえない）",
    "をものともせずに",
    "をもって / をもちまして",
    "をおいて～ない",
    "を押して / を押し切って（をおして / をおしきって）",
    "を境に（をさかいに）",
    "を余儀なくされる（をよぎなくされる）",
    "をよそに",
    "を前提として（をぜんていとして）",
    "思いをする（おもいをする）",
    "折に（おりに）",
    "およそ",
    "さ",
    "さも",
    "さもないと",
    "さぞ",
    "始末だ（しまつだ）",
    "そばから",
    "そびれる",
    "損なう / 損ねる / 損じる（そこなう / そこねる / そんじる）",
    "術がない（すべがない）",
    "すら / ですら",
    "た弾みに / た拍子に（たはずみに / たひょうしに）",
    "たことにする / たことになる",
    "たところで",
    "たつもりはない",
    "ただ～のみだ",
    "ためしがない",
    "たら最後 / たが最後（たらさいご / たがさいご）",
    "たら～たで",
    "たら～ところだ",
    "たりとも",
    "たるもの / たる",
    "て敵わない（てかなわない）",
    "てからというもの",
    "てみせる",
    "てしかるべきだ",
    "て済むことではない（てすむことではない）",
    "てやまない",
    "手前（てまえ）",
    "てもどうにもならない",
    "ても差し支えない（てもさしつかえない）",
    "ても知らない（てもしらない）",
    "と相まって（とあいまって）",
    "とあれば",
    "とあって",
    "とばかりに",
    "といえども",
    "と言えなくもない（といえなくもない）",
    "といい～といい",
    "といったらない",
    "という",
    "というか～というか",
    "というもの",
    "というところだ / といったところだ",
    "というわけだ",
    "というわけではない",
    "といわず～といわず",
    "ときている",
    "とみると",
    "と見るや（とみるや）",
    "となると / となれば",
    "とされる",
    "ときたら",
    "ところを",
    "ともあろうものが",
    "ともなく / ともなしに",
    "ともすれば",
    "とも～とも",
    "とりわけ",
    "としたことが",
    "とっさに",
    "とて",
    "とは",
    "とはいえ",
    "とは比べものにならない（とはくらべものにならない）",
    "とは打って変わって / とは打って変わり（とはうってかわって / とはうってかわり）",
    "つ～つ",
    "尽くす（つくす）",
    "ってば / ったら",
    "うちに入らない（うちにはいらない）",
    "わ",
    "はどうであれ",
    "はおろか",
    "はさておき",
    "はそっちのけで / をそっちのけで",
    "わ〜わで",
    "や否や（やいなや）",
    "やしない",
    "やれ～やれ",
    "ようが / ようと",
    "ようが～ようが / ようと～ようと",
    "ようによっては / ようでは",
    "ようにも～ない",
    "ようと～まいと / ようが～まいが",
    "ゆえに",
    "ぞ・ぜ",
    "ずじまい",
    "ずにはおかない / ないではおかない",
    "ずには済まない / ないでは済まない",
    "ずとも",
    "ずくめ",
]

assert len(N1_GRAMMAR) == 253, len(N1_GRAMMAR)
assert len(set(N1_GRAMMAR)) == 253, "duplicate pattern in N1_GRAMMAR"
