"""
bunpou_meaning_en.py

Locked source of truth for the English translations of Bunpou grammar
content: BunpouEntry.meaningEn/formationEn/usageNotesEn, and
SentenceExample.translationEn (the shared module-neutral class).
apply_bunpou_meaning_en.py reads this and patches
assets/data/bunpou_data.json, so translations live in exactly one
place.

Key format (four content kinds share one dict, disambiguated by
suffix):
    "{id}|meaning"      -> the pattern's meaning gloss
    "{id}|formation"    -> the formation/conjugation rule text
    "{id}|usageNotes"   -> the usage-notes prose
    "{id}|se{i}"        -> the i-th (0-based) sentenceExample's
                            translation

Code-gap note: BunpouEntry.formationEn/localizedFormation did not
exist before this rollout — `formation` was rendered raw in
BunpouDetailScreen with no localization at all. Fixed as part of this
rollout (bunpou_entry.dart + bunpou_detail_screen.dart). Separately,
meaningEn/usageNotesEn already existed as model fields but were never
actually read in BunpouEntry.fromJson — so even already-authored
translations would never have loaded. Both gaps fixed in the same
pass, verified with flutter analyze before any content was authored.

STATUS: in progress. Total scope, counted directly from
    assets/data/bunpou_data.json (848 real entries, 0 placeholders):
        meaning:            848
        formation:          848
        usageNotes:         848
        sentence examples: 2,544
        TOTAL:             5,088
    This corrects the stale "3,839" figure quoted elsewhere in
    CLAUDE.md, which undercounted by not including formation (a field
    that had no English path at all until this rollout) and possibly
    miscounted sentence examples. Batched by JLPT level (N5/N4/N3/N2/N1),
    same verify-patch-apply-commit cycle as every other rollout in
    this codebase.
"""

BUNPOU_MEANING_EN = {
    # ---------------- N5 (84 patterns, 504 fields) ----------------
    "bunpou_cha_ikenai|meaning": "Must not ~ (casual form)",
    "bunpou_cha_ikenai|formation": "Verb te-form (て→ちゃ) + いけない; for nouns/na-adjectives use じゃいけない (だ→じゃ)",
    "bunpou_cha_ikenai|usageNotes": "A casual contraction of てはいけない (verbs) / ではいけない (nouns/na-adjectives), used in everyday conversation with friends/family. In formal situations, use the full form てはいけない/ではいけない.",
    "bunpou_cha_ikenai|se0": "You mustn't be late to class, you know.",
    "bunpou_cha_ikenai|se1": "You mustn't forget to do your homework.",
    "bunpou_cha_ikenai|se2": "You mustn't smoke here.",
    "bunpou_da_desu|meaning": "The copula \"to be\" — casual/formal form",
    "bunpou_da_desu|formation": "Noun/na-adjective + だ (casual) or です (formal/polite)",
    "bunpou_da_desu|usageNotes": "だ is used in casual conversation or inner monologue, です is used in formal/polite situations such as with someone you've just met or an elder. だ is often omitted entirely in casual women's speech.",
    "bunpou_da_desu|se0": "I am a student.",
    "bunpou_da_desu|se1": "I am a student.",
    "bunpou_da_desu|se2": "Today is sunny.",
    "bunpou_dake|meaning": "Only, just",
    "bunpou_dake|formation": "Noun/verb dictionary form + だけ",
    "bunpou_dake|usageNotes": "Shows a limit in quantity/scope, similar to \"only\" in English. Can attach directly to a noun or come after another particle.",
    "bunpou_dake|se0": "I'll only eat this.",
    "bunpou_dake|se1": "Only one person came.",
    "bunpou_dake|se2": "Please wait just a moment.",
    "bunpou_darou|meaning": "Probably, I think (conjecture)",
    "bunpou_darou|formation": "Noun/adjective/verb dictionary form + だろう",
    "bunpou_darou|usageNotes": "The casual form of でしょう, expressing the speaker's guess/estimate. Often used by men in casual speech; rising intonation can turn it into a rhetorical question \"right?\".",
    "bunpou_darou|se0": "It'll probably rain tomorrow.",
    "bunpou_darou|se1": "He's probably already gone home.",
    "bunpou_darou|se2": "This should be enough, right?",
    "bunpou_de|meaning": "Particle marking the place an action happens, or the means/method",
    "bunpou_de|formation": "Noun + で",
    "bunpou_de|usageNotes": "Unlike the particle に (location of existence), で marks the place where an activity takes place, or the tool/means used to do something.",
    "bunpou_de|se0": "Studying at the library.",
    "bunpou_de|se1": "Going to school by bus.",
    "bunpou_de|se2": "Please write with a pen.",
    "bunpou_demo|meaning": "But, even so / also (with a question word, \"~ever\")",
    "bunpou_demo|formation": "Sentence + でも (at the start as a conjunction); or Question word + でも",
    "bunpou_demo|usageNotes": "As a conjunction at the start of a sentence it means \"but/however\". Attached after a question word (nan/dare/itsu) it means \"whatever/whoever/whenever\".",
    "bunpou_demo|se0": "I'm tired. But, I'll try my best.",
    "bunpou_demo|se1": "I eat anything.",
    "bunpou_demo|se2": "Come whenever.",
    "bunpou_deshou|meaning": "Probably, most likely (polite conjecture)",
    "bunpou_deshou|formation": "Noun/adjective/verb dictionary form + でしょう",
    "bunpou_deshou|usageNotes": "The polite form of だろう, expressing a guess with a high degree of certainty. Also used in weather forecasts and to ask for confirmation with rising intonation.",
    "bunpou_deshou|se0": "It'll probably be sunny tomorrow.",
    "bunpou_deshou|se1": "He's probably a teacher.",
    "bunpou_deshou|se2": "Is this good enough?",
    "bunpou_donna|meaning": "What kind of, what sort of",
    "bunpou_donna|formation": "どんな + noun",
    "bunpou_donna|usageNotes": "A question word asking about the type/characteristics of something, always directly followed by a noun (no の particle in between).",
    "bunpou_donna|se0": "What kind of movie do you like?",
    "bunpou_donna|se1": "What kind of person?",
    "bunpou_donna|se2": "I want to always smile no matter the situation.",
    "bunpou_doushite|meaning": "Why",
    "bunpou_doushite|formation": "どうして + sentence",
    "bunpou_doushite|usageNotes": "A synonym of なぜ, asking for a reason/cause. どうして feels a bit more emotional/personal compared to なぜ, which is more neutral/formal.",
    "bunpou_doushite|se0": "Why are you late?",
    "bunpou_doushite|se1": "Why are you crying?",
    "bunpou_doushite|se2": "Why do you think that?",
    "bunpou_douyatte|meaning": "How, in what way",
    "bunpou_douyatte|formation": "どうやって + verb",
    "bunpou_douyatte|usageNotes": "Asks about the method/way of doing something, different from どう, which is more general (asking about a state/condition).",
    "bunpou_douyatte|se0": "How do you get there?",
    "bunpou_douyatte|se1": "How do you use this?",
    "bunpou_douyatte|se2": "How do you study Japanese?",
    "bunpou_ga|meaning": "Subject-marking particle",
    "bunpou_ga|formation": "Noun + が",
    "bunpou_ga|usageNotes": "Marks the sentence's subject, especially when introducing new information or answering a \"who/what\" question. Unlike は, which marks an already-known/discussed topic.",
    "bunpou_ga|se0": "There's a cat.",
    "bunpou_ga|se1": "Who came?",
    "bunpou_ga|se2": "It's raining.",
    "bunpou_ga_arimasu|meaning": "There is/are (for inanimate objects)",
    "bunpou_ga_arimasu|formation": "Noun + が + あります",
    "bunpou_ga_arimasu|usageNotes": "Expresses the existence of an inanimate/non-moving object (a thing, a building, an event). For living things, use がいます.",
    "bunpou_ga_arimasu|se0": "There's a book on the table.",
    "bunpou_ga_arimasu|se1": "There's a park near the station.",
    "bunpou_ga_arimasu|se2": "There's an exam tomorrow.",
    "bunpou_ga_hoshii|meaning": "Want (to have something)",
    "bunpou_ga_hoshii|formation": "Noun + が + ほしい",
    "bunpou_ga_hoshii|usageNotes": "Expresses a desire to own an object. Used only for oneself (first person) in a plain statement; for others, a different form is needed (ほしがっている).",
    "bunpou_ga_hoshii|se0": "I want new shoes.",
    "bunpou_ga_hoshii|se1": "What do you want?",
    "bunpou_ga_hoshii|se2": "I want money.",
    "bunpou_ga_imasu|meaning": "There is/are (for living things)",
    "bunpou_ga_imasu|formation": "Noun (living thing) + が + います",
    "bunpou_ga_imasu|usageNotes": "Expresses the existence of a living thing (a person, an animal). For inanimate objects, use があります.",
    "bunpou_ga_imasu|se0": "There's a cat in the room.",
    "bunpou_ga_imasu|se1": "Do you have any siblings?",
    "bunpou_ga_imasu|se2": "There are children at the park.",
    "bunpou_hou_ga_ii|meaning": "It's better to ~",
    "bunpou_hou_ga_ii|formation": "Verb past form (~た) + ほうがいい (positive advice); verb ~ない form + ほうがいい (negative advice)",
    "bunpou_hou_ga_ii|usageNotes": "Gives advice/a recommendation. For advice not to do something, use the ~ないほうがいい form, not the dictionary form + ないほうがいい, which sounds odd.",
    "bunpou_hou_ga_ii|se0": "It's better to sleep earlier.",
    "bunpou_hou_ga_ii|se1": "You'd better go to the hospital.",
    "bunpou_hou_ga_ii|se2": "It's better not to smoke.",
    "bunpou_i_keiyoushi|meaning": "i-adjectives",
    "bunpou_i_keiyoushi|formation": "Adjectives ending in い (except きれい etc., which are actually na-adjectives); negative: い→くない; past: い→かった",
    "bunpou_i_keiyoushi|usageNotes": "One of the two adjective classes in Japanese. Can directly modify a noun (大きい家) or stand as a predicate (家が大きい) without needing an additional だ/です (though です may be added for politeness).",
    "bunpou_i_keiyoushi|se0": "This book is interesting.",
    "bunpou_i_keiyoushi|se1": "It was cold yesterday.",
    "bunpou_i_keiyoushi|se2": "This cake isn't tasty.",
    "bunpou_ichiban|meaning": "Most, number one",
    "bunpou_ichiban|formation": "いちばん + adjective/verb",
    "bunpou_ichiban|usageNotes": "Expresses the superlative \"most ~\" within a group/comparison.",
    "bunpou_ichiban|se0": "I like Japanese the most.",
    "bunpou_ichiban|se1": "This is the most expensive.",
    "bunpou_ichiban|se2": "He's the tallest in the class.",
    "bunpou_issho_ni|meaning": "Together",
    "bunpou_issho_ni|formation": "一緒に + verb",
    "bunpou_issho_ni|usageNotes": "Expresses doing something together with someone else. Often used in invitations (一緒に行きませんか).",
    "bunpou_issho_ni|se0": "Let's watch a movie together.",
    "bunpou_issho_ni|se1": "Studying together with a friend.",
    "bunpou_issho_ni|se2": "Would you like to go together?",
    "bunpou_itsumo|meaning": "Always",
    "bunpou_itsumo|formation": "いつも + verb/adjective",
    "bunpou_itsumo|usageNotes": "Expresses the habit/frequency \"always\", usually placed before the verb.",
    "bunpou_itsumo|se0": "I always eat breakfast.",
    "bunpou_itsumo|se1": "He always smiles.",
    "bunpou_itsumo|se2": "Thank you always (for your kindness).",
    "bunpou_ja_nai|meaning": "Is not (negative form of だ/です)",
    "bunpou_ja_nai|formation": "Noun/na-adjective + じゃない (casual) or ではない (somewhat formal/written)",
    "bunpou_ja_nai|usageNotes": "じゃない is a casual contraction of ではない, used in everyday conversation. ではない appears more often in writing or formal situations.",
    "bunpou_ja_nai|se0": "This isn't mine.",
    "bunpou_ja_nai|se1": "Today isn't a holiday.",
    "bunpou_ja_nai|se2": "He's not a student.",
    "bunpou_ka|meaning": "Question-marking particle",
    "bunpou_ka|formation": "Sentence + か",
    "bunpou_ka|usageNotes": "Added at the end of a sentence to turn it into a question, replacing the question mark in formal writing (though か and？ are sometimes combined in casual writing).",
    "bunpou_ka|se0": "Are you going to school tomorrow?",
    "bunpou_ka|se1": "What's this?",
    "bunpou_ka|se2": "How are you?",
    "bunpou_ka_ka|meaning": "Either ~ or ~ (connecting two uncertain alternatives)",
    "bunpou_ka_ka|formation": "Noun/sentence + か + Noun/sentence + か",
    "bunpou_ka_ka|usageNotes": "Connects two uncertain choices, similar to \"or\" in a context of uncertainty, not a direct offer of options like それとも.",
    "bunpou_ka_ka|se0": "Please choose coffee or tea.",
    "bunpou_ka_ka|se1": "I haven't decided whether to go or not.",
    "bunpou_ka_ka|se2": "I forget whether it's tomorrow or the day after.",
    "bunpou_kara|meaning": "From (starting point); because (reason)",
    "bunpou_kara|formation": "Noun + から (starting point); Sentence (plain/desu-masu form) + から (reason)",
    "bunpou_kara|usageNotes": "Two main functions: marking a starting point in time/place (\"from\"), and connecting a reason before its result (\"because\"). The sentence context determines which meaning applies.",
    "bunpou_kara|se0": "Starting from nine o'clock.",
    "bunpou_kara|se1": "Because it's raining, I'm not going.",
    "bunpou_kara|se2": "I came from Japan.",
    "bunpou_kata|meaning": "The way (of doing something)",
    "bunpou_kata|formation": "Verb ~ます form (drop ます) + 方",
    "bunpou_kata|usageNotes": "Turns a verb into a noun meaning \"the way to do X\", e.g. 食べます→食べ方 (the way to eat). Different from どうやって, which asks about the method verbally.",
    "bunpou_kata|se0": "Please teach me how to use it.",
    "bunpou_kata|se1": "I don't know how to read this kanji.",
    "bunpou_kata|se2": "The way to make it is very easy.",
    "bunpou_kedo|meaning": "But, although (casual)",
    "bunpou_kedo|formation": "Sentence (plain form) + けど",
    "bunpou_kedo|usageNotes": "A casual version of けれども/が, used in everyday conversation to connect two contrasting clauses or give background before the main statement.",
    "bunpou_kedo|se0": "Even though it's expensive, I'll buy it.",
    "bunpou_kedo|se1": "Sorry, but I'm busy right now.",
    "bunpou_kedo|se2": "I want to go, but there's no time.",
    "bunpou_keredomo|meaning": "But, however (more formal than けど)",
    "bunpou_keredomo|formation": "Sentence (plain/desu-masu form) + けれども",
    "bunpou_keredomo|usageNotes": "A more formal/written form of けど, often shortened to けれど in speech that's slightly more polite than けど.",
    "bunpou_keredomo|se0": "Even though it's hard, I'll try my best.",
    "bunpou_keredomo|se1": "Even though he's busy, he helped me.",
    "bunpou_keredomo|se2": "Even though it's cheap, the quality is good.",
    "bunpou_mada|meaning": "Still, not yet",
    "bunpou_mada|formation": "まだ + verb/adjective (affirmative = \"still\"; negative = \"not yet\")",
    "bunpou_mada|usageNotes": "With an affirmative form it means \"still\" (a condition continues); with a negative form it means \"not yet\" (hasn't happened yet).",
    "bunpou_mada|se0": "It's still raining.",
    "bunpou_mada|se1": "I haven't eaten yet.",
    "bunpou_mada|se2": "He's still a child.",
    "bunpou_mada_te_imasen|meaning": "Haven't done ~ yet",
    "bunpou_mada_te_imasen|formation": "まだ + Verb te-form + いません",
    "bunpou_mada_te_imasen|usageNotes": "Expresses that an action hasn't been finished/done yet, emphasizing the \"not yet\" aspect compared to a plain negative past form.",
    "bunpou_mada_te_imasen|se0": "I haven't done my homework yet.",
    "bunpou_mada_te_imasen|se1": "I haven't met him yet.",
    "bunpou_mada_te_imasen|se2": "I haven't received a reply yet.",
    "bunpou_made|meaning": "Until (a time/place limit)",
    "bunpou_made|formation": "Noun + まで",
    "bunpou_made|usageNotes": "Marks the end point of a span of time or place, the natural counterpart of から (from ~ to ~).",
    "bunpou_made|se0": "Working until five o'clock.",
    "bunpou_made|se1": "Walking as far as the station.",
    "bunpou_made|se2": "Please wait until next week.",
    "bunpou_mae_ni|meaning": "Before",
    "bunpou_mae_ni|formation": "Verb dictionary form + 前に; or Noun + の + 前に",
    "bunpou_mae_ni|usageNotes": "Expresses the time order \"before doing X\". The verb preceding it is always in the dictionary form, regardless of the overall sentence's tense.",
    "bunpou_mae_ni|se0": "Brushing teeth before sleeping.",
    "bunpou_mae_ni|se1": "Washing hands before eating.",
    "bunpou_mae_ni|se2": "Please turn off the light before going out.",
    "bunpou_masen_ka|meaning": "Would you like to ~? (polite invitation)",
    "bunpou_masen_ka|formation": "Verb ~ます form (negative form) + か",
    "bunpou_masen_ka|usageNotes": "A polite invitation form, literally asking \"wouldn't you like to ~?\" but functioning as a softer invitation than ~ましょう.",
    "bunpou_masen_ka|se0": "Would you like to watch a movie together?",
    "bunpou_masen_ka|se1": "Would you like some tea?",
    "bunpou_masen_ka|se2": "Would you like to go somewhere this weekend?",
    "bunpou_mashou|meaning": "Let's ~ (invitation)",
    "bunpou_mashou|formation": "Verb ~ます form (drop ます) + ましょう",
    "bunpou_mashou|usageNotes": "Invites the listener to do something together, more direct/certain than ~ませんか, which asks more about willingness.",
    "bunpou_mashou|se0": "Let's try our best together.",
    "bunpou_mashou|se1": "Let's go home now.",
    "bunpou_mashou|se2": "Let's rest for a bit.",
    "bunpou_mashou_ka|meaning": "Shall I ~? / let's ~, shall we?",
    "bunpou_mashou_ka|formation": "Verb ~ます form (drop ます) + ましょうか",
    "bunpou_mashou_ka|usageNotes": "Two meanings depending on context: offering help (\"shall I do this for you?\") or inviting with a lighter tone/asking agreement compared to ましょう.",
    "bunpou_mashou_ka|se0": "Shall I carry that for you?",
    "bunpou_mashou_ka|se1": "Shall I open the window?",
    "bunpou_mashou_ka|se2": "Where shall we meet?",
    "bunpou_mo|meaning": "Also, too",
    "bunpou_mo|formation": "Noun + も (replaces the particle は/が/を)",
    "bunpou_mo|usageNotes": "Expresses similarity/addition \"also\", replacing the particle は, が, or を on the noun it marks (the particles に, で, と still appear alongside も).",
    "bunpou_mo|se0": "I'm a student too.",
    "bunpou_mo|se1": "I like apples too.",
    "bunpou_mo|se2": "He's going to Japan too.",
    "bunpou_mou|meaning": "Already (affirmative); anymore (with negative, \"not ~ anymore\")",
    "bunpou_mou|formation": "もう + verb past/affirmative form; もう + verb negative form",
    "bunpou_mou|usageNotes": "With an affirmative sentence it means \"already\" (finished earlier than expected); with a negative sentence it means \"not ~ anymore\".",
    "bunpou_mou|se0": "I've already eaten.",
    "bunpou_mou|se1": "It's already time.",
    "bunpou_mou|se2": "I can't eat anymore.",
    "bunpou_na_keiyoushi|meaning": "na-adjectives",
    "bunpou_na_keiyoushi|formation": "Adjective + な + noun (when modifying); Adjective + だ/です (as a predicate, without な)",
    "bunpou_na_keiyoushi|usageNotes": "The second adjective class, grammatically behaving like a noun — needs the particle な when directly modifying a noun (静かな部屋), but uses だ/です like a noun when acting as the predicate (部屋は静かです).",
    "bunpou_na_keiyoushi|se0": "This is a quiet park.",
    "bunpou_na_keiyoushi|se1": "This city is beautiful.",
    "bunpou_na_keiyoushi|se2": "He's a cheerful child.",
    "bunpou_naa|meaning": "Sentence-final particle expressing admiration/hope (\"how ~\", \"I wish ~\")",
    "bunpou_naa|formation": "Sentence (plain form) + なあ",
    "bunpou_naa|usageNotes": "A casual sentence-final particle expressing emotion such as admiration, hope, or the speaker's own deep feeling (similar to an inner monologue), more masculine/informal than ね.",
    "bunpou_naa|se0": "Wow, that's really beautiful.",
    "bunpou_naa|se1": "I wish the holiday would come soon.",
    "bunpou_naa|se2": "If only I'd studied harder.",
    "bunpou_naide|meaning": "Without doing ~ (accompanying another verb)",
    "bunpou_naide|formation": "Verb ~ない form (drop い) + で + another verb",
    "bunpou_naide|usageNotes": "Expresses that an action is done WITHOUT doing something else first, connecting two verbs in one sentence.",
    "bunpou_naide|se0": "Going to school without eating breakfast.",
    "bunpou_naide|se1": "Going out without bringing an umbrella.",
    "bunpou_naide|se2": "Going home without saying anything.",
    "bunpou_naide_kudasai|meaning": "Please don't ~",
    "bunpou_naide_kudasai|formation": "Verb ~ない form (drop い) + でください",
    "bunpou_naide_kudasai|usageNotes": "A polite request form asking the listener NOT to do something, the negative counterpart of ~てください.",
    "bunpou_naide_kudasai|se0": "Please don't sit here.",
    "bunpou_naide_kudasai|se1": "Please don't take photos.",
    "bunpou_naide_kudasai|se2": "Please don't worry.",
    "bunpou_nai_to_ikenai|meaning": "Must ~",
    "bunpou_nai_to_ikenai|formation": "Verb ~ない form (drop い) + といけない",
    "bunpou_nai_to_ikenai|usageNotes": "Expresses the obligation \"must do X\", literally \"if you don't do X, it's not good/not allowed\". A synonym of なければならない but feels more casual.",
    "bunpou_nai_to_ikenai|se0": "I have to wake up early tomorrow.",
    "bunpou_nai_to_ikenai|se1": "I have to take my medicine.",
    "bunpou_nai_to_ikenai|se2": "I have to go home now.",
    "bunpou_nakutemo_ii|meaning": "Don't need to ~, it's okay not to ~",
    "bunpou_nakutemo_ii|formation": "Verb ~ない form (drop い) + くてもいい",
    "bunpou_nakutemo_ii|usageNotes": "Expresses that an action isn't mandatory, the opposite meaning of なければならない/ないといけない.",
    "bunpou_nakutemo_ii|se0": "You don't need to come tomorrow.",
    "bunpou_nakutemo_ii|se1": "You don't need to finish everything.",
    "bunpou_nakutemo_ii|se2": "You don't need to worry.",
    "bunpou_nakucha|meaning": "Must ~ (casual contraction)",
    "bunpou_nakucha|formation": "Verb ~ない form (drop い) + くちゃ (contraction of くては)",
    "bunpou_nakucha|usageNotes": "A casual contraction of なくては(いけない), often used in daily conversation without explicitly stating the いけない/ならない part since it's already understood from context.",
    "bunpou_nakucha|se0": "I have to go now.",
    "bunpou_nakucha|se1": "I have to do my homework.",
    "bunpou_nakucha|se2": "I have to sleep early.",
    "bunpou_nakute_wa_ikenai|meaning": "Must ~ (formal/explicit)",
    "bunpou_nakute_wa_ikenai|formation": "Verb ~ない form (drop い) + くてはいけない",
    "bunpou_nakute_wa_ikenai|usageNotes": "The full/more formal form of なくちゃ, stating an obligation explicitly. A synonym of なくてはならない and ないといけない.",
    "bunpou_nakute_wa_ikenai|se0": "Must study every day.",
    "bunpou_nakute_wa_ikenai|se1": "Must bring your passport.",
    "bunpou_nakute_wa_ikenai|se2": "Must leave earlier.",
    "bunpou_nakute_wa_naranai|meaning": "Must ~ (even more formal/written)",
    "bunpou_nakute_wa_naranai|formation": "Verb ~ない form (drop い) + くてはならない",
    "bunpou_nakute_wa_naranai|usageNotes": "A synonym of なくてはいけない but feels more formal/written, often appearing in rules or official documents.",
    "bunpou_nakute_wa_naranai|se0": "Must follow the rules.",
    "bunpou_nakute_wa_naranai|se1": "Must pay taxes.",
    "bunpou_nakute_wa_naranai|se2": "Everyone must participate.",
    "bunpou_naru|meaning": "To become",
    "bunpou_naru|formation": "i-adjective (い→く) + なる; na-adjective/noun + に + なる",
    "bunpou_naru|usageNotes": "Expresses a state/condition changing into something new, different from する, which expresses deliberately making something happen.",
    "bunpou_naru|se0": "It's getting cold.",
    "bunpou_naru|se1": "Becoming healthy again.",
    "bunpou_naru|se2": "I want to become a doctor.",
    "bunpou_n_desu|meaning": "Explanatory particle (explaining a reason/situation)",
    "bunpou_n_desu|formation": "Verb/adjective plain form + んです; noun/na-adjective + なんです",
    "bunpou_n_desu|usageNotes": "Gives an explanation/background for a situation, often used when asking for a reason or explaining something already visible/known to the listener.",
    "bunpou_n_desu|se0": "Why are you late? (asking the reason)",
    "bunpou_n_desu|se1": "(That's because) my head hurts.",
    "bunpou_n_desu|se2": "(That's because) tomorrow is a holiday.",
    "bunpou_ne|meaning": "Sentence-final particle asking for agreement/confirming together",
    "bunpou_ne|formation": "Sentence + ね",
    "bunpou_ne|usageNotes": "A sentence-final particle inviting agreement or a shared feeling with the listener, similar to \"right?\" in English.",
    "bunpou_ne|se0": "The weather's nice, isn't it.",
    "bunpou_ne|se1": "This is tasty, isn't it.",
    "bunpou_ne|se2": "See you again tomorrow, okay.",
    "bunpou_ni|meaning": "Particle marking time, static location, or destination",
    "bunpou_ni|formation": "Noun + に",
    "bunpou_ni|usageNotes": "Multi-function: marks the specific time something happens (7時に), a static location (ここにいます), or the destination of movement (東京に行きます). Different from [[ni2]] N1 (repeating a verb for emphasis, e.g. 困りに困る).",
    "bunpou_ni|se0": "Waking up at seven.",
    "bunpou_ni|se1": "Living in Tokyo.",
    "bunpou_ni|se2": "Going to school.",
    "bunpou_ni_iku|meaning": "Go to ~ (purpose of an activity)",
    "bunpou_ni_iku|formation": "Verb ~ます form (drop ます) + に行く",
    "bunpou_ni_iku|usageNotes": "Expresses going to a place with the purpose of doing a certain activity, the purpose verb is always in the ~ます stem form.",
    "bunpou_ni_iku|se0": "Going to shop.",
    "bunpou_ni_iku|se1": "Going to watch a movie.",
    "bunpou_ni_iku|se2": "Going to meet a friend.",
    "bunpou_ni_suru|meaning": "Decide on/choose ~",
    "bunpou_ni_suru|formation": "Noun + にする",
    "bunpou_ni_suru|usageNotes": "Expresses a decision choosing something from several options, often used when ordering food or making a choice.",
    "bunpou_ni_suru|se0": "I'll have/order coffee.",
    "bunpou_ni_suru|se1": "Let's go with this color.",
    "bunpou_ni_suru|se2": "Please give/choose me a quiet room.",
    "bunpou_ni_e|meaning": "To, toward (directional particle)",
    "bunpou_ni_e|formation": "Noun (place) + に/へ",
    "bunpou_ni_e|usageNotes": "Both can mark the direction of movement and are often interchangeable; へ purely emphasizes \"heading toward\", while に can also mean a more definite specific destination/end point.",
    "bunpou_ni_e|se0": "Heading toward school.",
    "bunpou_ni_e|se1": "Moving toward the east.",
    "bunpou_ni_e|se2": "Going home.",
    "bunpou_no|meaning": "Possessive particle (\"of\", \"belonging to\") or a marker turning a verb into a noun phrase",
    "bunpou_no|formation": "Noun + の + noun; or Sentence + の (nominalization)",
    "bunpou_no|usageNotes": "The main function marks possession/relation between nouns (私の本), but it can also nominalize a clause (泳ぐの好きです — the act of swimming).",
    "bunpou_no|se0": "This is my book.",
    "bunpou_no|se1": "I like swimming.",
    "bunpou_no|se2": "A Japanese teacher.",
    "bunpou_no_desu|meaning": "The polite form of んです (explanatory)",
    "bunpou_no_desu|formation": "Verb/adjective plain form + のです",
    "bunpou_no_desu|usageNotes": "A written/more formal version of んです, giving an explanation with a more polite/written tone.",
    "bunpou_no_desu|se0": "(That's because) I'm a bit tired.",
    "bunpou_no_desu|se1": "This is the reason.",
    "bunpou_no_desu|se2": "(That's because) I'm on a business trip tomorrow.",
    "bunpou_no_ga_heta|meaning": "Not good at ~",
    "bunpou_no_ga_heta|formation": "Verb dictionary form + のが下手",
    "bunpou_no_ga_heta|usageNotes": "Expresses being unskilled at an activity, the preceding verb is first nominalized with の.",
    "bunpou_no_ga_heta|se0": "I'm not good at cooking.",
    "bunpou_no_ga_heta|se1": "I'm not good at singing.",
    "bunpou_no_ga_heta|se2": "I'm not good at drawing.",
    "bunpou_no_ga_jouzu|meaning": "Good at ~",
    "bunpou_no_ga_jouzu|formation": "Verb dictionary form + のが上手",
    "bunpou_no_ga_jouzu|usageNotes": "Expresses being skilled at an activity, the opposite meaning of のが下手.",
    "bunpou_no_ga_jouzu|se0": "He's good at playing piano.",
    "bunpou_no_ga_jouzu|se1": "I'm good at cooking.",
    "bunpou_no_ga_jouzu|se2": "You're good at speaking, aren't you.",
    "bunpou_no_ga_suki|meaning": "Like doing ~",
    "bunpou_no_ga_suki|formation": "Verb dictionary form + のが好き",
    "bunpou_no_ga_suki|usageNotes": "Expresses liking an activity, same pattern as のが下手/上手, the verb is nominalized with の.",
    "bunpou_no_ga_suki|se0": "I like watching movies.",
    "bunpou_no_ga_suki|se1": "I like reading books.",
    "bunpou_no_ga_suki|se2": "I like running.",
    "bunpou_no_naka_de_ichiban|meaning": "Among ~, [A] is the most ~",
    "bunpou_no_naka_de_ichiban|formation": "Noun (group) + の中で + [A] + が + いちばん + adjective",
    "bunpou_no_naka_de_ichiban|usageNotes": "A superlative pattern within a group, stating which is the best out of several options in a category.",
    "bunpou_no_naka_de_ichiban|se0": "Among fruits, I like apples the most.",
    "bunpou_no_naka_de_ichiban|se1": "Among the class, he's the tallest.",
    "bunpou_no_naka_de_ichiban|se2": "Among the seasons, I like summer the most.",
    "bunpou_node|meaning": "Because (reason, more polite/objective than から)",
    "bunpou_node|formation": "Verb/adjective plain form + ので; noun/na-adjective + なので",
    "bunpou_node|usageNotes": "A synonym of から but feels more polite and objective/less pushy of an opinion, often used for a more neutral/formal reason.",
    "bunpou_node|se0": "Since it's raining, I brought an umbrella.",
    "bunpou_node|se1": "Since I'm tired, I'll sleep early.",
    "bunpou_node|se2": "Since tomorrow's a holiday, I'll go out.",
    "bunpou_o_go|meaning": "Honorific prefix (politeness)",
    "bunpou_o_go|formation": "お + native Japanese word (wago); ご + Chinese-derived word (kango)",
    "bunpou_o_go|usageNotes": "A prefix adding a polite/refined nuance to a noun, generally お is used for native Japanese words and ご for Chinese-derived words, though there are exceptions that must be memorized per word (お茶, お電話).",
    "bunpou_o_go|se0": "What's your name?",
    "bunpou_o_go|se1": "Is your family well?",
    "bunpou_o_go|se2": "Please give me some water.",
    "bunpou_o|meaning": "Particle marking the direct object",
    "bunpou_o|formation": "Noun + を + transitive verb",
    "bunpou_o|usageNotes": "Marks the direct object of a transitive verb, one of the most basic and frequently used particles in Japanese.",
    "bunpou_o|se0": "Eating rice.",
    "bunpou_o|se1": "Reading a book.",
    "bunpou_o|se2": "Listening to music.",
    "bunpou_o_kudasai|meaning": "Please give me ~",
    "bunpou_o_kudasai|formation": "Noun + を + ください",
    "bunpou_o_kudasai|usageNotes": "A polite request for an item, commonly used when shopping/ordering.",
    "bunpou_o_kudasai|se0": "Please give me water.",
    "bunpou_o_kudasai|se1": "Please give me two of these cakes.",
    "bunpou_o_kudasai|se2": "Please give me a receipt.",
    "bunpou_shikashi|meaning": "However (formal conjunction)",
    "bunpou_shikashi|formation": "Sentence。しかし、sentence。",
    "bunpou_shikashi|usageNotes": "A formal/written conjunction connecting two contrasting sentences, more formal compared to でも, which is used more in conversation.",
    "bunpou_shikashi|se0": "I tried my best. However, I failed.",
    "bunpou_shikashi|se1": "The weather was bad. But, it was still fun.",
    "bunpou_shikashi|se2": "It's expensive. However, the quality is good.",
    "bunpou_sorekara|meaning": "After that, then",
    "bunpou_sorekara|formation": "Sentence。それから、sentence。",
    "bunpou_sorekara|usageNotes": "A conjunction connecting a chronological sequence of events, \"after that\" or adding extra information afterward.",
    "bunpou_sorekara|se0": "I did my homework. After that, I watched TV.",
    "bunpou_sorekara|se1": "I ate breakfast. After that, I went to school.",
    "bunpou_sorekara|se2": "First I washed my hands. After that, I started cooking.",
    "bunpou_soshite|meaning": "And, then (connecting sentences/words in sequence)",
    "bunpou_soshite|formation": "Sentence。そして、sentence。",
    "bunpou_soshite|usageNotes": "A conjunction connecting two things in sequence/addition, similar to それから but more neutral (doesn't always state a time order, can just add information).",
    "bunpou_soshite|se0": "Going to the park. And, taking photos.",
    "bunpou_soshite|se1": "He's a doctor. And, very kind.",
    "bunpou_soshite|se2": "Studying. Then, sleeping.",
    "bunpou_sugiru|meaning": "Too ~",
    "bunpou_sugiru|formation": "i-adjective (drop い) + すぎる; na-adjective + すぎる; verb ~ます form (drop ます) + すぎる",
    "bunpou_sugiru|usageNotes": "Expresses something being excessive/beyond a reasonable limit, used as a suffix attached to an adjective or verb.",
    "bunpou_sugiru|se0": "This is too expensive.",
    "bunpou_sugiru|se1": "I ate too much.",
    "bunpou_sugiru|se2": "A room that's too quiet.",
    "bunpou_ta_koto_ga_aru|meaning": "Have ~ before",
    "bunpou_ta_koto_ga_aru|formation": "Verb past form (~た) + ことがある",
    "bunpou_ta_koto_ga_aru|usageNotes": "Expresses the experience of having done something in the past, without stating exactly when.",
    "bunpou_ta_koto_ga_aru|se0": "I've been to Japan before.",
    "bunpou_ta_koto_ga_aru|se1": "I've never eaten sushi before.",
    "bunpou_ta_koto_ga_aru|se2": "I've watched this movie before.",
    "bunpou_tai|meaning": "Want to (do something)",
    "bunpou_tai|formation": "Verb ~ます form (drop ます) + たい",
    "bunpou_tai|usageNotes": "Expresses a personal desire to do an action, its conjugation follows the i-adjective pattern (たい→たかった, たくない).",
    "bunpou_tai|se0": "I want to go to Japan.",
    "bunpou_tai|se1": "What do you want to eat?",
    "bunpou_tai|se2": "I want to learn more.",
    "bunpou_tari_tari|meaning": "Doing this and that (example activities, non-exhaustive)",
    "bunpou_tari_tari|formation": "Verb past form (~た→たり) + たり + Verb past form (~た→たり) + たりする",
    "bunpou_tari_tari|usageNotes": "Lists a few examples of activities done (alternately or as a non-exhaustive list), not a fixed sequence like the te-form.",
    "bunpou_tari_tari|se0": "On weekends I read books, watch movies, and so on.",
    "bunpou_tari_tari|se1": "At the park I run around, take walks, and so on.",
    "bunpou_tari_tari|se2": "Sometimes crying, sometimes laughing.",
    "bunpou_te_aru|meaning": "Is already in the state of ~ (result of a deliberate action, still holds)",
    "bunpou_te_aru|formation": "Transitive verb te-form + ある",
    "bunpou_te_aru|usageNotes": "Emphasizes that the result of a deliberate action is still visible/holds now, focusing on the object and its condition, different from ている, which focuses on the continuation of the action itself.",
    "bunpou_te_aru|se0": "The window has been opened (and is still open).",
    "bunpou_te_aru|se1": "There's a note that's been written.",
    "bunpou_te_aru|se2": "The flowers have been arranged (and are still on display).",
    "bunpou_te_iru|meaning": "Is ~ing (ongoing action) / is in the state of ~ (result, for change verbs)",
    "bunpou_te_iru|formation": "Verb te-form + いる",
    "bunpou_te_iru|usageNotes": "Two main functions: expressing an ongoing action (action verbs like 食べる) or expressing a result/state that still holds (change verbs like 結婚する→結婚している).",
    "bunpou_te_iru|se0": "Right now, I'm watching TV.",
    "bunpou_te_iru|se1": "He's already married.",
    "bunpou_te_iru|se2": "It's raining.",
    "bunpou_te_kara|meaning": "After doing ~",
    "bunpou_te_kara|formation": "Verb te-form + から",
    "bunpou_te_kara|usageNotes": "Expresses a time sequence, emphasizing that the second action happens AFTER the first is finished, stressing the order more than a plain te-form.",
    "bunpou_te_kara|se0": "After doing my homework, I'll play.",
    "bunpou_te_kara|se1": "Please eat after washing your hands.",
    "bunpou_te_kara|se2": "It's been three years since I came to Japan.",
    "bunpou_te_kudasai|meaning": "Please do ~",
    "bunpou_te_kudasai|formation": "Verb te-form + ください",
    "bunpou_te_kudasai|usageNotes": "A polite request form asking the listener to do something, one of the most basic and frequently used patterns.",
    "bunpou_te_kudasai|se0": "Please sit here.",
    "bunpou_te_kudasai|se1": "Please say it once more.",
    "bunpou_te_kudasai|se2": "Please speak slowly.",
    "bunpou_te_wa_ikenai|meaning": "Must not ~ (full/formal form)",
    "bunpou_te_wa_ikenai|formation": "Verb te-form + はいけない",
    "bunpou_te_wa_ikenai|usageNotes": "The full form of ちゃいけない, expressing a prohibition more formally/explicitly.",
    "bunpou_te_wa_ikenai|se0": "You mustn't swim here.",
    "bunpou_te_wa_ikenai|se1": "You mustn't lie.",
    "bunpou_te_wa_ikenai|se2": "You mustn't sleep during class.",
    "bunpou_temo_ii|meaning": "May ~",
    "bunpou_temo_ii|formation": "Verb te-form + もいいです",
    "bunpou_temo_ii|usageNotes": "Expresses permission to do something, the opposite meaning of てはいけない.",
    "bunpou_temo_ii|se0": "May I sit here?",
    "bunpou_temo_ii|se1": "You may take a photo.",
    "bunpou_temo_ii|se2": "You may go home now.",
    "bunpou_to|meaning": "Quotation particle (\"that ~\"), \"and\" connector (for a complete list), or conditional \"if\"",
    "bunpou_to|formation": "Sentence + と + 言う/思う (quotation); Noun + と + Noun (and); Verb dictionary form + と (conditional)",
    "bunpou_to|usageNotes": "Multi-function depending on context: quoting direct speech/thought, connecting a complete list of nouns (unlike や, which is incomplete), or expressing an automatic condition \"if X then always Y\".",
    "bunpou_to|se0": "I think it'll rain tomorrow.",
    "bunpou_to|se1": "Buying apples and bananas.",
    "bunpou_to|se2": "If you press this button, the light will turn on.",
    "bunpou_toki|meaning": "Time, when",
    "bunpou_toki|formation": "Verb dictionary/past form + とき; Adjective + とき; Noun + の + とき",
    "bunpou_toki|usageNotes": "Expresses the time an event happens, the verb before とき uses the dictionary form if not yet happened/simultaneous, or the past form if already finished before the main event.",
    "bunpou_toki|se0": "When I went to Japan, I ate sushi.",
    "bunpou_toki|se1": "When I was a child, I often played at the park.",
    "bunpou_toki|se2": "When you're busy, please help me.",
    "bunpou_totemo|meaning": "Very",
    "bunpou_totemo|formation": "とても + adjective",
    "bunpou_totemo|usageNotes": "An intensity adverb \"very\", used before an adjective to emphasize its degree (only for positive sentences, not negative — for negative use あまり).",
    "bunpou_totemo|se0": "This book is very interesting.",
    "bunpou_totemo|se1": "It's very hot today.",
    "bunpou_totemo|se2": "He's very kind.",
    "bunpou_tsumori|meaning": "Intend, plan to",
    "bunpou_tsumori|formation": "Verb dictionary/~ない form + つもり",
    "bunpou_tsumori|usageNotes": "Expresses the speaker's intention/plan to do (or not do) something, emphasizing an inner decision more than a concrete plan like 予定.",
    "bunpou_tsumori|se0": "I intend to go to Japan next year.",
    "bunpou_tsumori|se1": "I intend to take tomorrow off.",
    "bunpou_tsumori|se2": "I don't intend to meet him again.",
    "bunpou_wa|meaning": "Topic-marking particle",
    "bunpou_wa|formation": "Noun + は",
    "bunpou_wa|usageNotes": "Marks the topic of conversation (not always the grammatical subject), used for something already known/discussed before, different from が, which marks the subject/new information.",
    "bunpou_wa|se0": "I am a student.",
    "bunpou_wa|se1": "This book is interesting.",
    "bunpou_wa|se2": "Today is hot.",
    "bunpou_wa_yori_desu|meaning": "[A] is more ... than [B]",
    "bunpou_wa_yori_desu|formation": "[A]は[B]より[adjective]です",
    "bunpou_wa_yori_desu|usageNotes": "A comparison pattern for two things, [B] followed by より becomes the reference point, [A] is the subject stated as superior in that quality.",
    "bunpou_wa_yori_desu|se0": "Japan is colder than Taiwan.",
    "bunpou_wa_yori_desu|se1": "My older brother is taller than me.",
    "bunpou_wa_yori_desu|se2": "This book is more interesting than that one.",
    "bunpou_wa_dou_desu_ka|meaning": "How about ~?",
    "bunpou_wa_dou_desu_ka|formation": "Noun + はどうですか",
    "bunpou_wa_dou_desu_ka|usageNotes": "Offers/asks the listener's opinion about something, often used to offer a choice or ask about a condition/impression.",
    "bunpou_wa_dou_desu_ka|se0": "How about tea (would you like some)?",
    "bunpou_wa_dou_desu_ka|se1": "How about tomorrow?",
    "bunpou_wa_dou_desu_ka|se2": "How about this color?",
    "bunpou_ya|meaning": "And (incomplete list, \"and so on\")",
    "bunpou_ya|formation": "Noun + や + Noun",
    "bunpou_ya|usageNotes": "Connects several nouns as examples from an incomplete list, different from と, which states a complete/definite list.",
    "bunpou_ya|se0": "There's a book, a notebook, and so on on the table.",
    "bunpou_ya|se1": "Buying fruit, cake, and so on.",
    "bunpou_ya|se2": "I like dogs, cats, and the like.",
    "bunpou_yo|meaning": "Sentence-final assertive particle (informing new information)",
    "bunpou_yo|formation": "Sentence + よ",
    "bunpou_yo|usageNotes": "A sentence-final particle asserting/informing something the listener may not know, giving emphasis to the information.",
    "bunpou_yo|se0": "It's already time, you know.",
    "bunpou_yo|se1": "This is tasty, you know.",
    "bunpou_yo|se2": "That's dangerous, you know.",
    "bunpou_yori_hou_ga|meaning": "[A] is better/more ... than [B]",
    "bunpou_yori_hou_ga|formation": "[B]より[A]のほうが+adjective",
    "bunpou_yori_hou_ga|usageNotes": "Another variation of the comparison pattern, placing the comparison point ([B]より) first and the superior subject ([A]のほうが) after — the reverse order of the は~より pattern.",
    "bunpou_yori_hou_ga|se0": "The train is faster than the bus.",
    "bunpou_yori_hou_ga|se1": "I prefer winter over summer.",
    "bunpou_yori_hou_ga|se2": "Today is hotter than yesterday.",
}
