"""
choukai_meaning_en.py

Locked source of truth for the English translations of Choukai clip
content: ChoukaiClip.titleEn / audioTranslationEn.
apply_choukai_meaning_en.py reads this and patches
assets/data/choukai_data.json, so translations live in exactly one place.

Key format:
    "{id}|title"             -> the clip's title
    "{id}|audioTranslation"  -> the clip's script, rendered into English

Translated from the Japanese `audioText`, not from the Indonesian
`audioTranslation` — going through a second language compounds drift,
and the Japanese is the authored source.

Scope note: `audioText` itself is never translated. It is the material
being tested and is only ever *played* through TTS, never shown, until
the result screen reveals it for review — where the translation below
sits beside it. Questions and options are Japanese and stay Japanese.

Speaker labels: 男/女 in the script become Man:/Woman:, matching the
Indonesian's Pria:/Wanita:. Where a third party's gender is not stated in
the Japanese, English uses they/them rather than inventing one.

STATUS: DONE. All 300/300 fields translated (150 clips x 2 fields),
batched by JLPT level (N5/N4/N3/N2/N1, 30 clips = 60 fields each).
"""

CHOUKAI_MEANING_EN = {
    # ---------------- N5 (30 clips, 60 fields) ----------------
    "choukai_n5_jam_berapa|title": "What Time Is It Now",
    "choukai_n5_jam_berapa|audioTranslation": "Man: Excuse me, what time is it now? Woman: It's half past three. Man: Thank you. The bus comes at four, right? Woman: Yes, thirty minutes from now.",
    "choukai_n5_cari_buku|title": "Looking for a Book in Class",
    "choukai_n5_cari_buku|audioTranslation": "Woman: Teacher, my book isn't here. Man: Did you look on the desk? Woman: Yes, I did. It wasn't there. Man: What about inside your bag? Woman: Oh, here it is. Sorry.",
    "choukai_n5_sarapan|title": "This Morning's Breakfast",
    "choukai_n5_sarapan|audioTranslation": "Man: What did you eat this morning? Woman: I had bread and eggs. Man: Did you drink milk? Woman: No, I drank tea.",
    "choukai_n5_berapa_harga|title": "How Much Is It",
    "choukai_n5_berapa_harga|audioTranslation": "Woman: Excuse me, how much is this notebook? Man: A hundred and fifty yen. Woman: Then I'll take two. Man: That comes to three hundred yen.",
    "choukai_n5_ulang_tahun|title": "When Is Your Birthday",
    "choukai_n5_ulang_tahun|audioTranslation": "Man: When is your birthday? Woman: July tenth. Man: Mine is July twentieth. They're close. Woman: They really are.",
    "choukai_n5_di_mana_tas|title": "Where Is My Bag",
    "choukai_n5_di_mana_tas|audioTranslation": "Woman: Mom, where is my bag? Man: It's under the chair. Woman: It isn't under the chair. Man: Then please look on the table. Woman: Found it. Thanks.",
    "choukai_n5_naik_apa|title": "How Do You Get to School",
    "choukai_n5_naik_apa|audioTranslation": "Man: How do you get to school every day? Woman: I go by bicycle. Man: By bicycle on rainy days too? Woman: No, on rainy days I take the bus.",
    "choukai_n5_cuaca_hari_ini|title": "Today's Weather",
    "choukai_n5_cuaca_hari_ini|audioTranslation": "Woman: It's cold today, isn't it. Man: It is. Yesterday was warm, though. Woman: They say it'll snow tomorrow. Man: What, really?",
    "choukai_n5_berapa_keluarga|title": "How Many People in Your Family",
    "choukai_n5_berapa_keluarga|audioTranslation": "Man: How many people are in your family? Woman: Four. I have my father, my mother and a younger brother. Man: You don't have an older sister? Woman: No, I don't.",
    "choukai_n5_warna_payung|title": "Whose Umbrella Is Whose",
    "choukai_n5_warna_payung|audioTranslation": "Woman: Whose is this red umbrella? Man: It's mine. Woman: Then what about the blue one? Man: That one is Tanaka's.",
    "choukai_n5_bertemu_stasiun|title": "Meeting in Front of the Station",
    "choukai_n5_bertemu_stasiun|audioTranslation": "Man: What time shall we meet tomorrow? Woman: How about ten? Man: Sounds good. Where shall we meet? Woman: Let's meet in front of the station.",
    "choukai_n5_makanan_tidak_suka|title": "Food You Don't Like",
    "choukai_n5_makanan_tidak_suka|audioTranslation": "Woman: Is there any food you dislike? Man: Yes, I don't like carrots. Woman: Are all vegetables out? Man: No, I like tomatoes.",
    "choukai_n5_pinjam_pensil|title": "Borrowing a Pencil",
    "choukai_n5_pinjam_pensil|audioTranslation": "Man: Excuse me, could you lend me a pencil? Woman: Sure, here you go. Man: Thank you. I'll give it back later. Woman: No rush.",
    "choukai_n5_nomor_telepon|title": "A Friend's Phone Number",
    "choukai_n5_nomor_telepon|audioTranslation": "Woman: Please tell me your phone number. Man: Sure, zero nine zero, one two three four, five six seven eight. Woman: Once more, please. Man: Zero nine zero, one two three four, five six seven eight.",
    "choukai_n5_hewan_peliharaan|title": "Pets at Home",
    "choukai_n5_hewan_peliharaan|audioTranslation": "Man: Do you keep any animals at home? Woman: Yes, I have two cats. Man: No dog? Woman: No dog. Just the cats.",
    "choukai_n5_pr_belum_selesai|title": "Homework Not Finished Yet",
    "choukai_n5_pr_belum_selesai|audioTranslation": "Woman: Have you finished your homework? Man: No, not yet. Woman: By when do you have to finish it? Man: By tomorrow morning. I'll do it tonight.",
    "choukai_n5_beli_minuman|title": "Buying Drinks",
    "choukai_n5_beli_minuman|audioTranslation": "Man: What would you like to drink? Woman: I'd like juice. Man: Then I'll have water. Woman: Excuse me, one juice and one water, please.",
    "choukai_n5_sakit_perut|title": "A Stomach Ache at School",
    "choukai_n5_sakit_perut|audioTranslation": "Woman: Teacher, my stomach hurts. Man: Since when? Woman: Since this morning. Man: Then let's go to the nurse's office.",
    "choukai_n5_rencana_minggu|title": "Sunday Plans",
    "choukai_n5_rencana_minggu|audioTranslation": "Man: What are you doing on Sunday? Woman: I'm going to see a film with a friend. Man: Nice. What time does it start? Woman: From two in the afternoon.",
    "choukai_n5_kelas_mulai|title": "What Time Class Starts",
    "choukai_n5_kelas_mulai|audioTranslation": "Woman: What time do classes start? Man: They start at half past eight. Woman: What time do they end? Man: They end at three.",
    "choukai_n5_cari_toilet|title": "Looking for the Toilet at the Station",
    "choukai_n5_cari_toilet|audioTranslation": "Woman: Excuse me, where is the toilet? Man: It's to the right of those stairs. Woman: Thank you. Man: But it might be being cleaned right now. There's one on the second floor too.",
    "choukai_n5_lama_kereta|title": "How Long the Train Takes",
    "choukai_n5_lama_kereta|audioTranslation": "Man: About how long does it take to Tokyo? Woman: Forty minutes by express. Man: And by local train? Woman: About an hour. Man: Then I'll take the express.",
    "choukai_n5_guru_baru|title": "Asking the New Teacher's Name",
    "choukai_n5_guru_baru|audioTranslation": "Woman: Do you know the new teacher's name? Man: Yes, it's Yamamoto-sensei. Woman: What do they teach? Man: Music. They start next week.",
    "choukai_n5_kucing_tetangga|title": "The Neighbour's Cat Got In",
    "choukai_n5_kucing_tetangga|audioTranslation": "Man: The cat from next door is here again. Woman: So it is. The window was open. Man: What should we do? Woman: I'll call the neighbours. They must be worried.",
    "choukai_n5_pilih_duduk|title": "Choosing a Seat",
    "choukai_n5_pilih_duduk|audioTranslation": "Woman: Where shall we sit? Man: Near the window would be nice. Woman: The sun hits that spot, though. Man: Then I'll take a seat at the back.",
    "choukai_n5_musim_favorit|title": "Favourite Season",
    "choukai_n5_musim_favorit|audioTranslation": "Man: Which season do you like best? Woman: Autumn, because it's cool. Man: What about summer? Woman: Summer is too hot. Winter is too cold as well.",
    "choukai_n5_hitung_buku|title": "Counting Books on the Shelf",
    "choukai_n5_hitung_buku|audioTranslation": "Woman: How many books are there altogether? Man: Ten on the top shelf and eight on the bottom shelf. Woman: Eighteen, then. Man: Yes, that's right.",
    "choukai_n5_tugas_piket|title": "Today's Cleaning Duty",
    "choukai_n5_tugas_piket|audioTranslation": "Man: Who's on cleaning duty today? Woman: Tanaka and me. Man: What are you cleaning? Woman: The classroom and the corridor. It'll take about twenty minutes.",
    "choukai_n5_tiket_bioskop|title": "Buying Cinema Tickets",
    "choukai_n5_tiket_bioskop|audioTranslation": "Woman: Two adult tickets, please. Man: That's three thousand six hundred yen. Woman: I'm a student — is there a discount? Man: With a student ID it's one thousand two hundred yen each.",
    "choukai_n5_kabar_teman_sakit|title": "Asking About a Sick Friend",
    "choukai_n5_kabar_teman_sakit|audioTranslation": "Man: Is Yamada absent again today? Woman: Yes, apparently they still have a fever. Man: When are they coming? Woman: They said they'd come from the day after tomorrow.",

    # ---------------- N4 (30 clips, 60 fields) ----------------
    "choukai_n4_batal_hujan|title": "Cancelled Because of Rain",
    "choukai_n4_batal_hujan|audioTranslation": "Woman: What happened with tomorrow's outing? Man: Apparently it was called off because it looks like rain. Woman: Oh no, and I was looking forward to it. Man: They say they'll hold it next Saturday instead. Woman: Then I'll keep that day free.",
    "choukai_n4_salah_halte|title": "Getting Off at the Wrong Stop",
    "choukai_n4_salah_halte|audioTranslation": "Man: Hm, where am I? Woman: Is something wrong? Man: It seems I got off one stop early. Which way is the station? Woman: Go straight along this road and turn right at the second corner. It's about ten minutes on foot. Man: That's a great help. Thank you.",
    "choukai_n4_jaga_adik|title": "Asking Someone to Watch a Younger Brother",
    "choukai_n4_jaga_adik|audioTranslation": "Woman: I have a small favour to ask. Man: What is it? Woman: Could you watch my younger brother tomorrow afternoon? I want to go shopping. Man: From what time to what time? Woman: From two to four. Man: Sure. I'll come at two.",
    "choukai_n4_barang_tertinggal|title": "Something Left on the Train",
    "choukai_n4_barang_tertinggal|audioTranslation": "Man: Excuse me, I've left my umbrella on the train. Woman: Roughly what time was the train? Man: Around half past seven. Woman: Could you tell me its colour and shape? Man: It's black and long. Woman: One moment, please. I'll check.",
    "choukai_n4_hadiah_guru|title": "Choosing a Gift for the Teacher",
    "choukai_n4_hadiah_guru|audioTranslation": "Woman: What do you think would be good as a present for the teacher? Man: How about flowers? Woman: It was flowers last year too. Man: Then what about a message card everyone writes in? Woman: That's a good one. Let's do that.",
    "choukai_n4_undur_janji|title": "Pushing Back an Appointment",
    "choukai_n4_undur_janji|audioTranslation": "Man: Hello, it's about our appointment today. Woman: Yes, it was six, wasn't it. Man: It doesn't look like my work will finish, so could we change it to seven? Woman: That's fine. Seven at the same place, then. Man: Sorry about this. Thank you.",
    "choukai_n4_ke_perpustakaan|title": "How to Get to the City Library",
    "choukai_n4_ke_perpustakaan|audioTranslation": "Woman: How do I get to the city library? Man: The bus is convenient. Take the number three bus. Woman: Which stop do I get off at? Man: The fourth one. You'll see it on your right as soon as you get off. Woman: Understood. Thank you.",
    "choukai_n4_lupa_dompet|title": "Forgetting a Wallet",
    "choukai_n4_lupa_dompet|audioTranslation": "Man: Oh no, I've left my wallet at home. Woman: What are you going to do about lunch, then? Man: I'll just go without today. Woman: I'll lend you some. You can pay me back tomorrow. Man: Thank you. That's a real help.",
    "choukai_n4_pesan_meja|title": "Booking a Table at a Restaurant",
    "choukai_n4_pesan_meja|audioTranslation": "Woman: Hello, I'd like to make a booking for this evening. Man: For how many people? Woman: Four. From seven, please. Man: I'm very sorry, seven is full, but half past seven is available. Woman: Half past seven, then, please.",
    "choukai_n4_buku_terlambat|title": "Returning a Book Late",
    "choukai_n4_buku_terlambat|audioTranslation": "Man: Excuse me, I've gone past the return date. Woman: By how many days? Man: Three. Woman: Three days is fine. Please be careful from next time. Man: Yes, I'm sorry.",
    "choukai_n4_kelas_tambahan|title": "After-School Extra Lessons",
    "choukai_n4_kelas_tambahan|audioTranslation": "Woman: Are you going to the after-school extra lesson? Man: Yes, I'm bad at maths so I plan to. Woman: What time was it again? Man: From four, for an hour, they said. Woman: Maybe I'll go too, then.",
    "choukai_n4_jam_buka_toko|title": "Asking a Shop's Opening Hours",
    "choukai_n4_jam_buka_toko|audioTranslation": "Man: Until what time are you open? Woman: Until eight on weekdays and until six on Saturdays. Man: And Sundays? Woman: We're closed on Sundays. Man: Understood. I'll come on Saturday.",
    "choukai_n4_teman_pindah|title": "A Friend Who's Moving Away",
    "choukai_n4_teman_pindah|audioTranslation": "Woman: I hear Tanaka is moving next month. Man: What, really? Where to? Woman: Osaka, they said. Something to do with their father's job. Man: It'll feel empty without them. Woman: It will. Shall we all write letters?",
    "choukai_n4_bantu_belanja|title": "Helping Mom with the Shopping",
    "choukai_n4_bantu_belanja|audioTranslation": "Man: Mom, is there anything you need me to buy? Woman: Could you get eggs and milk, then. Man: How many eggs? Woman: One pack of ten. One bottle of milk is enough. Man: Got it. I'm off.",
    "choukai_n4_kehujanan|title": "Caught in the Rain on the Way",
    "choukai_n4_kehujanan|audioTranslation": "Woman: You're soaked. What happened? Man: It suddenly started pouring on my way home. Woman: You didn't have an umbrella? Man: It was clear this morning, so I left it behind. Woman: Use this towel. You'll catch a cold.",
    "choukai_n4_acara_kelas|title": "Preparing the Class Party",
    "choukai_n4_acara_kelas|audioTranslation": "Man: How are the preparations for next week's class party? Woman: I've already bought the drinks. Not the snacks yet. Man: Then I'll get the snacks. Woman: That helps. We'll set the chairs out on the day. Man: Right, let's go early in the morning.",
    "choukai_n4_sepeda_rusak|title": "A Broken Bicycle",
    "choukai_n4_sepeda_rusak|audioTranslation": "Woman: What happened to your bike? Man: I got a flat tyre. Woman: Did you get it fixed? Man: Yes, I took it to the shop and they fixed it in thirty minutes. Woman: Good that it was quick.",
    "choukai_n4_pilih_klub|title": "Choosing a School Club",
    "choukai_n4_pilih_klub|audioTranslation": "Man: Have you decided which club to join? Woman: I'm still torn, between the tennis club and the music club. Man: Have you been to see both? Woman: I have. Tennis is every day, and music is three times a week, they said. Man: Thinking about the time, maybe the music club.",
    "choukai_n4_telepon_terlambat|title": "Calling Because of a Delay",
    "choukai_n4_telepon_terlambat|audioTranslation": "Woman: Hello, I'm sorry, the train is delayed. Man: About how late do you expect to be? Woman: About fifteen minutes. Man: Understood. We'll start without you. Woman: Yes, please do.",
    "choukai_n4_rencana_piknik|title": "Planning a Picnic Together",
    "choukai_n4_rencana_piknik|audioTranslation": "Man: Shall we all go to the park on the next day off? Woman: Sounds good. Are we bringing packed lunches? Man: Yes, let's each prepare our own. Woman: Then I'll bring extra drinks. Man: Thanks. Let's meet at the station at nine.",
    "choukai_n4_ganti_kelas|title": "Changing Language Class",
    "choukai_n4_ganti_kelas|audioTranslation": "Woman: I'd like to move from the beginner class to the intermediate one. Man: You'll need to take a test first. Woman: Is it difficult? Man: If you've finished the beginner course, I think you'll be fine. We'll let you know the result in three days.",
    "choukai_n4_cari_barang_toko|title": "Finding an Item in a Department Store",
    "choukai_n4_cari_barang_toko|audioTranslation": "Man: Excuse me, where are the notebooks? Woman: In the stationery section on the third floor. Man: Are the pens in the same place? Woman: Yes, the same floor. Though it's being refurbished at the moment, so it has moved to the second floor.",
    "choukai_n4_izin_pulang|title": "Asking to Leave Early",
    "choukai_n4_izin_pulang|audioTranslation": "Woman: Excuse me, would it be all right if I went home early today? Man: Has something happened? Woman: I've had a call from my child's school. Man: That sounds serious. Please finish just what you're working on and then go. Woman: Thank you. I'll be done shortly.",
    "choukai_n4_resep_teman|title": "Explaining a Recipe to a Friend",
    "choukai_n4_resep_teman|audioTranslation": "Man: How do you make this soup? Woman: You just cut up the vegetables and simmer them from cold water. Man: You don't put meat in? Woman: You can, but it comes out sweeter with vegetables alone. Man: Huh. I'll try making it sometime.",
    "choukai_n4_warna_cat|title": "Choosing a Room Colour",
    "choukai_n4_warna_cat|audioTranslation": "Woman: For the room colour, which do you think is better, white or blue? Man: Blue is calming, but it might make the room look dark. Woman: White might be better, then. Man: How about white walls and blue curtains? Woman: That's a good idea.",
    "choukai_n4_kartu_perpustakaan|title": "Getting a Library Card",
    "choukai_n4_kartu_perpustakaan|audioTranslation": "Man: I'd like to get a member's card. Woman: Do you have something that shows your address? Man: I have my driver's licence. Woman: That will do. We can make it right here. Please wait about five minutes.",
    "choukai_n4_bantu_tetangga|title": "Offering a Neighbour a Hand",
    "choukai_n4_bantu_tetangga|audioTranslation": "Woman: That's a lot to carry. Shall I take some? Man: No, I'm fine. Woman: Please don't hold back. It's up to the second floor, isn't it. Man: Then could you take just this box. That's a help.",
    "choukai_n4_film_ditonton|title": "Talking About a Film You Saw",
    "choukai_n4_film_ditonton|audioTranslation": "Man: How was yesterday's film? Woman: The story was easy to follow, but the ending felt abrupt. Man: I thought so too. The music was good, though. Woman: It was. That stayed with me.",
    "choukai_n4_atur_tempat_duduk|title": "Arranging Seats for an Event",
    "choukai_n4_atur_tempat_duduk|audioTranslation": "Woman: Will seats for fifty be enough? Man: We have forty-five sign-ups, but some people turn up on the day. Woman: I'll make it fifty-five, then. Man: Yes. Better to have too many than too few.",
    "choukai_n4_arah_kantor_pos|title": "Asking the Way to the Post Office",
    "choukai_n4_arah_kantor_pos|audioTranslation": "Man: Is there a post office near here? Woman: Yes, go straight along this road and turn left at the traffic lights. Man: How long is it on foot? Woman: About five minutes. But today is Saturday, so the counter is only open until midday.",

    # ---------------- N3 (30 clips, 60 fields) ----------------
    "choukai_n3_alasan_jurusan|title": "Why You Chose Your Major",
    "choukai_n3_alasan_jurusan|audioTranslation": "Woman: Why did you choose the economics faculty? Man: At first I was thinking about law, but I realised that looking at how society works through numbers suits me better. Woman: Did your family say anything? Man: My father didn't object, but he told me to think about employment. Woman: That's practical advice.",
    "choukai_n3_tetangga_berisik|title": "A Complaint About Noisy Neighbours",
    "choukai_n3_tetangga_berisik|audioTranslation": "Man: Have you been sleeping all right lately? Woman: Well, the noise from the floor above goes on until the middle of the night. Man: Have you told the building manager? Woman: I mentioned it once and it quietened down a little, but then it went back to how it was. Man: Rather than saying something directly, I think it's better to go through the manager again.",
    "choukai_n3_menawar_pasar|title": "Haggling at the Market",
    "choukai_n3_menawar_pasar|audioTranslation": "Woman: Could you make this fruit a little cheaper? Man: Hmm, any lower is a bit difficult. Woman: I'll buy three, so could you do them together? Man: Three? In that case I'll knock a little off. Woman: Thank you. I'll take three, then.",
    "choukai_n3_kesalahpahaman|title": "A Misunderstanding with a Friend",
    "choukai_n3_kesalahpahaman|audioTranslation": "Man: About the other day, are you angry? Woman: I'm not angry. The signal was just bad and I couldn't hear. Man: Oh, was that it? Since there was no reply, I thought you were avoiding me. Woman: Not at all. If anything I was worried. Man: I should have said something sooner.",
    "choukai_n3_wawancara_kerja|title": "A Part-Time Job Interview",
    "choukai_n3_wawancara_kerja|audioTranslation": "Woman: About how many days a week can you work? Man: I have classes on weekdays, so about three days, mainly Saturday and Sunday. Woman: How about evenings? Man: On Tuesdays and Thursdays I'm free after six. Woman: Understood. I'll try to arrange it on those terms.",
    "choukai_n3_banding_apartemen|title": "Comparing Two Apartments",
    "choukai_n3_banding_apartemen|audioTranslation": "Man: Have you decided which of the two you'll take? Woman: The one near the station has high rent, and the quiet one is far from the station. Man: If you commute every day, the closer one is easier. Woman: But thinking about studying, the quiet one. Man: True, that's not something you can compromise on.",
    "choukai_n3_perubahan_jadwal|title": "Announcement of a Schedule Change",
    "choukai_n3_perubahan_jadwal|audioTranslation": "Man: An announcement. Tomorrow's information session has had its time changed due to venue circumstances. It was scheduled to begin at ten, but it will now start at one in the afternoon. There is no change of location. Those who have already registered will be contacted by email later.",
    "choukai_n3_minta_maaf|title": "Apologising for an Oversight",
    "choukai_n3_minta_maaf|audioTranslation": "Woman: Regarding the documents from the other day, I failed to check them. I'm very sorry. Man: No, I did ask you at short notice. Woman: From now on I'll make sure to look them over once more before submitting. Man: That would be a help. Please do so from next time.",
    "choukai_n3_pilih_liburan|title": "Choosing a Holiday Destination",
    "choukai_n3_pilih_liburan|audioTranslation": "Man: Where shall we go for this year's holiday? Woman: We went to the sea last year, so how about the mountains this year? Man: The mountains would be nice, but the children are small, so a long journey is hard. Woman: That's true. Let's look for somewhere close with some nature, then. Man: Right, I'll look into it along those lines.",
    "choukai_n3_tugas_kelompok|title": "Discussing a Group Assignment",
    "choukai_n3_tugas_kelompok|audioTranslation": "Woman: How should we split up the presentation? Man: I think we should separate making the materials from speaking. Woman: I'm not good at speaking in front of people, so maybe I'll do the materials. Man: Then I'll speak at the front. Let's both check the conclusion together. Woman: Yes, that puts my mind at ease.",
    "choukai_n3_kartu_hilang|title": "Reporting a Lost Card",
    "choukai_n3_kartu_hilang|audioTranslation": "Man: I've lost my card. Woman: First we need to put a stop on it. Your name and date of birth, please. Man: Yes. How long does reissuing take? Woman: About a week to ten days. If you're in a hurry, you can also collect it at the counter. Man: The counter, then, please.",
    "choukai_n3_menolak_sopan|title": "Declining an Invitation Politely",
    "choukai_n3_menolak_sopan|audioTranslation": "Woman: Can you come to the meal this weekend? Man: It's a kind invitation, but I have a family commitment that day. Woman: I see, that's a shame. Man: Please do invite me again next time. Woman: Of course. I'll let you know.",
    "choukai_n3_rencana_masa_depan|title": "Talking About Future Plans",
    "choukai_n3_rencana_masa_depan|audioTranslation": "Man: Have you decided what you'll do after graduating? Woman: I'd been planning to get a job, but lately I've also been thinking about further study. Man: Why are you hesitating? Woman: A wish to study something more specialised has come up. But there's the cost, too. Man: Don't rush. Look into both, then decide.",
    "choukai_n3_komplain_rusak|title": "Complaining About a Damaged Item",
    "choukai_n3_komplain_rusak|audioTranslation": "Woman: About the item that arrived last week, there was a scratch on it when I opened the box. Man: I'm sorry for the trouble. Could you send us a photo? Woman: Yes, I'll send it right away. Could you exchange it? Man: Once we've checked, we'll send a new one. Please return the current item with the postage charged to us. Woman: Understood.",
    "choukai_n3_cara_pakai_alat|title": "Explaining How to Use a Machine",
    "choukai_n3_cara_pakai_alat|audioTranslation": "Man: How do you use this machine? Woman: First switch it on and wait until the screen turns green. Man: And once it's green? Woman: Then put the paper in here and press the blue button. Man: What about the red button? Woman: Only use that one to stop it.",
    "choukai_n3_kebiasaan_makan|title": "A Change in Eating Habits",
    "choukai_n3_kebiasaan_makan|audioTranslation": "Woman: I hear you've been eating out less lately. Man: Yes, since I started cooking for myself I've been feeling better. Woman: Isn't it a lot of trouble, taking all that time? Man: I cook in bulk on my days off, so on weekdays I just heat it up. Woman: I see. That sounds like something you can keep up.",
    "choukai_n3_pindah_kota|title": "Moving to Another City",
    "choukai_n3_pindah_kota|audioTranslation": "Man: From next month I'll be working in Sendai. Woman: That's sudden. Is your family going with you? Man: No, because of the children's school, I'll be on my own for a while. Woman: That must be hard. How long is it expected to be? Man: About two years, I'm told.",
    "choukai_n3_syarat_pendaftaran|title": "Asking About Application Requirements",
    "choukai_n3_syarat_pendaftaran|audioTranslation": "Woman: Could you tell me what I need in order to apply? Man: You'll need two photographs and a copy of your ID. Woman: Is the photo size fixed? Man: Yes, four centimetres tall by three wide, please. Taken within the last three months. Woman: Understood. I'll get them ready.",
    "choukai_n3_atur_waktu|title": "Struggling to Manage Time",
    "choukai_n3_atur_waktu|audioTranslation": "Man: Are you managing to balance your part-time job and your studies? Woman: Honestly, it isn't going very well. Man: Have you thought about which to cut back? Woman: I'm thinking of dropping one shift a week. Money will get a bit tight. Man: Better than wrecking your health, I'd say.",
    "choukai_n3_sampaikan_pesan|title": "Passing On a Message",
    "choukai_n3_sampaikan_pesan|audioTranslation": "Woman: A message from Yamada. For tomorrow's meeting, they'd like ten copies of the documents prepared. Man: Ten copies. In colour? Woman: Black and white is fine, they said. Also, the start has been moved thirty minutes earlier. Man: Understood. Half past nine, then. Thank you.",
    "choukai_n3_kursus_tambahan|title": "Choosing an Extra Course",
    "choukai_n3_kursus_tambahan|audioTranslation": "Woman: Which do you think is better, the evening course or the weekend course? Man: A lot of people say they can't stay focused after work. Woman: But weekends cut into family time. Man: In that case, there's also the option of weekend mornings only. Woman: I see, that hadn't occurred to me.",
    "choukai_n3_keterlambatan_proyek|title": "Explaining a Project Delay",
    "choukai_n3_keterlambatan_proyek|audioTranslation": "Man: I hear you're a week behind schedule. Woman: Yes. But the cause isn't slow work; it's that a change of specification came in partway through. Man: When did the change instruction arrive? Woman: In the third week. The work done up to then had to be redone.",
    "choukai_n3_sewa_ruangan|title": "Negotiating Room Hire",
    "choukai_n3_sewa_ruangan|audioTranslation": "Woman: I'd like to hire it for just one day. How much would that be? Man: Normally it's thirty thousand yen a day. Woman: Would it be the same for just the morning? Man: For half a day it comes to eighteen thousand yen. Woman: Half a day, then, please.",
    "choukai_n3_kebiasaan_belajar|title": "Changing Study Habits",
    "choukai_n3_kebiasaan_belajar|audioTranslation": "Man: I hear you've changed the way you study. Woman: Yes. I used to work late into the night, but since switching to mornings the amount I can remember has gone up. Man: Hasn't the time gone down? Woman: It has, actually. But even in the same amount of time, it goes into my head differently.",
    "choukai_n3_undangan_reuni|title": "Responding to a Reunion Invitation",
    "choukai_n3_undangan_reuni|audioTranslation": "Woman: Have you replied to the reunion invitation? Man: Not yet. I do want to go. Woman: Are you hesitating? Man: It's been so many years since we graduated that it feels a bit late now. Woman: But I think it'd bother you more if you didn't go.",
    "choukai_n3_alat_transportasi|title": "Choosing How to Travel",
    "choukai_n3_alat_transportasi|audioTranslation": "Man: To get to the venue, would the car or the train be better? Woman: Looking only at time, the car is faster. However, on the day the car parks nearby will very likely be full. Man: Then, even if it takes a bit longer, the train is more reliable. Woman: Yes, that's the safer bet.",
    "choukai_n3_aturan_asrama|title": "Explaining the Dormitory Rules",
    "choukai_n3_aturan_asrama|audioTranslation": "Woman: Curfew is eleven o'clock. If you're going to be later than that, you need to notify us in advance. Man: So if I notify you, I can still get in? Woman: You can, but it's limited to three times a month. Man: Understood. What about cleaning the shared areas? Woman: It's a rota that changes weekly.",
    "choukai_n3_pekerjaan_impian|title": "Talking About a Dream Job",
    "choukai_n3_pekerjaan_impian|audioTranslation": "Man: Do you remember what you dreamed of being as a child? Woman: I wanted to be a nurse. Man: That's completely different from your job now. Woman: It is. But the part about wanting to be useful to people hasn't changed, I think. Man: So only the form changed.",
    "choukai_n3_paket_salah_kirim|title": "Sorting Out a Wrong Delivery",
    "choukai_n3_paket_salah_kirim|audioTranslation": "Woman: An item different from what I ordered has arrived. Man: I'm very sorry. Your tracking number, please. Woman: Here it is. Should I send it back? Man: We'll come and collect it. Your home is fine. Woman: That's a help.",
    "choukai_n3_jam_tidur|title": "Talking About Sleep",
    "choukai_n3_jam_tidur|audioTranslation": "Man: Are you getting enough sleep? Woman: About five hours, I suppose. I've been busy. Man: Are you the type who's fine on a short night? Woman: I thought I was, but lately I've been making more mistakes. I think I just hadn't noticed.",

    # ---------------- N2 (30 clips, 60 fields) ----------------
    "choukai_n2_rute_bus|title": "Announcement of a Bus Route Change",
    "choukai_n2_rute_bus|audioTranslation": "Woman: An announcement for our passengers. From the first of next month, part of the route for service number five will change. It will no longer go via the city hall; instead it will run past Central Hospital. The journey is expected to be about five minutes shorter than before. Please note that there is no change to fares.",
    "choukai_n2_evaluasi_proyek|title": "A Project Review Meeting",
    "choukai_n2_evaluasi_proyek|audioTranslation": "Man: Sales for this project didn't reach the target. Woman: But the response from younger customers exceeded what we expected, didn't it. Man: It did. Looking only at the numbers it's a failure, but I think we got material we can build on. Woman: So we keep the direction and rethink the way we advertise. Man: Yes, let's proceed along those lines.",
    "choukai_n2_keluhan_pelanggan|title": "Responding to a Customer Complaint",
    "choukai_n2_keluhan_pelanggan|audioTranslation": "Woman: That customer just now was quite angry. Man: They were. But listening to them, it seems their dissatisfaction was less about the slow response than about not being contacted. Woman: True, we didn't tell them how things were progressing. Man: From now on, let's keep them updated regularly, even before a matter is resolved.",
    "choukai_n2_kerja_jarak_jauh|title": "Remote Working Policy",
    "choukai_n2_kerja_jarak_jauh|audioTranslation": "Man: Do you think we should keep working from home? Woman: Going back entirely wouldn't be realistic. That said, when it comes to training new staff, in person is clearly more efficient. Man: So would coming in half the week be reasonable? Woman: I think that's about where the compromise lies.",
    "choukai_n2_hasil_survei|title": "Presenting the Survey Results",
    "choukai_n2_hasil_survei|audioTranslation": "Woman: I'll report the survey results. User satisfaction rose three points on last year. Looking at respondents in their twenties alone, however, it fell slightly. In the free-text answers, the most common comment by far was that the controls are hard to understand. I believe this is where the priority for improvement should sit.",
    "choukai_n2_negosiasi_tenggat|title": "Negotiating a Deadline",
    "choukai_n2_negosiasi_tenggat|audioTranslation": "Man: Could we have the delivery date extended by a week? Woman: We have commitments to the other party as well, so a week would be difficult. Man: How about three days, then? Woman: Three days we could just about arrange, I think. Please understand, though, that anything beyond that would be hard.",
    "choukai_n2_pindah_karier|title": "An Interview About Changing Careers",
    "choukai_n2_pindah_karier|audioTranslation": "Woman: Did you not hesitate about leaving a company you'd worked at for so many years? Man: Honestly, thinking about the salary, I was anxious. But when I pictured myself carrying on with the same work until retirement, regret felt like the scarier prospect. Woman: So what decided it was how you felt yourself.",
    "choukai_n2_prosedur_asuransi|title": "Explaining the Insurance Procedure",
    "choukai_n2_prosedur_asuransi|audioTranslation": "Man: To make a claim, you first submit the prescribed form. Please attach a doctor's certificate when you do. Once the documents are complete, assessment usually takes about two weeks. If anything is missing we will contact you each time, which means the assessment period will be extended further.",
    "choukai_n2_cuaca_ekstrem|title": "A Severe Weather Report",
    "choukai_n2_cuaca_ekstrem|audioTranslation": "Woman: From tonight through to the early hours of tomorrow, record-breaking heavy rain is forecast. In mountainside areas in particular, the risk of landslides is expected to rise. Rising river levels are also a concern, so those living near a river should consider evacuating early. Please refrain from any non-essential travel.",
    "choukai_n2_rencana_keuangan|title": "A Financial Planning Consultation",
    "choukai_n2_rencana_keuangan|audioTranslation": "Man: What should I start with when planning for later life? Woman: First, get a clear picture of your monthly spending. Investment can come after that. Man: Is investing really better than saving? Woman: It isn't a question of which is better; you choose according to your purpose and your time frame.",
    "choukai_n2_ulasan_buku|title": "A Book Review on the Radio",
    "choukai_n2_ulasan_buku|audioTranslation": "Woman: This week's book is a record following regional food culture. The writing certainly can't be called easy to read. But the depth of the interviews the author gathered over ten years offers something you won't find in other books. It isn't for readers after something light, but it rewards sitting down with properly.",
    "choukai_n2_alasan_penundaan|title": "Explaining a Postponement",
    "choukai_n2_alasan_penundaan|audioTranslation": "Man: Let me explain how we came to postpone the event. At first we thought the reason was the venue, but in fact what decided it was that the performers' schedules could not be aligned. The venue had been secured, so that was not the problem.",
    "choukai_n2_daur_ulang|title": "An Environmental Recycling Programme",
    "choukai_n2_daur_ulang|audioTranslation": "Woman: We keep calling for thorough sorting, but it just isn't taking hold. Man: Some say the rules are too finely detailed. Woman: But if we simplify them, the amount of material that can be reused goes down. Man: I think the first step is holding more residents' meetings and explaining the reasons behind the rules.",
    "choukai_n2_keselamatan_kerja|title": "A Workplace Safety Briefing",
    "choukai_n2_keselamatan_kerja|audioTranslation": "Man: Always carry out the pre-work inspection. For work at height in particular, the rule is that two people check the safety line attachment. Checking alone is not permitted. Also, if you are not feeling well, do not push through — say so. The decision to stop work may be made by anyone.",
    "choukai_n2_kritik_atasan|title": "Taking Criticism from a Manager",
    "choukai_n2_kritik_atasan|audioTranslation": "Woman: I'm down about what the manager pointed out earlier. Man: What they said was harsh, but it wasn't a rejection of you as a person. Woman: I know, but having it said in front of everyone was hard. Man: On that point I do think there was a lack of consideration. But wasn't the criticism itself on the mark?",
    "choukai_n2_penarikan_produk|title": "A Product Recall Announcement",
    "choukai_n2_penarikan_produk|audioTranslation": "Woman: We are writing to inform you that a defect has been found in some of our products. Those affected were manufactured between March and May. No effect on health has been confirmed, but as a precaution please stop using the product and return the item you have. We will cover the postage.",
    "choukai_n2_renovasi_gedung|title": "Building Renovation Plans",
    "choukai_n2_renovasi_gedung|audioTranslation": "Man: What happens to operations during the renovation work? Woman: Rather than closing entirely, we plan to work floor by floor in turn. Man: So the impact on users will be limited. Woman: Yes. There will be a period when one of the lifts is out of service, though, so we expect crowding.",
    "choukai_n2_petani_lokal|title": "An Interview with a Local Farmer",
    "choukai_n2_petani_lokal|audioTranslation": "Woman: People talk about a shortage of successors — do you feel it yourself? Man: I do. But I think the problem is less that young people don't come, and more that there's no structure letting them keep going once they do. If the income isn't stable, no amount of enthusiasm is enough. Woman: So what's being called into question is how prepared the receiving side is.",
    "choukai_n2_sistem_antrean|title": "A Change to the Queueing System",
    "choukai_n2_sistem_antrean|audioTranslation": "Man: I hear the reception system has changed. Woman: Yes. Until now you queued up; from now on you take a numbered ticket. Man: Will the waiting time get shorter? Woman: The waiting time itself doesn't change. But you'll be able to wait away from your seat.",
    "choukai_n2_anggaran_tahunan|title": "Discussing the Annual Budget",
    "choukai_n2_anggaran_tahunan|audioTranslation": "Woman: On next year's budget, there's a proposal to cut publicity spending. Man: It is spending whose effect is hard to see in the short term. Woman: But there are cases where enquiries dropped sharply the year after it was cut. Man: In that case, rather than cutting across the board, keeping whatever can be measured would be the realistic approach.",
    "choukai_n2_sistem_absensi|title": "Reviewing the Attendance System",
    "choukai_n2_sistem_absensi|audioTranslation": "Woman: How is the new clock-in system being received on the ground? Man: Many say the operation itself is simple. Complaints are concentrated on not being able to clock in while out of the office, though. Woman: In the briefing before rollout we said that was planned. Man: We did. That not having materialised is what's feeding the distrust.",
    "choukai_n2_usulan_karyawan|title": "Responding to Staff Suggestions",
    "choukai_n2_usulan_karyawan|audioTranslation": "Man: How should we handle the suggestions that have come in through the scheme? Woman: Replying to every one is difficult, but if we don't show why something wasn't adopted, people stop submitting. Man: True — the worst outcome is people thinking there's no point. Woman: Yes. The sense that something comes back matters more than the number of replies.",
    "choukai_n2_uji_coba_produk|title": "A Product Testing Report",
    "choukai_n2_uji_coba_produk|audioTranslation": "Woman: I'll report the test results. On durability it exceeded the standard, but instability was observed in operation at low temperatures. At this point I believe we should hold off on selling in cold regions. Improvements are expected to take about three months.",
    "choukai_n2_beban_kerja|title": "Discussing Workload",
    "choukai_n2_beban_kerja|audioTranslation": "Man: Is overtime not falling because we're short-staffed? Woman: That's part of it, but there are plenty of cases where two people check the same work separately. Man: So you're saying we should tidy up the procedures before adding people. Woman: Yes. I think hiring more is the last resort.",
    "choukai_n2_perubahan_tarif|title": "A Fare Change Announcement",
    "choukai_n2_perubahan_tarif|audioTranslation": "Man: From April next year we will revise our fare structure. The base fare stays as it is, but it changes to a system where a surcharge applies depending on the time of day. Morning and evening peak periods are affected. There is no impact on season ticket holders.",
    "choukai_n2_pemilik_toko_lama|title": "An Interview with a Long-Standing Shop Owner",
    "choukai_n2_pemilik_toko_lama|audioTranslation": "Woman: What's the secret to keeping going for fifty years? Man: There's nothing that deserves to be called a secret. Though not chasing trends may have counted for a lot. If you chase them, what makes the shop ours starts to fade. Woman: So not changing turned out to be the strength.",
    "choukai_n2_ruang_merokok|title": "Smoking Room Policy",
    "choukai_n2_ruang_merokok|audioTranslation": "Man: What are your thoughts on the proposal to remove the smoking room? Woman: From a health standpoint I think it's desirable. But if we simply remove it, more people will smoke outside the building, which could lead to complaints from the neighbourhood. Man: So alongside removing it we also need to communicate the change and offer an alternative.",
    "choukai_n2_hasil_audit|title": "Explaining the Audit Findings",
    "choukai_n2_hasil_audit|audioTranslation": "Woman: This audit produced three findings. None of them are serious, but what concerns me is that they keep coming from the same department. Man: So you're saying it's a problem with the system rather than with individual handling. Woman: I think that's very likely.",
    "choukai_n2_jam_kerja_fleksibel|title": "Debating Flexible Working Hours",
    "choukai_n2_jam_kerja_fleksibel|audioTranslation": "Man: I think staggered start times should be extended company-wide. Woman: But depending on the department, there's work that doesn't function unless people are present at the same time. Man: Then how about letting each department decide how to apply it? Woman: That's realistic. Rather than one rule for the whole company, I think it takes hold better when each department is accountable for its own.",
    "choukai_n2_kepadatan_wisata|title": "A Report on Tourist Congestion",
    "choukai_n2_kepadatan_wisata|audioTranslation": "Woman: This is a report on congestion at tourist sites over the long weekend. Visitor numbers were in line with last year, but the tendency to concentrate in particular time bands grew stronger. As a result, traffic on the surrounding roads was worse than last year. What's needed is not capping the total number but finding ways to spread people across the day.",

    # ---------------- N1 (30 clips, 60 fields) ----------------
    "choukai_n1_demografi|title": "A Lecture on Demographic Change",
    "choukai_n1_demografi|audioTranslation": "Man: Debate around population decline tends to concentrate on labour shortages. What really deserves examination, though, is that the very premises of society are being shaken. Systems designed on the assumption of ever-rising growth, for example, function poorly in a phase of shrinking population. However much we argue about making up the numbers, unless we revisit the design thinking behind our institutions, the same problem will simply reappear in a different form.",
    "choukai_n1_kecerdasan_buatan|title": "A Debate on Artificial Intelligence",
    "choukai_n1_kecerdasan_buatan|audioTranslation": "Woman: We cannot stop technological progress. Rather than regulating it, we should hurry to put it to use. Man: I take the opposite view — hurrying is the more dangerous course. The problem is not the technology itself but its spreading while responsibility remains unclear. Woman: But the loss of opportunity that comes from being overly cautious can't be ignored either. Man: I'm well aware of that. What I am saying is that a structure in which the cost of failure falls on individuals should be put right first.",
    "choukai_n1_kebijakan_pendidikan|title": "A Review of Education Policy",
    "choukai_n1_kebijakan_pendidikan|audioTranslation": "Woman: This reform promises a diversification of assessment methods. As a principle, that is to be welcomed. But if the number of teachers on the ground stays the same while only the assessment criteria multiply, it risks collapsing into mere box-ticking. The soundness of a principle and the provision of the conditions that support it need to be discussed as two separate questions.",
    "choukai_n1_peneliti_iklim|title": "An Interview with a Climate Researcher",
    "choukai_n1_peneliti_iklim|audioTranslation": "Man: How do you view arguments for postponing action on the grounds that the projections are uncertain? Woman: Being uncertain and knowing nothing are not the same thing. Even a projection given as a range indicates clearly enough the direction we should take. If anything, we must not overlook that the posture of waiting until things are certain itself narrows our options.",
    "choukai_n1_tren_konsumsi|title": "An Analysis of Consumption Trends",
    "choukai_n1_tren_konsumsi|audioTranslation": "Man: The phrase from ownership to access is widely used. Look at the statistics, however, and the shift is not proceeding uniformly across every generation. In rural areas in particular, constraints on transport mean that ownership still holds a considerable advantage. We should be cautious about reading an urban phenomenon as the overall current.",
    "choukai_n1_etika_jurnalistik|title": "A Discussion of Journalistic Ethics",
    "choukai_n1_etika_jurnalistik|audioTranslation": "Woman: In the rush to be first, cases where verification gets pushed back stand out. Man: But it isn't as simple as saying that delaying makes things accurate. Woman: Of course not. The issue is how an error is handled once it comes to light. If the correction doesn't reach readers with the same weight as the original article, their understanding stays fixed on that first impression.",
    "choukai_n1_memori_kolektif|title": "A Talk on Collective Memory",
    "choukai_n1_memori_kolektif|audioTranslation": "Man: How an event is remembered is not determined by the facts of what happened alone. Who was in a position to pass the story on is what shapes its outline. It is not that something is remembered because a record survives; the record survives as a result of a force working to remember. Get that order the wrong way round and you will overlook the areas that stay silent.",
    "choukai_n1_pelestarian_warisan|title": "A Debate on Heritage Preservation",
    "choukai_n1_pelestarian_warisan|audioTranslation": "Woman: Preservation is often taken to mean leaving a building exactly as it was. Man: But a building that stops being used deteriorates rapidly. Woman: Quite. So continuing to use it, even by changing its function, can mean it survives longer in the end. Man: Perhaps it is the view that sets preservation and use against each other that needs rethinking.",
    "choukai_n1_ekonomi_triwulan|title": "A Quarterly Economic Report",
    "choukai_n1_ekonomi_triwulan|audioTranslation": "Woman: This quarter's growth rate exceeded the previous quarter's. Break it down, however, and most of the increase comes from temporary factors. Capital investment has remained flat, and companies' judgement of the outlook is still cautious. Taking the improvement in the figures as a turn in the underlying trend would be premature.",
    "choukai_n1_sutradara_film|title": "An Interview with a Film Director",
    "choukai_n1_sutradara_film|audioTranslation": "Man: Do you consciously try to make things easy for the audience to follow? Woman: Once clarity becomes the goal, the work drifts towards explaining itself. What I want to hold on to instead is the sense of unease that remains once the film has ended. Even if it isn't understood on the spot, it can fall into place some years later. Being able to hold that span of time is, I think, film's strength.",
    "choukai_n1_bahasa_punah|title": "A Lecture on Dying Languages",
    "choukai_n1_bahasa_punah|audioTranslation": "Man: When a language disappears, what is lost is not a list of words. What disappears is a way of dividing up the world that was drawn nowhere but in that language. If we believe we have preserved it by carrying across only the parts that can be translated, that is documentation, not inheritance. Continuing to be used in the lives of its speakers and surviving as archive material are entirely different things.",
    "choukai_n1_reformasi_hukum|title": "A Discussion of Legal Reform",
    "choukai_n1_reformasi_hukum|audioTranslation": "Woman: I have doubts about the premise that making the provisions more detailed makes them fairer. Man: Some do point out that leaving room for interpretation invites arbitrary application. Woman: Yes. But as long as unforeseen cases are certain to arise, eliminating that room is impossible. What matters, surely, is that the reasons for a decision are published and can be examined.",
    "choukai_n1_konsumen_digital|title": "An Analysis of Digital Consumer Behaviour",
    "choukai_n1_konsumen_digital|audioTranslation": "Man: It has long been assumed that more choice raises satisfaction. In practice, however, the more effort goes into comparing, the more satisfaction after the decision tends to fall. In other words, abundance in itself is not the value; what is in question is whether the design lets people finish choosing.",
    "choukai_n1_arsitektur_kota|title": "A Talk on Urban Architecture",
    "choukai_n1_arsitektur_kota|audioTranslation": "Woman: The idea that building a square will draw people is far too naive. What decides whether people linger is not floor area but conditions of the most concrete kind — whether there is somewhere to sit down that falls in the shade, for instance. Examples of spaces that are beautiful on the drawing and used by nobody in practice are too numerous to count.",
    "choukai_n1_sumber_energi|title": "A Debate on Energy Sources",
    "choukai_n1_sumber_energi|audioTranslation": "Man: If stable supply is the priority, we should not narrow the options. Woman: But the idea that spreading them out brings safety is risky too. If each supply network carries the same weakness, increasing their number only means they all stop at once. Man: True — diversification with little independence can hardly be called diversification.",
    "choukai_n1_penulis_veteran|title": "An Interview with a Veteran Writer",
    "choukai_n1_penulis_veteran|audioTranslation": "Woman: What has driven you to keep writing for so long? Man: The stage of writing because there is something I want to write passed long ago. Now I write because I don't understand unless I write. Rather than writing once my thoughts have come together, I have come to know that there are places you can reach only by writing.",
    "choukai_n1_dampak_otomatisasi|title": "A Study of the Impact of Automation",
    "choukai_n1_dampak_otomatisasi|audioTranslation": "Man: The argument that automation destroys jobs has been repeated many times. Look back at history, though, and what vanished was less the occupation than the bundle of tasks that made it up. How the remaining tasks and the newly arising ones are reorganised, and whether one can take part in that, is what has determined the scale of the impact.",
    "choukai_n1_kesehatan_masyarakat|title": "A Discussion of Public Health",
    "choukai_n1_kesehatan_masyarakat|audioTranslation": "Woman: Campaigns urging personal effort do have a certain effect. Man: But they have a limit too: they only reach those with enough room to change their behaviour. Woman: Yes. Asking only for awareness without shifting conditions such as working hours and food prices could be said to put the responsibility in the wrong place. Man: Awareness campaigns that don't touch the structure risk widening the gap.",
    "choukai_n1_seni_kontemporer|title": "A Talk on Contemporary Art",
    "choukai_n1_seni_kontemporer|audioTranslation": "Man: Most works called difficult are not in fact hiding an answer. They do not take the form of an answer as their premise at all. As long as you keep asking what it means, all that comes back is the fact that there is no answer fitting the question. Changing how you frame the question is the way in.",
    "choukai_n1_kebijakan_transportasi|title": "An Analysis of Transport Policy",
    "choukai_n1_kebijakan_transportasi|audioTranslation": "Woman: The assumption that widening roads eases congestion has often been betrayed. When capacity increases, demand that had been holding back appears. Man: So one could also see congestion as a pricing problem rather than a shortage of supply. Woman: Yes. We need to re-examine what it is we are providing free of charge.",
    "choukai_n1_kepercayaan_publik|title": "A Lecture on Public Trust",
    "choukai_n1_kepercayaan_publik|audioTranslation": "Man: Trust in an institution is not determined solely by whether it functions correctly. What people watch, rather, is how failure is handled. A mechanism designed on the premise that errors will not occur loses a great deal of trust from a single tear. An institution whose correction procedures are made visible is, in the long run, the stronger one.",
    "choukai_n1_kebebasan_berekspresi|title": "A Debate on Freedom of Expression",
    "choukai_n1_kebebasan_berekspresi|audioTranslation": "Woman: I think we can agree that freedom of expression is not unlimited. Man: Yes. The question is who draws the line. Woman: Which is why I say we should debate the procedure, not the content. Man: I agree. Though the neutrality of a procedure is not itself free of the values of whoever designed it.",
    "choukai_n1_pasar_tenaga_kerja|title": "An Analysis of the Labour Market",
    "choukai_n1_pasar_tenaga_kerja|audioTranslation": "Man: Reports treating a rising ratio of vacancies to applicants as an indicator of labour shortage stand out. But that figure is no more than the ratio of openings to applicants, and it also rises when vacancies whose terms nobody will accept pile up. In other words, what is in short supply may not be people but acceptable terms.",
    "choukai_n1_arsiparis|title": "An Interview with an Archivist",
    "choukai_n1_arsiparis|audioTranslation": "Woman: How do you judge what to keep and what to discard? Man: That is the hardest part of the work. Something judged unimportant by today's values can become a decisive source fifty years from now. So we build our criteria on the premise that our own judgement may be wrong.",
    "choukai_n1_waktu_ingatan|title": "A Talk on Time and Memory",
    "choukai_n1_waktu_ingatan|audioTranslation": "Man: It is generally believed that memory fades as time passes. In fact, though, it is more accurate to see it as being rebuilt each time rather than fading. The act of recalling itself rewrites the memory. If that is so, the events told and retold most often may be the ones furthest from their original form.",
    "choukai_n1_otonomi_daerah|title": "A Discussion of Regional Autonomy",
    "choukai_n1_otonomi_daerah|audioTranslation": "Woman: There is an argument that transferring authority to local government allows policy that fits the actual situation. Man: But if only the authority moves and no funding comes with it, what can be done is limited. Woman: Yes. It risks becoming a structure in which only the responsibility moves, and residents' dissatisfaction is directed at the local authority. Man: Any debate on devolution has to be conducted together with the question of funding.",
    "choukai_n1_perilaku_kerumunan|title": "A Study of Crowd Behaviour",
    "choukai_n1_perilaku_kerumunan|audioTranslation": "Man: Accidents in crowds tend to be spoken of as individual carelessness. But past a certain density, no amount of individual care lets a person control their own movement. Beyond that point it is not a question of psychology but of physical conditions. There is a limit to seeking the remedy in raising awareness.",
    "choukai_n1_nilai_kerja|title": "A Debate on the Value of Work",
    "choukai_n1_nilai_kerja|audioTranslation": "Woman: I have doubts about the tendency to demand too much meaning from work. Man: But work in which no meaning can be felt doesn't last. Woman: Yes. Though meaning is not necessarily inherent in the work itself. Sometimes the simple fact that it supports a life is enough. Man: I can understand the point that forcing meaning onto it can instead corner people.",
    "choukai_n1_penerjemahan|title": "A Talk on Translation",
    "choukai_n1_penerjemahan|audioTranslation": "Man: Being faithful to the original and getting through to the reader often cannot both be achieved. Merely substituting a word drops the context that word was carrying. Supply too much, on the other hand, and the translator's interpretation comes to the front. Translation might also be described as the work of choosing where to give up.",
    "choukai_n1_kesenjangan_digital|title": "An Analysis of the Digital Divide",
    "choukai_n1_kesenjangan_digital|audioTranslation": "Woman: It was long assumed that as device ownership rose, the gap would narrow. But today's gap has shifted away from whether you have the hardware to whether you have the time to master it and the support to draw on. Even holding the same device, where people end up differs greatly according to whether there is someone they can ask when they get stuck.",
}
