# Canonical Dokkai (reading comprehension) scope — the single source of
# truth generate_dokkai_seed.py imports, mirroring kaiwa_lists.py's
# locked-list + LEVEL_META pattern.
#
# 2026-07-20: user asked to bring Dokkai to full parity across N5-N1,
# target ~100 passages per level (~500 total) — this is a genuine
# multi-session content rollout, same shape as Kaiwa's N4-N1 expansion
# (which took several phased sessions to reach 1700 dialogues). N5
# phase 1 below brings N5 from 3 to 20 passages. N4-N1 remain locked as
# not-yet-authored levels until their own phases start.

N5_TITLES = [
    "Surat dari Sahabat Pena",
    "Papan Pengumuman di Sekolah",
    "Jadwal Harian Yuki",
    "Memo dari Ibu",
    "Ramalan Cuaca Hari Ini",
    "Aturan Perpustakaan",
    "Iklan Lowongan Kerja Paruh Waktu",
    "Rencana Perjalanan Kelas",
    "Pengumuman Menu Baru Restoran",
    "Surat dari Teman Lama",
    "Pengumuman di Stasiun",
    "Pengumuman Kelas Tambahan",
    "Buku Harian Tanaka",
    "Peraturan Taman Kota",
    "Pengumuman Pindah Rumah",
    "Jam Buka Rumah Sakit",
    "Undangan Pesta Ulang Tahun",
    "Diskon Supermarket Akhir Pekan",
    "Liburan Keluarga ke Laut",
    "Perubahan Jadwal Sekolah",
    "Pengumuman Kelas Memasak",
    "Jadwal Bus Sekolah",
    "Surat Terima Kasih ke Guru",
    "Pengumuman Vaksinasi di Sekolah",
    "Cerita Piknik Sekolah",
    "Aturan Kolam Renang",
    "Menu Kantin Sekolah",
    "Pengumuman Lomba Menggambar",
    "Surat untuk Sahabat di Kota Lain",
    "Jadwal Kunjungan Dokter Gigi",
    "Pengumuman Perbaikan AC di Kelas",
    "Cerita Membantu Orang Tua di Rumah",
    "Aturan Menggunakan Komputer di Sekolah",
    "Pengumuman Bazar Sekolah",
    "Surat Undangan Piknik Keluarga",
    "Jadwal Latihan Klub Sepak Bola",
    "Cerita Membeli Hadiah untuk Ibu",
    "Pengumuman Libur Sekolah",
    "Cerita Belajar Kelompok",
    "Pengumuman Pameran Seni Sekolah",
    "Pengumuman Perbaikan Toilet Sekolah",
    "Cerita Menonton Kembang Api",
    "Surat Meminta Izin Tidak Masuk Sekolah",
    "Aturan Ruang Musik",
    "Jadwal Ujian Akhir Semester",
    "Cerita Membuat Kue Bersama Teman",
    "Pengumuman Donor Darah",
    "Menu Sarapan di Asrama",
    "Surat untuk Kakak yang Kuliah",
    "Pengumuman Perpindahan Kelas",
    "Pengumuman Perbaikan Lapangan Sekolah",
    "Cerita Piknik ke Kebun Binatang",
    "Surat Ucapan Selamat Ulang Tahun untuk Teman",
    "Aturan Ruang Komputer Perpustakaan Kota",
    "Jadwal Kegiatan Pramuka",
    "Cerita Membantu Adik Belajar",
    "Pengumuman Pertukaran Pelajar",
    "Menu Spesial Hari Anak",
    "Surat Permintaan Maaf ke Guru",
    "Pengumuman Perpustakaan Buka di Hari Libur",
    "Pengumuman Perbaikan Perpustakaan Sekolah",
    "Jadwal Kunjungan Museum",
    "Surat untuk Guru Baru",
    "Menu Makan Siang Spesial",
    "Pengumuman Kompetisi Olahraga",
    "Cerita Membantu Membersihkan Taman",
    "Jadwal Praktik Musik",
    "Pengumuman Perpindahan Perpustakaan",
    "Surat Ucapan Selamat Kelulusan",
    "Cerita Belanja di Pasar bersama Ayah",
    "Pengumuman Perpanjangan Waktu Belajar di Perpustakaan",
    "Jadwal Kunjungan ke Pemadam Kebakaran",
    "Surat dari Sepupu di Desa",
    "Menu Makan Malam Keluarga",
    "Pengumuman Kelas Origami",
    "Cerita Menanam Bunga di Sekolah",
    "Jadwal Latihan Klub Basket",
    "Pengumuman Pertukaran Buku Bekas",
    "Surat Ucapan Selamat Tahun Baru",
    "Cerita Membantu Kakek di Kebun",
    "Pengumuman Latihan Evakuasi Gempa",
    "Jadwal Kelas Kaligrafi",
    "Surat dari Teman di Sekolah Baru",
    "Menu Bekal untuk Piknik",
    "Pengumuman Perbaikan Lapangan Basket",
    "Cerita Membantu Ibu Memasak",
    "Jadwal Latihan Klub Menari",
    "Pengumuman Pemeriksaan Kesehatan Sekolah",
    "Surat Ucapan Terima Kasih untuk Orang Tua",
    "Cerita Bermain Salju di Musim Dingin",
]

# N4-N1 initial seed (10 each) — every level now has real starting
# content instead of zero; deepening toward the ~100/level target
# continues in future sessions/phases, same as N5's own rollout.
N4_TITLES = [
    "Hasil Wawancara Kerja",
    "Peringatan Topan",
    "Ulasan Restoran",
    "Blog Perjalanan",
    "Esai Pendapat tentang Media Sosial",
    "Ulasan Produk",
    "Surat Keluhan",
    "Balasan Undangan",
    "Pengumuman Pindah Alamat",
    "Artikel Tips Kesehatan",
    "Pengumuman Perpustakaan Baru Dibuka",
    "Resep Sederhana",
    "Pengalaman Hari Pertama Kerja",
    "Panduan Naik Kereta",
    "Iklan Kursus Bahasa",
    "Email Konfirmasi Reservasi",
    "Blog tentang Hobi Baru",
    "Pengumuman Perbaikan Jalan",
    "Surat dari Anak yang Kuliah di Luar Negeri",
    "Artikel tentang Manfaat Olahraga",
    "Pengumuman Diskon Toko Buku",
    "Belajar Memasak dari Nenek",
    "Email Permintaan Cuti Kerja",
    "Artikel tentang Kebiasaan Menabung",
    "Blog tentang Adaptasi di Kota Baru",
    "Surat Pengunduran Diri dari Klub",
    "Ulasan Aplikasi Belajar Bahasa",
    "Pengumuman Perubahan Jam Kerja",
    "Pengalaman Pertama Kali Naik Pesawat",
    "Panduan Merawat Tanaman",
    "Artikel tentang Kebiasaan Tidur yang Baik",
    "Email Ucapan Selamat Promosi",
    "Blog tentang Mencoba Hobi Berkebun",
    "Pengumuman Perbaikan Lift",
    "Surat Permintaan Maaf ke Teman",
    "Ulasan Tempat Wisata Baru",
    "Artikel tentang Cara Menghemat Uang",
    "Cerita Membantu Tetangga",
    "Panduan Menggunakan Mesin Cuci Umum",
    "Pengumuman Perekrutan Anggota Klub",
    "Ulasan Kursus Online",
    "Artikel tentang Manfaat Sarapan",
    "Blog tentang Belajar Bahasa Asing",
    "Email Konfirmasi Pesanan Online",
    "Pengalaman Bekerja Paruh Waktu",
    "Pengumuman Perubahan Menu Kantin Kantor",
    "Surat Permohonan Informasi Lowongan Kerja",
    "Panduan Daur Ulang Sampah",
    "Artikel tentang Kebiasaan Berolahraga Pagi",
    "Blog tentang Merapikan Rumah",
    "Blog tentang Mencoba Resep Baru",
    "Artikel tentang Cara Mengatur Waktu",
    "Surat Ucapan Terima Kasih atas Bantuan Pindahan",
    "Email Pengingat Rapat",
    "Cerita Belajar Mengendarai Sepeda Motor",
    "Pengumuman Perpanjangan Masa Berlaku Kartu Anggota",
    "Ulasan Aplikasi Pengatur Keuangan",
    "Blog tentang Menonton Film di Bioskop",
    "Artikel tentang Manfaat Membaca Buku",
    "Pengumuman Penggantian Jadwal Bus Kantor",
    "Blog tentang Belajar Fotografi",
    "Artikel tentang Kebiasaan Membaca sebelum Tidur",
    "Email Permintaan Rekomendasi Kerja",
    "Ulasan Kafe Baru di Kota",
    "Panduan Menghemat Listrik di Rumah",
    "Surat Undangan Reuni Sekolah",
    "Artikel tentang Manfaat Berjalan Kaki",
    "Pengalaman Pindah ke Apartemen Baru",
    "Blog tentang Belajar Memasak Masakan Jepang",
    "Pengumuman Perubahan Rute Bus Kota",
    "Blog tentang Belajar Bahasa Isyarat",
    "Artikel tentang Manfaat Menulis Jurnal",
    "Email Permintaan Informasi Kursus",
    "Ulasan Toko Buku Baru",
    "Panduan Merawat Sepeda",
    "Surat Ucapan Selamat Pernikahan",
    "Artikel tentang Manfaat Peregangan Pagi",
    "Pengalaman Menjadi Sukarelawan Pertama Kali",
    "Blog tentang Belajar Merajut",
    "Pengumuman Perubahan Jam Operasional Toko",
    "Blog tentang Belajar Membuat Kerajinan Tangan",
    "Artikel tentang Manfaat Mendengarkan Musik",
    "Email Permintaan Perpanjangan Sewa Apartemen",
    "Ulasan Aplikasi Belanja Online",
    "Panduan Merawat Kucing Peliharaan",
    "Surat Ucapan Selamat Kelahiran Anak",
    "Artikel tentang Manfaat Minum Air Putih",
    "Pengalaman Pertama Kali Mengajar",
    "Blog tentang Belajar Bahasa Korea",
    "Pengumuman Perubahan Sistem Pembayaran Toko",
]

N3_TITLES = [
    "Artikel Koran tentang Lingkungan",
    "Memo Tempat Kerja tentang Perubahan Sistem",
    "Esai Perbandingan Budaya",
    "Petunjuk Penggunaan Alat",
    "Esai Kesadaran Lingkungan",
    "Artikel Kesehatan",
    "Artikel Tren Teknologi",
    "Teks Sejarah Singkat",
    "Memo Rapat Kerja",
    "Cerita Pertukaran Budaya Internasional",
    "Artikel tentang Kebiasaan Makan Sehat",
    "Esai tentang Perubahan Musim",
    "Panduan Etika Bisnis di Jepang",
    "Artikel tentang Perkembangan Kota",
    "Pengalaman Kegiatan Sukarelawan",
    "Perbandingan Media Tradisional dan Digital",
    "Esai tentang Persahabatan",
    "Panduan Prosedur Darurat",
    "Artikel tentang Tren Pariwisata",
    "Cerita tentang Mengatasi Kegagalan",
    "Artikel tentang Sampah Makanan",
    "Esai tentang Kebiasaan Membaca",
    "Panduan Etika di Transportasi Umum",
    "Artikel tentang Perubahan Pola Kerja",
    "Esai tentang Menjaga Tradisi Keluarga",
    "Cerita Pengalaman Magang",
    "Artikel tentang Media Sosial dan Remaja",
    "Petunjuk Prosedur Evakuasi Kebakaran",
    "Esai tentang Pentingnya Hobi",
    "Artikel tentang Perkembangan Belanja Online",
    "Cerita Pengalaman Mengajar Anak",
    "Esai tentang Menghadapi Perubahan",
    "Artikel tentang Konservasi Air",
    "Panduan Menulis Email Bisnis",
    "Esai tentang Menemukan Passion",
    "Artikel tentang Tren Kerja Remote",
    "Cerita Pengalaman Pindah Sekolah",
    "Esai tentang Menghargai Waktu",
    "Artikel tentang Perkembangan Transportasi Umum",
    "Esai tentang Belajar dari Kegagalan Orang Lain",
    "Artikel tentang Keamanan Pangan",
    "Esai tentang Menghargai Guru",
    "Panduan Etika Wawancara Kerja",
    "Artikel tentang Tren Konsumsi Berkelanjutan",
    "Pengalaman Menjadi Relawan Bencana",
    "Esai tentang Menjaga Kesehatan Mental",
    "Artikel tentang Dampak Media terhadap Opini Publik",
    "Petunjuk Menghadapi Wawancara Kerja",
    "Esai tentang Nilai Kejujuran",
    "Artikel tentang Tren Kerja Freelance",
    "Artikel tentang Etika Penggunaan Media Sosial di Tempat Kerja",
    "Esai tentang Menemukan Keseimbangan Hidup",
    "Cerita Pengalaman Belajar di Luar Negeri",
    "Panduan Merencanakan Anggaran Perjalanan",
    "Artikel tentang Tren Belanja Berkelanjutan",
    "Esai tentang Menghadapi Kritik",
    "Petunjuk Prosedur Pengajuan Klaim Asuransi",
    "Artikel tentang Perubahan Gaya Hidup Perkotaan",
    "Cerita Pengalaman Menjadi Mentor",
    "Esai tentang Arti Kesuksesan bagi Generasi Muda",
    "Artikel tentang Perkembangan Kerja Jarak Jauh",
    "Esai tentang Menghadapi Tekanan Ujian",
    "Cerita Pengalaman Menjadi Ketua Kelas",
    "Panduan Etika Menggunakan Media Sosial",
    "Artikel tentang Tren Konsumsi Ramah Lingkungan",
    "Esai tentang Pentingnya Komunikasi Keluarga",
    "Petunjuk Prosedur Pengajuan Beasiswa",
    "Artikel tentang Perubahan Kebiasaan Belanja",
    "Esai tentang Menemukan Motivasi Belajar",
    "Cerita Pengalaman Bekerja di Perusahaan Asing",
    "Artikel tentang Perkembangan Kendaraan Listrik",
    "Esai tentang Menghadapi Perpisahan dengan Teman",
    "Cerita Pengalaman Menjadi Panitia Acara",
    "Panduan Etika Berkomunikasi lewat Email",
    "Artikel tentang Tren Kerja Paruh Waktu bagi Pelajar",
    "Esai tentang Pentingnya Waktu Istirahat",
    "Petunjuk Prosedur Pengajuan Visa",
    "Artikel tentang Perubahan Kebiasaan Berolahraga",
    "Esai tentang Menemukan Keberanian Berbicara di Depan Umum",
    "Cerita Pengalaman Tinggal di Asrama",
    "Artikel tentang Perkembangan Energi Surya di Rumah",
    "Esai tentang Menghadapi Rasa Iri",
    "Cerita Pengalaman Menjadi Tutor Sebaya",
    "Panduan Etika Menerima Tamu di Rumah",
    "Artikel tentang Tren Makanan Nabati",
    "Esai tentang Pentingnya Meminta Maaf",
    "Petunjuk Prosedur Pengajuan Cuti Melahirkan",
    "Artikel tentang Perubahan Kebiasaan Menonton",
    "Esai tentang Menemukan Arti Kerja Tim",
    "Cerita Pengalaman Menjadi Penerjemah Sukarela",
]

N2_TITLES = [
    "Laporan Manajemen Perusahaan",
    "Editorial Sosial",
    "Penjelasan Ilmiah",
    "Esai tentang Karier dan Kehidupan",
    "Berita Ekonomi",
    "Analisis Budaya",
    "Pengembangan Karier",
    "Kebijakan Medis",
    "Strategi Perusahaan",
    "Esai tentang Pendidikan",
    "Laporan Riset Pasar",
    "Editorial tentang Pendidikan Anak",
    "Artikel tentang Inovasi Teknologi Ramah Lingkungan",
    "Esai tentang Keseimbangan Kerja dan Kehidupan",
    "Analisis Tren Konsumen",
    "Artikel tentang Diplomasi Budaya",
    "Esai tentang Warisan Keluarga",
    "Laporan tentang Perubahan Demografi",
    "Artikel tentang Etika Bisnis Global",
    "Esai tentang Definisi Kesuksesan",
    "Laporan tentang Krisis Iklim",
    "Editorial tentang Reformasi Sistem Pensiun",
    "Analisis tentang Pergeseran Nilai Generasi",
    "Esai tentang Etika Kecerdasan Buatan",
    "Artikel tentang Ketimpangan Ekonomi",
    "Laporan tentang Inovasi Medis",
    "Editorial tentang Kebebasan Pers",
    "Esai tentang Warisan Intelektual",
    "Analisis tentang Perubahan Struktur Keluarga",
    "Artikel tentang Diplomasi Ekonomi",
    "Esai tentang Batas Privasi Digital",
    "Laporan tentang Revitalisasi Daerah",
    "Editorial tentang Kesetaraan Gender di Tempat Kerja",
    "Esai tentang Filosofi Minimalisme",
    "Artikel tentang Krisis Tenaga Kerja",
    "Analisis tentang Dampak Pariwisata Berlebihan",
    "Esai tentang Makna Rumah",
    "Laporan tentang Perkembangan Kota Pintar",
    "Editorial tentang Reformasi Pendidikan Tinggi",
    "Esai tentang Menyeimbangkan Tradisi dan Modernitas",
    "Editorial tentang Krisis Kepercayaan Institusi",
    "Analisis tentang Perubahan Perilaku Konsumen Digital",
    "Esai tentang Tanggung Jawab Sosial Perusahaan",
    "Artikel tentang Dilema Etika Bioteknologi",
    "Laporan tentang Transformasi Industri Manufaktur",
    "Editorial tentang Polarisasi Opini Publik",
    "Esai tentang Adaptasi Terhadap Globalisasi",
    "Artikel tentang Masa Depan Energi Terbarukan",
    "Analisis tentang Perubahan Preferensi Karier Generasi Muda",
    "Esai tentang Makna Kerja dalam Kehidupan Modern",
    "Editorial tentang Krisis Perumahan Perkotaan",
    "Analisis tentang Perubahan Pola Migrasi Tenaga Kerja",
    "Esai tentang Dilema Kemajuan Teknologi Medis",
    "Artikel tentang Tantangan Regulasi Mata Uang Digital",
    "Laporan tentang Perubahan Perilaku Investasi Generasi Muda",
    "Editorial tentang Beban Sistem Kesehatan Masyarakat",
    "Esai tentang Tanggung Jawab Antar Generasi",
    "Artikel tentang Dampak Otomatisasi terhadap Pasar Kerja",
    "Analisis tentang Krisis Kepercayaan pada Sains",
    "Esai tentang Definisi Komunitas di Era Digital",
    "Esai tentang Etika Penelitian Ilmiah",
    "Artikel tentang Reformasi Sistem Pajak",
    "Analisis tentang Dampak Media Sosial pada Demokrasi",
    "Laporan tentang Perubahan Pola Konsumsi Energi",
    "Editorial tentang Krisis Kepercayaan Politik",
    "Esai tentang Batas Kebebasan Berekspresi",
    "Artikel tentang Tantangan Integrasi Imigran",
    "Analisis tentang Perubahan Nilai Kerja Generasi Z",
    "Laporan tentang Inovasi dalam Pendidikan Daring",
    "Esai tentang Dilema Privasi dan Keamanan",
    "Esai tentang Etika Jurnalisme Investigasi",
    "Artikel tentang Reformasi Sistem Kesehatan",
    "Analisis tentang Dampak Kecerdasan Buatan pada Lapangan Kerja",
    "Laporan tentang Perubahan Pola Migrasi Perkotaan",
    "Editorial tentang Krisis Kepercayaan Media",
    "Esai tentang Batas Tanggung Jawab Perusahaan",
    "Artikel tentang Tantangan Kesetaraan Pendidikan",
    "Analisis tentang Perubahan Nilai Keluarga Modern",
    "Laporan tentang Inovasi dalam Transportasi Umum",
    "Esai tentang Dilema Kebebasan Individu dan Kepentingan Bersama",
    "Esai tentang Etika Periklanan Digital",
    "Artikel tentang Reformasi Sistem Ketenagakerjaan",
    "Analisis tentang Dampak Otomasi pada Industri Ritel",
    "Laporan tentang Perubahan Pola Konsumsi Media",
    "Editorial tentang Krisis Kepercayaan Perbankan",
    "Esai tentang Batas Tanggung Jawab Individu dalam Krisis Iklim",
    "Artikel tentang Tantangan Kesehatan Mental di Tempat Kerja",
    "Analisis tentang Perubahan Nilai Konsumsi Generasi Muda",
    "Laporan tentang Inovasi dalam Pertanian Perkotaan",
    "Esai tentang Dilema Kemajuan Genetika Manusia",
]

N1_TITLES = [
    "Esai tentang Kehilangan",
    "Esai tentang Ketidakkekalan Waktu",
    "Kritik Sosial",
    "Surat Formal Perkenalan Bisnis",
    "Esai tentang Proses Kemandirian",
    "Kajian Sejarah Mendalam",
    "Refleksi tentang Pemaafan Diri",
    "Diskusi Filosofis tentang Etika Sains",
    "Kritik Seni Sastra",
    "Kajian Perubahan Sosial",
    "Esai tentang Makna Kebebasan",
    "Refleksi tentang Warisan Budaya yang Hilang",
    "Kritik tentang Konsumerisme Modern",
    "Diskusi tentang Hubungan Manusia dan Alam",
    "Diskusi tentang Bahasa dan Identitas",
    "Refleksi tentang Perjalanan Hidup",
    "Esai tentang Keheningan dan Kebijaksanaan",
    "Kritik Sastra Klasik",
    "Esai tentang Batas Antara Realita dan Ilusi",
    "Refleksi Filosofis tentang Kematian dan Kehidupan",
    "Esai tentang Arti Menunggu",
    "Refleksi tentang Kesenyapan Kota Malam",
    "Kritik tentang Budaya Kecepatan Modern",
    "Esai tentang Warisan Leluhur yang Tak Terlihat",
    "Diskusi Filosofis tentang Kebenaran",
    "Refleksi tentang Kerinduan akan Tempat Asal",
    "Esai tentang Batas Antara Cinta dan Kewajiban",
    "Kritik Sastra tentang Narasi Sejarah",
    "Esai tentang Ketakutan Menghadapi Perubahan",
    "Refleksi tentang Makna Sebuah Perpisahan",
    "Diskusi tentang Etika dalam Seni",
    "Esai tentang Beban Ekspektasi Sosial",
    "Refleksi tentang Kesendirian yang Bermakna",
    "Kritik tentang Modernisasi Bahasa",
    "Esai tentang Warisan Trauma Antar Generasi",
    "Diskusi Filosofis tentang Waktu dan Ingatan",
    "Refleksi tentang Keberanian Menjadi Diri Sendiri",
    "Esai tentang Paradoks Kebahagiaan",
    "Kritik tentang Objektivitas dalam Jurnalisme",
    "Refleksi Penutup tentang Perjalanan Menulis",
    "Esai tentang Keindahan Ketidaksempurnaan",
    "Refleksi tentang Beban Sejarah Keluarga",
    "Diskusi Filosofis tentang Kehendak Bebas",
    "Esai tentang Arti Menjadi Dewasa",
    "Kritik tentang Budaya Perbandingan Sosial",
    "Refleksi tentang Suara yang Tak Terdengar",
    "Esai tentang Ketahanan dalam Kesulitan",
    "Diskusi tentang Batas Pengetahuan Manusia",
    "Refleksi tentang Jejak yang Ditinggalkan",
    "Esai Penutup tentang Perjalanan Mencari Makna",
    "Esai tentang Ambang Batas Antara Kewarasan dan Kegilaan",
    "Refleksi tentang Kefanaan Kenangan",
    "Diskusi Filosofis tentang Makna Penderitaan",
    "Esai tentang Ironi Kemajuan Peradaban",
    "Kritik tentang Tirani Pilihan dalam Masyarakat Modern",
    "Refleksi tentang Jarak Antara Kata dan Perasaan",
    "Esai tentang Paradoks Kebebasan dan Keterikatan",
    "Diskusi tentang Batas Antara Empati dan Simpati",
    "Refleksi tentang Warisan yang Tak Diminta",
    "Esai Akhir tentang Rekonsiliasi dengan Masa Lalu",
    "Refleksi tentang Makna Keheningan dalam Percakapan",
    "Esai tentang Beban Menjadi Saksi Sejarah",
    "Diskusi Filosofis tentang Batas Moralitas",
    "Kritik tentang Estetika Kesempurnaan",
    "Refleksi tentang Arti Rumah bagi Perantau",
    "Esai tentang Ironi Kemajuan Ilmu Pengetahuan",
    "Diskusi tentang Batas Antara Seni dan Kehidupan",
    "Refleksi tentang Warisan Kata-kata yang Tak Terucap",
    "Esai tentang Ketahanan Jiwa dalam Kehilangan",
    "Kritik tentang Mitos Kesuksesan Individual",
    "Refleksi tentang Makna Kesetiaan",
    "Esai tentang Beban Menjaga Warisan Keluarga",
    "Diskusi Filosofis tentang Batas Kebenaran Subjektif",
    "Kritik tentang Estetika Kesederhanaan",
    "Refleksi tentang Arti Kepulangan",
    "Esai tentang Ironi Kemajuan Sosial",
    "Diskusi tentang Batas Antara Mimpi dan Kenyataan",
    "Refleksi tentang Warisan Diam yang Diwariskan",
    "Esai tentang Ketahanan dalam Menghadapi Kesepian",
    "Kritik tentang Mitos Kebahagiaan Sempurna",
    "Refleksi tentang Makna Menunggu Tanpa Kepastian",
    "Esai tentang Beban Menjadi Penerus Tunggal",
    "Diskusi Filosofis tentang Batas Identitas Diri",
    "Kritik tentang Estetika Ketidakabadian",
    "Refleksi tentang Arti Kehilangan Bahasa Ibu",
    "Esai tentang Ironi Kemajuan Komunikasi",
    "Diskusi tentang Batas Antara Ingatan dan Rekaan",
    "Refleksi tentang Warisan Luka yang Tersembunyi",
    "Esai tentang Ketahanan dalam Menghadapi Ketidakpastian",
    "Kritik tentang Mitos Kesempurnaan Cinta",
]

LEVEL_META = {
    "n5": ("N5", True),
    "n4": ("N4", True),
    "n3": ("N3", True),
    "n2": ("N2", True),
    "n1": ("N1", True),
}
