# Canonical Dokkai (reading comprehension) scope — the single source of
# truth generate_dokkai_seed.py imports, mirroring kaiwa_lists.py's
# locked-list + LEVEL_META pattern.
#
# 2026-07-20: user asked to bring Dokkai to full parity across N5-N1,
# target ~100 passages per level (~500 total) — this is a genuine
# multi-session content rollout, same shape as Kaiwa's N4-N1 expansion
# (which took several phased sessions to reach 1700 dialogues). N5
# phase 1 below brings N5 from 3 to 20 passages. N4-N1 remain locked as
# not-yet-authored levels until their own phases start.

N5_TITLES = [
    "Surat dari Sahabat Pena",
    "Papan Pengumuman di Sekolah",
    "Jadwal Harian Yuki",
    "Memo dari Ibu",
    "Ramalan Cuaca Hari Ini",
    "Aturan Perpustakaan",
    "Iklan Lowongan Kerja Paruh Waktu",
    "Rencana Perjalanan Kelas",
    "Pengumuman Menu Baru Restoran",
    "Surat dari Teman Lama",
    "Pengumuman di Stasiun",
    "Pengumuman Kelas Tambahan",
    "Buku Harian Tanaka",
    "Peraturan Taman Kota",
    "Pengumuman Pindah Rumah",
    "Jam Buka Rumah Sakit",
    "Undangan Pesta Ulang Tahun",
    "Diskon Supermarket Akhir Pekan",
    "Liburan Keluarga ke Laut",
    "Perubahan Jadwal Sekolah",
    "Pengumuman Kelas Memasak",
    "Jadwal Bus Sekolah",
    "Surat Terima Kasih ke Guru",
    "Pengumuman Vaksinasi di Sekolah",
    "Cerita Piknik Sekolah",
    "Aturan Kolam Renang",
    "Menu Kantin Sekolah",
    "Pengumuman Lomba Menggambar",
    "Surat untuk Sahabat di Kota Lain",
    "Jadwal Kunjungan Dokter Gigi",
    "Pengumuman Perbaikan AC di Kelas",
    "Cerita Membantu Orang Tua di Rumah",
    "Aturan Menggunakan Komputer di Sekolah",
    "Pengumuman Bazar Sekolah",
    "Surat Undangan Piknik Keluarga",
    "Jadwal Latihan Klub Sepak Bola",
    "Cerita Membeli Hadiah untuk Ibu",
    "Pengumuman Libur Sekolah",
    "Cerita Belajar Kelompok",
    "Pengumuman Pameran Seni Sekolah",
    "Pengumuman Perbaikan Toilet Sekolah",
    "Cerita Menonton Kembang Api",
    "Surat Meminta Izin Tidak Masuk Sekolah",
    "Aturan Ruang Musik",
    "Jadwal Ujian Akhir Semester",
    "Cerita Membuat Kue Bersama Teman",
    "Pengumuman Donor Darah",
    "Menu Sarapan di Asrama",
    "Surat untuk Kakak yang Kuliah",
    "Pengumuman Perpindahan Kelas",
]

# N4-N1 initial seed (10 each) — every level now has real starting
# content instead of zero; deepening toward the ~100/level target
# continues in future sessions/phases, same as N5's own rollout.
N4_TITLES = [
    "Hasil Wawancara Kerja",
    "Peringatan Topan",
    "Ulasan Restoran",
    "Blog Perjalanan",
    "Esai Pendapat tentang Media Sosial",
    "Ulasan Produk",
    "Surat Keluhan",
    "Balasan Undangan",
    "Pengumuman Pindah Alamat",
    "Artikel Tips Kesehatan",
    "Pengumuman Perpustakaan Baru Dibuka",
    "Resep Sederhana",
    "Pengalaman Hari Pertama Kerja",
    "Panduan Naik Kereta",
    "Iklan Kursus Bahasa",
    "Email Konfirmasi Reservasi",
    "Blog tentang Hobi Baru",
    "Pengumuman Perbaikan Jalan",
    "Surat dari Anak yang Kuliah di Luar Negeri",
    "Artikel tentang Manfaat Olahraga",
    "Pengumuman Diskon Toko Buku",
    "Belajar Memasak dari Nenek",
    "Email Permintaan Cuti Kerja",
    "Artikel tentang Kebiasaan Menabung",
    "Blog tentang Adaptasi di Kota Baru",
    "Surat Pengunduran Diri dari Klub",
    "Ulasan Aplikasi Belajar Bahasa",
    "Pengumuman Perubahan Jam Kerja",
    "Pengalaman Pertama Kali Naik Pesawat",
    "Panduan Merawat Tanaman",
    "Artikel tentang Kebiasaan Tidur yang Baik",
    "Email Ucapan Selamat Promosi",
    "Blog tentang Mencoba Hobi Berkebun",
    "Pengumuman Perbaikan Lift",
    "Surat Permintaan Maaf ke Teman",
    "Ulasan Tempat Wisata Baru",
    "Artikel tentang Cara Menghemat Uang",
    "Cerita Membantu Tetangga",
    "Panduan Menggunakan Mesin Cuci Umum",
    "Pengumuman Perekrutan Anggota Klub",
    "Ulasan Kursus Online",
    "Artikel tentang Manfaat Sarapan",
    "Blog tentang Belajar Bahasa Asing",
    "Email Konfirmasi Pesanan Online",
    "Pengalaman Bekerja Paruh Waktu",
    "Pengumuman Perubahan Menu Kantin Kantor",
    "Surat Permohonan Informasi Lowongan Kerja",
    "Panduan Daur Ulang Sampah",
    "Artikel tentang Kebiasaan Berolahraga Pagi",
    "Blog tentang Merapikan Rumah",
]

N3_TITLES = [
    "Artikel Koran tentang Lingkungan",
    "Memo Tempat Kerja tentang Perubahan Sistem",
    "Esai Perbandingan Budaya",
    "Petunjuk Penggunaan Alat",
    "Esai Kesadaran Lingkungan",
    "Artikel Kesehatan",
    "Artikel Tren Teknologi",
    "Teks Sejarah Singkat",
    "Memo Rapat Kerja",
    "Cerita Pertukaran Budaya Internasional",
    "Artikel tentang Kebiasaan Makan Sehat",
    "Esai tentang Perubahan Musim",
    "Panduan Etika Bisnis di Jepang",
    "Artikel tentang Perkembangan Kota",
    "Pengalaman Kegiatan Sukarelawan",
    "Perbandingan Media Tradisional dan Digital",
    "Esai tentang Persahabatan",
    "Panduan Prosedur Darurat",
    "Artikel tentang Tren Pariwisata",
    "Cerita tentang Mengatasi Kegagalan",
    "Artikel tentang Sampah Makanan",
    "Esai tentang Kebiasaan Membaca",
    "Panduan Etika di Transportasi Umum",
    "Artikel tentang Perubahan Pola Kerja",
    "Esai tentang Menjaga Tradisi Keluarga",
    "Cerita Pengalaman Magang",
    "Artikel tentang Media Sosial dan Remaja",
    "Petunjuk Prosedur Evakuasi Kebakaran",
    "Esai tentang Pentingnya Hobi",
    "Artikel tentang Perkembangan Belanja Online",
    "Cerita Pengalaman Mengajar Anak",
    "Esai tentang Menghadapi Perubahan",
    "Artikel tentang Konservasi Air",
    "Panduan Menulis Email Bisnis",
    "Esai tentang Menemukan Passion",
    "Artikel tentang Tren Kerja Remote",
    "Cerita Pengalaman Pindah Sekolah",
    "Esai tentang Menghargai Waktu",
    "Artikel tentang Perkembangan Transportasi Umum",
    "Esai tentang Belajar dari Kegagalan Orang Lain",
    "Artikel tentang Keamanan Pangan",
    "Esai tentang Menghargai Guru",
    "Panduan Etika Wawancara Kerja",
    "Artikel tentang Tren Konsumsi Berkelanjutan",
    "Pengalaman Menjadi Relawan Bencana",
    "Esai tentang Menjaga Kesehatan Mental",
    "Artikel tentang Dampak Media terhadap Opini Publik",
    "Petunjuk Menghadapi Wawancara Kerja",
    "Esai tentang Nilai Kejujuran",
    "Artikel tentang Tren Kerja Freelance",
]

N2_TITLES = [
    "Laporan Manajemen Perusahaan",
    "Editorial Sosial",
    "Penjelasan Ilmiah",
    "Esai tentang Karier dan Kehidupan",
    "Berita Ekonomi",
    "Analisis Budaya",
    "Pengembangan Karier",
    "Kebijakan Medis",
    "Strategi Perusahaan",
    "Esai tentang Pendidikan",
    "Laporan Riset Pasar",
    "Editorial tentang Pendidikan Anak",
    "Artikel tentang Inovasi Teknologi Ramah Lingkungan",
    "Esai tentang Keseimbangan Kerja dan Kehidupan",
    "Analisis Tren Konsumen",
    "Artikel tentang Diplomasi Budaya",
    "Esai tentang Warisan Keluarga",
    "Laporan tentang Perubahan Demografi",
    "Artikel tentang Etika Bisnis Global",
    "Esai tentang Definisi Kesuksesan",
    "Laporan tentang Krisis Iklim",
    "Editorial tentang Reformasi Sistem Pensiun",
    "Analisis tentang Pergeseran Nilai Generasi",
    "Esai tentang Etika Kecerdasan Buatan",
    "Artikel tentang Ketimpangan Ekonomi",
    "Laporan tentang Inovasi Medis",
    "Editorial tentang Kebebasan Pers",
    "Esai tentang Warisan Intelektual",
    "Analisis tentang Perubahan Struktur Keluarga",
    "Artikel tentang Diplomasi Ekonomi",
    "Esai tentang Batas Privasi Digital",
    "Laporan tentang Revitalisasi Daerah",
    "Editorial tentang Kesetaraan Gender di Tempat Kerja",
    "Esai tentang Filosofi Minimalisme",
    "Artikel tentang Krisis Tenaga Kerja",
    "Analisis tentang Dampak Pariwisata Berlebihan",
    "Esai tentang Makna Rumah",
    "Laporan tentang Perkembangan Kota Pintar",
    "Editorial tentang Reformasi Pendidikan Tinggi",
    "Esai tentang Menyeimbangkan Tradisi dan Modernitas",
    "Editorial tentang Krisis Kepercayaan Institusi",
    "Analisis tentang Perubahan Perilaku Konsumen Digital",
    "Esai tentang Tanggung Jawab Sosial Perusahaan",
    "Artikel tentang Dilema Etika Bioteknologi",
    "Laporan tentang Transformasi Industri Manufaktur",
    "Editorial tentang Polarisasi Opini Publik",
    "Esai tentang Adaptasi Terhadap Globalisasi",
    "Artikel tentang Masa Depan Energi Terbarukan",
    "Analisis tentang Perubahan Preferensi Karier Generasi Muda",
    "Esai tentang Makna Kerja dalam Kehidupan Modern",
]

N1_TITLES = [
    "Esai tentang Kehilangan",
    "Esai tentang Ketidakkekalan Waktu",
    "Kritik Sosial",
    "Surat Formal Perkenalan Bisnis",
    "Esai tentang Proses Kemandirian",
    "Kajian Sejarah Mendalam",
    "Refleksi tentang Pemaafan Diri",
    "Diskusi Filosofis tentang Etika Sains",
    "Kritik Seni Sastra",
    "Kajian Perubahan Sosial",
    "Esai tentang Makna Kebebasan",
    "Refleksi tentang Warisan Budaya yang Hilang",
    "Kritik tentang Konsumerisme Modern",
    "Diskusi tentang Hubungan Manusia dan Alam",
    "Diskusi tentang Bahasa dan Identitas",
    "Refleksi tentang Perjalanan Hidup",
    "Esai tentang Keheningan dan Kebijaksanaan",
    "Kritik Sastra Klasik",
    "Esai tentang Batas Antara Realita dan Ilusi",
    "Refleksi Filosofis tentang Kematian dan Kehidupan",
    "Esai tentang Arti Menunggu",
    "Refleksi tentang Kesenyapan Kota Malam",
    "Kritik tentang Budaya Kecepatan Modern",
    "Esai tentang Warisan Leluhur yang Tak Terlihat",
    "Diskusi Filosofis tentang Kebenaran",
    "Refleksi tentang Kerinduan akan Tempat Asal",
    "Esai tentang Batas Antara Cinta dan Kewajiban",
    "Kritik Sastra tentang Narasi Sejarah",
    "Esai tentang Ketakutan Menghadapi Perubahan",
    "Refleksi tentang Makna Sebuah Perpisahan",
    "Diskusi tentang Etika dalam Seni",
    "Esai tentang Beban Ekspektasi Sosial",
    "Refleksi tentang Kesendirian yang Bermakna",
    "Kritik tentang Modernisasi Bahasa",
    "Esai tentang Warisan Trauma Antar Generasi",
    "Diskusi Filosofis tentang Waktu dan Ingatan",
    "Refleksi tentang Keberanian Menjadi Diri Sendiri",
    "Esai tentang Paradoks Kebahagiaan",
    "Kritik tentang Objektivitas dalam Jurnalisme",
    "Refleksi Penutup tentang Perjalanan Menulis",
    "Esai tentang Keindahan Ketidaksempurnaan",
    "Refleksi tentang Beban Sejarah Keluarga",
    "Diskusi Filosofis tentang Kehendak Bebas",
    "Esai tentang Arti Menjadi Dewasa",
    "Kritik tentang Budaya Perbandingan Sosial",
    "Refleksi tentang Suara yang Tak Terdengar",
    "Esai tentang Ketahanan dalam Kesulitan",
    "Diskusi tentang Batas Pengetahuan Manusia",
    "Refleksi tentang Jejak yang Ditinggalkan",
    "Esai Penutup tentang Perjalanan Mencari Makna",
]

LEVEL_META = {
    "n5": ("N5", True),
    "n4": ("N4", True),
    "n3": ("N3", True),
    "n2": ("N2", True),
    "n1": ("N1", True),
}
