"""
dokkai_meaning_en.py

Locked source of truth for the English translations of Dokkai passage
content: DokkaiPassage.titleEn/passageTranslationEn.
apply_dokkai_meaning_en.py reads this and patches assets/data/dokkai_data.json,
so translations live in exactly one place.

Key format:
    "{id}|title"               -> the passage's title
    "{id}|passageTranslation"  -> the Indonesian translation of the passage's
                                   Japanese text, rendered into English

Scope note: neither field is currently rendered anywhere in the app —
the passage-title list screen (DokkaiLevelScreen) was deleted in an
earlier session (tapping a level now opens a random passage directly),
and DokkaiExamScreen only ever shows passageJapanese (the original
Japanese text) plus Japanese questions/options, never the Indonesian/
English translation, to keep the reading-comprehension exam genuine.
Translated anyway for completeness, mirroring Kaiwa's npc lines.

STATUS: in progress. Total scope: 500 passages x 2 fields = 1,000.
Batched by JLPT level (N5/N4/N3/N2/N1, 100 passages = 200 fields each),
same verify-patch-apply-commit cycle as every other rollout in this
codebase.
"""

DOKKAI_MEANING_EN = {
    # ---------------- N5 (100 passages, 200 fields) ----------------
    "dokkai_surat_sahabat_pena|title": "A Letter from a Pen Pal",
    "dokkai_surat_sahabat_pena|passageTranslation": "Nice to meet you. I'm Mary. I'm from America. I'm studying Japanese now. My hobbies are cooking and reading. I often walk in the park on weekends. I've never been to Japan. I want to go someday. Please look after me.",
    "dokkai_papan_pengumuman_sekolah|title": "School Notice Board",
    "dokkai_papan_pengumuman_sekolah|passageTranslation": "There's a sports event next Monday. Please come to school at 8 in the morning. Please bring a packed lunch. If it rains, the sports event won't be held. In that case it will be held on Tuesday.",
    "dokkai_jadwal_harian_yuki|title": "Yuki's Daily Schedule",
    "dokkai_jadwal_harian_yuki|passageTranslation": "Yuki wakes up at 6:30 every morning. She eats at 7. At 8 she leaves the house and goes to school. Classes are from 9 to 3. After school, she studies at the library. After coming home, she has dinner and does her homework. She sleeps at 10.",
    "dokkai_memo_okaasan|title": "A Note from Mom",
    "dokkai_memo_okaasan|passageTranslation": "To Yuta. Mom is coming home late today because of work. There's curry in the fridge. Please heat it up and eat it. Mom will be home before 8. Don't forget your homework. From Mom.",
    "dokkai_tenki_yohou|title": "Today's Weather Forecast",
    "dokkai_tenki_yohou|passageTranslation": "Here's today's weather forecast. It'll be cloudy in the morning. Rain will start falling from midday. Around 3 in the afternoon, the rain will be heaviest. It's expected to clear up in the evening. Please bring an umbrella when you go out.",
    "dokkai_annai_toshokan|title": "Library Rules",
    "dokkai_annai_toshokan|passageTranslation": "A library announcement. Books can be borrowed for two weeks. One person can borrow up to five books. Please don't eat or drink inside the library. Please don't use your mobile phone.",
    "dokkai_shinbun_kokoku|title": "Part-Time Job Ad",
    "dokkai_shinbun_kokoku|passageTranslation": "Part-time job wanted. Want to work at a cafe nearby? Working hours are from 5 pm to 9 pm. You can start working twice a week. No experience needed. If interested, please call the shop.",
    "dokkai_ryokou_annai|title": "Class Trip Plan",
    "dokkai_ryokou_annai|passageTranslation": "Next month, our class will go on a trip to Kyoto. We'll go by bus. Please gather at school at 7 in the morning. Please bring a packed lunch and money. Let's also take lots of photos.",
    "dokkai_resutoran_menu_annai|title": "Restaurant's New Menu Announcement",
    "dokkai_resutoran_menu_annai|passageTranslation": "Our restaurant has a new menu. Starting this month, ramen and curry are available. Ramen is 700 yen, curry is 600 yen. On Saturdays and Sundays it's 100 yen cheaper. Please come visit.",
    "dokkai_tomodachi_no_tegami|title": "A Letter from an Old Friend",
    "dokkai_tomodachi_no_tegami|passageTranslation": "It's been a while. How are you? I moved to a new city last month. The new house is close to the station, very convenient. Since I still have few friends, it's a bit lonely. Come visit sometime.",
    "dokkai_eki_annai|title": "Station Announcement",
    "dokkai_eki_annai|passageTranslation": "Announcement. Due to an accident, the train is running twenty minutes late. The next train will arrive at 10:10. If you're in a hurry, please use the bus. We apologize for the inconvenience.",
    "dokkai_kurasu_annai|title": "Extra Class Announcement",
    "dokkai_kurasu_annai|passageTranslation": "For students with low exam scores, extra classes will be held starting next week. They'll be held in the classroom after school on Tuesdays and Thursdays. Anyone who wants to join, please tell the teacher.",
    "dokkai_nikki_ichinichi|title": "Tanaka's Diary",
    "dokkai_nikki_ichinichi|passageTranslation": "Today is Sunday. In the morning, I took a walk in the park. The weather was nice, and I felt good. At noon I ate ramen. In the afternoon I cleaned my room. At night I read a book and went to bed early.",
    "dokkai_kouen_kisoku|title": "City Park Rules",
    "dokkai_kouen_kisoku|passageTranslation": "To use this park comfortably, here's a request. Please take your trash home with you. When walking your dog, please use a leash. Entry isn't allowed from 10 pm to 6 am.",
    "dokkai_hikkoshi_annai|title": "Moving-In Announcement",
    "dokkai_hikkoshi_annai|passageTranslation": "On the 10th of next month, a new person will move into the room next door. On that day a truck will arrive from the morning, so it might be a bit noisy. Thank you for your understanding.",
    "dokkai_byouin_uketsuke|title": "Hospital Opening Hours",
    "dokkai_byouin_uketsuke|passageTranslation": "This hospital is open Monday to Friday, 9 am to 6 pm. On Saturdays, until noon. Closed Sundays and holidays. In an emergency, please call the emergency line.",
    "dokkai_paatii_shoutai|title": "Birthday Party Invitation",
    "dokkai_paatii_shoutai|passageTranslation": "Next Saturday, I'm having a birthday party. It'll be at my house. It starts at 6 pm. No gifts needed. Please bring lots of fun stories.",
    "dokkai_supa_seru|title": "Weekend Supermarket Sale",
    "dokkai_supa_seru|passageTranslation": "This Saturday and Sunday, our store is having a sale. Vegetables and fruit will be 20 percent cheaper. Meat and fish will be 10 percent cheaper. Please come take this chance.",
    "dokkai_kazoku_ryokou|title": "Family Trip to the Sea",
    "dokkai_kazoku_ryokou|passageTranslation": "During summer vacation, I went to the sea with my family. It took three hours by train and bus. The sea was very beautiful. We swam and played in the sand. At night we watched fireworks. It was very fun.",
    "dokkai_gakkou_koushi|title": "School Schedule Change",
    "dokkai_gakkou_koushi|passageTranslation": "Next Monday, because of a teachers' meeting, classes will only run until noon. Students may go home in the afternoon. From Tuesday, the schedule returns to normal.",
    "dokkai_ryouri_kyoushitsu|title": "Cooking Class Announcement",
    "dokkai_ryouri_kyoushitsu|passageTranslation": "Next Saturday, there's a cooking class. Anyone who wants to join, please tell the teacher by Friday. Please bring an apron. The ingredient fee is 500 yen.",
    "dokkai_sukuuru_basu|title": "School Bus Schedule",
    "dokkai_sukuuru_basu|passageTranslation": "The school bus schedule has changed. It departs at 7:30 in the morning. It returns at 3:30. When it rains, it might be a bit late.",
    "dokkai_kansha_tegami|title": "A Thank-You Letter to the Teacher",
    "dokkai_kansha_tegami|passageTranslation": "Teacher, thank you for this past year. Your lessons were always fun. Whenever I didn't understand something, you always taught me kindly. I hope you stay well next year too.",
    "dokkai_yobou_sesshu|title": "School Vaccination Announcement",
    "dokkai_yobou_sesshu|passageTranslation": "On the 10th of next month, vaccinations will be given at school. Don't forget to bring the vaccination consent form. Anyone feeling unwell can't be vaccinated that day.",
    "dokkai_gakkou_pikunikku|title": "A School Picnic Story",
    "dokkai_gakkou_pikunikku|passageTranslation": "Last week, our school went on a picnic to the park. The weather was very nice, and everyone ate their packed lunch together. After that, we played tag. It was a very fun day.",
    "dokkai_puuru_kisoku|title": "Swimming Pool Rules",
    "dokkai_puuru_kisoku|passageTranslation": "Before using the pool, please shower first. Running inside the pool area isn't allowed. Don't bring drinks or snacks in. Children must always enter together with an adult.",
    "dokkai_kantin_menyu|title": "School Cafeteria Menu",
    "dokkai_kantin_menyu|passageTranslation": "Here's this month's new cafeteria menu. Monday is curry rice, Tuesday is ramen. Everything is 300 yen. Dessert can be bought for 100 yen.",
    "dokkai_e_konkuuru|title": "Drawing Contest Announcement",
    "dokkai_e_konkuuru|passageTranslation": "This year's drawing contest theme is 'My Family'. Anyone who wants to join, please submit their drawing to the teacher by next Friday. The best drawing will receive a certificate.",
    "dokkai_tooi_machi_tomodachi|title": "A Letter to a Friend in Another City",
    "dokkai_tooi_machi_tomodachi|passageTranslation": "How are you? I'm doing fine. I've also gotten used to the new school. My friends are slowly increasing too. Can I come visit during summer vacation? Waiting for your reply.",
    "dokkai_haisha_yotei|title": "Dentist Appointment Schedule",
    "dokkai_haisha_yotei|passageTranslation": "Next Wednesday, there's a dentist appointment at 3 pm. Can you go by yourself after school ends? If it's hard, Mom will pick you up.",
    "dokkai_eakon_shuuri|title": "Classroom AC Repair Announcement",
    "dokkai_eakon_shuuri|passageTranslation": "The classroom AC is broken, so it will be repaired next week. During the repair, it might be a bit hot. Please bring a water bottle and drink enough water.",
    "dokkai_oya_tetsudai|title": "A Story About Helping Parents at Home",
    "dokkai_oya_tetsudai|passageTranslation": "Every Sunday, I help clean the house. I wash the dishes and fold the laundry. It was hard at first, but now I can do it well. Mom is always happy.",
    "dokkai_konpyuutaa_kisoku|title": "School Computer Room Rules",
    "dokkai_konpyuutaa_kisoku|passageTranslation": "When using the computer room, eating or drinking is forbidden. After you finish using it, make sure to turn off the power. If there's anything you don't understand, please ask the teacher. Don't play personal games.",
    "dokkai_bazaa_annai|title": "School Bazaar Announcement",
    "dokkai_bazaa_annai|passageTranslation": "Next month, a bazaar will be held at school. Please bring toys or books you no longer use. The proceeds will be used to buy library books. Please join in.",
    "dokkai_kazoku_pikunikku_shoutai|title": "Family Picnic Invitation Letter",
    "dokkai_kazoku_pikunikku_shoutai|passageTranslation": "How about a family picnic at the park next weekend? I'll make the packed lunch. Please bring drinks and a picnic mat. If the weather is bad, we'll hold it the following week.",
    "dokkai_sakkaa_bu_renshuu|title": "Soccer Club Practice Schedule",
    "dokkai_sakkaa_bu_renshuu|passageTranslation": "Soccer club practice is on Mondays, Wednesdays, and Fridays after school. When it rains, practice is held in the gym. The next match is on the 3rd of next month. Let's practice with enthusiasm.",
    "dokkai_haha_purezento|title": "A Story About Buying a Gift for Mom",
    "dokkai_haha_purezento|passageTranslation": "Next week is Mother's Day. I'm planning to save my allowance to buy flowers for Mom. I want to choose the prettiest flowers at the flower shop. I think Mom will surely be happy.",
    "dokkai_gakkou_yasumi_oshirase|title": "School Holiday Announcement",
    "dokkai_gakkou_yasumi_oshirase|passageTranslation": "Next Monday is a national holiday, so school is closed. Don't forget to do your homework. From Tuesday, classes will be as usual.",
    "dokkai_gurupu_benkyou|title": "A Group Study Story",
    "dokkai_gurupu_benkyou|passageTranslation": "Yesterday, I studied in a group at a friend's house. Four of us worked on math homework together. We thought together about problems we didn't understand. Compared to studying alone, this was more fun and easier to understand.",
    "dokkai_bijutsu_tenrankai|title": "School Art Exhibition Announcement",
    "dokkai_bijutsu_tenrankai|passageTranslation": "Next month, there's an art exhibition at school. Paintings and works made by everyone will be displayed in the gym. Parents are also welcome to come see. Admission is free.",
    "dokkai_toire_shuuri|title": "School Restroom Repair Announcement",
    "dokkai_toire_shuuri|passageTranslation": "Next week, the second-floor restroom will be repaired. During that time, please use the first-floor restroom. We apologize for the inconvenience.",
    "dokkai_hanabi_taikai|title": "A Story About Watching Fireworks",
    "dokkai_hanabi_taikai|passageTranslation": "Last weekend, I went to a fireworks festival with my family. The fireworks were very big and beautiful. There were a lot of people, so it was a bit tiring, but it became a fun memory.",
    "dokkai_kesseki_renraku|title": "A Letter Asking for Leave from School",
    "dokkai_kesseki_renraku|passageTranslation": "Teacher, since my son has a fever, I'm letting him miss school today. I plan to take him to the hospital. I'll bring his homework tomorrow. Thank you for understanding.",
    "dokkai_ongaku_shitsu_kisoku|title": "Music Room Rules",
    "dokkai_ongaku_shitsu_kisoku|passageTranslation": "In the music room, please handle the instruments with care. After you finish using them, return them to their original place. Bringing drinks in isn't allowed.",
    "dokkai_kimatsu_shiken_nittei|title": "Final Exam Schedule",
    "dokkai_kimatsu_shiken_nittei|passageTranslation": "Final exams run from the 15th to the 19th of next month. Japanese and math are on the 15th, English and science are on the 16th. Please prepare well for the exams.",
    "dokkai_okashi_zukuri|title": "A Story About Making Snacks with a Friend",
    "dokkai_okashi_zukuri|passageTranslation": "Yesterday, I made cookies with a friend. It was the first time, but the result was better than I expected. Freshly baked cookies were very tasty. I want to make them again.",
    "dokkai_kenketsu_annai|title": "Blood Donation Announcement",
    "dokkai_kenketsu_annai|passageTranslation": "Next Tuesday, you can donate blood at the school gym. People aged 16 and up can join. If interested, please ask the school nurse.",
    "dokkai_ryou_asagohan|title": "Dormitory Breakfast Menu",
    "dokkai_ryou_asagohan|passageTranslation": "Breakfast at the dormitory is from 6:30 to 8 am. You can choose bread or rice, both are available. Eggs and salad can also be eaten together.",
    "dokkai_ane_ouen_tegami|title": "A Letter to a Sister at University",
    "dokkai_ane_ouen_tegami|passageTranslation": "Sis, how's university life? I think studying and living alone must be tough, but hang in there. Next holiday, we're planning to visit you as a family.",
    "dokkai_kurasu_gae_oshirase|title": "Class Reshuffle Announcement",
    "dokkai_kurasu_gae_oshirase|passageTranslation": "Starting next month, there will be a class reshuffle. The new classes will be announced next Friday. Even though we'll part from our friends, let's make new friends again.",
    "dokkai_guraundo_shuuri|title": "School Field Repair Announcement",
    "dokkai_guraundo_shuuri|passageTranslation": "Next month, the school field will be repaired. During the repair, PE classes will be held in the gym. Please play ball games in the park. Thank you for your cooperation.",
    "dokkai_doubutsuen_pikunikku|title": "A Zoo Picnic Story",
    "dokkai_doubutsuen_pikunikku|passageTranslation": "Last week, our class went to the zoo. We could see elephants and lions up close. After eating our packed lunches, we also saw pandas. It was a very fun picnic.",
    "dokkai_tanjoubi_iwai_tegami|title": "A Birthday Greeting Letter to a Friend",
    "dokkai_tanjoubi_iwai_tegami|passageTranslation": "Happy birthday! Let's play a lot together this year too. I've already prepared a gift, I'll give it to you when we meet again. I hope this year becomes a wonderful year.",
    "dokkai_toshokan_konpyuutaa_kisoku|title": "City Library Computer Room Rules",
    "dokkai_toshokan_konpyuutaa_kisoku|passageTranslation": "The library computer can be used for up to one hour per person. Before using it, please write your name at the reception desk. Printing documents costs 10 yen per page.",
    "dokkai_bouizukatsudou_nittei|title": "Scout Activity Schedule",
    "dokkai_bouizukatsudou_nittei|passageTranslation": "Scout activities are on the second Saturday of every month. We learn camping practice and how to set up a tent. Anyone who wants to join, please contact the leader.",
    "dokkai_imouto_benkyou_tetsudai|title": "A Story About Helping My Sister Study",
    "dokkai_imouto_benkyou_tetsudai|passageTranslation": "Since my little sister was struggling with math homework, I studied with her. After carefully explaining the difficult problem, she understood. When she said 'Thanks, big brother/sister', I was happy.",
    "dokkai_koukan_ryuugaku_boshuu|title": "Exchange Student Program Announcement",
    "dokkai_koukan_ryuugaku_boshuu|passageTranslation": "Next year, we're recruiting exchange students to Australia. The period is three months. If interested, please submit an application form by the end of next month.",
    "dokkai_kodomo_no_hi_menyu|title": "Children's Day Special Menu",
    "dokkai_kodomo_no_hi_menyu|passageTranslation": "May 5th is Children's Day. The school lunch menu will be more lavish than usual. This year, apparently there will be hamburg steak and cake. That's exciting.",
    "dokkai_sensei_ayamari_tegami|title": "An Apology Letter to the Teacher",
    "dokkai_sensei_ayamari_tegami|passageTranslation": "Teacher, I'm sorry I forgot to bring my homework. From now on, I'll always check before going to bed. I'll definitely turn it in today. Thank you for your understanding.",
    "dokkai_toshokan_kyuujitsu_kaikan|title": "Library Open on Holiday Announcement",
    "dokkai_toshokan_kyuujitsu_kaikan|passageTranslation": "This week's holiday, the library will be open specially. Hours are from 10 am to 4 pm. Please make use of it for your summer vacation book report.",
    "dokkai_toshokan_shuuri_oshirase|title": "School Library Repair Announcement",
    "dokkai_toshokan_shuuri_oshirase|passageTranslation": "From Monday to Wednesday next week, the library can't be used due to repairs. Anyone who wants to borrow books, please borrow them this week. Returns can be made starting Thursday. If you have any questions, please ask the teacher.",
    "dokkai_hakubutsukan_kengaku_yotei|title": "Museum Visit Schedule",
    "dokkai_hakubutsukan_kengaku_yotei|passageTranslation": "Next month, our class will go to the museum. Gather at 9 in front of the school. Since we're going by bus, please bring a packed lunch. Don't speak loudly inside the museum.",
    "dokkai_atarashii_sensei_tegami|title": "A Letter to the New Teacher",
    "dokkai_atarashii_sensei_tegami|passageTranslation": "To the new teacher. Thank you for becoming our homeroom teacher starting in April. Our class is full of energy, and many of us like soccer. Let's study happily together.",
    "dokkai_tokubetsu_hiruhan_menu|title": "Special Lunch Menu",
    "dokkai_tokubetsu_hiruhan_menu|passageTranslation": "Today's lunch is a special menu. There's curry rice, salad, and fruit. Dessert is ice cream. Please look forward to it.",
    "dokkai_undoukai_taikai_oshirase|title": "Sports Competition Announcement",
    "dokkai_undoukai_taikai_oshirase|passageTranslation": "Next Saturday there's a sports competition. If it rains, it will be moved to Sunday. Please bring a packed lunch and water. Let's also cheer with enthusiasm.",
    "dokkai_kouen_souji_tetsudai|title": "A Story About Helping Clean the Park",
    "dokkai_kouen_souji_tetsudai|passageTranslation": "On Sunday, I helped clean up the park near my house. I picked up trash and watered the flowers. Since everyone worked together, the park became clean. It felt very rewarding.",
    "dokkai_ongaku_renshuu_jikanwari|title": "Music Practice Schedule",
    "dokkai_ongaku_renshuu_jikanwari|passageTranslation": "Music club practice is on Tuesdays and Thursdays after school. It's held in the music room. Don't forget to bring your instrument. The concert is on the fifteenth of next month.",
    "dokkai_toshokan_ikkou_oshirase|title": "Library Relocation Announcement",
    "dokkai_toshokan_ikkou_oshirase|passageTranslation": "Next month the school library will move from the second floor to the first floor. During the move, the library can't be used for three days. Anyone who wants to read books, please read in the classroom.",
    "dokkai_sotsugyou_oiwai_tegami|title": "A Graduation Congratulations Letter",
    "dokkai_sotsugyou_oiwai_tegami|passageTranslation": "Congratulations on your graduation. It was wonderful being able to study together for six years. I hope you stay energetic in middle school too. Come visit sometime.",
    "dokkai_ichiba_kaimono_chichi|title": "A Story About Shopping at the Market with Dad",
    "dokkai_ichiba_kaimono_chichi|passageTranslation": "Saturday morning, I went shopping at the market with my dad. We bought fresh fish and vegetables. The market was very lively, and various sounds could be heard. It was a fun time.",
    "dokkai_toshokan_benkyou_jikan_encho|title": "Library Study Hours Extension Announcement",
    "dokkai_toshokan_benkyou_jikan_encho|passageTranslation": "Starting next month, the library's usage hours will be longer. Until now it was until 5 pm, but from now on it can be used until 7 pm. Anyone who wants to study before exams, please make use of it.",
    "dokkai_shouboushomi_kengaku|title": "Fire Station Visit Schedule",
    "dokkai_shouboushomi_kengaku|passageTranslation": "Next Friday, our class will visit the fire station. We'll see the fire truck and hear stories from the firefighters. Gather at half past nine in the morning in front of the school entrance.",
    "dokkai_inaka_itoko_tegami|title": "A Letter from a Cousin in the Countryside",
    "dokkai_inaka_itoko_tegami|passageTranslation": "How are you? Life in the countryside is different from the city, calm and relaxed. Every morning, I wake up to the sound of birds. Later, during summer vacation, come play here. Let's swim together in the river.",
    "dokkai_kazoku_yuushoku_menu|title": "Family Dinner Menu",
    "dokkai_kazoku_yuushoku_menu|passageTranslation": "Tonight's dinner is grilled fish, miso soup, and a vegetable salad everyone likes. There's also fruit for dessert. Eating together with the whole family is very fun.",
    "dokkai_origami_kyoushitsu_oshirase|title": "Origami Class Announcement",
    "dokkai_origami_kyoushitsu_oshirase|passageTranslation": "Next Wednesday, there's an origami class after school. It's held in the library room. For those who don't have origami paper, the school will provide it. Anyone can join.",
    "dokkai_hana_ue_gakkou_hanashi|title": "A Story About Planting Flowers at School",
    "dokkai_hana_ue_gakkou_hanashi|passageTranslation": "Last week, our class planted flowers. We dug the soil, sowed the seeds, and watered them. Watering every day is my job. I'm looking forward to those flowers blooming.",
    "dokkai_basuke_renshuu_jikanwari|title": "Basketball Club Practice Schedule",
    "dokkai_basuke_renshuu_jikanwari|passageTranslation": "Basketball club practice is on Mondays, Wednesdays, and Fridays. It's after school from 3 to 5. The match is on the third Sunday of next month.",
    "dokkai_furuhon_koukan_oshirase|title": "Used Book Exchange Announcement",
    "dokkai_furuhon_koukan_oshirase|passageTranslation": "Next month, the school will hold a used book exchange event. Bring books you've finished reading, and you can exchange them for someone else's book. We can also learn to appreciate books.",
    "dokkai_shinnen_aisatsu_tegami|title": "A New Year's Greeting Letter",
    "dokkai_shinnen_aisatsu_tegami|passageTranslation": "Happy New Year. Please look after me again this year. You helped me a lot last year, thank you. This year I'll work even harder.",
    "dokkai_sofu_kaen_tetsudai|title": "A Story About Helping Grandpa in the Garden",
    "dokkai_sofu_kaen_tetsudai|passageTranslation": "On Sunday, I went to help in Grandpa's garden. We harvested tomatoes and eggplants. Grandpa said 'thank you, that was a big help.' I was very happy.",
    "dokkai_jishin_hinan_kunren_oshirase|title": "Earthquake Evacuation Drill Announcement",
    "dokkai_jishin_hinan_kunren_oshirase|passageTranslation": "Next Thursday, the school will hold an earthquake evacuation drill. If you hear the announcement 'earthquake', hide under your desk. After that, evacuate to the school field following the teacher's instructions.",
    "dokkai_shodou_kyoushitsu_jikanwari|title": "Calligraphy Class Schedule",
    "dokkai_shodou_kyoushitsu_jikanwari|passageTranslation": "Calligraphy class is every Saturday at 10 am. Brushes and ink can be borrowed in class. Beginners are very welcome too.",
    "dokkai_atarashii_gakkou_tomodachi_tegami|title": "A Letter from a Friend at a New School",
    "dokkai_atarashii_gakkou_tomodachi_tegami|passageTranslation": "How are you? Little by little I'm starting to get used to the new school. I'm happy because I have a good friend in class. Later, can I come visit?",
    "dokkai_piknikku_bentou_menu|title": "Picnic Lunch Box Menu",
    "dokkai_piknikku_bentou_menu|passageTranslation": "Tomorrow's picnic lunch box will have onigiri, rolled omelet, and fried chicken. Strawberries are also brought for dessert. Looking forward to eating together at the park.",
    "dokkai_basuke_court_shuuri_oshirase|title": "Basketball Court Repair Announcement",
    "dokkai_basuke_court_shuuri_oshirase|passageTranslation": "Starting next week for two weeks, the gym's basketball court will be repaired. During that time, the basketball club will practice on the school field. Thank you for your cooperation.",
    "dokkai_haha_ryouri_tetsudai|title": "A Story About Helping Mom Cook",
    "dokkai_haha_ryouri_tetsudai|passageTranslation": "Today, I cooked dinner together with Mom. My job was to cut the vegetables. It was a bit difficult, but I tried until I finished. I was very happy when the family said 'delicious'.",
    "dokkai_dance_bu_renshuu_jikanwari|title": "Dance Club Practice Schedule",
    "dokkai_dance_bu_renshuu_jikanwari|passageTranslation": "Dance club practice is on Tuesdays, Thursdays, and Saturdays. It's always held in the dance room next to the music room. The performance is at the school culture festival.",
    "dokkai_kenkou_shindan_oshirase|title": "School Health Checkup Announcement",
    "dokkai_kenkou_shindan_oshirase|passageTranslation": "Next week, there's a health checkup at school. Height and weight will be measured, and eyes and ears will be checked. Please bring your gym clothes.",
    "dokkai_oyagata_kansha_tegami|title": "A Thank-You Letter to Parents",
    "dokkai_oyagata_kansha_tegami|passageTranslation": "To Dad, Mom. Thank you for always working hard for me. The delicious food, the gentle words, all of it makes me happy. From now on too, I want to keep living happily together with the whole family.",
    "dokkai_yuki_asobi_fuyu_hanashi|title": "A Story About Playing in the Snow in Winter",
    "dokkai_yuki_asobi_fuyu_hanashi|passageTranslation": "During winter vacation, I went on a trip with my family to a place with lots of snow. I made a snowman for the first time. Playing a snowball fight too, it was very fun. My hands were cold, but my heart felt warm.",
    "dokkai_suiei_kyoushitsu_natsu_jikanwari|title": "Summer Swimming Class Schedule",
    "dokkai_suiei_kyoushitsu_natsu_jikanwari|passageTranslation": "Summer vacation swimming class is every Tuesday and Thursday in July and August. Before entering the pool, make sure to shower first. Don't forget to bring your swimsuit and swim cap.",
    "dokkai_gaikoku_hikkoshi_tomodachi_tegami|title": "A Letter from a Friend Who Moved Abroad",
    "dokkai_gaikoku_hikkoshi_tomodachi_tegami|passageTranslation": "How are you? Because of Dad's job, I'll be living abroad starting next month. The new school worries me a bit, but I'll try my best. If I come back to Japan, let's play together again.",
    "dokkai_undoubi_hiruhan_menu|title": "Sports Day Lunch Menu",
    "dokkai_undoubi_hiruhan_menu|passageTranslation": "The lunch box on sports day is a special one eaten together with everyone. There's onigiri, fried chicken, rolled omelet, and also jelly. We eat on the grass together with family.",
    "dokkai_taiikukan_yane_shuuri_oshirase|title": "Gym Roof Repair Announcement",
    "dokkai_taiikukan_yane_shuuri_oshirase|passageTranslation": "Starting next month for one month, the gym roof will be repaired. During that time, PE classes will be held on the school field. On rainy days, other activities will be done in the classroom.",
    "dokkai_imouto_sewa_tetsudai|title": "A Story About Helping Care for a Baby Sister",
    "dokkai_imouto_sewa_tetsudai|passageTranslation": "Today, since Mom was busy, I helped take care of my baby sister. I gave her milk and read her a picture book. When my sister smiled, I felt very happy.",
    "dokkai_gasshou_bu_renshuu_jikanwari|title": "Choir Club Practice Schedule",
    "dokkai_gasshou_bu_renshuu_jikanwari|passageTranslation": "Choir club practice is on Mondays, Wednesdays, and Fridays after school. It's held in the music room. The performance is at the Christmas event in December.",
    "dokkai_ha_kenshin_oshirase|title": "School Dental Checkup Announcement",
    "dokkai_ha_kenshin_oshirase|passageTranslation": "Next week, there's a dental checkup at school. We'll be examined by a dentist in turn. Brush your teeth well after breakfast.",
    "dokkai_shinkyuu_oiwai_tegami|title": "A Grade Promotion Congratulations Letter",
    "dokkai_shinkyuu_oiwai_tegami|passageTranslation": "Congratulations on moving up a grade. You grew a lot this past year. In the new class too, surely fun days await. From now on too, I'll keep supporting you.",
    "dokkai_sofu_tsuri_hanashi|title": "A Story About Fishing with Grandpa",
    "dokkai_sofu_tsuri_hanashi|passageTranslation": "On Sunday, I went fishing at the river with Grandpa. For the first time I could catch a fish by myself. Grandpa was very happy, and took lots of photos.",
    "dokkai_idou_toshokan_oshirase|title": "Mobile Library Announcement",
    "dokkai_idou_toshokan_oshirase|passageTranslation": "Starting next month, a mobile library van will come to school. Once a month, it brings various books. You can borrow and return books during break time.",

    # ---------------- N4 (100 passages, 200 fields) ----------------
    "dokkai_mensetsu_kekka|title": "Job Interview Result",
    "dokkai_mensetsu_kekka|passageTranslation": "Dear Tanaka. Thank you for coming to the interview a few days ago. We got a very good impression. Could you start working next Monday? Details will be given by phone. If you have any questions, feel free to contact us anytime.",
    "dokkai_taifuu_keikai|title": "Typhoon Warning",
    "dokkai_taifuu_keikai|passageTranslation": "It's said a big typhoon will arrive tomorrow. School might be closed. Since strong winds can send things flying, it's best not to go outside. Please close the windows tightly. If the power goes out, use a flashlight.",
    "dokkai_resutoran_review|title": "Restaurant Review",
    "dokkai_resutoran_review|passageTranslation": "Last week I went to a newly opened Italian restaurant. The pasta was very delicious. The staff were also friendly, so I could eat comfortably. It's just that I felt the price was a bit expensive. I want to go again, but I'm thinking of going on a special day.",
    "dokkai_ryokou_burogu|title": "Travel Blog",
    "dokkai_ryokou_burogu|passageTranslation": "I just got back from a trip to Hokkaido. A lot of snow fell and it was very beautiful. After going into the hot spring, my body warmed up. The local fish was also very delicious, I ate a lot of it. I want to go again next year.",
    "dokkai_iken_essay|title": "Opinion Essay on Social Media",
    "dokkai_iken_essay|passageTranslation": "Lately, a lot of people use social media. Since you can easily connect with friends, it's convenient. But, if you look at social media too much, sometimes your time gets used up. I decided to only look at social media one hour a day. Thanks to that, my time for other things has increased.",
    "dokkai_seihin_hyouka|title": "Product Review",
    "dokkai_seihin_hyouka|passageTranslation": "I'm writing about the vacuum cleaner I bought last month. It's very light and easy to use. The sound is also quiet, so it can be used even at night. It's just that, since the price was expensive, I hesitated to buy it. But, I feel glad I bought it.",
    "dokkai_kujou_tegami|title": "Complaint Letter",
    "dokkai_kujou_tegami|passageTranslation": "A few days ago, I stayed at your hotel. The room was clean, but the noise from the next room was very loud, so I couldn't sleep well. Next time I stay, could I be given a quiet room? Thank you for your understanding.",
    "dokkai_shoutaijou_henji|title": "Invitation Reply",
    "dokkai_shoutaijou_henji|passageTranslation": "Thank you for the invitation. I'll gladly attend the wedding. If there's anything I can help with, please don't hesitate to let me know. I'm looking forward to that day. If anyone has a food allergy, please let me know beforehand.",
    "dokkai_hikkoshi_oshirase|title": "Address Change Announcement",
    "dokkai_hikkoshi_oshirase|passageTranslation": "This time, our office is moving. The new address can be used starting the 1st of next month. The phone number stays the same. During the move, replies might be a bit slow for a while. We apologize for the inconvenience, thank you for your understanding.",
    "dokkai_kenkou_kiji|title": "Health Tips Article",
    "dokkai_kenkou_kiji|passageTranslation": "For health, it's said to be important to exercise a little every day. For busy people who don't have time, it's said it's enough to just take the stairs or walk a little further. Besides that, getting enough sleep is also important for health.",
    "dokkai_toshokan_open|title": "New Library Opening Announcement",
    "dokkai_toshokan_open|passageTranslation": "Next month, a new library will open near the station. Opening hours are from 9 am to 8 pm. There's also a picture-book corner for children. Anyone can use it for free. Please come visit once.",
    "dokkai_kantan_reshipi|title": "Simple Recipe",
    "dokkai_kantan_reshipi|passageTranslation": "I'll introduce how to make a simple omelet. First, crack two eggs and mix them well. Next, heat oil in a pan. After adding the egg, cook slowly on low heat. Be careful not to burn it.",
    "dokkai_shigoto_hajimete|title": "First Day at Work Experience",
    "dokkai_shigoto_hajimete|passageTranslation": "Today is my first day at work. Because I was nervous, I woke up too early. After arriving at the office, my coworkers greeted me warmly. I don't understand the job very well yet, but I want to learn little by little.",
    "dokkai_densha_norikata|title": "Guide to Riding the Train",
    "dokkai_densha_norikata|passageTranslation": "I'll explain this for people riding a train in Japan for the first time. First, please buy a ticket or prepare an IC card. When entering the platform, pass your ticket through the ticket gate. So you don't get off at the wrong station, please look carefully at the station name.",
    "dokkai_gengo_kouza|title": "Language Course Ad",
    "dokkai_gengo_kouza|passageTranslation": "We're looking for people who want to learn English conversation. There are classes by level, from beginner to advanced. Classes are twice a week, starting at 7 pm. All teachers are experienced, so you can learn with peace of mind.",
    "dokkai_yoyaku_kakunin|title": "Reservation Confirmation Email",
    "dokkai_yoyaku_kakunin|passageTranslation": "Thank you for your reservation this time. Your reservation date is next Friday, starting at 7 pm. We've accepted it for 4 people. If there's any change or cancellation, please contact us up until the day before.",
    "dokkai_shumi_burogu|title": "Blog About a New Hobby",
    "dokkai_shumi_burogu|passageTranslation": "Lately, I've come to like taking photos. On days off, I go to various places to take photos. I'm not very skilled yet, but little by little I'm starting to understand how to use the camera. I want to keep continuing it going forward.",
    "dokkai_douro_kouji|title": "Road Repair Announcement",
    "dokkai_douro_kouji|passageTranslation": "Starting next week, there will be repairs on the road in front of the station. During the repair, the road will narrow, so those driving cars should be careful. A separate path is prepared for pedestrians. We apologize for the inconvenience, thank you for your understanding.",
    "dokkai_ryuugaku_tegami|title": "A Letter from a Child Studying Abroad",
    "dokkai_ryuugaku_tegami|passageTranslation": "Dad, Mom, how are you? I've gotten fairly used to life here. It was hard at first because I didn't understand the language, but now I have many friends, and every day is fun. Next holiday, I'm planning to come home to Japan. I'm looking forward to seeing you.",
    "dokkai_undou_kouka|title": "Article on the Benefits of Exercise",
    "dokkai_undou_kouka|passageTranslation": "It's said that exercising a little every day makes not just the body but also the mood more energetic. Even busy people, it's said, can start the day feeling good just by moving their body lightly in the morning. It's important to find exercise that suits you without pushing yourself too hard.",
    "dokkai_hon_ten_waribiki|title": "Bookstore Discount Announcement",
    "dokkai_hon_ten_waribiki|passageTranslation": "This weekend, if you buy books at our store, you get a 10 percent discount. If you show a student ID, it becomes 5 percent cheaper still. Please come take this chance.",
    "dokkai_sobo_ryouri|title": "Learning to Cook from Grandma",
    "dokkai_sobo_ryouri|passageTranslation": "Last week I went to Grandma's house and was taught how to make traditional dishes. Grandma's hand movements were very fast, I was surprised. I thought that if I practice, someday I want to be able to make it the same way.",
    "dokkai_kyuuka_shinsei|title": "Work Leave Request Email",
    "dokkai_kyuuka_shinsei|passageTranslation": "Dear Section Chief, next Wednesday, due to a family matter, I'd like to take a day off. I'll try to finish my work by Tuesday. Please confirm.",
    "dokkai_chokin_shuukan|title": "Article on Saving Habits",
    "dokkai_chokin_shuukan|passageTranslation": "More and more people, as soon as their salary comes in each month, set aside a certain amount for savings first. Living on what's left is said to allow you to keep saving without forcing yourself. A small habit seems to lead to a sense of security in the future.",
    "dokkai_atarashii_machi_burogu|title": "Blog on Adjusting to a New Town",
    "dokkai_atarashii_machi_burogu|passageTranslation": "It's been three months since I moved to a new town. At first I didn't even know the roads, and a lot of things made me anxious. However, the people around me kindly told me things, and little by little life has become easier.",
    "dokkai_kurabu_taikai|title": "Club Resignation Letter",
    "dokkai_kurabu_taikai|passageTranslation": "To the club captain. Thank you for your guidance all this time. Since I want to focus on studying, I've decided to quit the tennis club. I'm grateful for everything I was taught. I'll be supporting all of your success.",
    "dokkai_apuri_hyouka|title": "Language Learning App Review",
    "dokkai_apuri_hyouka|passageTranslation": "I've been using this language learning app for three months. Since I can study a little every day, it's easy to keep going. The pronunciation practice feature is also convenient. It's just that, unfortunately, few features can be used in the free version.",
    "dokkai_shuugyou_jikan_henkou|title": "Working Hours Change Announcement",
    "dokkai_shuugyou_jikan_henkou|passageTranslation": "Starting next month, the company's working hours will change. The new hours are from 9 am to 5 pm. It ends 30 minutes earlier than before. For details, please ask the general affairs department.",
    "dokkai_hikouki_hajimete|title": "First Time Flying on a Plane",
    "dokkai_hikouki_hajimete|passageTranslation": "Last week, I flew on a plane for the first time. I was very nervous, but the flight attendant guided me kindly, so I calmed down. The view from the window was very beautiful, I was impressed. I want to fly again.",
    "dokkai_shokubutsu_sewa|title": "Guide to Caring for Plants",
    "dokkai_shokubutsu_sewa|passageTranslation": "When caring for houseplants, please be careful not to water them too much. The basic rule is to give water after the soil has dried. A place with too much strong sunlight also isn't good for the plant.",
    "dokkai_suimin_shuukan|title": "Article on Good Sleep Habits",
    "dokkai_suimin_shuukan|passageTranslation": "For a good night's sleep, it's said to be better not to look at your smartphone before bed. Because the screen light stimulates the brain and makes it hard to sleep. Before bed, it's recommended to listen to calm music.",
    "dokkai_shoushin_oiwai|title": "Promotion Congratulations Email",
    "dokkai_shoushin_oiwai|passageTranslation": "Congratulations on your promotion. It's wonderful that your daily effort was recognized. In the new position too, please keep the same energy as before. Next time, let's eat together to celebrate.",
    "dokkai_gaadeningu_burogu|title": "Blog on Trying Gardening as a Hobby",
    "dokkai_gaadeningu_burogu|passageTranslation": "Lately, I started growing vegetables on my balcony. I planted tomatoes and basil. Watering them every day has become a joy of its own. If I can harvest them, I want to use my own homegrown vegetables in cooking.",
    "dokkai_erebeetaa_shuuri|title": "Elevator Repair Announcement",
    "dokkai_erebeetaa_shuuri|passageTranslation": "From next Monday to Wednesday, the elevator will be inspected. During that time, the elevator can't be used. Please use the stairs. We apologize for the inconvenience.",
    "dokkai_ayamari_tegami|title": "An Apology Letter to a Friend",
    "dokkai_ayamari_tegami|passageTranslation": "I'm really sorry for being late from the promised time yesterday. There was a sudden matter, to the point I couldn't even contact you. When we meet again, I'll definitely be on time. Can you forgive me?",
    "dokkai_atarashii_kankouchi|title": "New Tourist Spot Review",
    "dokkai_atarashii_kankouchi|passageTranslation": "I went to a new tourist spot that opened last month. The scenery was very beautiful, I took a lot of photos. It's just that, since it's popular, I heard it gets very crowded on weekends. It's recommended to go on a weekday.",
    "dokkai_setsuyaku_houhou|title": "Article on Ways to Save Money",
    "dokkai_setsuyaku_houhou|passageTranslation": "There's a calculation that by making your own coffee at home every day, you can save about 5000 yen a month. Even just reviewing small expenses can add up to a large amount over a year. It's best to try starting within limits that don't strain yourself.",
    "dokkai_tonari_tetsudai|title": "A Story About Helping a Neighbor",
    "dokkai_tonari_tetsudai|passageTranslation": "I saw the elderly woman living next door carrying heavy things, so I helped her. She was very happy, and as thanks I was given a snack. Even though it was a small thing, I was glad to be useful to someone else.",
    "dokkai_sentakuki_kyoudou|title": "Guide to Using the Shared Washing Machine",
    "dokkai_sentakuki_kyoudou|passageTranslation": "When using the shared washing machine, please follow the time limit. One use is up to one hour. After you finish using it, take your laundry out right away. Sometimes someone else is waiting.",
    "dokkai_kurabu_boshuu|title": "Club Member Recruitment Announcement",
    "dokkai_kurabu_boshuu|passageTranslation": "The photography club is recruiting new members. It's fine even if you don't have a camera. Anyone who likes taking photos, or is interested, please come take a look. Activities are every Thursday.",
    "dokkai_onrain_kouza_hyouka|title": "Online Course Review",
    "dokkai_onrain_kouza_hyouka|passageTranslation": "I took an online English course for two months. What's good is that you can learn at your own pace. The teacher's explanations were also easy to understand. It's just that sometimes a bad internet connection was troublesome.",
    "dokkai_asagohan_kouka|title": "Article on the Benefits of Breakfast",
    "dokkai_asagohan_kouka|passageTranslation": "It's said that if you eat breakfast properly, your concentration improves in the morning. Even busy people who don't have time should eat something simple like a banana or yogurt.",
    "dokkai_gaikokugo_burogu|title": "Blog on Learning a Foreign Language",
    "dokkai_gaikokugo_burogu|passageTranslation": "Since last year I've been learning Korean. Memorizing the alphabet was tough at first, but now I can hold a simple conversation. I'm looking forward to the day I can watch dramas without subtitles.",
    "dokkai_chuumon_kakunin_meeru|title": "Online Order Confirmation Email",
    "dokkai_chuumon_kakunin_meeru|passageTranslation": "Thank you for your order. The item is planned to ship within 3 days. Shipping status will be notified by email. If there's any problem, please contact us.",
    "dokkai_arubaito_taiken|title": "Part-Time Work Experience",
    "dokkai_arubaito_taiken|passageTranslation": "Since becoming a university student, I started a part-time job at a cafe. At first I was nervous because I couldn't talk well with customers, but now I can serve them with a smile. As a social experience, this has become a valuable lesson.",
    "dokkai_shokudou_menyu_henkou|title": "Office Cafeteria Menu Change Announcement",
    "dokkai_shokudou_menyu_henkou|passageTranslation": "Starting next month, the employee cafeteria menu is being updated. With health in mind, vegetable dishes have been added. If you have any opinions or requests, please let the general affairs department know.",
    "dokkai_kyuujin_toiawase|title": "Job Opening Inquiry Letter",
    "dokkai_kyuujin_toiawase|passageTranslation": "I saw the job opening on your company's website. I'm interested in the sales position, could you explain the job details? Even though you're busy, thank you for your understanding.",
    "dokkai_gomi_risaikuru|title": "Trash Recycling Guide",
    "dokkai_gomi_risaikuru|passageTranslation": "Please throw away PET bottles after removing the label and cap. Please put burnable and non-burnable trash into separate bags. Following the sorting rules contributes to protecting the environment.",
    "dokkai_asa_undou_shuukan|title": "Article on Morning Exercise Habits",
    "dokkai_asa_undou_shuukan|passageTranslation": "It's said that if you do light exercise in the morning, you can spend the day with energy. It's best to start with jogging or stretching, within limits that don't strain yourself. It might take a little time before it becomes a habit.",
    "dokkai_heya_katazuke_burogu|title": "Blog on Tidying Up the House",
    "dokkai_heya_katazuke_burogu|passageTranslation": "On the weekend, I tidied up my room. After throwing away a lot of unused items, the room became neat, and I felt lighter too. I learned that if you have fewer things, cleaning also becomes easier.",
    "dokkai_reshipi_burogu|title": "Blog on Trying a New Recipe",
    "dokkai_reshipi_burogu|passageTranslation": "Last week, I tried a new recipe. Thai green curry. Adjusting the seasoning was difficult, but the result was tastier than I expected. Next I want to try other Thai dishes.",
    "dokkai_jikan_kanri_hou|title": "Article on Time Management Methods",
    "dokkai_jikan_kanri_hou|passageTranslation": "It's said that by writing your daily schedule on paper, you can use your time effectively. The trick is to set priorities and do important things first. A small habit leads to a big result.",
    "dokkai_hikkoshi_tetsudai_orei|title": "A Thank-You Letter for Moving Help",
    "dokkai_hikkoshi_tetsudai_orei|passageTranslation": "Thank you so much for helping with the move a few days ago. Thanks to you, everything was finished in one day. Next time, I'll treat you to a meal as thanks. Come visit again anytime.",
    "dokkai_kaigi_risendaa|title": "Meeting Reminder Email",
    "dokkai_kaigi_risendaa|passageTranslation": "This is a notice about tomorrow's meeting. Start time is 2 pm, location is the 3rd floor meeting room. Please read the document beforehand and prepare your opinion.",
    "dokkai_baiku_menkyo|title": "A Story About Learning to Ride a Motorcycle",
    "dokkai_baiku_menkyo|passageTranslation": "Since last month, I've been going to driving school to get my motorcycle license. Keeping my balance was hard at first, but as I practiced, I started to get used to it. Next month, I'm planning to take the exam.",
    "dokkai_kaiin_kaado_koushin|title": "Membership Card Renewal Announcement",
    "dokkai_kaiin_kaado_koushin|passageTranslation": "Your membership card's validity is about to expire. To renew it, you need to complete a procedure at the store. Once renewed, you can use the discount service for the next one year.",
    "dokkai_kakeibo_apuri_hyouka|title": "Budgeting App Review",
    "dokkai_kakeibo_apuri_hyouka|passageTranslation": "It's been three months since I started using this household budgeting app. Since it automatically records just by photographing the receipt, it's very convenient. I've come to clearly know where I was spending too much money.",
    "dokkai_eigakan_burogu|title": "Blog on Watching a Movie at the Cinema",
    "dokkai_eigakan_burogu|passageTranslation": "After not going for a long time, I watched a movie at the cinema. With the big screen and powerful sound, it was a completely different experience from watching at home. Eating popcorn while watching is also a unique cinema pleasure.",
    "dokkai_dokusho_kouka|title": "Article on the Benefits of Reading",
    "dokkai_dokusho_kouka|passageTranslation": "It's said that reading books not only increases knowledge, but also helps imagination and reduces stress. By taking even ten minutes a day to read a book, daily life might become richer.",
    "dokkai_kaisha_basu_henkou|title": "Company Commuter Bus Schedule Change Announcement",
    "dokkai_kaisha_basu_henkou|passageTranslation": "Starting next month, the commuter bus schedule will change. It'll depart 15 minutes earlier than now in the morning. The new schedule will be sent via internal email next week, please check it.",
    "dokkai_shashin_shumi_burogu|title": "Blog on Learning Photography",
    "dokkai_shashin_shumi_burogu|passageTranslation": "Lately, I started a photography hobby. I was surprised that you can take good photos even with a smartphone. I was taught how to take photos by a senior, and little by little I'm getting more skilled. I think that with more practice, I'll surely be able to take good photos.",
    "dokkai_neru_mae_dokusho_shuukan|title": "Article on Reading Before Bed Habits",
    "dokkai_neru_mae_dokusho_shuukan|passageTranslation": "It's said that more and more people read books instead of looking at their smartphone before bed. The screen light is said to stimulate the eyes and brain, making it hard to fall asleep. On the other hand, if you read a paper book, you can relax more and fall asleep easily.",
    "dokkai_shokuba_suisen_irai_mail|title": "Work Recommendation Request Email",
    "dokkai_shokuba_suisen_irai_mail|passageTranslation": "Dear Mr./Ms. Tanaka. Thank you for your help all this time. I'm sorry for this sudden request, but for a job change, could I ask you to write me a recommendation letter? If you're willing, I'll send the necessary documents. Thank you for your understanding.",
    "dokkai_shinsetsu_cafe_report|title": "New Cafe in Town Review",
    "dokkai_shinsetsu_cafe_report|passageTranslation": "Last week, I tried going to a newly opened cafe in front of the station. The inside of the shop was bright, and since the windows were big, the sunlight was pleasant. The coffee aroma was also nice, and the staff were friendly too. The price was a bit expensive, but I want to go again.",
    "dokkai_setsuden_katsuyou_guide|title": "Guide to Saving Electricity at Home",
    "dokkai_setsuden_katsuyou_guide|passageTranslation": "To reduce summer electricity costs, there are several methods. Just raising the AC temperature by one degree can change the electricity bill a lot. Also don't forget to turn off lights in rooms not in use. A small effort can become a big saving.",
    "dokkai_doukyuukai_shoutai_tegami|title": "School Reunion Invitation Letter",
    "dokkai_doukyuukai_shoutai_tegami|passageTranslation": "How are you all doing? It's been ten years since graduation. How about we gather again as classmates after not seeing each other for a long time? The date and time are planned for the second Saturday of next month, at the restaurant in front of the station we used to go to often. Anyone who can attend, please reply.",
    "dokkai_aruku_koto_kouka_kiji|title": "Article on the Benefits of Walking",
    "dokkai_aruku_koto_kouka_kiji|passageTranslation": "There's research showing that walking just a little every day has a good effect on health. It's said that even without special exercise, simply increasing the walking distance during your commute or shopping is effective enough. This could be called a health method easy to start even for busy people.",
    "dokkai_apaato_hikkoshi_taiken|title": "Experience Moving to a New Apartment",
    "dokkai_apaato_hikkoshi_taiken|passageTranslation": "Last month, I moved to a new apartment. It's a bit smaller than my previous room, but it's close to the station and convenient. I've also made it a habit to greet my neighbors when I meet them. I feel like I'm slowly starting to get used to my new life.",
    "dokkai_nihon_ryouri_manabu_burogu|title": "Blog on Learning to Cook Japanese Food",
    "dokkai_nihon_ryouri_manabu_burogu|passageTranslation": "Since I'm interested in Japanese food, lately I started learning how to make miso soup. Making dashi broth was difficult at first, but I practiced many times while watching videos. Now my family has said it's 'delicious'.",
    "dokkai_shiei_basu_route_henkou|title": "City Bus Route Change Announcement",
    "dokkai_shiei_basu_route_henkou|passageTranslation": "Starting the first of next month, due to road repairs, part of the city bus route will change. The bus from the station front to the hospital will take a different road. For detailed schedules, please check the city hall website.",
    "dokkai_shuwa_manabu_burogu|title": "Blog on Learning Sign Language",
    "dokkai_shuwa_manabu_burogu|passageTranslation": "Lately, I started learning sign language. The trigger was making a friend who has a hearing impairment. At first I could only do simple greetings, but little by little I can now hold conversations. I hope to communicate with more people through sign language.",
    "dokkai_nikki_shuukan_kouka_kiji|title": "Article on the Benefits of Journaling",
    "dokkai_nikki_shuukan_kouka_kiji|passageTranslation": "The habit of writing a journal every day, even briefly, is said to have a calming effect on the heart. By reflecting on the day's events, it's said to become easier to organize your own feelings. It's said to be important to keep it up even with short sentences, without overthinking it.",
    "dokkai_kouza_jouhou_toiawase_mail|title": "Course Information Request Email",
    "dokkai_kouza_jouhou_toiawase_mail|passageTranslation": "To whom it may concern. I'd like to ask about the Japanese course at your school. Could you explain in detail the beginner class start date and tuition fees? Sorry to bother you during your busy time, thank you for your understanding.",
    "dokkai_shinsetsu_honya_report|title": "New Bookstore Review",
    "dokkai_shinsetsu_honya_report|passageTranslation": "I tried going to a bookstore that opened last month. Inside the shop there's a cafe space, so you can choose books while drinking coffee. The selection is large too, and the book I was looking for was found right away. This has become a place I want to visit again.",
    "dokkai_jitensha_teire_guide|title": "Bicycle Maintenance Guide",
    "dokkai_jitensha_teire_guide|passageTranslation": "To use a bicycle long-term, regular maintenance is unavoidable. Let's check the tire air once a month. Also don't forget to oil the chain, so it moves smoothly.",
    "dokkai_kekkon_oiwai_tegami|title": "Wedding Congratulations Letter",
    "dokkai_kekkon_oiwai_tegami|passageTranslation": "Congratulations on your wedding. Seeing your two happy smiles makes me happy too. From now on too, stay close and support each other through life. I wish you happiness forever.",
    "dokkai_asa_stretch_kouka_kiji|title": "Article on the Benefits of Morning Stretching",
    "dokkai_asa_stretch_kouka_kiji|passageTranslation": "It's said that if you stretch right after waking up in the morning, your body wakes up more easily. Blood flow improves, so you can spend the day actively. It's said even a simple five-minute stretch is effective enough.",
    "dokkai_volunteer_hajimete_taiken|title": "First Time Volunteering Experience",
    "dokkai_volunteer_hajimete_taiken|passageTranslation": "Last week, I joined a local cleanup volunteer event for the first time. I was a bit nervous at first, but greeted the other participants while working. After it finished, seeing the town become clean, I felt satisfied.",
    "dokkai_amimono_manabu_burogu|title": "Blog on Learning to Knit",
    "dokkai_amimono_manabu_burogu|passageTranslation": "Since winter arrived, I tried starting knitting. At first I couldn't knit well, and redid it many times. However, little by little I mastered the trick, and can now make a simple scarf. Next I want to try making gloves.",
    "dokkai_mise_eigyou_jikan_henkou|title": "Store Business Hours Change Announcement",
    "dokkai_mise_eigyou_jikan_henkou|passageTranslation": "Starting next month, our store's business hours will change. The closing time, which was 8 pm until now, will become 7 pm. We ask for your understanding even though it may inconvenience customers.",
    "dokkai_kougei_shumi_burogu|title": "Blog on Learning Handicrafts",
    "dokkai_kougei_shumi_burogu|passageTranslation": "Lately, I started a hobby of making handmade accessories. Even choosing the materials is fun, I lose track of time absorbed in it. When I gave one as a gift to a friend, they liked it a lot. I've already started thinking about what to make next.",
    "dokkai_ongaku_kouka_kiji|title": "Article on the Benefits of Listening to Music",
    "dokkai_ongaku_kouka_kiji|passageTranslation": "It's said that if you listen to music you like, stress becomes lighter. In particular, music listened to while working is also said to have the effect of improving concentration. Finding music that suits you is said to be one way to enrich daily life.",
    "dokkai_apaato_keiyaku_koushin_mail|title": "Apartment Lease Renewal Request Email",
    "dokkai_apaato_keiyaku_koushin_mail|passageTranslation": "To the manager. Thank you for your help all this time. Since my current room's contract period is about to end, I'd like to renew the contract. Could you explain the procedure? Thank you for your understanding.",
    "dokkai_online_shopping_app_report|title": "Online Shopping App Review",
    "dokkai_online_shopping_app_report|passageTranslation": "The online shopping app I recently started using is very easy to use. Searching for products is easy, and the reviews are also helpful. Shipping is also fast, so far there's been no major dissatisfaction. It's just that the return procedure feels a bit complicated.",
    "dokkai_neko_kau_guide|title": "Guide to Caring for a Pet Cat",
    "dokkai_neko_kau_guide|passageTranslation": "If you start keeping a cat, it's important to first prepare a comfortable environment. Let's always keep the litter box clean. Also don't forget to pay attention to the food amount, and be careful it doesn't become overweight.",
    "dokkai_shussan_oiwai_tegami|title": "Childbirth Congratulations Letter",
    "dokkai_shussan_oiwai_tegami|passageTranslation": "Congratulations on the birth. I'm so happy to hear a healthy baby was born. I think it'll be tough for a while, but please rest enough without pushing yourself too hard. Once things settle down a bit, let me come visit.",
    "dokkai_mizu_kenkou_kouka_kiji|title": "Article on the Benefits of Drinking Water",
    "dokkai_mizu_kenkou_kouka_kiji|passageTranslation": "Drinking enough of the fluid you need each day is said to be the basis of managing your physical condition. If you lack fluids, it's said it can cause a drop in concentration and fatigue. It's recommended to make a habit of regularly drinking water little by little.",
    "dokkai_kyoushi_hajimete_taiken|title": "First Time Teaching Experience",
    "dokkai_kyoushi_hajimete_taiken|passageTranslation": "Last week, I got the chance to teach children for the first time. I was worried about whether I could explain well, but when the children said 'I understand!' I was truly happy. For the first time I felt the joy of teaching.",
    "dokkai_kankokugo_manabu_burogu|title": "Blog on Learning Korean",
    "dokkai_kankokugo_manabu_burogu|passageTranslation": "Since getting into Korean dramas as the trigger, I started learning Korean. Memorizing the alphabet was tough, but little by little I'm starting to understand simple conversations. Someday I want to be able to watch dramas without subtitles.",
    "dokkai_mise_shiharai_system_henkou|title": "Store Payment System Change Announcement",
    "dokkai_mise_shiharai_system_henkou|passageTranslation": "Starting next month, our store will only accept cashless payments. Cash payments will no longer be possible, please understand in advance. If anything is unclear, please ask the staff.",
    "dokkai_pan_tsukuru_manabu_burogu|title": "Blog on Learning to Make Bread",
    "dokkai_pan_tsukuru_manabu_burogu|passageTranslation": "Lately, I started a hobby of making bread at home. Waiting for the fermentation time is tough, but the aroma when it's done is special. Sometimes the shape still isn't neat, but I feel myself getting a little more skilled bit by bit.",
    "dokkai_uekiuebachi_kouka_kiji|title": "Article on the Benefits of Growing Plants at Home",
    "dokkai_uekiuebachi_kouka_kiji|passageTranslation": "It's said that placing a plant indoors has a relaxing effect. The time spent caring for the plant itself is said to become a precious, heart-calming moment amid daily busyness.",
    "dokkai_mensetsu_yotei_toiawase_mail|title": "Job Interview Schedule Request Email",
    "dokkai_mensetsu_yotei_toiawase_mail|passageTranslation": "To the recruitment contact. Thank you for passing my document screening this time. Regarding the interview schedule, could you let me know a suitable date and time? Thank you for your understanding.",
    "dokkai_gym_shinsetsu_report|title": "New Gym Near Home Review",
    "dokkai_gym_shinsetsu_report|passageTranslation": "I started going to a new gym that opened near my house. The machine types are varied, and the staff also teach carefully. The price is a bit expensive, but since the location is easy to reach, it feels easy to keep going.",
    "dokkai_kawagutsu_teire_guide|title": "Leather Shoe Care Guide",
    "dokkai_kawagutsu_teire_guide|passageTranslation": "To make leather shoes last long, it's important to brush off the dust after wearing them. Also don't forget to regularly apply cream to nourish the leather. It's best to avoid wearing them in the rain as much as possible.",
    "dokkai_teinen_oiwai_tegami|title": "Retirement Congratulations Letter",
    "dokkai_teinen_oiwai_tegami|passageTranslation": "Congratulations on your retirement. For all these years, truly thank you for your hard work. From now on, please take time for yourself, enjoy your hobbies and travel. I wish you health and happiness going forward.",
    "dokkai_hirune_kouka_kiji|title": "Article on the Benefits of Napping",
    "dokkai_hirune_kouka_kiji|passageTranslation": "It's said that a short nap has the effect of restoring concentration in the afternoon. However, since sleeping too long can affect nighttime sleep, it's said to be best to limit it to about twenty minutes.",
    "dokkai_unten_hajimete_taiken|title": "First Time Driving Alone Experience",
    "dokkai_unten_hajimete_taiken|passageTranslation": "Last weekend, for the first time after getting my license, I drove alone. My hands were shaking from being nervous, but I made it to my destination safely. It was the first moment I felt the freedom of being able to drive by myself.",
    "dokkai_video_tsukuru_manabu_burogu|title": "Blog on Learning to Make Videos",
    "dokkai_video_tsukuru_manabu_burogu|passageTranslation": "Interested in video editing, I started learning it self-taught. At first I didn't even understand simple operations, but as I practiced while watching free courses, I can now make short videos.",
    "dokkai_office_ichi_henkou_oshirase|title": "Office Location Change Announcement",
    "dokkai_office_ichi_henkou_oshirase|passageTranslation": "Starting the first of next month, the head office will move to a new location. The nearest station will change, please take note. A detailed map will be sent by email at a later date.",
}
