"""
kaiwa_meaning_en.py

Locked source of truth for the English translations of Kaiwa dialogue
content: KaiwaEntry.titleEn/descriptionEn, KaiwaLine.npcLine.translationEn,
KaiwaAnswerOption.translationEn. apply_kaiwa_meaning_en.py reads this and
patches assets/data/kaiwa_data.json, so translations live in exactly one
place.

Key format (four content kinds share one dict, disambiguated by suffix):
    "{entry_id}|title"              -> the dialogue's title
    "{entry_id}|description"        -> the dialogue's one-line description
    "{entry_id}|{line_id}|npc"      -> an NPC turn's sentence translation
    "{entry_id}|{line_id}|opt{i}"   -> the i-th (0-based) answer option's
                                        translation, for a user turn

line_id is only unique within its own entry (verified dataset-wide: no
entry repeats a line id), so it's always paired with entry_id. opt{i} is
the option's position in its own line's authored options list (stable —
shuffling for display happens at render time in a copy, never in the
data).

Scope note: npcLine.translationEn is not currently rendered anywhere
(KaiwaDialogueScreen shows NPC turns as image + speak button only, no
on-screen text — see CLAUDE.md's Kaiwa section) but is translated anyway
for completeness, since the field exists on the model and may be used
later. option translations ARE rendered today, right after the learner
picks the correct answer.

Must be re-applied after generate_kaiwa_seed.py regenerates the dataset.

STATUS: in progress. Total scope, counted directly from
    assets/data/kaiwa_data.json (1,700 real dialogues, 0 placeholders):
        titles:            1,700
        descriptions:      1,700
        npc lines:         7,468
        answer options:   23,151
        TOTAL:            34,019
    Order: titles + descriptions first (3,400 - smallest, highest
    visibility, shown in every Home/Level/Category list), then answer
    options (23,151 - the actual practice content, rendered after a
    correct tap), then npc lines (7,468 - currently unrendered, lowest
    priority) last. Given the scale, expect this to span many sessions;
    batch and commit incrementally the same way N1 kanji glosses did
    (scripts/kanji_word_meaning_en.py's STATUS block has the full
    history of that approach) so no single interruption loses much work.

    Titles+descriptions: batches 1-2/? done (1,000/3,400 rows =
    500/1,700 entries, dump order). Remaining: entries 501-1,700 (rows
    1,001-3,400 of the titles+descriptions dump).

    Dump a phase's source rows with, e.g. (titles+descriptions):
        python -c "import json; d=json.load(open('assets/data/kaiwa_data.json', encoding='utf-8')); [print(f\"{e['id']}|title :: {e['title']}\") or print(f\"{e['id']}|description :: {e['description']}\") for e in d]"
    or (answer options):
        python -c "import json; d=json.load(open('assets/data/kaiwa_data.json', encoding='utf-8')); [print(f\"{e['id']}|{l['id']}|opt{i} :: {o['translation']}\") for e in d for l in e['lines'] for i, o in enumerate(l.get('options', []))]"
    or (npc lines):
        python -c "import json; d=json.load(open('assets/data/kaiwa_data.json', encoding='utf-8')); [print(f\"{e['id']}|{l['id']}|npc :: {l['npcLine']['translation']}\") for e in d for l in e['lines'] if l.get('npcLine')]"

Style: translate the Indonesian gloss as it stands - natural
conversational English, no new senses added.
"""

KAIWA_MEANING_EN = {
    # ---------------- titles+descriptions batch 1 ----------------
    "kaiwa_kenalan_teman_baru|title": "Meeting a New Friend",
    "kaiwa_kenalan_teman_baru|description": "Yuki greets you and introduces herself for the first time.",
    "kaiwa_sapa_pagi_hari|title": "Morning Greetings",
    "kaiwa_sapa_pagi_hari|description": "Mr. Tanaka, your neighbor, greets you in the morning before you leave for school.",
    "kaiwa_tanya_asal_negara|title": "Asking Where You're From",
    "kaiwa_tanya_asal_negara|description": "Sari asks about your home country and your favorite food there.",
    "kaiwa_tukar_nomor|title": "Exchanging Phone Numbers",
    "kaiwa_tukar_nomor|description": "You and Yuki exchange phone numbers.",
    "kaiwa_tanya_umur|title": "Asking Your Age",
    "kaiwa_tanya_umur|description": "Sora asks your age.",
    "kaiwa_kenalan_kelas_baru|title": "Introducing Yourself in a New Class",
    "kaiwa_kenalan_kelas_baru|description": "On your first day in a new class, you introduce yourself.",
    "kaiwa_tanya_pekerjaan|title": "Asking About Someone's Job",
    "kaiwa_tanya_pekerjaan|description": "You ask Mr. Hiro, whom you just met, about his job.",
    "kaiwa_kenalan_pesta|title": "Meeting Someone at a Party",
    "kaiwa_kenalan_pesta|description": "You meet Mei, someone new, at a party.",
    "kaiwa_tanya_alamat|title": "Asking for a Home Address",
    "kaiwa_tanya_alamat|description": "Joko, your new friend, asks where you live.",
    "kaiwa_pisah_kenalan|title": "Saying Goodbye After Meeting",
    "kaiwa_pisah_kenalan|description": "After chatting for a while, you and Fitri have to part ways.",
    "kaiwa_tanya_bahasa|title": "Asking What Languages You Speak",
    "kaiwa_tanya_bahasa|description": "Haruto asks what languages you can speak.",
    "kaiwa_kenalan_keluarga|title": "Introducing Family Members",
    "kaiwa_kenalan_keluarga|description": "You show a family photo to Dewi.",
    "kaiwa_tanya_kota_asal|title": "Asking Your Hometown",
    "kaiwa_tanya_kota_asal|description": "Rian asks your hometown in Indonesia.",
    "kaiwa_kenalan_tetangga_baru|title": "Meeting a New Neighbor",
    "kaiwa_kenalan_tetangga_baru|description": "Mrs. Yamada, your new neighbor, introduces herself.",
    "kaiwa_kenalan_acara_kampus|title": "Meeting Someone at a Campus Event",
    "kaiwa_kenalan_acara_kampus|description": "Aiko starts a conversation with you at a campus orientation event.",
    "kaiwa_tanya_golongan_darah|title": "Asking Your Blood Type",
    "kaiwa_tanya_golongan_darah|description": "Bram asks your blood type, a typical light Japanese small-talk topic.",
    "kaiwa_kenalan_video_call|title": "Introducing Yourself Over Video Call",
    "kaiwa_kenalan_video_call|description": "Sakura, your new pen pal, invites you to a video call for the first time.",
    "kaiwa_tanya_warna_favorit|title": "Asking Your Favorite Color",
    "kaiwa_tanya_warna_favorit|description": "Nina asks your favorite color and why.",
    "kaiwa_kenalan_teman_sekamar|title": "Meeting Your Dorm Roommate",
    "kaiwa_kenalan_teman_sekamar|description": "Kenji, your new dorm roommate, introduces himself.",
    "kaiwa_tanya_rencana_lulus|title": "Asking Your Plans After Graduation",
    "kaiwa_tanya_rencana_lulus|description": "Lestari asks your plans after finishing school.",
    "kaiwa_tanya_zodiak|title": "Asking Your Zodiac Sign",
    "kaiwa_tanya_zodiak|description": "Rani asks your zodiac sign.",
    "kaiwa_tukar_medsos|title": "Exchanging Social Media Accounts",
    "kaiwa_tukar_medsos|description": "You and Kenji exchange social media accounts.",
    "kaiwa_tanya_makanan_favorit_kenalan|title": "Asking Your Favorite Food While Getting Acquainted",
    "kaiwa_tanya_makanan_favorit_kenalan|description": "Dian asks your favorite food.",
    "kaiwa_kenalan_klub_buku|title": "Meeting Someone at a Book Club",
    "kaiwa_kenalan_klub_buku|description": "Mira greets you at the book club for the first time.",
    "kaiwa_tanya_kepribadian|title": "Asking About Your Personality",
    "kaiwa_tanya_kepribadian|description": "Sinta asks about your personality.",
    "kaiwa_kenalan_lewat_teman|title": "Meeting Someone Through a Mutual Friend",
    "kaiwa_kenalan_lewat_teman|description": "Andi introduces you to his friend, Hiro.",
    "kaiwa_tanya_musim_favorit_kenalan|title": "Asking Your Favorite Season",
    "kaiwa_tanya_musim_favorit_kenalan|description": "Yudi asks your favorite season.",
    "kaiwa_kenalan_kelas_bahasa|title": "Meeting Someone in Japanese Class",
    "kaiwa_kenalan_kelas_bahasa|description": "You're introduced as a new student in Japanese class.",
    "kaiwa_tanya_hewan_peliharaan_kenalan|title": "Asking About Pets While Getting Acquainted",
    "kaiwa_tanya_hewan_peliharaan_kenalan|description": "Wati asks about your pet.",
    "kaiwa_kenalan_bandara|title": "Meeting Someone at the Airport",
    "kaiwa_kenalan_bandara|description": "A Japanese tourist strikes up a conversation with you at the airport.",
    "kaiwa_tanya_jurusan_kuliah|title": "Asking Your College Major",
    "kaiwa_tanya_jurusan_kuliah|description": "Farid asks your college major.",
    "kaiwa_kenalan_rekan_kerja|title": "Meeting a New Coworker",
    "kaiwa_kenalan_rekan_kerja|description": "Mr. Yamamoto welcomes you on your first day at work.",
    "kaiwa_tanya_cita_cita|title": "Asking About Your Dream Career",
    "kaiwa_tanya_cita_cita|description": "Lina asks your dream career.",
    "kaiwa_kenalan_gym|title": "Meeting Someone at the Gym",
    "kaiwa_kenalan_gym|description": "Rio greets you at the gym for the first time.",
    "kaiwa_tanya_minuman_favorit|title": "Asking Your Favorite Drink",
    "kaiwa_tanya_minuman_favorit|description": "Bella asks your favorite drink.",
    "kaiwa_kenalan_pasangan_teman|title": "Meeting a Friend's Partner",
    "kaiwa_kenalan_pasangan_teman|description": "Sari introduces her boyfriend, Dian, to you.",
    "kaiwa_tanya_buku_favorit|title": "Asking Your Favorite Book",
    "kaiwa_tanya_buku_favorit|description": "Ilham asks your favorite book.",
    "kaiwa_kenalan_pindah_sekolah|title": "Meeting New People After Changing Schools",
    "kaiwa_kenalan_pindah_sekolah|description": "Your first day at a new school after transferring.",
    "kaiwa_tanya_tinggi_badan|title": "Asking Your Height",
    "kaiwa_tanya_tinggi_badan|description": "Your friend asks your height.",
    "kaiwa_janji_bertemu_lagi|title": "Parting With a Promise to Meet Again",
    "kaiwa_janji_bertemu_lagi|description": "You and your new friend promise to meet again next week.",
    "kaiwa_pesan_makanan|title": "Ordering Food at a Restaurant",
    "kaiwa_pesan_makanan|description": "You order food and drinks from the restaurant server.",
    "kaiwa_minta_bill|title": "Asking for the Bill / Paying",
    "kaiwa_minta_bill|description": "You've finished eating and want to pay.",
    "kaiwa_menu_rekomendasi|title": "Asking for a Menu Recommendation",
    "kaiwa_menu_rekomendasi|description": "You're unsure what to order and ask the server for a recommendation.",
    "kaiwa_pesan_minuman_tambahan|title": "Ordering an Extra Drink",
    "kaiwa_pesan_minuman_tambahan|description": "You order an extra drink while eating.",
    "kaiwa_meja_empat_orang|title": "Requesting a Table for Four",
    "kaiwa_meja_empat_orang|description": "You and your friends arrive to eat as a group of four.",
    "kaiwa_tanya_alergi|title": "Mentioning a Food Allergy",
    "kaiwa_tanya_alergi|description": "You tell the server about your food allergy.",
    "kaiwa_makanan_pedas|title": "Ordering Spicy Food",
    "kaiwa_makanan_pedas|description": "You like spicy food and ask about the menu's spice level.",
    "kaiwa_bungkus_sisa|title": "Asking for a To-Go Box",
    "kaiwa_bungkus_sisa|description": "You have leftover food and ask to have it packed.",
    "kaiwa_puji_masakan|title": "Complimenting the Food to the Server",
    "kaiwa_puji_masakan|description": "You compliment the dish you just ate.",
    "kaiwa_reservasi_telepon|title": "Making a Table Reservation by Phone",
    "kaiwa_reservasi_telepon|description": "You call the restaurant to reserve a table.",
    "kaiwa_pesan_vegetarian|title": "Ordering Vegetarian Food",
    "kaiwa_pesan_vegetarian|description": "You ask the server about vegetarian menu options.",
    "kaiwa_duduk_konter_sushi|title": "Sitting at the Sushi Counter",
    "kaiwa_duduk_konter_sushi|description": "You eat sushi right in front of the chef at the counter.",
    "kaiwa_pesan_set_menu|title": "Ordering a Set Menu",
    "kaiwa_pesan_set_menu|description": "You order a full set menu.",
    "kaiwa_ganti_pesanan|title": "Changing Your Order",
    "kaiwa_ganti_pesanan|description": "You want to change an order you've already placed.",
    "kaiwa_tanya_jam_buka|title": "Asking the Restaurant's Opening Hours",
    "kaiwa_tanya_jam_buka|description": "You ask the server about the restaurant's operating hours.",
    "kaiwa_pesan_delivery|title": "Ordering Delivery",
    "kaiwa_pesan_delivery|description": "You call the restaurant to order food delivery.",
    "kaiwa_komplain_pesanan_salah|title": "Complaining About a Wrong Order",
    "kaiwa_komplain_pesanan_salah|description": "Your order arrives different from what you asked for.",
    "kaiwa_rayakan_ulang_tahun|title": "Celebrating a Birthday at a Restaurant",
    "kaiwa_rayakan_ulang_tahun|description": "You call the restaurant to arrange a birthday surprise.",
    "kaiwa_restoran_keluarga|title": "Eating at a Family Restaurant With a Child",
    "kaiwa_restoran_keluarga|description": "You're eating with a young child and need a special chair.",
    "kaiwa_bayar_terpisah|title": "Paying Separately (Splitting the Bill)",
    "kaiwa_bayar_terpisah|description": "You and your friend want to split the bill.",
    "kaiwa_tambah_nasi|title": "Asking for More Rice",
    "kaiwa_tambah_nasi|description": "You ask the server for a rice refill.",
    "kaiwa_tanya_halal|title": "Asking About Halal Menu Options",
    "kaiwa_tanya_halal|description": "You ask the restaurant server about halal menu options.",
    "kaiwa_meja_luar|title": "Requesting an Outdoor Table",
    "kaiwa_meja_luar|description": "You ask for an outdoor table with a view.",
    "kaiwa_cicip_menu_baru|title": "Trying the Restaurant's New Menu",
    "kaiwa_cicip_menu_baru|description": "The server offers a newly launched menu item.",
    "kaiwa_minta_sendok|title": "Asking for a Spoon Instead of Chopsticks",
    "kaiwa_minta_sendok|description": "You ask for a spoon because you're not used to chopsticks.",
    "kaiwa_tanya_kandungan_alergen|title": "Asking About Allergens in the Menu",
    "kaiwa_tanya_kandungan_alergen|description": "You ask about allergens before ordering.",
    "kaiwa_pesan_dessert|title": "Ordering Dessert",
    "kaiwa_pesan_dessert|description": "You order dessert after dinner.",
    "kaiwa_restoran_berisik|title": "Complaining the Restaurant Is Too Noisy",
    "kaiwa_restoran_berisik|description": "You ask for a quieter table.",
    "kaiwa_restoran_buffet|title": "Eating at a Buffet Restaurant",
    "kaiwa_restoran_buffet|description": "You ask about the buffet's price and rules.",
    "kaiwa_tanya_wifi_restoran|title": "Asking About the Restaurant's Wi-Fi",
    "kaiwa_tanya_wifi_restoran|description": "You ask about the restaurant's Wi-Fi and password.",
    "kaiwa_bayar_voucher|title": "Paying With a Discount Voucher",
    "kaiwa_bayar_voucher|description": "You pay using a discount coupon.",
    "kaiwa_pesan_take_away|title": "Ordering Food to Go",
    "kaiwa_pesan_take_away|description": "You order food to be packed to take home.",
    "kaiwa_minta_air_gratis|title": "Asking for Free Drinking Water",
    "kaiwa_minta_air_gratis|description": "You ask the server for plain water.",
    "kaiwa_restoran_waiting_list|title": "Restaurant Full, Joining the Waitlist",
    "kaiwa_restoran_waiting_list|description": "The restaurant is full and you join the waiting list.",
    "kaiwa_menu_musiman|title": "Asking About the Seasonal Menu",
    "kaiwa_menu_musiman|description": "You ask about this season's special menu.",
    "kaiwa_pesan_appetizer|title": "Ordering an Appetizer",
    "kaiwa_pesan_appetizer|description": "You order an appetizer before the main course.",
    "kaiwa_meja_non_smoking|title": "Requesting a Non-Smoking Table",
    "kaiwa_meja_non_smoking|description": "You ask for a table in the non-smoking area.",
    "kaiwa_live_music_restoran|title": "Enjoying Live Music at a Restaurant",
    "kaiwa_live_music_restoran|description": "The server tells you about tonight's live music.",
    "kaiwa_restoran_pemandangan|title": "Eating at a Restaurant With a View",
    "kaiwa_restoran_pemandangan|description": "You ask for a table with an ocean view.",
    "kaiwa_pamit_pelayan_favorit|title": "Saying Goodbye to Your Favorite Server",
    "kaiwa_pamit_pelayan_favorit|description": "You say goodbye to a server you've gotten to know well.",
    "kaiwa_beli_tiket|title": "Buying a Train Ticket",
    "kaiwa_beli_tiket|description": "You buy a train ticket at the station counter.",
    "kaiwa_tanya_peron|title": "Asking About the Platform",
    "kaiwa_tanya_peron|description": "You're having trouble finding the right platform at the station.",
    "kaiwa_tanya_jadwal|title": "Asking the Train Schedule",
    "kaiwa_tanya_jadwal|description": "You want to know when the next train arrives.",
    "kaiwa_salah_kereta|title": "Boarding the Wrong Train",
    "kaiwa_salah_kereta|description": "You realize you're on the wrong train and ask a station staff member.",
    "kaiwa_tanya_kereta_ekspres|title": "Asking About an Express Train",
    "kaiwa_tanya_kereta_ekspres|description": "You ask if there's an express train to your destination.",
    "kaiwa_kehilangan_barang|title": "Losing an Item on the Train",
    "kaiwa_kehilangan_barang|description": "You realize you left your bag on the train.",
    "kaiwa_kartu_isi_ulang|title": "Buying a Rechargeable Train Card",
    "kaiwa_kartu_isi_ulang|description": "You buy a rechargeable train card.",
    "kaiwa_tanya_pintu_keluar|title": "Asking About the Station Exit",
    "kaiwa_tanya_pintu_keluar|description": "You're having trouble finding the right exit.",
    "kaiwa_jam_sibuk|title": "Riding the Train During Rush Hour",
    "kaiwa_jam_sibuk|description": "You board a very crowded train during rush hour.",
    "kaiwa_stasiun_transit|title": "Asking About a Transfer Station",
    "kaiwa_stasiun_transit|description": "You need to change trains and ask which station to transfer at.",
    "kaiwa_beli_tiket_shinkansen|title": "Buying a Shinkansen Ticket",
    "kaiwa_beli_tiket_shinkansen|description": "You buy a shinkansen bullet-train ticket at the counter.",
    "kaiwa_loker_penitipan|title": "Asking About Luggage Lockers",
    "kaiwa_loker_penitipan|description": "You're looking for a coin locker to store your luggage.",
    "kaiwa_ketinggalan_kereta|title": "Missing the Train",
    "kaiwa_ketinggalan_kereta|description": "You missed the train and ask a staff member for help.",
    "kaiwa_gerbong_wanita|title": "Asking About the Women-Only Car",
    "kaiwa_gerbong_wanita|description": "You ask a staff member where the women-only car is.",
    "kaiwa_bantuan_koper|title": "Asking for Help Carrying a Suitcase",
    "kaiwa_bantuan_koper|description": "You ask a staff member to help carry your heavy suitcase.",
    "kaiwa_reservasi_kursi_kereta|title": "Asking About Reserved Seating",
    "kaiwa_reservasi_kursi_kereta|description": "You reserve a special seat at the ticket counter.",
    "kaiwa_kereta_terakhir|title": "Asking About the Last Night Train",
    "kaiwa_kereta_terakhir|description": "You ask what time the last train is tonight.",
    "kaiwa_kembalikan_tiket_kereta|title": "Returning a Wrongly Bought Ticket",
    "kaiwa_kembalikan_tiket_kereta|description": "You bought the wrong ticket and want to exchange it.",
    "kaiwa_akses_kursi_roda|title": "Asking About Wheelchair Access",
    "kaiwa_akses_kursi_roda|description": "You ask about wheelchair facilities at the station.",
    "kaiwa_rute_tercepat|title": "Asking for the Fastest Route",
    "kaiwa_rute_tercepat|description": "You ask for the fastest train route to your destination.",
    "kaiwa_tiket_anak|title": "Buying a Child's Ticket",
    "kaiwa_tiket_anak|description": "You also buy a train ticket for your child.",
    "kaiwa_stasiun_terdekat_hotel|title": "Asking About the Nearest Station to a Hotel",
    "kaiwa_stasiun_terdekat_hotel|description": "You ask the hotel receptionist about the nearest station.",
    "kaiwa_kelas_kereta|title": "Choosing Economy or Business Train Class",
    "kaiwa_kelas_kereta|description": "You choose a train class at the counter.",
    "kaiwa_loket_informasi|title": "Finding the Information Counter",
    "kaiwa_loket_informasi|description": "You're looking for the information counter because you're confused about the train.",
    "kaiwa_bawa_sepeda_kereta|title": "Asking the Rules for Bringing a Bicycle on the Train",
    "kaiwa_bawa_sepeda_kereta|description": "You ask whether bicycles are allowed on the train.",
    "kaiwa_kereta_berhenti_mendadak|title": "The Train Suddenly Stops",
    "kaiwa_kereta_berhenti_mendadak|description": "The train you're on suddenly stops midway.",
    "kaiwa_jadwal_kereta_akhir_pekan|title": "Asking About Weekend Train Schedules",
    "kaiwa_jadwal_kereta_akhir_pekan|description": "You ask about the difference in train schedules on weekends.",
    "kaiwa_tiket_kereta_panorama|title": "Buying a Panorama Train Ticket",
    "kaiwa_tiket_kereta_panorama|description": "You buy a panorama train ticket with a window seat.",
    "kaiwa_toilet_stasiun|title": "Asking for the Station Restroom",
    "kaiwa_toilet_stasiun|description": "You ask where the restroom is at the station.",
    "kaiwa_tunggu_kereta_dingin|title": "Waiting for a Train in Winter",
    "kaiwa_tunggu_kereta_dingin|description": "You wait for the train with other passengers in cold weather.",
    "kaiwa_tanya_kursi_kosong|title": "Asking About an Empty Seat",
    "kaiwa_tanya_kursi_kosong|description": "You ask the passenger next to you about an empty seat.",
    "kaiwa_tiket_grup|title": "Buying Tickets for a Group",
    "kaiwa_tiket_grup|description": "You buy train tickets for a group of 10 people.",
    "kaiwa_mesin_tiket_otomatis|title": "Asking How to Use the Ticket Machine",
    "kaiwa_mesin_tiket_otomatis|description": "You ask how to use the automatic ticket machine.",
    "kaiwa_terjebak_pintu_kereta|title": "Caught in the Train Door",
    "kaiwa_terjebak_pintu_kereta|description": "Your bag gets caught in the train door as it departs.",
    "kaiwa_sewa_loker_besar|title": "Renting a Large Locker",
    "kaiwa_sewa_loker_besar|description": "You're looking for a large locker for your suitcase.",
    "kaiwa_kereta_pertama|title": "Asking About the First Train",
    "kaiwa_kereta_pertama|description": "You ask what time the first morning train is.",
    "kaiwa_kehujanan_stasiun|title": "Caught in the Rain at the Station",
    "kaiwa_kehujanan_stasiun|description": "You get soaked by the rain when you arrive at the station.",
    "kaiwa_denda_tanpa_tiket|title": "Asking About the Fine for Riding Without a Ticket",
    "kaiwa_denda_tanpa_tiket|description": "You forgot your ticket and have to pay at the exit gate.",
    "kaiwa_bertemu_teman_stasiun|title": "Meeting an Old Friend at the Station",
    "kaiwa_bertemu_teman_stasiun|description": "You unexpectedly run into an old friend at the station.",
    "kaiwa_nomor_gerbong|title": "Asking the Train Car Number",
    "kaiwa_nomor_gerbong|description": "You ask which car number you should board.",
    "kaiwa_tanya_harga|title": "Asking the Price of an Item",
    "kaiwa_tanya_harga|description": "You ask the price of an item at the store.",
    "kaiwa_coba_baju|title": "Trying on Clothes at the Store",
    "kaiwa_coba_baju|description": "You want to try on clothes before buying.",
    "kaiwa_bayar_kasir|title": "Paying at the Cashier",
    "kaiwa_bayar_kasir|description": "You pay for your purchases at the cashier.",
    "kaiwa_minta_diskon|title": "Asking for a Discount",
    "kaiwa_minta_diskon|description": "You try to haggle over the price at the store.",
    "kaiwa_tukar_barang_rusak|title": "Exchanging a Damaged Item",
    "kaiwa_tukar_barang_rusak|description": "The item you bought turns out to be damaged, and you want to exchange it.",
    "kaiwa_cari_ukuran_pas|title": "Finding the Right Size",
    "kaiwa_cari_ukuran_pas|description": "The clothes you tried on don't quite fit.",
    "kaiwa_bandingkan_barang|title": "Comparing Two Items",
    "kaiwa_bandingkan_barang|description": "You're torn between two items.",
    "kaiwa_tanya_jam_buka_toko|title": "Asking the Store's Opening Hours",
    "kaiwa_tanya_jam_buka_toko|description": "You ask about the store's operating hours.",
    "kaiwa_beli_oleh_oleh|title": "Buying Souvenirs",
    "kaiwa_beli_oleh_oleh|description": "You're looking for souvenirs for your family in Indonesia.",
    "kaiwa_beli_elektronik|title": "Buying Electronics",
    "kaiwa_beli_elektronik|description": "You want to buy new headphones.",
    "kaiwa_cari_barang_rak|title": "Looking for an Item on the Shelf",
    "kaiwa_cari_barang_rak|description": "You're looking for cooking spices at the supermarket.",
    "kaiwa_beli_baju_musim_dingin|title": "Buying Winter Clothes",
    "kaiwa_beli_baju_musim_dingin|description": "You're looking for a warm coat for winter.",
    "kaiwa_tanya_metode_bayar|title": "Asking About Payment Methods",
    "kaiwa_tanya_metode_bayar|description": "You ask what payment methods are available at the register.",
    "kaiwa_beli_sepatu|title": "Buying New Shoes",
    "kaiwa_beli_sepatu|description": "You try on new shoes before buying.",
    "kaiwa_beli_hadiah_teman|title": "Buying a Gift for a Friend",
    "kaiwa_beli_hadiah_teman|description": "You're looking for a gift for your friend.",
    "kaiwa_barang_habis_stok|title": "Asking About an Out-of-Stock Item",
    "kaiwa_barang_habis_stok|description": "The size you're looking for turns out to be out of stock.",
    "kaiwa_gunakan_poin_member|title": "Using Membership Points",
    "kaiwa_gunakan_poin_member|description": "You sign up for a membership points card at the register.",
    "kaiwa_beli_buah_pasar|title": "Buying Fruit at the Market",
    "kaiwa_beli_buah_pasar|description": "You buy fresh fruit at the market.",
    "kaiwa_tanya_garansi|title": "Asking About the Warranty",
    "kaiwa_tanya_garansi|description": "You ask about the warranty period on the electronics you bought.",
    "kaiwa_ambil_di_toko|title": "Shopping Online, Picking Up In-Store",
    "kaiwa_ambil_di_toko|description": "You pick up your online order at the store.",
    "kaiwa_beli_buku_toko|title": "Buying a Book at the Bookstore",
    "kaiwa_beli_buku_toko|description": "You're looking for a Japanese textbook at the bookstore.",
    "kaiwa_kembalikan_barang_refund|title": "Asking How to Return an Item / Get a Refund",
    "kaiwa_kembalikan_barang_refund|description": "You want to return an item because the size doesn't fit.",
    "kaiwa_beli_barang_bekas|title": "Buying Secondhand Items at a Thrift Store",
    "kaiwa_beli_barang_bekas|description": "You're looking for secondhand furniture at a thrift store.",
    "kaiwa_ukuran_baju_anak|title": "Asking About Kids' Clothing Sizes",
    "kaiwa_ukuran_baju_anak|description": "You're looking for kids' clothes in the right size.",
    "kaiwa_beli_alat_sekolah|title": "Buying School Supplies",
    "kaiwa_beli_alat_sekolah|description": "You buy notebooks, pencils, and erasers.",
    "kaiwa_belanja_pasar_malam|title": "Shopping at a Night Market",
    "kaiwa_belanja_pasar_malam|description": "You haggle over the price of a doll at the night market.",
    "kaiwa_produk_ramah_lingkungan|title": "Asking About Eco-Friendly Products",
    "kaiwa_produk_ramah_lingkungan|description": "You're looking for eco-friendly products.",
    "kaiwa_beli_tas_belanja|title": "Buying a Reusable Shopping Bag",
    "kaiwa_beli_tas_belanja|description": "You buy an eco-friendly shopping bag at the register.",
    "kaiwa_cara_pakai_kosmetik|title": "Asking How to Use a Beauty Product",
    "kaiwa_cara_pakai_kosmetik|description": "You ask how to use a new beauty product.",
    "kaiwa_beli_alat_masak|title": "Buying Cookware",
    "kaiwa_beli_alat_masak|description": "You buy a new frying pan at the store.",
    "kaiwa_diskon_akhir_tahun|title": "Asking About Year-End Discounts",
    "kaiwa_diskon_akhir_tahun|description": "You ask the store clerk about the year-end sale schedule.",
    "kaiwa_beli_perhiasan|title": "Buying Jewelry",
    "kaiwa_beli_perhiasan|description": "You buy a ring as a gift.",
    "kaiwa_antre_kasir|title": "Chatting While Queuing at the Cashier",
    "kaiwa_antre_kasir|description": "You chat with someone else while waiting in line at the cashier.",
    "kaiwa_cara_merawat_barang|title": "Asking How to Care for an Item",
    "kaiwa_cara_merawat_barang|description": "You ask how to take care of the new shoes you bought.",
    "kaiwa_beli_bunga|title": "Buying Flowers as a Gift",
    "kaiwa_beli_bunga|description": "You buy roses as a gift for your mother.",
    "kaiwa_ukuran_internasional|title": "Asking About International vs. Japanese Sizes",
    "kaiwa_ukuran_internasional|description": "You ask about the difference between Japanese clothing sizes and your country's.",
    "kaiwa_barang_custom|title": "Ordering a Custom-Made Item",
    "kaiwa_barang_custom|description": "You order an item with a custom name printed on it.",
    "kaiwa_bayar_qr_code|title": "Asking How to Pay With a QR Code",
    "kaiwa_bayar_qr_code|description": "You pay for your purchase by scanning a QR code.",
    "kaiwa_beli_payung_mendadak|title": "Buying an Umbrella Because of Sudden Rain",
    "kaiwa_beli_payung_mendadak|description": "You buy an umbrella because it suddenly starts raining.",
    "kaiwa_sewa_kostum|title": "Renting a Costume for an Event",
    "kaiwa_sewa_kostum|description": "You rent a costume for a Halloween party.",
    "kaiwa_jalan_ke_stasiun|title": "Asking the Way to the Station",
    "kaiwa_jalan_ke_stasiun|description": "You're lost and ask someone on the street for directions to the station.",
    "kaiwa_jalan_ke_toilet|title": "Asking the Way to a Public Restroom",
    "kaiwa_jalan_ke_toilet|description": "You're looking for a public restroom in a tourist area.",
    "kaiwa_tanya_jarak|title": "Asking About the Distance",
    "kaiwa_tanya_jarak|description": "You want to know how far your destination is.",
    "kaiwa_jalan_ke_rumah_sakit|title": "Asking the Way to the Hospital",
    "kaiwa_jalan_ke_rumah_sakit|description": "You ask for directions to the hospital.",
    "kaiwa_tersesat_kota_baru|title": "Getting Lost in a New City",
    "kaiwa_tersesat_kota_baru|description": "You get lost and ask someone on the street for help.",
    "kaiwa_arah_dengan_peta|title": "Asking for Directions Using a Map",
    "kaiwa_arah_dengan_peta|description": "You show a map and ask a staff member for directions.",
    "kaiwa_jalan_ke_supermarket|title": "Asking the Way to the Supermarket",
    "kaiwa_jalan_ke_supermarket|description": "You ask where the nearest supermarket is.",
    "kaiwa_naik_kendaraan_apa|title": "Asking Which Mode of Transport to Take",
    "kaiwa_naik_kendaraan_apa|description": "You're unsure whether to take a bus or a taxi.",
    "kaiwa_jalan_pintas|title": "Asking About a Shortcut",
    "kaiwa_jalan_pintas|description": "You ask if there's a shortcut to your destination.",
    "kaiwa_terima_kasih_arah|title": "Thanking Someone for Directions",
    "kaiwa_terima_kasih_arah|description": "The person who gave you directions makes sure you understood.",
    "kaiwa_jalan_ke_bank|title": "Asking the Way to the Bank",
    "kaiwa_jalan_ke_bank|description": "You ask someone on the street for directions to the bank.",
    "kaiwa_jalan_ke_taman|title": "Asking the Way to the City Park",
    "kaiwa_jalan_ke_taman|description": "You ask for directions to the famous city park.",
    "kaiwa_arah_dengan_landmark|title": "Asking for Directions Using a Landmark",
    "kaiwa_arah_dengan_landmark|description": "You ask for directions using a building as a landmark.",
    "kaiwa_jalan_ke_kantor_polisi|title": "Asking the Way to the Police Station",
    "kaiwa_jalan_ke_kantor_polisi|description": "Your wallet is lost, so you ask for directions to the police box.",
    "kaiwa_arah_malam_hari|title": "Asking for Directions at Night",
    "kaiwa_arah_malam_hari|description": "You ask about how safe the road is at night.",
    "kaiwa_jalan_ditutup|title": "Asking About a Detour Because a Road Is Closed",
    "kaiwa_jalan_ditutup|description": "The road you usually take is currently closed.",
    "kaiwa_tunjukkan_arah_turis|title": "Giving Directions to Another Tourist",
    "kaiwa_tunjukkan_arah_turis|description": "A tourist asks you for directions on the street.",
    "kaiwa_jalan_ke_perpustakaan|title": "Asking the Way to the Library",
    "kaiwa_jalan_ke_perpustakaan|description": "You ask for directions to the city library.",
    "kaiwa_arah_aplikasi_peta|title": "Asking for Directions Using a Phone Map App",
    "kaiwa_arah_aplikasi_peta|description": "You're confused reading the map on your phone and ask for help.",
    "kaiwa_jalan_naik_sepeda|title": "Asking About Cycling Directions",
    "kaiwa_jalan_naik_sepeda|description": "You ask whether your destination can be reached by bicycle.",
    "kaiwa_jalan_ke_kuil|title": "Asking the Way to a Temple/Shrine",
    "kaiwa_jalan_ke_kuil|description": "You ask someone on the street for directions to a temple.",
    "kaiwa_jalan_ke_kolam_renang|title": "Asking the Way to the Swimming Pool",
    "kaiwa_jalan_ke_kolam_renang|description": "You ask for directions to the swimming pool.",
    "kaiwa_jalan_ke_pantai|title": "Asking the Way to the Beach",
    "kaiwa_jalan_ke_pantai|description": "You ask how to get to the beach.",
    "kaiwa_tangga_atau_lift|title": "Asking Whether to Take the Stairs or Elevator",
    "kaiwa_tangga_atau_lift|description": "You ask which is faster, taking the stairs or the elevator.",
    "kaiwa_jalan_ke_toko_oleh_oleh|title": "Asking the Way to a Souvenir Shop",
    "kaiwa_jalan_ke_toko_oleh_oleh|description": "You ask for directions to a souvenir shop.",
    "kaiwa_jarak_dengan_mobil|title": "Asking About Travel Time by Car",
    "kaiwa_jarak_dengan_mobil|description": "You ask how long the trip takes by car.",
    "kaiwa_tersesat_barang_berat|title": "Getting Lost While Carrying Heavy Luggage",
    "kaiwa_tersesat_barang_berat|description": "You get lost while carrying heavy luggage.",
    "kaiwa_jalan_ke_kantor_pemerintah|title": "Asking the Way to a Government Building",
    "kaiwa_jalan_ke_kantor_pemerintah|description": "You ask for directions to city hall.",
    "kaiwa_arah_bawa_anak|title": "Asking for Directions While Bringing a Child",
    "kaiwa_arah_bawa_anak|description": "You're looking for a small park to play at with your child.",
    "kaiwa_jalan_ke_pasar|title": "Asking the Way to a Traditional Market",
    "kaiwa_jalan_ke_pasar|description": "You ask for directions to a traditional market.",
    "kaiwa_jalan_ke_karaoke|title": "Directions to a Karaoke Place",
    "kaiwa_jalan_ke_karaoke|description": "You ask for directions to a karaoke place.",
    "kaiwa_rute_bebas_tangga|title": "Asking for a Stair-Free Route",
    "kaiwa_rute_bebas_tangga|description": "You ask for a route without stairs because you're carrying a large suitcase.",
    "kaiwa_arah_dengan_foto|title": "Asking for Directions by Showing a Photo",
    "kaiwa_arah_dengan_foto|description": "You show a photo of the place you want to go to.",
    "kaiwa_jalan_ke_gym|title": "Asking the Way to the Gym",
    "kaiwa_jalan_ke_gym|description": "You ask for directions to the nearest gym.",
    "kaiwa_salah_arah_gps|title": "Going the Wrong Way Because of a GPS Error",
    "kaiwa_salah_arah_gps|description": "You get lost because the map app on your phone is malfunctioning.",
    "kaiwa_jalan_pulang_pesta|title": "Asking the Way Home from a Party",
    "kaiwa_jalan_pulang_pesta|description": "It's already late at night and you're figuring out how to get home from the party.",
    "kaiwa_arah_ke_teman_sekelas|title": "Asking the Way to a Classmate's House",
    "kaiwa_arah_ke_teman_sekelas|description": "You ask for directions to a classmate's house.",
    "kaiwa_arah_angin_kencang|title": "Asking for Directions in Strong Wind",
    "kaiwa_arah_angin_kencang|description": "You ask for directions while the wind is blowing strongly.",
    "kaiwa_tunjukkan_arah_kurir|title": "Giving Directions to a Delivery Courier",
    "kaiwa_tunjukkan_arah_kurir|description": "A courier asks you for the delivery address.",
    "kaiwa_terima_kasih_diantar|title": "Thanking Someone for Walking You There",
    "kaiwa_terima_kasih_diantar|description": "A kind person walks you directly to your destination.",
    "kaiwa_sapa_guru|title": "Greeting the Teacher in Class",
    "kaiwa_sapa_guru|description": "You greet your teacher in the morning before class starts.",
    "kaiwa_tanya_pr|title": "Asking About Homework",
    "kaiwa_tanya_pr|description": "You ask a friend about today's homework assignment.",
    "kaiwa_pinjam_alat_tulis|title": "Borrowing Stationery",
    "kaiwa_pinjam_alat_tulis|description": "You forgot to bring a pencil and want to borrow one from a friend.",
    "kaiwa_jadwal_pelajaran|title": "Asking About the Class Schedule",
    "kaiwa_jadwal_pelajaran|description": "You ask Dewi about today's class schedule.",
    "kaiwa_izin_toilet|title": "Asking Permission to Use the Restroom",
    "kaiwa_izin_toilet|description": "You ask the teacher for permission to use the restroom.",
    "kaiwa_terlambat_kelas|title": "Arriving Late to Class",
    "kaiwa_terlambat_kelas|description": "You're late to class because the train was delayed.",
    "kaiwa_ajak_belajar_kelompok|title": "Inviting Someone to Study Together",
    "kaiwa_ajak_belajar_kelompok|description": "You invite Rian to study together for the exam.",
    "kaiwa_tanya_nilai_ujian|title": "Asking About Exam Scores",
    "kaiwa_tanya_nilai_ujian|description": "Lisa asks about your exam score.",
    "kaiwa_bolos_sakit|title": "Missing School Due to Illness",
    "kaiwa_bolos_sakit|description": "You call the school to report you're absent due to illness.",
    "kaiwa_pisah_akhir_semester|title": "Parting Ways at the End of the Semester",
    "kaiwa_pisah_akhir_semester|description": "Andi starts a conversation with you about the end of the semester.",
    "kaiwa_ikut_ekstrakurikuler|title": "Joining an Extracurricular Activity",
    "kaiwa_ikut_ekstrakurikuler|description": "You sign up for the art club at school.",
    "kaiwa_tugas_kelompok|title": "Asking About a Group Assignment",
    "kaiwa_tugas_kelompok|description": "You coordinate with a friend about a group presentation.",
    "kaiwa_izin_pulang_cepat|title": "Asking Permission to Leave Early",
    "kaiwa_izin_pulang_cepat|description": "You're feeling unwell and ask permission to leave early.",
    "kaiwa_tanya_ruang_kelas|title": "Asking About the Classroom",
    "kaiwa_tanya_ruang_kelas|description": "You're a new student looking for your classroom.",
    "kaiwa_makan_kantin_sekolah|title": "Having Lunch at the School Cafeteria",
    "kaiwa_makan_kantin_sekolah|description": "You have lunch with a friend at the school cafeteria.",
    "kaiwa_persiapan_ujian_akhir|title": "Preparing for the Final Exam",
    "kaiwa_persiapan_ujian_akhir|description": "You ask about the scope of material for the final exam.",
    "kaiwa_guru_pengganti|title": "Asking About a Substitute Teacher",
    "kaiwa_guru_pengganti|description": "A friend tells you there's a substitute teacher today.",
    "kaiwa_ikut_karyawisata|title": "Joining a School Field Trip",
    "kaiwa_ikut_karyawisata|description": "You ask about the school's field trip plans.",
    "kaiwa_kembalikan_buku_sekolah|title": "Returning a School Library Book",
    "kaiwa_kembalikan_buku_sekolah|description": "You return a borrowed book to the school library.",
    "kaiwa_tugas_piket|title": "Asking About Classroom Cleaning Duty",
    "kaiwa_tugas_piket|description": "You help a friend who's on cleaning duty today.",
    "kaiwa_sapa_teman_sebelum_kelas|title": "Greeting a Friend Before Class Starts",
    "kaiwa_sapa_teman_sebelum_kelas|description": "Your friend greets you before class starts this morning.",
    "kaiwa_tanya_materi_terlewat|title": "Asking About Missed Material",
    "kaiwa_tanya_materi_terlewat|description": "You were absent yesterday and ask about the material you missed.",
    "kaiwa_pinjam_catatan|title": "Borrowing Notes",
    "kaiwa_pinjam_catatan|description": "You borrow class notes from a friend.",
    "kaiwa_study_tour_sehari|title": "Going on a One-Day Field Trip to a Museum",
    "kaiwa_study_tour_sehari|description": "The teacher announces tomorrow's museum visit schedule.",
    "kaiwa_jadwal_ujian_semester|title": "Asking About the Semester Exam Schedule",
    "kaiwa_jadwal_ujian_semester|description": "You ask about the final semester exam schedule.",
    "kaiwa_jadi_ketua_kelas|title": "Becoming Class President",
    "kaiwa_jadi_ketua_kelas|description": "The teacher asks you to be class president this semester.",
    "kaiwa_izin_sakit_saat_kelas|title": "Asking the Teacher for Sick Leave During Class",
    "kaiwa_izin_sakit_saat_kelas|description": "You feel unwell in the middle of class.",
    "kaiwa_ikut_lomba_sekolah|title": "Joining a School Competition",
    "kaiwa_ikut_lomba_sekolah|description": "You sign up for a speech competition at school.",
    "kaiwa_tugas_tambahan|title": "Asking About Extra Homework",
    "kaiwa_tugas_tambahan|description": "You ask if there's any extra homework.",
    "kaiwa_bersih_bersih_kelas|title": "Cleaning the Classroom Together",
    "kaiwa_bersih_bersih_kelas|description": "The whole class works together to clean the classroom.",
    "kaiwa_tanya_nilai_turun|title": "Asking Why Your Grades Dropped",
    "kaiwa_tanya_nilai_turun|description": "The teacher asks why your exam scores have dropped lately.",
    "kaiwa_ikut_klub_debat|title": "Joining the Debate Club",
    "kaiwa_ikut_klub_debat|description": "You sign up for the debate club at school.",
    "kaiwa_loker_sekolah|title": "Asking About the School Locker",
    "kaiwa_loker_sekolah|description": "You ask about your school locker number.",
    "kaiwa_keluar_ekskul|title": "Quitting an Extracurricular Activity",
    "kaiwa_keluar_ekskul|description": "You quit the club to focus on studying.",
    "kaiwa_jenguk_teman_sakit_sekolah|title": "Visiting a Sick Friend at Home",
    "kaiwa_jenguk_teman_sakit_sekolah|description": "You bring homework to the house of a friend who's out sick.",
    "kaiwa_ikut_les_tambahan|title": "Joining Extra Tutoring Classes",
    "kaiwa_ikut_les_tambahan|description": "You sign up with the teacher for extra math tutoring.",
    "kaiwa_siapkan_presentasi|title": "Preparing a Group Presentation",
    "kaiwa_siapkan_presentasi|description": "You and a friend prepare a group presentation together.",
    "kaiwa_aturan_seragam|title": "Asking About School Uniform Rules",
    "kaiwa_aturan_seragam|description": "You ask the teacher about school uniform rules.",
    "kaiwa_rayakan_kelulusan|title": "Celebrating Graduation",
    "kaiwa_rayakan_kelulusan|description": "You and your friends celebrate graduation together.",
    "kaiwa_tukar_kontak_sekelas|title": "Exchanging Contacts With a Classmate",
    "kaiwa_tukar_kontak_sekelas|description": "You exchange contacts with a new classmate.",
    "kaiwa_bicara_cuaca|title": "Talking About the Weather",
    "kaiwa_bicara_cuaca|description": "You make small talk about the weather with a neighbor.",
    "kaiwa_tanya_akhir_pekan|title": "Asking About Weekend Plans",
    "kaiwa_tanya_akhir_pekan|description": "Your friend asks about your weekend plans.",
    "kaiwa_berpamitan|title": "Saying Goodbye",
    "kaiwa_berpamitan|description": "You say goodbye to a friend after running into them on the street.",
    "kaiwa_musim_favorit|title": "Talking About Your Favorite Season",
    "kaiwa_musim_favorit|description": "Mrs. Sato asks your favorite season.",
    "kaiwa_tunggu_bus|title": "Small Talk While Waiting for the Bus",
    "kaiwa_tunggu_bus|description": "You make light conversation with someone while waiting for the bus.",
    "kaiwa_kabar_lama_tidak_bertemu|title": "Catching Up After a Long Time",
    "kaiwa_kabar_lama_tidak_bertemu|description": "You run into Budi, an old friend, after not seeing him for a long time.",
    "kaiwa_rencana_malam_ini|title": "Talking About Tonight's Plans",
    "kaiwa_rencana_malam_ini|description": "Sinta invites you to watch a movie tonight.",
    "kaiwa_basa_basi_pekerjaan_rumah|title": "Small Talk About Household Chores",
    "kaiwa_basa_basi_pekerjaan_rumah|description": "Mrs. Wati, your neighbor, asks what's been keeping you busy lately.",
    "kaiwa_berita_terkini|title": "Talking About Current News",
    "kaiwa_berita_terkini|description": "Doni talks with you about today's weather news.",
    "kaiwa_sapa_tetangga_baru|title": "Greeting a New Neighbor",
    "kaiwa_sapa_tetangga_baru|description": "Mr. Endro, a new neighbor, introduces himself.",
    # ---------------- titles+descriptions batch 2 ----------------
    "kaiwa_bicara_hujan_deras|title": "Talking About Heavy Rain",
    "kaiwa_bicara_hujan_deras|description": "You chat with a neighbor about today's heavy rain.",
    "kaiwa_basa_basi_hobi_baru|title": "Small Talk About a New Hobby",
    "kaiwa_basa_basi_hobi_baru|description": "Your friend asks about a new hobby you've started.",
    "kaiwa_komentar_angin_kencang|title": "Commenting on Strong Wind",
    "kaiwa_komentar_angin_kencang|description": "You chat with someone on the street about the strong wind.",
    "kaiwa_basa_basi_lift|title": "Small Talk in the Elevator",
    "kaiwa_basa_basi_lift|description": "You ride the elevator with a neighbor and make light conversation.",
    "kaiwa_bicara_suhu_dingin|title": "Talking About Cold Weather",
    "kaiwa_bicara_suhu_dingin|description": "You chat with a neighbor about today's cold weather.",
    "kaiwa_tunggu_hujan_reda|title": "Small Talk While Waiting for the Rain to Stop",
    "kaiwa_tunggu_hujan_reda|description": "You chat with someone else while waiting for the rain to stop at the bus stop.",
    "kaiwa_rencana_liburan_musim_panas|title": "Talking About Summer Vacation Plans",
    "kaiwa_rencana_liburan_musim_panas|description": "Your friend asks about your summer vacation plans.",
    "kaiwa_basa_basi_kesehatan|title": "Small Talk About Health",
    "kaiwa_basa_basi_kesehatan|description": "Your neighbor asks how you've been feeling health-wise lately.",
    "kaiwa_komentar_bunga_mekar|title": "Commenting on the Blooming Flowers",
    "kaiwa_komentar_bunga_mekar|description": "You chat with a neighbor about the cherry blossoms in bloom.",
    "kaiwa_basa_basi_antrean|title": "Small Talk While Queuing",
    "kaiwa_basa_basi_antrean|description": "You make light conversation with someone else while waiting in line.",
    "kaiwa_salju_pertama|title": "Talking About the First Snow",
    "kaiwa_salju_pertama|description": "You and a neighbor talk about this year's first snowfall.",
    "kaiwa_basa_basi_salon|title": "Small Talk at the Salon/Barbershop",
    "kaiwa_basa_basi_salon|description": "You make light conversation with the barber.",
    "kaiwa_komentar_kualitas_udara|title": "Commenting on Air Quality",
    "kaiwa_komentar_kualitas_udara|description": "You and a neighbor talk about the poor air quality.",
    "kaiwa_basa_basi_sebelum_rapat|title": "Small Talk Before a Meeting",
    "kaiwa_basa_basi_sebelum_rapat|description": "You chat with a coworker before the meeting starts.",
    "kaiwa_perubahan_musim|title": "Talking About the Changing Seasons",
    "kaiwa_perubahan_musim|description": "You and a neighbor talk about the shift from summer to autumn.",
    "kaiwa_basa_basi_ruang_tunggu|title": "Small Talk in the Doctor's Waiting Room",
    "kaiwa_basa_basi_ruang_tunggu|description": "You chat with another patient while waiting for your turn.",
    "kaiwa_komentar_petir|title": "Commenting on Lightning and Thunder",
    "kaiwa_komentar_petir|description": "You and a neighbor chat during loud thunder and lightning.",
    "kaiwa_lift_rusak|title": "Small Talk While Waiting for a Broken Elevator",
    "kaiwa_lift_rusak|description": "You and a neighbor are both dealing with a broken elevator.",
    "kaiwa_kabut_pagi|title": "Talking About Morning Fog",
    "kaiwa_kabut_pagi|description": "You and a neighbor talk about this morning's thick fog.",
    "kaiwa_harga_naik|title": "Small Talk About Rising Prices",
    "kaiwa_harga_naik|description": "You and a neighbor complain about rising prices.",
    "kaiwa_bintang_malam|title": "Commenting on the Stars in the Night Sky",
    "kaiwa_bintang_malam|description": "You and a friend look up at a starry night sky.",
    "kaiwa_basa_basi_fotokopi|title": "Small Talk at the Office Copy Room",
    "kaiwa_basa_basi_fotokopi|description": "You chat with a coworker while the copy machine is malfunctioning.",
    "kaiwa_gempa_kecil|title": "Talking About a Minor Earthquake",
    "kaiwa_gempa_kecil|description": "You and a neighbor talk about a minor earthquake that just happened.",
    "kaiwa_tunggu_teman_terlambat|title": "Small Talk While Waiting for a Late Friend",
    "kaiwa_tunggu_teman_terlambat|description": "You chat with another friend while waiting for one who's running late.",
    "kaiwa_bau_masakan_tetangga|title": "Commenting on the Smell of a Neighbor's Cooking",
    "kaiwa_bau_masakan_tetangga|description": "You smell delicious cooking coming from a neighbor's house.",
    "kaiwa_rencana_sudah_penuh|title": "Declining an Invitation Because You Already Have Plans",
    "kaiwa_rencana_sudah_penuh|description": "Your friend invites you to hang out, but you already have other plans.",
    "kaiwa_hari_libur_nasional|title": "Talking About a National Holiday",
    "kaiwa_hari_libur_nasional|description": "You and a coworker talk about next week's national holiday.",
    "kaiwa_basa_basi_cuci_mobil|title": "Small Talk at the Car Wash",
    "kaiwa_basa_basi_cuci_mobil|description": "You chat with an attendant while washing your car.",
    "kaiwa_suara_serangga|title": "Commenting on the Sound of Summer Insects",
    "kaiwa_suara_serangga|description": "You and a neighbor talk about the sound of summer cicadas.",
    "kaiwa_pamit_janji_kirim_foto|title": "Saying Goodbye and Promising to Send Photos",
    "kaiwa_pamit_janji_kirim_foto|description": "You say goodbye to a friend and promise to send them photos.",
    "kaiwa_jelaskan_sakit|title": "Explaining Your Illness to the Doctor",
    "kaiwa_jelaskan_sakit|description": "You feel unwell and go to the doctor.",
    "kaiwa_janji_temu|title": "Making an Appointment",
    "kaiwa_janji_temu|description": "You call the hospital to make an appointment with a doctor.",
    "kaiwa_beli_obat|title": "Buying Medicine at the Pharmacy",
    "kaiwa_beli_obat|description": "You buy medicine according to the doctor's prescription at the pharmacy.",
    "kaiwa_gejala_flu|title": "Explaining Flu Symptoms",
    "kaiwa_gejala_flu|description": "You explain your flu symptoms to the doctor.",
    "kaiwa_efek_samping_obat|title": "Asking About Medicine Side Effects",
    "kaiwa_efek_samping_obat|description": "You ask the pharmacist about the medicine's side effects.",
    "kaiwa_kontrol_setelah_sakit|title": "Follow-Up Checkup After an Illness",
    "kaiwa_kontrol_setelah_sakit|description": "You go for a follow-up checkup after being sick.",
    "kaiwa_antar_keluarga_berobat|title": "Taking a Family Member to the Doctor",
    "kaiwa_antar_keluarga_berobat|description": "You take your younger sibling, who has a fever, to the hospital.",
    "kaiwa_biaya_berobat|title": "Asking About Treatment Costs",
    "kaiwa_biaya_berobat|description": "You ask about and pay the examination fee.",
    "kaiwa_cedera_olahraga|title": "Minor Injury While Exercising",
    "kaiwa_cedera_olahraga|description": "You injure your leg while exercising and go see a doctor.",
    "kaiwa_periksa_kesehatan_rutin|title": "Getting a Routine Health Checkup",
    "kaiwa_periksa_kesehatan_rutin|description": "You get your annual routine health checkup.",
    "kaiwa_daftar_pasien_baru|title": "Registering as a New Patient",
    "kaiwa_daftar_pasien_baru|description": "You register as a new patient at the hospital.",
    "kaiwa_alergi_obat|title": "Explaining a Medicine Allergy",
    "kaiwa_alergi_obat|description": "You tell the doctor about a medicine allergy you have.",
    "kaiwa_periksa_gigi|title": "Getting a Dental Checkup",
    "kaiwa_periksa_gigi|description": "Your tooth hurts and you go see a dentist.",
    "kaiwa_jenguk_teman_sakit|title": "Visiting a Sick Friend in the Hospital",
    "kaiwa_jenguk_teman_sakit|description": "You visit a friend who is being treated in the hospital.",
    "kaiwa_surat_keterangan_sakit|title": "Requesting a Doctor's Note",
    "kaiwa_surat_keterangan_sakit|description": "You ask for a doctor's note to submit to school.",
    "kaiwa_jadwal_praktik_dokter|title": "Asking About the Doctor's Office Hours",
    "kaiwa_jadwal_praktik_dokter|description": "You ask about a specialist's office hours.",
    "kaiwa_cek_mata|title": "Getting an Eye Exam at the Ophthalmologist",
    "kaiwa_cek_mata|description": "You feel your eyesight has gotten worse and see an eye doctor.",
    "kaiwa_vaksinasi|title": "Getting Vaccinated at the Hospital",
    "kaiwa_vaksinasi|description": "You get your routine vaccination at the hospital.",
    "kaiwa_ruang_rawat_inap|title": "Asking About an Inpatient Room",
    "kaiwa_ruang_rawat_inap|description": "You ask about an inpatient room for your family member.",
    "kaiwa_konsultasi_sakit_perut|title": "Consulting About a Stomachache",
    "kaiwa_konsultasi_sakit_perut|description": "Your stomach has hurt since yesterday and you see a doctor.",
    "kaiwa_dokter_spesialis_jantung|title": "Asking About a Cardiologist",
    "kaiwa_dokter_spesialis_jantung|description": "You want to get your heart checked by a specialist.",
    "kaiwa_imunisasi_anak|title": "Taking a Child for Immunization",
    "kaiwa_imunisasi_anak|description": "You take your child for a routine immunization.",
    "kaiwa_sakit_punggung|title": "Explaining Back Pain",
    "kaiwa_sakit_punggung|description": "You explain the back pain you've been having to the doctor.",
    "kaiwa_kontrol_kehamilan|title": "Prenatal Checkup",
    "kaiwa_kontrol_kehamilan|description": "Your wife has a routine prenatal checkup and you accompany her.",
    "kaiwa_operasi_usus_buntu|title": "Minor Appendix Surgery",
    "kaiwa_operasi_usus_buntu|description": "The doctor explains that you need appendix surgery.",
    "kaiwa_hasil_lab|title": "Asking About Lab Results",
    "kaiwa_hasil_lab|description": "You come in to ask about your lab test results.",
    "kaiwa_fisioterapi|title": "Physical Therapy After an Injury",
    "kaiwa_fisioterapi|description": "You undergo a physical therapy session after a leg injury.",
    "kaiwa_donor_darah|title": "Donating Blood at the Hospital",
    "kaiwa_donor_darah|description": "You come to the hospital to donate blood.",
    "kaiwa_gigi_bungsu|title": "Wisdom Tooth Pain",
    "kaiwa_gigi_bungsu|description": "You get your aching wisdom tooth checked by a dentist.",
    "kaiwa_cek_tekanan_darah|title": "Checking Blood Pressure",
    "kaiwa_cek_tekanan_darah|description": "You get your blood pressure checked at the hospital.",
    "kaiwa_insomnia|title": "Explaining Insomnia to the Doctor",
    "kaiwa_insomnia|description": "You explain the trouble sleeping you've been having to the doctor.",
    "kaiwa_rawat_jalan_kecelakaan|title": "Outpatient Care After a Minor Accident",
    "kaiwa_rawat_jalan_kecelakaan|description": "You have a minor accident and receive outpatient care.",
    "kaiwa_vaksin_bepergian|title": "Asking About Travel Vaccines",
    "kaiwa_vaksin_bepergian|description": "You're traveling abroad and ask what vaccines you'll need.",
    "kaiwa_obat_tanpa_resep|title": "Buying Over-the-Counter Medicine",
    "kaiwa_obat_tanpa_resep|description": "You buy pain relievers without a prescription at the pharmacy.",
    "kaiwa_konsultasi_kulit|title": "Consulting About a Skin Problem",
    "kaiwa_konsultasi_kulit|description": "You get a rash on your skin checked by a dermatologist.",
    "kaiwa_jenguk_bayi_baru_lahir|title": "Visiting a Newborn Baby",
    "kaiwa_jenguk_bayi_baru_lahir|description": "You visit your relative who just gave birth.",
    "kaiwa_ambil_nomor_antrean|title": "Getting a Queue Number at the Hospital",
    "kaiwa_ambil_nomor_antrean|description": "You get a queue number before your examination.",
    "kaiwa_ruang_ugd|title": "Asking About the ER",
    "kaiwa_ruang_ugd|description": "You ask about the location of the emergency room.",
    "kaiwa_migrain|title": "Consulting About Migraine Headaches",
    "kaiwa_migrain|description": "You consult about migraines that keep recurring.",
    "kaiwa_kontrol_pasca_operasi|title": "Follow-Up Checkup After Surgery",
    "kaiwa_kontrol_pasca_operasi|description": "You get a routine follow-up checkup after having surgery.",
    "kaiwa_tanya_hobi|title": "Asking a Friend's Hobby",
    "kaiwa_tanya_hobi|description": "Rina asks about your hobby.",
    "kaiwa_ajak_bermain|title": "Inviting Someone to Play Together",
    "kaiwa_ajak_bermain|description": "You invite Kenta to play together.",
    "kaiwa_musik_favorit|title": "Talking About Favorite Music",
    "kaiwa_musik_favorit|description": "You and Mika talk about your favorite music.",
    "kaiwa_film_favorit|title": "Talking About Your Favorite Movie",
    "kaiwa_film_favorit|description": "Dian asks your favorite movie.",
    "kaiwa_belajar_hobi_baru|title": "Learning a New Hobby",
    "kaiwa_belajar_hobi_baru|description": "You chat with Nia about a new hobby.",
    "kaiwa_koleksi_sesuatu|title": "Collecting Something",
    "kaiwa_koleksi_sesuatu|description": "Eko asks about your stamp collection.",
    "kaiwa_buku_sedang_dibaca|title": "Talking About the Book You're Reading",
    "kaiwa_buku_sedang_dibaca|description": "Wulan asks what book you're currently reading.",
    "kaiwa_ikut_klub_hobi|title": "Joining a Hobby Club",
    "kaiwa_ikut_klub_hobi|description": "You sign up for a photography club.",
    "kaiwa_berbagi_foto_hobi|title": "Sharing Photos From Your Hobby",
    "kaiwa_berbagi_foto_hobi|description": "Fajar asks to see the photos you took over the weekend.",
    "kaiwa_ajak_komunitas_hobi|title": "Inviting Someone to Join a Hobby Community",
    "kaiwa_ajak_komunitas_hobi|description": "You invite Galih to join a book-reading community.",
    "kaiwa_main_alat_musik|title": "Playing a Musical Instrument",
    "kaiwa_main_alat_musik|description": "Your friend asks what instrument you can play.",
    "kaiwa_menanam_tanaman|title": "Growing Ornamental Plants",
    "kaiwa_menanam_tanaman|description": "You tell a friend about your new hobby of growing cacti.",
    "kaiwa_memasak_hobi|title": "Cooking as a Hobby",
    "kaiwa_memasak_hobi|description": "A friend asks about your weekend cooking hobby.",
    "kaiwa_mendaki_gunung|title": "Mountain Hiking",
    "kaiwa_mendaki_gunung|description": "You tell a friend about your experience hiking Mount Fuji.",
    "kaiwa_main_board_game|title": "Playing Board Games",
    "kaiwa_main_board_game|description": "Your friend invites you to play board games together.",
    "kaiwa_menulis_diary|title": "Keeping a Diary/Journal",
    "kaiwa_menulis_diary|description": "You tell a friend about your habit of keeping a diary.",
    "kaiwa_merajut|title": "Knitting/Embroidery",
    "kaiwa_merajut|description": "Your friend is curious seeing you knit a scarf.",
    "kaiwa_main_game_online|title": "Playing Online Games",
    "kaiwa_main_game_online|description": "Your friend invites you to play an online game together.",
    "kaiwa_berkebun_akhir_pekan|title": "Gardening on the Weekend",
    "kaiwa_berkebun_akhir_pekan|description": "Your neighbor asks about your weekend gardening.",
    "kaiwa_fotografi_alam|title": "Nature Photography",
    "kaiwa_fotografi_alam|description": "You tell a friend about your hobby of photographing nature.",
    "kaiwa_melukis|title": "Painting as a Hobby",
    "kaiwa_melukis|description": "You tell a friend about your painting hobby.",
    "kaiwa_koleksi_kartu|title": "Card Collecting",
    "kaiwa_koleksi_kartu|description": "You show your game card collection to your friend.",
    "kaiwa_main_catur|title": "Playing Chess",
    "kaiwa_main_catur|description": "You invite a friend to play chess.",
    "kaiwa_nonton_anime|title": "Watching Anime",
    "kaiwa_nonton_anime|description": "You talk about the anime you're currently watching.",
    "kaiwa_kaligrafi|title": "Learning Calligraphy",
    "kaiwa_kaligrafi|description": "You talk about the Japanese calligraphy class you're taking.",
    "kaiwa_origami|title": "Origami as a Hobby",
    "kaiwa_origami|description": "You teach a friend to make simple origami.",
    "kaiwa_yoga_hobi|title": "Practicing Yoga as a Hobby",
    "kaiwa_yoga_hobi|description": "You talk about the yoga you regularly do at home.",
    "kaiwa_kerajinan_tangan|title": "Making Handicrafts",
    "kaiwa_kerajinan_tangan|description": "You show off a handicraft you made.",
    "kaiwa_memancing|title": "Fishing as a Hobby",
    "kaiwa_memancing|description": "You invite a friend to go fishing on the weekend.",
    "kaiwa_koleksi_sepatu|title": "Shoe Collecting",
    "kaiwa_koleksi_sepatu|description": "You show your shoe collection to a friend.",
    "kaiwa_main_puzzle|title": "Doing Puzzles",
    "kaiwa_main_puzzle|description": "You and a friend complete a puzzle together.",
    "kaiwa_belajar_bahasa_hobi|title": "Learning a Foreign Language as a Hobby",
    "kaiwa_belajar_bahasa_hobi|description": "You talk about studying a foreign language in your free time.",
    "kaiwa_karaoke_hobi|title": "Karaoke as a Hobby",
    "kaiwa_karaoke_hobi|description": "You invite a friend to karaoke as a regular hobby.",
    "kaiwa_buat_konten_video|title": "Making Video Content",
    "kaiwa_buat_konten_video|description": "You talk about your hobby of making videos for social media.",
    "kaiwa_baca_komik|title": "Reading Comics as a Hobby",
    "kaiwa_baca_komik|description": "You talk about the comic you're currently reading.",
    "kaiwa_fotografi_potret|title": "Learning Portrait Photography",
    "kaiwa_fotografi_potret|description": "You learn portrait photography techniques from a photographer friend.",
    "kaiwa_koleksi_action_figure|title": "Action Figure Collecting",
    "kaiwa_koleksi_action_figure|description": "You show your action figure collection to a friend.",
    "kaiwa_nonton_drama|title": "Watching Korean Dramas as a Hobby",
    "kaiwa_nonton_drama|description": "You talk about the Korean drama you're currently watching.",
    "kaiwa_tukar_hobi_teman_baru|title": "Sharing Hobbies With a New Friend",
    "kaiwa_tukar_hobi_teman_baru|description": "You share hobby stories with a friend you just met.",
    "kaiwa_menari_hobi|title": "Dancing as a Hobby",
    "kaiwa_menari_hobi|description": "You talk about the dance class you attend every week.",
    "kaiwa_terima_telepon|title": "Answering a Phone Call",
    "kaiwa_terima_telepon|description": "Tanaka calls you.",
    "kaiwa_telepon_teman|title": "Calling a Friend",
    "kaiwa_telepon_teman|description": "You call Sari to invite her to study together.",
    "kaiwa_tinggalkan_pesan|title": "Leaving a Message",
    "kaiwa_tinggalkan_pesan|description": "The person you're looking for isn't available.",
    "kaiwa_telepon_layanan_pelanggan|title": "Calling Customer Service",
    "kaiwa_telepon_layanan_pelanggan|description": "You call customer service because your internet isn't working.",
    "kaiwa_salah_sambung|title": "Wrong Number",
    "kaiwa_salah_sambung|description": "You accidentally call the wrong number.",
    "kaiwa_batalkan_janji_telepon|title": "Calling to Cancel an Appointment",
    "kaiwa_batalkan_janji_telepon|description": "You call Vino to cancel tomorrow's plans.",
    "kaiwa_telepon_orang_tua|title": "Calling Your Parent",
    "kaiwa_telepon_orang_tua|description": "You call your mother for a chat.",
    "kaiwa_tutup_telepon_sopan|title": "Ending a Call Politely",
    "kaiwa_tutup_telepon_sopan|description": "You end a call with your coworker, Mr. Joni.",
    "kaiwa_telepon_terputus|title": "The Call Gets Cut Off",
    "kaiwa_telepon_terputus|description": "Your phone connection with Sisi is unclear.",
    "kaiwa_ucapkan_selamat_telepon|title": "Calling to Offer Congratulations",
    "kaiwa_ucapkan_selamat_telepon|description": "You call Putri to wish her a happy birthday.",
    "kaiwa_telepon_pesan_makanan|title": "Calling to Order Food",
    "kaiwa_telepon_pesan_makanan|description": "You call a restaurant to order food delivery.",
    "kaiwa_telepon_minta_bantuan|title": "Asking for Help Over the Phone",
    "kaiwa_telepon_minta_bantuan|description": "You call a friend to ask for help carrying something.",
    "kaiwa_telepon_konsultasi_dokter|title": "Calling a Doctor for a Consultation",
    "kaiwa_telepon_konsultasi_dokter|description": "Your fever won't go down even after taking medicine, so you call a doctor.",
    "kaiwa_baterai_hp_habis|title": "Phone Battery Almost Dead",
    "kaiwa_baterai_hp_habis|description": "Your phone battery is almost dead while you're calling a friend.",
    "kaiwa_ingatkan_adik_telepon|title": "Reminding a Younger Sibling Over the Phone",
    "kaiwa_ingatkan_adik_telepon|description": "You call your younger sibling to remind them to do their homework.",
    "kaiwa_video_call_teman_lama|title": "Video Calling an Old Friend",
    "kaiwa_video_call_teman_lama|description": "You video call an old friend after not seeing them for a long time.",
    "kaiwa_telepon_bengkel|title": "Calling a Motorcycle Repair Shop",
    "kaiwa_telepon_bengkel|description": "Your motorcycle breaks down and you call a repair shop.",
    "kaiwa_telepon_izin_sakit_kantor|title": "Calling the Office to Report Sick Leave",
    "kaiwa_telepon_izin_sakit_kantor|description": "You call your boss to ask for sick leave from work.",
    "kaiwa_telepon_konfirmasi_reservasi|title": "Calling to Confirm a Reservation",
    "kaiwa_telepon_konfirmasi_reservasi|description": "You call to confirm tomorrow's restaurant reservation.",
    "kaiwa_telepon_spam_promosi|title": "Receiving a Spam/Promotional Call",
    "kaiwa_telepon_spam_promosi|description": "You receive an unsolicited promotional sales call.",
    "kaiwa_telepon_reservasi_restoran|title": "Calling to Reserve a Restaurant Table",
    "kaiwa_telepon_reservasi_restoran|description": "You call a restaurant to reserve a table.",
    "kaiwa_telepon_minta_maaf_terlambat|title": "Calling to Apologize for Being Late",
    "kaiwa_telepon_minta_maaf_terlambat|description": "You call your friend to apologize that you'll be late.",
    "kaiwa_telepon_curhat_teman|title": "Calling a Friend to Talk Things Through",
    "kaiwa_telepon_curhat_teman|description": "You call a close friend to talk about your problems.",
    "kaiwa_salah_nomor_telepon|title": "Wrong Phone Number",
    "kaiwa_salah_nomor_telepon|description": "You receive a call from someone who dialed the wrong number.",
    "kaiwa_telepon_provider_internet|title": "Calling the Internet Provider",
    "kaiwa_telepon_provider_internet|description": "You call your internet provider because the connection isn't working.",
    "kaiwa_telepon_pacar_malam|title": "Calling Your Partner at Night",
    "kaiwa_telepon_pacar_malam|description": "You call your partner before bed to say goodnight.",
    "kaiwa_telepon_kurir_alamat|title": "A Courier Calls to Confirm the Address",
    "kaiwa_telepon_kurir_alamat|description": "A courier calls to confirm your delivery address.",
    "kaiwa_sinyal_telepon_buruk|title": "Bad Phone Signal",
    "kaiwa_sinyal_telepon_buruk|description": "You call a friend but the signal is bad and the call keeps cutting out.",
    "kaiwa_telepon_sekolah_anak|title": "Calling Your Child's School",
    "kaiwa_telepon_sekolah_anak|description": "You call your child's school to ask about something.",
    "kaiwa_telepon_batalkan_langganan|title": "Calling to Cancel a Subscription",
    "kaiwa_telepon_batalkan_langganan|description": "You call a service to cancel your monthly subscription.",
    "kaiwa_telepon_bank_blokir_kartu|title": "Calling the Bank to Block a Card",
    "kaiwa_telepon_bank_blokir_kartu|description": "Your card is lost and you call the bank to block it.",
    "kaiwa_telepon_ajak_nonton|title": "Calling a Friend to Invite Them to a Movie",
    "kaiwa_telepon_ajak_nonton|description": "You call a friend to invite them to watch a movie together.",
    "kaiwa_telepon_ucapkan_ultah|title": "Calling to Wish Someone a Happy Birthday",
    "kaiwa_telepon_ucapkan_ultah|description": "You call a friend to wish them a happy birthday.",
    "kaiwa_telepon_tanya_alamat|title": "Calling to Ask for an Address",
    "kaiwa_telepon_tanya_alamat|description": "You call your friend to ask for their home address.",
    "kaiwa_panggilan_tidak_terjawab|title": "Missed Call",
    "kaiwa_panggilan_tidak_terjawab|description": "You call a friend back after seeing a missed call.",
    "kaiwa_telepon_izin_pulang_malam|title": "Calling to Ask Permission to Come Home Late",
    "kaiwa_telepon_izin_pulang_malam|description": "You call your parents to ask permission to come home late at night.",
    "kaiwa_telepon_dukung_teman_sedih|title": "Calling to Support a Sad Friend",
    "kaiwa_telepon_dukung_teman_sedih|description": "Your friend is sad and you call them to offer support.",
    "kaiwa_telepon_konfirmasi_kedatangan|title": "Calling to Confirm Attendance",
    "kaiwa_telepon_konfirmasi_kedatangan|description": "You call the host to confirm you're coming to the event.",
    "kaiwa_telepon_minta_jemput|title": "Calling to Ask for a Ride",
    "kaiwa_telepon_minta_jemput|description": "You call your family to ask for a ride because of heavy rain.",
    "kaiwa_video_call_rapat_kerja|title": "Video Calling for a Work Meeting",
    "kaiwa_video_call_rapat_kerja|description": "You join a work meeting via video call from home.",
    "kaiwa_naik_bus|title": "Riding the Bus",
    "kaiwa_naik_bus|description": "You confirm the bus's destination with the driver.",
    "kaiwa_panggil_taksi|title": "Calling a Taxi",
    "kaiwa_panggil_taksi|description": "You ask the hotel receptionist to call a taxi for you.",
    "kaiwa_tanya_ongkos|title": "Asking the Fare",
    "kaiwa_tanya_ongkos|description": "You ask the driver about the taxi fare.",
    "kaiwa_kereta_bawah_tanah|title": "Riding the Subway",
    "kaiwa_kereta_bawah_tanah|description": "You ask where the subway station is.",
    "kaiwa_sewa_sepeda|title": "Renting a Bicycle",
    "kaiwa_sewa_sepeda|description": "You rent a bicycle to get around the city.",
    "kaiwa_naik_pesawat|title": "Flying on a Plane",
    "kaiwa_naik_pesawat|description": "You check in at the airport before boarding your flight.",
    "kaiwa_ketinggalan_bus|title": "Missing the Bus",
    "kaiwa_ketinggalan_bus|description": "You miss the bus and ask about the next schedule.",
    "kaiwa_jam_terakhir_transportasi|title": "Asking About the Last Departure Time",
    "kaiwa_jam_terakhir_transportasi|description": "You ask what time the last train is tonight.",
    "kaiwa_naik_ride_sharing|title": "Taking a Ride-Sharing Service",
    "kaiwa_naik_ride_sharing|description": "You ride in a car booked through an app.",
    "kaiwa_tanya_rute_terbaik|title": "Asking for the Best Route",
    "kaiwa_tanya_rute_terbaik|description": "You ask for the fastest way to the airport.",
    "kaiwa_naik_kapal_feri|title": "Riding the Ferry",
    "kaiwa_naik_kapal_feri|description": "You confirm the ferry's destination with a staff member.",
    "kaiwa_sewa_mobil|title": "Renting a Car",
    "kaiwa_sewa_mobil|description": "You rent a car for a multi-day trip.",
    "kaiwa_bus_malam_antar_kota|title": "Riding an Intercity Night Bus",
    "kaiwa_bus_malam_antar_kota|description": "You buy a ticket for a night bus to another city.",
    "kaiwa_tanya_tempat_parkir|title": "Asking About Parking",
    "kaiwa_tanya_tempat_parkir|description": "You ask about the location and rate of a parking lot.",
    "kaiwa_naik_becak|title": "Riding a Pedicab/Horse Cart",
    "kaiwa_naik_becak|description": "You ride a pedicab to the station.",
    "kaiwa_terjebak_macet|title": "Stuck in Traffic",
    "kaiwa_terjebak_macet|description": "Your taxi is stuck in severe traffic on the way.",
    "kaiwa_kursi_prioritas|title": "Asking About Priority Seating",
    "kaiwa_kursi_prioritas|description": "You ask about priority seating on the train.",
    "kaiwa_naik_trem|title": "Riding the Tram/Monorail",
    "kaiwa_naik_trem|description": "You're looking for where to board the monorail at the station.",
    "kaiwa_bawa_barang_besar|title": "Bringing Large Luggage on Public Transport",
    "kaiwa_bawa_barang_besar|description": "You have a large suitcase and ask if you're allowed to board.",
    "kaiwa_turun_halte_salah|title": "Getting Off at the Wrong Stop",
    "kaiwa_turun_halte_salah|description": "You get off at the wrong station and ask a staff member for help.",
    "kaiwa_naik_taksi_online|title": "Taking an Online-Booked Taxi",
    "kaiwa_naik_taksi_online|description": "You book a taxi through an app and ride it.",
    "kaiwa_tanya_tarif_tol|title": "Asking About Toll Fees",
    "kaiwa_tanya_tarif_tol|description": "You ask the taxi driver about the toll fee.",
    "kaiwa_bus_antar_jemput_sekolah|title": "Riding the School Shuttle Bus",
    "kaiwa_bus_antar_jemput_sekolah|description": "You ride the school shuttle bus every morning.",
    "kaiwa_ban_motor_bocor|title": "Flat Motorcycle Tire",
    "kaiwa_ban_motor_bocor|description": "Your motorcycle tire goes flat on the road and you ask for help.",
    "kaiwa_naik_kereta_peluru|title": "Riding the Bullet Train",
    "kaiwa_naik_kereta_peluru|description": "You take the bullet train for a long-distance trip.",
    "kaiwa_jadwal_bus_malam|title": "Asking About the Night Bus Schedule",
    "kaiwa_jadwal_bus_malam|description": "You ask a staff member about the intercity night bus schedule.",
    "kaiwa_naik_angkot|title": "Riding a Public Minivan",
    "kaiwa_naik_angkot|description": "You ride a public minivan and ask the driver about the route.",
    "kaiwa_nyebrang_jalan_raya|title": "Crossing a Busy Road",
    "kaiwa_nyebrang_jalan_raya|description": "You ask how to safely cross a busy road.",
    "kaiwa_skuter_listrik|title": "Riding an Electric Scooter",
    "kaiwa_skuter_listrik|description": "You rent an electric scooter to get around the city.",
    "kaiwa_mobil_mogok|title": "Car Breaking Down on the Road",
    "kaiwa_mobil_mogok|description": "Your car breaks down on the road and you ask for help.",
    "kaiwa_rute_alternatif_macet|title": "Asking for an Alternate Route During Traffic",
    "kaiwa_rute_alternatif_macet|description": "You ask the taxi driver for an alternate route because of severe traffic.",
    "kaiwa_bus_wisata|title": "Riding a Sightseeing Bus",
    "kaiwa_bus_wisata|description": "You take a sightseeing bus around the city with other tourists.",
    "kaiwa_tempat_isi_bensin|title": "Asking Where to Get Gas",
    "kaiwa_tempat_isi_bensin|description": "You ask where the nearest gas station is.",
    "kaiwa_berbagi_tumpangan|title": "Carpooling With a Friend",
    "kaiwa_berbagi_tumpangan|description": "You and a friend carpool to the office.",
    "kaiwa_lift_bandara|title": "Using the Airport Elevator",
    "kaiwa_lift_bandara|description": "You're looking for an elevator at the airport to carry a large suitcase.",
    "kaiwa_zona_parkir_sepeda|title": "Asking About the Bicycle Parking Zone",
    "kaiwa_zona_parkir_sepeda|description": "You ask about the proper place to park your bicycle.",
    "kaiwa_terlambat_pesawat|title": "Almost Missing a Flight",
    "kaiwa_terlambat_pesawat|description": "You almost miss your flight and run to the gate.",
    "kaiwa_tukar_tiket_bus|title": "Exchanging a Bus Ticket",
    "kaiwa_tukar_tiket_bus|description": "You want to exchange your bus ticket for a different departure time.",
    "kaiwa_kereta_gantung|title": "Riding a Cable Car",
    "kaiwa_kereta_gantung|description": "You ride a cable car to see the view from above.",
    "kaiwa_rute_bebas_macet|title": "Asking for a Traffic-Free Route",
    "kaiwa_rute_bebas_macet|description": "You ask for a route that avoids traffic during rush hour.",
    "kaiwa_kirim_surat|title": "Sending a Letter",
    "kaiwa_kirim_surat|description": "You send a letter abroad through the post office.",
    "kaiwa_kirim_paket|title": "Sending a Package",
    "kaiwa_kirim_paket|description": "You send a package of books through the post office.",
    "kaiwa_beli_perangko|title": "Buying Stamps",
    "kaiwa_beli_perangko|description": "You buy a few stamps.",
    "kaiwa_ambil_paket_tertahan|title": "Picking Up a Held Package",
    "kaiwa_ambil_paket_tertahan|description": "You pick up a package that was being held at the post office.",
    "kaiwa_lama_pengiriman|title": "Asking How Long Delivery Takes",
    "kaiwa_lama_pengiriman|description": "You ask how long delivery takes and choose express shipping.",
    "kaiwa_kirim_uang_pos|title": "Sending Money by Post",
    "kaiwa_kirim_uang_pos|description": "You send money to your family through the post office.",
    "kaiwa_buka_kotak_pos|title": "Opening a Post Office Box",
    "kaiwa_buka_kotak_pos|description": "You sign up to open a post office box.",
    "kaiwa_komplain_paket_rusak|title": "Complaining About a Damaged Package",
    "kaiwa_komplain_paket_rusak|description": "The package you received turns out to be damaged.",
    "kaiwa_kirim_barang_internasional|title": "Sending an International Package",
    "kaiwa_kirim_barang_internasional|description": "You send clothes to America through the post office.",
    "kaiwa_asuransi_pengiriman|title": "Asking About Shipping Insurance",
    "kaiwa_asuransi_pengiriman|description": "You ask about insurance for your package.",
    "kaiwa_cek_nomor_resi|title": "Checking a Tracking Number",
    "kaiwa_cek_nomor_resi|description": "You ask about your package's delivery status using the tracking number.",
    "kaiwa_kirim_kartu_pos|title": "Sending a Postcard",
    "kaiwa_kirim_kartu_pos|description": "You send a postcard to a friend within the country.",
    "kaiwa_jam_buka_kantor_pos|title": "Asking the Post Office's Opening Hours",
    "kaiwa_jam_buka_kantor_pos|description": "You ask about the post office's operating hours.",
    "kaiwa_ubah_alamat_pengiriman|title": "Changing a Delivery Address",
    "kaiwa_ubah_alamat_pengiriman|description": "You change the delivery address of a package that's already been sent.",
    "kaiwa_kirim_dokumen_penting|title": "Sending an Important Document",
    "kaiwa_kirim_dokumen_penting|description": "You send an important document using registered mail.",
    "kaiwa_bungkus_paket|title": "Wrapping a Package at the Post Office",
    "kaiwa_bungkus_paket|description": "You ask for help wrapping a package before sending it.",
    "kaiwa_terima_paket_cod|title": "Receiving a Cash-on-Delivery Package",
    "kaiwa_terima_paket_cod|description": "A courier delivers a cash-on-delivery package to your house.",
    "kaiwa_hilang_bukti_pengiriman|title": "Losing a Shipping Receipt",
    "kaiwa_hilang_bukti_pengiriman|description": "You lose the shipping receipt for your package.",
    "kaiwa_kirim_barang_pecah_belah|title": "Sending a Package of Fragile Items",
    "kaiwa_kirim_barang_pecah_belah|description": "You send fragile items and ask for special handling.",
    "kaiwa_buat_akun_pengiriman|title": "Creating an Online Shipping Account",
    "kaiwa_buat_akun_pengiriman|description": "You sign up for an online account to track packages.",
    "kaiwa_kirim_bunga_pos|title": "Sending Flowers by Post",
    "kaiwa_kirim_bunga_pos|description": "You want to send flowers for a friend's birthday through the post office.",
    "kaiwa_ukuran_maksimal_paket|title": "Asking About the Maximum Package Size",
    "kaiwa_ukuran_maksimal_paket|description": "You ask about the size limit for packages that can be shipped.",
    "kaiwa_beli_amplop|title": "Buying Envelopes and Stationery",
    "kaiwa_beli_amplop|description": "You buy envelopes and stationery at the post office.",
    "kaiwa_kirim_paket_luar_pulau|title": "Sending a Package to Another Island",
    "kaiwa_kirim_paket_luar_pulau|description": "You send a package to another island and ask how long it will take.",
    "kaiwa_berat_maksimal_paket|title": "Asking About the Maximum Package Weight",
    "kaiwa_berat_maksimal_paket|description": "You ask about the weight limit for packages that can be shipped.",
    "kaiwa_ambil_antrean_kantor_pos|title": "Getting a Queue Number at the Post Office",
    "kaiwa_ambil_antrean_kantor_pos|description": "You get a queue number before being served at the post office.",
    "kaiwa_cara_packing_aman|title": "Asking How to Pack Items Safely",
    "kaiwa_cara_packing_aman|description": "You ask how to safely pack fragile items.",
    "kaiwa_bayar_tagihan_pos|title": "Paying a Bill at the Post Office",
    "kaiwa_bayar_tagihan_pos|description": "You pay your electricity bill through the post office.",
    "kaiwa_kirim_paket_express|title": "Sending an Express Package",
    "kaiwa_kirim_paket_express|description": "You want to send a package using the fastest service.",
    "kaiwa_status_pengiriman|title": "Asking About Delivery Status",
    "kaiwa_status_pengiriman|description": "You ask about the status of a package that hasn't arrived yet.",
    "kaiwa_kembalikan_barang_pos|title": "Returning an Item by Post",
    "kaiwa_kembalikan_barang_pos|description": "You return an online purchase through the post office.",
    "kaiwa_buka_po_box|title": "Opening a PO Box",
    "kaiwa_buka_po_box|description": "You sign up to open a private post office box (PO box).",
    "kaiwa_asuransi_tambahan|title": "Sending a Package With Extra Insurance",
    "kaiwa_asuransi_tambahan|description": "You want to add extra insurance for a valuable package.",
    "kaiwa_lacak_paket|title": "Asking How to Track a Package",
    "kaiwa_lacak_paket|description": "You ask how to track a package that's already been sent.",
    "kaiwa_kirim_buku_pos|title": "Sending Books by Post",
    "kaiwa_kirim_buku_pos|description": "You send a few books to your friend by post.",
    "kaiwa_komplain_paket_terlambat|title": "Complaining About a Late Package",
    "kaiwa_komplain_paket_terlambat|description": "Your package arrives late and you complain to the post office.",
    "kaiwa_loket_khusus|title": "Asking About a Special Counter",
    "kaiwa_loket_khusus|description": "You ask about the special counter for international shipping.",
    "kaiwa_ambil_formulir_pengiriman|title": "Getting a Shipping Form",
    "kaiwa_ambil_formulir_pengiriman|description": "You get and fill out a form for international shipping.",
    "kaiwa_kirim_paket_makanan|title": "Sending a Food Package",
    "kaiwa_kirim_paket_makanan|description": "You send a package of dried food to your family.",
    "kaiwa_bayar_ewallet_pos|title": "Asking How to Pay With an E-Wallet",
    "kaiwa_bayar_ewallet_pos|description": "You ask if you can pay with an e-wallet at the post office.",
    "kaiwa_rencana_liburan|title": "Talking About Vacation Plans",
    "kaiwa_rencana_liburan|description": "Yuta asks about your summer vacation plans.",
    "kaiwa_ajak_liburan|title": "Inviting Someone on a Trip Together",
    "kaiwa_ajak_liburan|description": "You invite Dewi to go on vacation together.",
    "kaiwa_cerita_liburan|title": "Telling a Story After a Vacation",
    "kaiwa_cerita_liburan|description": "Aiko asks how your vacation was.",
    "kaiwa_pesan_hotel_liburan|title": "Booking a Hotel for Vacation",
    "kaiwa_pesan_hotel_liburan|description": "You book a hotel room for next weekend.",
    "kaiwa_tempat_wisata|title": "Talking About Tourist Spots",
    "kaiwa_tempat_wisata|description": "Reza asks about your vacation destination.",
    "kaiwa_packing_liburan|title": "Packing for Vacation",
    "kaiwa_packing_liburan|description": "Wina asks about your vacation preparations.",
    "kaiwa_liburan_keluarga|title": "Vacationing With Family",
    "kaiwa_liburan_keluarga|description": "Your father suggests a family vacation.",
    "kaiwa_liburan_dibatalkan|title": "A Canceled Vacation",
    "kaiwa_liburan_dibatalkan|description": "Lala asks about your vacation plans that got canceled.",
    "kaiwa_beli_oleh_oleh_liburan|title": "Buying Vacation Souvenirs",
    "kaiwa_beli_oleh_oleh_liburan|description": "You're looking for regional souvenirs for your family.",
    "kaiwa_liburan_akhir_tahun|title": "Year-End Vacation Plans",
    "kaiwa_liburan_akhir_tahun|description": "Bayu asks about your year-end vacation plans.",
    "kaiwa_liburan_pantai|title": "Beach Vacation",
    "kaiwa_liburan_pantai|description": "You and a friend plan a beach vacation.",
    "kaiwa_liburan_backpacker|title": "Budget/Backpacker Travel",
    "kaiwa_liburan_backpacker|description": "Your friend gives tips for budget backpacker travel.",
    "kaiwa_ikut_tur_wisata|title": "Joining a Sightseeing Tour",
    "kaiwa_ikut_tur_wisata|description": "You sign up for a sightseeing tour around the city.",
    "kaiwa_cari_penginapan_murah|title": "Looking for Cheap Lodging",
    "kaiwa_cari_penginapan_murah|description": "You ask a tourist information staff member about cheap lodging.",
    "kaiwa_liburan_solo|title": "Solo Travel",
    "kaiwa_liburan_solo|description": "You prepare for your first solo vacation.",
    "kaiwa_tukar_uang_liburan|title": "Exchanging Money for Vacation",
    "kaiwa_tukar_uang_liburan|description": "You exchange money for yen before your trip to Japan.",
    "kaiwa_liburan_diperpanjang|title": "Extending a Vacation",
    "kaiwa_liburan_diperpanjang|description": "You decide to extend your hotel stay.",
    "kaiwa_kembali_dari_liburan|title": "Returning From Vacation",
    "kaiwa_kembali_dari_liburan|description": "Your friend welcomes you back from your vacation.",
    "kaiwa_camping_liburan|title": "Camping on Vacation",
    "kaiwa_camping_liburan|description": "You invite a friend to go camping on vacation.",
    "kaiwa_liburan_sahabat|title": "Vacationing With Your Best Friend",
    "kaiwa_liburan_sahabat|description": "Your best friend invites you on a trip together and plans the details.",
}
