# Canonical Kaiwa scenario/dialogue scope — the single source of truth
# generate_kaiwa_seed.py imports to know which themes/dialogues to write
# full content for, mirroring how particle_lists.py / bunpou_grammar_lists.py
# / kanji_char_lists.py lock their own module's scope.
#
# Kaiwa is organized in two layers: JLPT level (N5-N1, LEVEL_META below) ->
# scenario theme (Perkenalan, Di Restoran, ...) -> dialogue. Themes are
# still situational/thematic, not graded by grammar difficulty on their
# own — the level is what determines the vocabulary/grammar ceiling used
# within a theme's dialogues, not the theme's subject matter itself (e.g.
# "Di Restoran" could exist at N5 with simple ordering phrases, or in
# principle at a higher level with more nuanced language — this dataset
# currently only has N5 content, so that distinction is theoretical for
# now, not yet exercised).
#
# All content authored so far is N5. N4-N1 are locked in LEVEL_META as
# not-yet-authored levels — the level layer exists in the schema from day
# one, but there is deliberately no separate "PLANNED_LEVELS" list the way
# PLANNED_CATEGORIES works for themes, since a level with zero themes is
# already unambiguous (LEVEL_META entry present, available=False).

PERKENALAN_TITLES = [
    "Berkenalan dengan Teman Baru",
    "Menyapa di Pagi Hari",
    "Menanyakan Asal Negara",
    "Bertukar Nomor Telepon",
    "Menanyakan Umur",
    "Memperkenalkan Diri di Kelas Baru",
    "Menanyakan Pekerjaan",
    "Berkenalan di Pesta",
    "Menanyakan Alamat Rumah",
    "Berpisah Setelah Kenalan",
    "Menanyakan Bahasa yang Dikuasai",
    "Memperkenalkan Anggota Keluarga",
    "Menanyakan Kota Asal",
    "Bertemu Tetangga Baru",
    "Berkenalan di Acara Kampus",
    "Menanyakan Golongan Darah",
    "Memperkenalkan Diri Lewat Video Call",
    "Menanyakan Warna Favorit",
    "Berkenalan dengan Teman Sekamar Asrama",
    "Menanyakan Rencana Setelah Lulus",
    "Menanyakan Zodiak",
    "Bertukar Akun Media Sosial",
    "Menanyakan Makanan Favorit saat Kenalan",
    "Berkenalan di Klub Buku",
    "Menanyakan Kepribadian",
    "Berkenalan Lewat Teman Bersama",
    "Menanyakan Musim Favorit",
    "Berkenalan di Kelas Bahasa Jepang",
    "Menanyakan Hewan Peliharaan saat Kenalan",
    "Berkenalan di Bandara",
    "Menanyakan Jurusan Kuliah",
    "Berkenalan dengan Rekan Kerja Baru",
    "Menanyakan Cita-cita",
    "Berkenalan di Gym",
    "Menanyakan Minuman Favorit",
    "Berkenalan dengan Pasangan Teman",
    "Menanyakan Buku Favorit",
    "Berkenalan Setelah Pindah Sekolah",
    "Menanyakan Tinggi Badan",
    "Berpisah dengan Janji Bertemu Lagi",
]

RESTORAN_TITLES = [
    "Memesan Makanan di Restoran",
    "Meminta Bill / Membayar",
    "Menanyakan Menu Rekomendasi",
    "Memesan Minuman Tambahan",
    "Meminta Meja untuk Empat Orang",
    "Menanyakan Alergi Makanan",
    "Memesan Makanan Pedas",
    "Meminta Kotak untuk Dibawa Pulang",
    "Memuji Masakan ke Pelayan",
    "Reservasi Meja Lewat Telepon",
    "Memesan Makanan Vegetarian",
    "Duduk di Konter Sushi",
    "Memesan Paket Set Menu",
    "Mengganti Pesanan",
    "Menanyakan Jam Buka Restoran",
    "Memesan Antar / Delivery",
    "Komplain Pesanan yang Salah",
    "Merayakan Ulang Tahun di Restoran",
    "Makan di Restoran Keluarga dengan Anak",
    "Membayar Terpisah (Split Bill)",
    "Meminta Tambah Nasi",
    "Menanyakan Menu Halal",
    "Memesan Meja di Luar Ruangan",
    "Mencicipi Menu Baru Restoran",
    "Meminta Sendok Pengganti Sumpit",
    "Menanyakan Kandungan Alergen di Menu",
    "Memesan Hidangan Penutup",
    "Mengeluh Restoran Terlalu Berisik",
    "Makan di Restoran Prasmanan",
    "Menanyakan Wifi Restoran",
    "Membayar dengan Voucher Diskon",
    "Memesan Makanan untuk Dibawa Pulang",
    "Meminta Air Minum Gratis",
    "Restoran Penuh, Masuk Daftar Tunggu",
    "Menanyakan Menu Musiman",
    "Memesan Hidangan Pembuka",
    "Meminta Meja Bebas Rokok",
    "Menikmati Live Music di Restoran",
    "Makan di Restoran dengan Pemandangan",
    "Berpamitan dengan Pelayan Favorit",
]

STASIUN_TITLES = [
    "Membeli Tiket Kereta",
    "Menanyakan Peron/Jalur",
    "Menanyakan Jadwal Kereta",
    "Naik Kereta yang Salah",
    "Menanyakan Kereta Ekspres",
    "Kehilangan Barang di Kereta",
    "Membeli Kartu Kereta Isi Ulang",
    "Menanyakan Pintu Keluar Stasiun",
    "Naik Kereta Saat Jam Sibuk",
    "Bertanya Stasiun Transit",
    "Membeli Tiket Shinkansen",
    "Menanyakan Loker Penitipan Barang",
    "Terlambat Ketinggalan Kereta",
    "Menanyakan Gerbong Khusus Wanita",
    "Meminta Bantuan Membawa Koper",
    "Menanyakan Reservasi Kursi Kereta",
    "Bertanya Kereta Malam Terakhir",
    "Mengembalikan Tiket yang Salah Beli",
    "Menanyakan Akses untuk Kursi Roda",
    "Menanyakan Rute Tercepat",
    "Membeli Tiket Anak-anak",
    "Menanyakan Stasiun Terdekat dari Hotel",
    "Memilih Kelas Kereta Ekonomi atau Bisnis",
    "Menemukan Loket Informasi",
    "Menanyakan Aturan Membawa Sepeda di Kereta",
    "Kereta Berhenti Mendadak",
    "Menanyakan Jadwal Kereta Akhir Pekan",
    "Membeli Tiket Kereta Panorama",
    "Menanyakan Toilet di Stasiun",
    "Menunggu Kereta di Musim Dingin",
    "Menanyakan Tempat Duduk Kosong",
    "Membeli Tiket untuk Rombongan",
    "Menanyakan Cara Pakai Mesin Tiket Otomatis",
    "Terjebak di Pintu Kereta",
    "Menyewa Loker Ukuran Besar",
    "Menanyakan Jam Kereta Pertama",
    "Kehujanan Saat di Stasiun",
    "Menanyakan Denda Naik Tanpa Tiket",
    "Bertemu Teman Lama di Stasiun",
    "Menanyakan Nomor Gerbong",
]

BELANJA_TITLES = [
    "Menanyakan Harga Barang",
    "Mencoba Baju di Toko",
    "Membayar di Kasir",
    "Meminta Diskon",
    "Menukar Barang yang Rusak",
    "Mencari Ukuran yang Pas",
    "Membandingkan Dua Barang",
    "Bertanya Jam Buka Toko",
    "Membeli Oleh-oleh",
    "Membeli Barang Elektronik",
    "Mencari Barang di Rak",
    "Membeli Baju Musim Dingin",
    "Menanyakan Metode Pembayaran",
    "Membeli Sepatu Baru",
    "Membeli Hadiah untuk Teman",
    "Bertanya Barang Stok Habis",
    "Menggunakan Poin Member",
    "Membeli Buah di Pasar",
    "Menanyakan Garansi Barang",
    "Belanja Online, Ambil di Toko",
    "Membeli Buku di Toko Buku",
    "Menanyakan Cara Kembali Barang / Refund",
    "Membeli Barang Bekas di Toko Loak",
    "Menanyakan Ukuran Baju Anak",
    "Membeli Perlengkapan Sekolah",
    "Berbelanja di Pasar Malam",
    "Menanyakan Produk Ramah Lingkungan",
    "Membeli Tas Belanja Reusable",
    "Menanyakan Cara Pakai Produk Kecantikan",
    "Membeli Alat Masak",
    "Menanyakan Diskon Akhir Tahun",
    "Membeli Perhiasan",
    "Menanyakan Jam Antre di Kasir",
    "Menanyakan Cara Merawat Barang",
    "Membeli Bunga untuk Hadiah",
    "Menanyakan Ukuran Internasional vs Jepang",
    "Membeli Barang Custom/Pesanan Khusus",
    "Menanyakan Cara Membayar dengan QR Code",
    "Membeli Payung karena Hujan Mendadak",
    "Menyewa Kostum untuk Acara",
]

ARAH_JALAN_TITLES = [
    "Menanyakan Jalan ke Stasiun",
    "Menanyakan Jalan ke Toilet Umum",
    "Menanyakan Jarak Tempuh",
    "Menanyakan Jalan ke Rumah Sakit",
    "Tersesat di Kota Baru",
    "Menanyakan Arah dengan Peta",
    "Menanyakan Jalan ke Supermarket",
    "Menanyakan Naik Kendaraan Apa",
    "Menanyakan Jalan Pintas",
    "Berterima Kasih Setelah Diberi Arah",
    "Menanyakan Jalan ke Bank",
    "Menanyakan Jalan ke Taman Kota",
    "Menanyakan Arah dengan Landmark",
    "Menanyakan Jalan ke Kantor Polisi",
    "Bertanya Arah Malam Hari",
    "Menanyakan Jalan Memutar Karena Ditutup",
    "Menunjukkan Arah ke Turis Lain",
    "Menanyakan Jalan ke Perpustakaan",
    "Bertanya Arah dengan Aplikasi Peta HP",
    "Menanyakan Jalan Naik Sepeda",
    "Menanyakan Jalan ke Kuil",
    "Menanyakan Jalan ke Kolam Renang",
    "Bertanya Arah ke Pantai",
    "Menanyakan Naik Tangga atau Lift",
    "Bertanya Arah ke Toko Oleh-oleh",
    "Menanyakan Jarak Tempuh dengan Mobil",
    "Tersesat Membawa Barang Berat",
    "Menanyakan Jalan ke Gedung Pemerintahan",
    "Bertanya Arah Sambil Membawa Anak",
    "Menanyakan Jalan ke Pasar Tradisional",
    "Arah ke Tempat Karaoke",
    "Menanyakan Rute Bebas Tangga",
    "Bertanya Arah dengan Menunjukkan Foto",
    "Menanyakan Jalan ke Gym",
    "Salah Arah karena GPS Error",
    "Menanyakan Jalan Pulang dari Pesta",
    "Bertanya Arah ke Rumah Teman Sekelas",
    "Menanyakan Jalan Saat Angin Kencang",
    "Menunjukkan Arah ke Kurir Paket",
    "Berterima Kasih Setelah Diantar",
]

SEKOLAH_TITLES = [
    "Menyapa Guru di Kelas",
    "Menanyakan Pekerjaan Rumah (PR)",
    "Meminjam Alat Tulis",
    "Bertanya Jadwal Pelajaran",
    "Meminta Izin ke Toilet",
    "Terlambat Masuk Kelas",
    "Mengajak Belajar Kelompok",
    "Menanyakan Nilai Ujian",
    "Membolos Karena Sakit",
    "Berpisah di Akhir Semester",
    "Mengikuti Ekstrakurikuler",
    "Bertanya Tugas Kelompok",
    "Meminta Izin Pulang Cepat",
    "Bertanya Ruang Kelas",
    "Makan Siang di Kantin Sekolah",
    "Mempersiapkan Ujian Akhir",
    "Bertanya Guru Pengganti",
    "Ikut Study Tour / Karyawisata",
    "Mengembalikan Buku Perpustakaan Sekolah",
    "Bertanya Tugas Piket Kelas",
    "Menyapa Teman Sebelum Kelas Dimulai",
    "Bertanya Materi yang Terlewat",
    "Meminjam Buku Catatan",
    "Ikut Study Tour Sehari ke Museum",
    "Bertanya Jadwal Ujian Semester",
    "Menjadi Ketua Kelas",
    "Meminta Izin Sakit ke Guru saat di Kelas",
    "Ikut Lomba Sekolah",
    "Menanyakan Tugas Rumah Tambahan",
    "Membersihkan Kelas Bersama",
    "Bertanya Alasan Nilai Turun",
    "Mengikuti Klub Debat",
    "Menanyakan Loker Sekolah",
    "Mengundurkan Diri dari Ekstrakurikuler",
    "Menjenguk Teman Sakit di Rumah",
    "Mengikuti Kelas Tambahan/Les",
    "Menyiapkan Presentasi Kelompok",
    "Bertanya Aturan Seragam Sekolah",
    "Merayakan Kelulusan",
    "Bertukar Kontak dengan Teman Sekelas",
]

CUACA_BASA_BASI_TITLES = [
    "Membicarakan Cuaca",
    "Menanyakan Kegiatan Akhir Pekan",
    "Berpamitan",
    "Membicarakan Musim Favorit",
    "Basa-basi Menunggu Bus",
    "Menanyakan Kabar Setelah Lama Tidak Bertemu",
    "Membicarakan Rencana Malam Ini",
    "Basa-basi Tentang Pekerjaan Rumah Tangga",
    "Membicarakan Berita Terkini",
    "Menyapa Tetangga Baru",
    "Membicarakan Hujan Deras",
    "Basa-basi soal Hobi Baru",
    "Mengomentari Angin Kencang",
    "Basa-basi di Lift",
    "Membicarakan Suhu Dingin",
    "Basa-basi Menunggu Hujan Reda",
    "Membicarakan Rencana Liburan Musim Panas",
    "Basa-basi tentang Kesehatan",
    "Mengomentari Bunga Bermekaran",
    "Basa-basi di Antrean",
]

RUMAH_SAKIT_TITLES = [
    "Menjelaskan Sakit ke Dokter",
    "Membuat Janji Temu",
    "Membeli Obat di Apotek",
    "Menjelaskan Gejala Flu",
    "Menanyakan Efek Samping Obat",
    "Kontrol Setelah Sakit",
    "Mengantar Keluarga Berobat",
    "Menanyakan Biaya Berobat",
    "Cedera Ringan Saat Olahraga",
    "Memeriksa Kesehatan Rutin",
    "Mendaftar sebagai Pasien Baru",
    "Menjelaskan Alergi Obat",
    "Memeriksa Gigi ke Dokter Gigi",
    "Menjenguk Teman di Rumah Sakit",
    "Meminta Surat Keterangan Sakit",
    "Bertanya Jadwal Praktik Dokter",
    "Cek Mata di Dokter Spesialis Mata",
    "Vaksinasi di Rumah Sakit",
    "Menanyakan Ruang Rawat Inap",
    "Konsultasi Sakit Perut",
]

HOBI_TITLES = [
    "Menanyakan Hobi Teman",
    "Mengajak Bermain Bersama",
    "Membicarakan Musik Favorit",
    "Membicarakan Film Favorit",
    "Belajar Hobi Baru",
    "Mengoleksi Sesuatu",
    "Membicarakan Buku yang Sedang Dibaca",
    "Ikut Klub Hobi",
    "Berbagi Foto Hasil Hobi",
    "Mengajak Ikut Komunitas Hobi",
    "Bermain Alat Musik",
    "Menanam Tanaman Hias",
    "Memasak sebagai Hobi",
    "Mendaki Gunung",
    "Bermain Board Game",
    "Menulis Diary/Jurnal",
    "Merajut/Menyulam",
    "Bermain Game Online",
    "Berkebun di Akhir Pekan",
    "Fotografi Alam",
]

TELEPON_TITLES = [
    "Menerima Telepon",
    "Menelepon Teman",
    "Meninggalkan Pesan",
    "Menelepon Layanan Pelanggan",
    "Salah Sambung Telepon",
    "Menelepon untuk Membatalkan Janji",
    "Menelepon Orang Tua",
    "Menutup Telepon dengan Sopan",
    "Telepon Terputus",
    "Menelepon untuk Mengucapkan Selamat",
    "Menelepon untuk Memesan Makanan",
    "Meminta Bantuan Lewat Telepon",
    "Menelepon Dokter untuk Konsultasi",
    "Baterai HP Hampir Habis",
    "Mengingatkan Adik Lewat Telepon",
    "Video Call dengan Teman Lama",
    "Menelepon Bengkel Motor",
    "Menghubungi Kantor untuk Izin Sakit",
    "Menelepon untuk Konfirmasi Reservasi",
    "Menerima Telepon Spam/Promosi",
]

TRANSPORTASI_TITLES = [
    "Naik Bus",
    "Memanggil Taksi",
    "Menanyakan Ongkos",
    "Naik Kereta Bawah Tanah",
    "Menyewa Sepeda",
    "Naik Pesawat",
    "Ketinggalan Bus",
    "Menanyakan Jam Terakhir Transportasi",
    "Naik Ojek/Ride Sharing",
    "Menanyakan Rute Terbaik",
    "Naik Kapal Feri",
    "Menyewa Mobil",
    "Naik Bus Malam Antar Kota",
    "Menanyakan Tempat Parkir",
    "Naik Becak/Delman",
    "Terjebak Macet",
    "Menanyakan Kursi Prioritas",
    "Naik Trem/Monorel",
    "Membawa Barang Besar di Transportasi Umum",
    "Turun di Halte yang Salah",
]

KANTOR_POS_TITLES = [
    "Mengirim Surat",
    "Mengirim Paket",
    "Membeli Perangko",
    "Mengambil Paket yang Tertahan",
    "Menanyakan Lama Pengiriman",
    "Mengirim Uang Lewat Pos",
    "Membuka Kotak Pos",
    "Komplain Paket Rusak",
    "Mengirim Barang Internasional",
    "Menanyakan Asuransi Pengiriman",
    "Mengecek Nomor Resi",
    "Mengirim Kartu Pos",
    "Menanyakan Jam Buka Kantor Pos",
    "Mengubah Alamat Pengiriman",
    "Mengirim Dokumen Penting",
    "Membungkus Paket di Kantor Pos",
    "Menerima Paket COD",
    "Kehilangan Bukti Pengiriman",
    "Mengirim Paket Barang Pecah Belah",
    "Membuat Akun Pengiriman Online",
]

LIBURAN_TITLES = [
    "Membicarakan Rencana Liburan",
    "Mengajak Berlibur Bersama",
    "Cerita Setelah Liburan",
    "Memesan Hotel untuk Liburan",
    "Membicarakan Tempat Wisata",
    "Packing untuk Liburan",
    "Liburan Bersama Keluarga",
    "Liburan yang Dibatalkan",
    "Membeli Oleh-oleh Liburan",
    "Rencana Liburan Akhir Tahun",
    "Liburan ke Pantai",
    "Liburan Hemat / Backpacker",
    "Ikut Tur Wisata",
    "Mencari Penginapan Murah",
    "Liburan Solo (Sendirian)",
    "Menukar Uang untuk Liburan",
    "Liburan yang Diperpanjang",
    "Kembali dari Liburan",
    "Camping saat Liburan",
    "Liburan Bersama Sahabat",
]

KELUARGA_TITLES = [
    "Memperkenalkan Anggota Keluarga",
    "Menanyakan Jumlah Saudara",
    "Membicarakan Pekerjaan Orang Tua",
    "Menceritakan Kebiasaan Keluarga",
    "Membicarakan Anggota Keluarga yang Jauh",
    "Merayakan Ulang Tahun Keluarga",
    "Membicarakan Hewan Peliharaan Keluarga",
    "Menjenguk Kakek Nenek",
    "Membicarakan Rumah Keluarga",
    "Cerita Masa Kecil",
    "Membantu Pekerjaan Rumah Bersama Keluarga",
    "Merencanakan Makan Malam Keluarga",
    "Menjadi Anak Sulung/Bungsu",
    "Membicarakan Kemiripan dengan Orang Tua",
    "Membantu Adik Belajar",
    "Video Call dengan Keluarga di Kampung",
    "Membicarakan Aturan di Rumah",
    "Merencanakan Reuni Keluarga Besar",
    "Menceritakan Tradisi Keluarga",
    "Membicarakan Sepupu",
]

BANK_TITLES = [
    "Membuka Rekening",
    "Menukar Uang",
    "Menarik Uang di ATM",
    "Mengecek Saldo Rekening",
    "Mengajukan Pinjaman",
    "Mentransfer Uang",
    "Melaporkan Kartu Hilang",
    "Membuat Kartu Kredit",
    "Menyetor Uang Tunai",
    "Menanyakan Suku Bunga",
    "Mengganti PIN Kartu ATM",
    "Membuka Rekening Deposito",
    "Mengaktifkan Mobile Banking",
    "Menutup Rekening Bank",
    "Menanyakan Biaya Administrasi Bulanan",
    "Mengambil Cek/Giro",
    "Membuka Rekening Bersama (Joint Account)",
    "Menukar Uang Rusak/Robek",
    "Mentransfer Uang ke Luar Negeri",
    "Konsultasi Investasi ke Bank",
]

OLAHRAGA_TITLES = [
    "Mengajak Olahraga Bersama",
    "Menanyakan Olahraga Favorit",
    "Menonton Pertandingan",
    "Mengajak Lari Pagi",
    "Bergabung dengan Klub Olahraga",
    "Membeli Perlengkapan Olahraga",
    "Menonton Latihan Tim",
    "Mengikuti Kelas Yoga",
    "Menanyakan Aturan Kolam Renang",
    "Mendaftar Lomba Lari",
    "Bermain Bulu Tangkis",
    "Ikut Kelas Renang",
    "Menonton Olimpiade di TV",
    "Membicarakan Cedera Ringan",
    "Ikut Turnamen Sekolah",
    "Bersepeda Santai Akhir Pekan",
    "Latihan Beban di Gym",
    "Menjadi Suporter Tim Favorit",
    "Mengikuti Kelas Bela Diri",
    "Bermain Tenis Meja",
]

BIOSKOP_TITLES = [
    "Membeli Tiket Bioskop",
    "Memilih Kursi",
    "Membicarakan Film Setelah Nonton",
    "Memesan Tiket Online",
    "Membeli Popcorn dan Minuman",
    "Terlambat Datang ke Bioskop",
    "Memilih Jenis Film",
    "Menonton Film 3D",
    "Mencari Toilet di Bioskop",
    "Mengembalikan Tiket",
    "Menonton Midnight Premiere",
    "Duduk di Bioskop VIP",
    "Membawa Anak Nonton Bioskop",
    "Mengajak Nonton Bareng",
    "Bertanya Rating Umur Film",
    "Kehilangan Tiket Bioskop",
    "Menonton Film Subtitle vs Dubbing",
    "Bioskop Penuh, Menunggu Jadwal Berikutnya",
    "Menonton Marathon Film",
    "Bertanya Diskon Tiket Pelajar",
]

# category_id -> (display name, icon emoji, JLPT level key)
CATEGORY_META = {
    "perkenalan": ("Perkenalan", "👋", "N5"),
    "restoran": ("Di Restoran", "🍽️", "N5"),
    "stasiun": ("Di Stasiun", "🚉", "N5"),
    "belanja": ("Belanja", "🛍️", "N5"),
    "arah_jalan": ("Menanyakan Arah", "🧭", "N5"),
    "sekolah": ("Di Sekolah", "🏫", "N5"),
    "cuaca_basa_basi": ("Cuaca & Basa-basi", "☁️", "N5"),
    "rumah_sakit": ("Di Rumah Sakit", "🏥", "N5"),
    "hobi": ("Hobi", "🎨", "N5"),
    "telepon": ("Telepon", "☎️", "N5"),
    "transportasi": ("Transportasi", "🚌", "N5"),
    "kantor_pos": ("Di Kantor Pos", "📮", "N5"),
    "liburan": ("Rencana Liburan", "🏖️", "N5"),
    "keluarga": ("Keluarga", "👨‍👩‍👧", "N5"),
    "bank": ("Di Bank", "🏦", "N5"),
    "olahraga": ("Olahraga", "⚽", "N5"),
    "bioskop": ("Di Bioskop", "🎬", "N5"),
}

# category_id -> locked dialogue title list, for themes with real content.
AVAILABLE_CATEGORIES = {
    "perkenalan": PERKENALAN_TITLES,
    "restoran": RESTORAN_TITLES,
    "stasiun": STASIUN_TITLES,
    "belanja": BELANJA_TITLES,
    "arah_jalan": ARAH_JALAN_TITLES,
    "sekolah": SEKOLAH_TITLES,
    "cuaca_basa_basi": CUACA_BASA_BASI_TITLES,
    "rumah_sakit": RUMAH_SAKIT_TITLES,
    "hobi": HOBI_TITLES,
    "telepon": TELEPON_TITLES,
    "transportasi": TRANSPORTASI_TITLES,
    "kantor_pos": KANTOR_POS_TITLES,
    "liburan": LIBURAN_TITLES,
    "keluarga": KELUARGA_TITLES,
    "bank": BANK_TITLES,
    "olahraga": OLAHRAGA_TITLES,
    "bioskop": BIOSKOP_TITLES,
}

# (id, display name, icon emoji) for themes with no dataset yet —
# registered in _categories.json as available: False. Empty for now.
PLANNED_CATEGORIES = []

# level_id -> (display name, available)
LEVEL_META = {
    "N5": ("N5", True),
    "N4": ("N4", False),
    "N3": ("N3", False),
    "N2": ("N2", False),
    "N1": ("N1", False),
}

_ALL_TITLE_LISTS = {
    "PERKENALAN_TITLES": PERKENALAN_TITLES,
    "RESTORAN_TITLES": RESTORAN_TITLES,
    "STASIUN_TITLES": STASIUN_TITLES,
    "BELANJA_TITLES": BELANJA_TITLES,
    "ARAH_JALAN_TITLES": ARAH_JALAN_TITLES,
    "SEKOLAH_TITLES": SEKOLAH_TITLES,
    "CUACA_BASA_BASI_TITLES": CUACA_BASA_BASI_TITLES,
    "RUMAH_SAKIT_TITLES": RUMAH_SAKIT_TITLES,
    "HOBI_TITLES": HOBI_TITLES,
    "TELEPON_TITLES": TELEPON_TITLES,
    "TRANSPORTASI_TITLES": TRANSPORTASI_TITLES,
    "KANTOR_POS_TITLES": KANTOR_POS_TITLES,
    "LIBURAN_TITLES": LIBURAN_TITLES,
    "KELUARGA_TITLES": KELUARGA_TITLES,
    "BANK_TITLES": BANK_TITLES,
    "OLAHRAGA_TITLES": OLAHRAGA_TITLES,
    "BIOSKOP_TITLES": BIOSKOP_TITLES,
}
for _name, _titles in _ALL_TITLE_LISTS.items():
    assert len(_titles) >= 3, f"{_name} should have at least 3 dialogues, has {len(_titles)}"
    assert len(_titles) == len(set(_titles)), f"duplicate title in {_name}"

assert set(CATEGORY_META.keys()) == set(AVAILABLE_CATEGORIES.keys()), (
    "CATEGORY_META and AVAILABLE_CATEGORIES must cover exactly the same theme ids"
)

_planned_ids = [c[0] for c in PLANNED_CATEGORIES]
assert len(_planned_ids) == len(set(_planned_ids)), "duplicate id in PLANNED_CATEGORIES"
assert set(_planned_ids).isdisjoint(AVAILABLE_CATEGORIES.keys()), (
    "a planned category id collides with an available one"
)

assert set(LEVEL_META.keys()) == {"N5", "N4", "N3", "N2", "N1"}, "LEVEL_META must cover all 5 JLPT levels"
_used_levels = {level for _, _, level in CATEGORY_META.values()}
assert _used_levels.issubset(LEVEL_META.keys()), "a theme references an unknown level"
