"""
kaiwa_meaning_en.py

Locked source of truth for the English translations of Kaiwa dialogue
content: KaiwaEntry.titleEn/descriptionEn, KaiwaLine.npcLine.translationEn,
KaiwaAnswerOption.translationEn. apply_kaiwa_meaning_en.py reads this and
patches assets/data/kaiwa_data.json, so translations live in exactly one
place.

Key format (four content kinds share one dict, disambiguated by suffix):
    "{entry_id}|title"              -> the dialogue's title
    "{entry_id}|description"        -> the dialogue's one-line description
    "{entry_id}|{line_id}|npc"      -> an NPC turn's sentence translation
    "{entry_id}|{line_id}|opt{i}"   -> the i-th (0-based) answer option's
                                        translation, for a user turn

line_id is only unique within its own entry (verified dataset-wide: no
entry repeats a line id), so it's always paired with entry_id. opt{i} is
the option's position in its own line's authored options list (stable —
shuffling for display happens at render time in a copy, never in the
data).

Scope note: npcLine.translationEn is not currently rendered anywhere
(KaiwaDialogueScreen shows NPC turns as image + speak button only, no
on-screen text — see CLAUDE.md's Kaiwa section) but is translated anyway
for completeness, since the field exists on the model and may be used
later. option translations ARE rendered today, right after the learner
picks the correct answer.

Must be re-applied after generate_kaiwa_seed.py regenerates the dataset.

STATUS: in progress. Total scope, counted directly from
    assets/data/kaiwa_data.json (1,700 real dialogues, 0 placeholders):
        titles:            1,700
        descriptions:      1,700
        npc lines:         7,468
        answer options:   23,151
        TOTAL:            34,019
    Order: titles + descriptions first (3,400 - smallest, highest
    visibility, shown in every Home/Level/Category list), then answer
    options (23,151 - the actual practice content, rendered after a
    correct tap), then npc lines (7,468 - currently unrendered, lowest
    priority) last. Given the scale, expect this to span many sessions;
    batch and commit incrementally the same way N1 kanji glosses did
    (scripts/kanji_word_meaning_en.py's STATUS block has the full
    history of that approach) so no single interruption loses much work.

    Titles+descriptions: batch 1/? done (500/3,400 rows = 250/1,700
    entries, alphabetical-ish order matching the dump). Remaining:
    entries 251-1,700 (rows 501-3,400 of the titles+descriptions dump).

    Dump a phase's source rows with, e.g. (titles+descriptions):
        python -c "import json; d=json.load(open('assets/data/kaiwa_data.json', encoding='utf-8')); [print(f\"{e['id']}|title :: {e['title']}\") or print(f\"{e['id']}|description :: {e['description']}\") for e in d]"
    or (answer options):
        python -c "import json; d=json.load(open('assets/data/kaiwa_data.json', encoding='utf-8')); [print(f\"{e['id']}|{l['id']}|opt{i} :: {o['translation']}\") for e in d for l in e['lines'] for i, o in enumerate(l.get('options', []))]"
    or (npc lines):
        python -c "import json; d=json.load(open('assets/data/kaiwa_data.json', encoding='utf-8')); [print(f\"{e['id']}|{l['id']}|npc :: {l['npcLine']['translation']}\") for e in d for l in e['lines'] if l.get('npcLine')]"

Style: translate the Indonesian gloss as it stands - natural
conversational English, no new senses added.
"""

KAIWA_MEANING_EN = {
    # ---------------- titles+descriptions batch 1 ----------------
    "kaiwa_kenalan_teman_baru|title": "Meeting a New Friend",
    "kaiwa_kenalan_teman_baru|description": "Yuki greets you and introduces herself for the first time.",
    "kaiwa_sapa_pagi_hari|title": "Morning Greetings",
    "kaiwa_sapa_pagi_hari|description": "Mr. Tanaka, your neighbor, greets you in the morning before you leave for school.",
    "kaiwa_tanya_asal_negara|title": "Asking Where You're From",
    "kaiwa_tanya_asal_negara|description": "Sari asks about your home country and your favorite food there.",
    "kaiwa_tukar_nomor|title": "Exchanging Phone Numbers",
    "kaiwa_tukar_nomor|description": "You and Yuki exchange phone numbers.",
    "kaiwa_tanya_umur|title": "Asking Your Age",
    "kaiwa_tanya_umur|description": "Sora asks your age.",
    "kaiwa_kenalan_kelas_baru|title": "Introducing Yourself in a New Class",
    "kaiwa_kenalan_kelas_baru|description": "On your first day in a new class, you introduce yourself.",
    "kaiwa_tanya_pekerjaan|title": "Asking About Someone's Job",
    "kaiwa_tanya_pekerjaan|description": "You ask Mr. Hiro, whom you just met, about his job.",
    "kaiwa_kenalan_pesta|title": "Meeting Someone at a Party",
    "kaiwa_kenalan_pesta|description": "You meet Mei, someone new, at a party.",
    "kaiwa_tanya_alamat|title": "Asking for a Home Address",
    "kaiwa_tanya_alamat|description": "Joko, your new friend, asks where you live.",
    "kaiwa_pisah_kenalan|title": "Saying Goodbye After Meeting",
    "kaiwa_pisah_kenalan|description": "After chatting for a while, you and Fitri have to part ways.",
    "kaiwa_tanya_bahasa|title": "Asking What Languages You Speak",
    "kaiwa_tanya_bahasa|description": "Haruto asks what languages you can speak.",
    "kaiwa_kenalan_keluarga|title": "Introducing Family Members",
    "kaiwa_kenalan_keluarga|description": "You show a family photo to Dewi.",
    "kaiwa_tanya_kota_asal|title": "Asking Your Hometown",
    "kaiwa_tanya_kota_asal|description": "Rian asks your hometown in Indonesia.",
    "kaiwa_kenalan_tetangga_baru|title": "Meeting a New Neighbor",
    "kaiwa_kenalan_tetangga_baru|description": "Mrs. Yamada, your new neighbor, introduces herself.",
    "kaiwa_kenalan_acara_kampus|title": "Meeting Someone at a Campus Event",
    "kaiwa_kenalan_acara_kampus|description": "Aiko starts a conversation with you at a campus orientation event.",
    "kaiwa_tanya_golongan_darah|title": "Asking Your Blood Type",
    "kaiwa_tanya_golongan_darah|description": "Bram asks your blood type, a typical light Japanese small-talk topic.",
    "kaiwa_kenalan_video_call|title": "Introducing Yourself Over Video Call",
    "kaiwa_kenalan_video_call|description": "Sakura, your new pen pal, invites you to a video call for the first time.",
    "kaiwa_tanya_warna_favorit|title": "Asking Your Favorite Color",
    "kaiwa_tanya_warna_favorit|description": "Nina asks your favorite color and why.",
    "kaiwa_kenalan_teman_sekamar|title": "Meeting Your Dorm Roommate",
    "kaiwa_kenalan_teman_sekamar|description": "Kenji, your new dorm roommate, introduces himself.",
    "kaiwa_tanya_rencana_lulus|title": "Asking Your Plans After Graduation",
    "kaiwa_tanya_rencana_lulus|description": "Lestari asks your plans after finishing school.",
    "kaiwa_tanya_zodiak|title": "Asking Your Zodiac Sign",
    "kaiwa_tanya_zodiak|description": "Rani asks your zodiac sign.",
    "kaiwa_tukar_medsos|title": "Exchanging Social Media Accounts",
    "kaiwa_tukar_medsos|description": "You and Kenji exchange social media accounts.",
    "kaiwa_tanya_makanan_favorit_kenalan|title": "Asking Your Favorite Food While Getting Acquainted",
    "kaiwa_tanya_makanan_favorit_kenalan|description": "Dian asks your favorite food.",
    "kaiwa_kenalan_klub_buku|title": "Meeting Someone at a Book Club",
    "kaiwa_kenalan_klub_buku|description": "Mira greets you at the book club for the first time.",
    "kaiwa_tanya_kepribadian|title": "Asking About Your Personality",
    "kaiwa_tanya_kepribadian|description": "Sinta asks about your personality.",
    "kaiwa_kenalan_lewat_teman|title": "Meeting Someone Through a Mutual Friend",
    "kaiwa_kenalan_lewat_teman|description": "Andi introduces you to his friend, Hiro.",
    "kaiwa_tanya_musim_favorit_kenalan|title": "Asking Your Favorite Season",
    "kaiwa_tanya_musim_favorit_kenalan|description": "Yudi asks your favorite season.",
    "kaiwa_kenalan_kelas_bahasa|title": "Meeting Someone in Japanese Class",
    "kaiwa_kenalan_kelas_bahasa|description": "You're introduced as a new student in Japanese class.",
    "kaiwa_tanya_hewan_peliharaan_kenalan|title": "Asking About Pets While Getting Acquainted",
    "kaiwa_tanya_hewan_peliharaan_kenalan|description": "Wati asks about your pet.",
    "kaiwa_kenalan_bandara|title": "Meeting Someone at the Airport",
    "kaiwa_kenalan_bandara|description": "A Japanese tourist strikes up a conversation with you at the airport.",
    "kaiwa_tanya_jurusan_kuliah|title": "Asking Your College Major",
    "kaiwa_tanya_jurusan_kuliah|description": "Farid asks your college major.",
    "kaiwa_kenalan_rekan_kerja|title": "Meeting a New Coworker",
    "kaiwa_kenalan_rekan_kerja|description": "Mr. Yamamoto welcomes you on your first day at work.",
    "kaiwa_tanya_cita_cita|title": "Asking About Your Dream Career",
    "kaiwa_tanya_cita_cita|description": "Lina asks your dream career.",
    "kaiwa_kenalan_gym|title": "Meeting Someone at the Gym",
    "kaiwa_kenalan_gym|description": "Rio greets you at the gym for the first time.",
    "kaiwa_tanya_minuman_favorit|title": "Asking Your Favorite Drink",
    "kaiwa_tanya_minuman_favorit|description": "Bella asks your favorite drink.",
    "kaiwa_kenalan_pasangan_teman|title": "Meeting a Friend's Partner",
    "kaiwa_kenalan_pasangan_teman|description": "Sari introduces her boyfriend, Dian, to you.",
    "kaiwa_tanya_buku_favorit|title": "Asking Your Favorite Book",
    "kaiwa_tanya_buku_favorit|description": "Ilham asks your favorite book.",
    "kaiwa_kenalan_pindah_sekolah|title": "Meeting New People After Changing Schools",
    "kaiwa_kenalan_pindah_sekolah|description": "Your first day at a new school after transferring.",
    "kaiwa_tanya_tinggi_badan|title": "Asking Your Height",
    "kaiwa_tanya_tinggi_badan|description": "Your friend asks your height.",
    "kaiwa_janji_bertemu_lagi|title": "Parting With a Promise to Meet Again",
    "kaiwa_janji_bertemu_lagi|description": "You and your new friend promise to meet again next week.",
    "kaiwa_pesan_makanan|title": "Ordering Food at a Restaurant",
    "kaiwa_pesan_makanan|description": "You order food and drinks from the restaurant server.",
    "kaiwa_minta_bill|title": "Asking for the Bill / Paying",
    "kaiwa_minta_bill|description": "You've finished eating and want to pay.",
    "kaiwa_menu_rekomendasi|title": "Asking for a Menu Recommendation",
    "kaiwa_menu_rekomendasi|description": "You're unsure what to order and ask the server for a recommendation.",
    "kaiwa_pesan_minuman_tambahan|title": "Ordering an Extra Drink",
    "kaiwa_pesan_minuman_tambahan|description": "You order an extra drink while eating.",
    "kaiwa_meja_empat_orang|title": "Requesting a Table for Four",
    "kaiwa_meja_empat_orang|description": "You and your friends arrive to eat as a group of four.",
    "kaiwa_tanya_alergi|title": "Mentioning a Food Allergy",
    "kaiwa_tanya_alergi|description": "You tell the server about your food allergy.",
    "kaiwa_makanan_pedas|title": "Ordering Spicy Food",
    "kaiwa_makanan_pedas|description": "You like spicy food and ask about the menu's spice level.",
    "kaiwa_bungkus_sisa|title": "Asking for a To-Go Box",
    "kaiwa_bungkus_sisa|description": "You have leftover food and ask to have it packed.",
    "kaiwa_puji_masakan|title": "Complimenting the Food to the Server",
    "kaiwa_puji_masakan|description": "You compliment the dish you just ate.",
    "kaiwa_reservasi_telepon|title": "Making a Table Reservation by Phone",
    "kaiwa_reservasi_telepon|description": "You call the restaurant to reserve a table.",
    "kaiwa_pesan_vegetarian|title": "Ordering Vegetarian Food",
    "kaiwa_pesan_vegetarian|description": "You ask the server about vegetarian menu options.",
    "kaiwa_duduk_konter_sushi|title": "Sitting at the Sushi Counter",
    "kaiwa_duduk_konter_sushi|description": "You eat sushi right in front of the chef at the counter.",
    "kaiwa_pesan_set_menu|title": "Ordering a Set Menu",
    "kaiwa_pesan_set_menu|description": "You order a full set menu.",
    "kaiwa_ganti_pesanan|title": "Changing Your Order",
    "kaiwa_ganti_pesanan|description": "You want to change an order you've already placed.",
    "kaiwa_tanya_jam_buka|title": "Asking the Restaurant's Opening Hours",
    "kaiwa_tanya_jam_buka|description": "You ask the server about the restaurant's operating hours.",
    "kaiwa_pesan_delivery|title": "Ordering Delivery",
    "kaiwa_pesan_delivery|description": "You call the restaurant to order food delivery.",
    "kaiwa_komplain_pesanan_salah|title": "Complaining About a Wrong Order",
    "kaiwa_komplain_pesanan_salah|description": "Your order arrives different from what you asked for.",
    "kaiwa_rayakan_ulang_tahun|title": "Celebrating a Birthday at a Restaurant",
    "kaiwa_rayakan_ulang_tahun|description": "You call the restaurant to arrange a birthday surprise.",
    "kaiwa_restoran_keluarga|title": "Eating at a Family Restaurant With a Child",
    "kaiwa_restoran_keluarga|description": "You're eating with a young child and need a special chair.",
    "kaiwa_bayar_terpisah|title": "Paying Separately (Splitting the Bill)",
    "kaiwa_bayar_terpisah|description": "You and your friend want to split the bill.",
    "kaiwa_tambah_nasi|title": "Asking for More Rice",
    "kaiwa_tambah_nasi|description": "You ask the server for a rice refill.",
    "kaiwa_tanya_halal|title": "Asking About Halal Menu Options",
    "kaiwa_tanya_halal|description": "You ask the restaurant server about halal menu options.",
    "kaiwa_meja_luar|title": "Requesting an Outdoor Table",
    "kaiwa_meja_luar|description": "You ask for an outdoor table with a view.",
    "kaiwa_cicip_menu_baru|title": "Trying the Restaurant's New Menu",
    "kaiwa_cicip_menu_baru|description": "The server offers a newly launched menu item.",
    "kaiwa_minta_sendok|title": "Asking for a Spoon Instead of Chopsticks",
    "kaiwa_minta_sendok|description": "You ask for a spoon because you're not used to chopsticks.",
    "kaiwa_tanya_kandungan_alergen|title": "Asking About Allergens in the Menu",
    "kaiwa_tanya_kandungan_alergen|description": "You ask about allergens before ordering.",
    "kaiwa_pesan_dessert|title": "Ordering Dessert",
    "kaiwa_pesan_dessert|description": "You order dessert after dinner.",
    "kaiwa_restoran_berisik|title": "Complaining the Restaurant Is Too Noisy",
    "kaiwa_restoran_berisik|description": "You ask for a quieter table.",
    "kaiwa_restoran_buffet|title": "Eating at a Buffet Restaurant",
    "kaiwa_restoran_buffet|description": "You ask about the buffet's price and rules.",
    "kaiwa_tanya_wifi_restoran|title": "Asking About the Restaurant's Wi-Fi",
    "kaiwa_tanya_wifi_restoran|description": "You ask about the restaurant's Wi-Fi and password.",
    "kaiwa_bayar_voucher|title": "Paying With a Discount Voucher",
    "kaiwa_bayar_voucher|description": "You pay using a discount coupon.",
    "kaiwa_pesan_take_away|title": "Ordering Food to Go",
    "kaiwa_pesan_take_away|description": "You order food to be packed to take home.",
    "kaiwa_minta_air_gratis|title": "Asking for Free Drinking Water",
    "kaiwa_minta_air_gratis|description": "You ask the server for plain water.",
    "kaiwa_restoran_waiting_list|title": "Restaurant Full, Joining the Waitlist",
    "kaiwa_restoran_waiting_list|description": "The restaurant is full and you join the waiting list.",
    "kaiwa_menu_musiman|title": "Asking About the Seasonal Menu",
    "kaiwa_menu_musiman|description": "You ask about this season's special menu.",
    "kaiwa_pesan_appetizer|title": "Ordering an Appetizer",
    "kaiwa_pesan_appetizer|description": "You order an appetizer before the main course.",
    "kaiwa_meja_non_smoking|title": "Requesting a Non-Smoking Table",
    "kaiwa_meja_non_smoking|description": "You ask for a table in the non-smoking area.",
    "kaiwa_live_music_restoran|title": "Enjoying Live Music at a Restaurant",
    "kaiwa_live_music_restoran|description": "The server tells you about tonight's live music.",
    "kaiwa_restoran_pemandangan|title": "Eating at a Restaurant With a View",
    "kaiwa_restoran_pemandangan|description": "You ask for a table with an ocean view.",
    "kaiwa_pamit_pelayan_favorit|title": "Saying Goodbye to Your Favorite Server",
    "kaiwa_pamit_pelayan_favorit|description": "You say goodbye to a server you've gotten to know well.",
    "kaiwa_beli_tiket|title": "Buying a Train Ticket",
    "kaiwa_beli_tiket|description": "You buy a train ticket at the station counter.",
    "kaiwa_tanya_peron|title": "Asking About the Platform",
    "kaiwa_tanya_peron|description": "You're having trouble finding the right platform at the station.",
    "kaiwa_tanya_jadwal|title": "Asking the Train Schedule",
    "kaiwa_tanya_jadwal|description": "You want to know when the next train arrives.",
    "kaiwa_salah_kereta|title": "Boarding the Wrong Train",
    "kaiwa_salah_kereta|description": "You realize you're on the wrong train and ask a station staff member.",
    "kaiwa_tanya_kereta_ekspres|title": "Asking About an Express Train",
    "kaiwa_tanya_kereta_ekspres|description": "You ask if there's an express train to your destination.",
    "kaiwa_kehilangan_barang|title": "Losing an Item on the Train",
    "kaiwa_kehilangan_barang|description": "You realize you left your bag on the train.",
    "kaiwa_kartu_isi_ulang|title": "Buying a Rechargeable Train Card",
    "kaiwa_kartu_isi_ulang|description": "You buy a rechargeable train card.",
    "kaiwa_tanya_pintu_keluar|title": "Asking About the Station Exit",
    "kaiwa_tanya_pintu_keluar|description": "You're having trouble finding the right exit.",
    "kaiwa_jam_sibuk|title": "Riding the Train During Rush Hour",
    "kaiwa_jam_sibuk|description": "You board a very crowded train during rush hour.",
    "kaiwa_stasiun_transit|title": "Asking About a Transfer Station",
    "kaiwa_stasiun_transit|description": "You need to change trains and ask which station to transfer at.",
    "kaiwa_beli_tiket_shinkansen|title": "Buying a Shinkansen Ticket",
    "kaiwa_beli_tiket_shinkansen|description": "You buy a shinkansen bullet-train ticket at the counter.",
    "kaiwa_loker_penitipan|title": "Asking About Luggage Lockers",
    "kaiwa_loker_penitipan|description": "You're looking for a coin locker to store your luggage.",
    "kaiwa_ketinggalan_kereta|title": "Missing the Train",
    "kaiwa_ketinggalan_kereta|description": "You missed the train and ask a staff member for help.",
    "kaiwa_gerbong_wanita|title": "Asking About the Women-Only Car",
    "kaiwa_gerbong_wanita|description": "You ask a staff member where the women-only car is.",
    "kaiwa_bantuan_koper|title": "Asking for Help Carrying a Suitcase",
    "kaiwa_bantuan_koper|description": "You ask a staff member to help carry your heavy suitcase.",
    "kaiwa_reservasi_kursi_kereta|title": "Asking About Reserved Seating",
    "kaiwa_reservasi_kursi_kereta|description": "You reserve a special seat at the ticket counter.",
    "kaiwa_kereta_terakhir|title": "Asking About the Last Night Train",
    "kaiwa_kereta_terakhir|description": "You ask what time the last train is tonight.",
    "kaiwa_kembalikan_tiket_kereta|title": "Returning a Wrongly Bought Ticket",
    "kaiwa_kembalikan_tiket_kereta|description": "You bought the wrong ticket and want to exchange it.",
    "kaiwa_akses_kursi_roda|title": "Asking About Wheelchair Access",
    "kaiwa_akses_kursi_roda|description": "You ask about wheelchair facilities at the station.",
    "kaiwa_rute_tercepat|title": "Asking for the Fastest Route",
    "kaiwa_rute_tercepat|description": "You ask for the fastest train route to your destination.",
    "kaiwa_tiket_anak|title": "Buying a Child's Ticket",
    "kaiwa_tiket_anak|description": "You also buy a train ticket for your child.",
    "kaiwa_stasiun_terdekat_hotel|title": "Asking About the Nearest Station to a Hotel",
    "kaiwa_stasiun_terdekat_hotel|description": "You ask the hotel receptionist about the nearest station.",
    "kaiwa_kelas_kereta|title": "Choosing Economy or Business Train Class",
    "kaiwa_kelas_kereta|description": "You choose a train class at the counter.",
    "kaiwa_loket_informasi|title": "Finding the Information Counter",
    "kaiwa_loket_informasi|description": "You're looking for the information counter because you're confused about the train.",
    "kaiwa_bawa_sepeda_kereta|title": "Asking the Rules for Bringing a Bicycle on the Train",
    "kaiwa_bawa_sepeda_kereta|description": "You ask whether bicycles are allowed on the train.",
    "kaiwa_kereta_berhenti_mendadak|title": "The Train Suddenly Stops",
    "kaiwa_kereta_berhenti_mendadak|description": "The train you're on suddenly stops midway.",
    "kaiwa_jadwal_kereta_akhir_pekan|title": "Asking About Weekend Train Schedules",
    "kaiwa_jadwal_kereta_akhir_pekan|description": "You ask about the difference in train schedules on weekends.",
    "kaiwa_tiket_kereta_panorama|title": "Buying a Panorama Train Ticket",
    "kaiwa_tiket_kereta_panorama|description": "You buy a panorama train ticket with a window seat.",
    "kaiwa_toilet_stasiun|title": "Asking for the Station Restroom",
    "kaiwa_toilet_stasiun|description": "You ask where the restroom is at the station.",
    "kaiwa_tunggu_kereta_dingin|title": "Waiting for a Train in Winter",
    "kaiwa_tunggu_kereta_dingin|description": "You wait for the train with other passengers in cold weather.",
    "kaiwa_tanya_kursi_kosong|title": "Asking About an Empty Seat",
    "kaiwa_tanya_kursi_kosong|description": "You ask the passenger next to you about an empty seat.",
    "kaiwa_tiket_grup|title": "Buying Tickets for a Group",
    "kaiwa_tiket_grup|description": "You buy train tickets for a group of 10 people.",
    "kaiwa_mesin_tiket_otomatis|title": "Asking How to Use the Ticket Machine",
    "kaiwa_mesin_tiket_otomatis|description": "You ask how to use the automatic ticket machine.",
    "kaiwa_terjebak_pintu_kereta|title": "Caught in the Train Door",
    "kaiwa_terjebak_pintu_kereta|description": "Your bag gets caught in the train door as it departs.",
    "kaiwa_sewa_loker_besar|title": "Renting a Large Locker",
    "kaiwa_sewa_loker_besar|description": "You're looking for a large locker for your suitcase.",
    "kaiwa_kereta_pertama|title": "Asking About the First Train",
    "kaiwa_kereta_pertama|description": "You ask what time the first morning train is.",
    "kaiwa_kehujanan_stasiun|title": "Caught in the Rain at the Station",
    "kaiwa_kehujanan_stasiun|description": "You get soaked by the rain when you arrive at the station.",
    "kaiwa_denda_tanpa_tiket|title": "Asking About the Fine for Riding Without a Ticket",
    "kaiwa_denda_tanpa_tiket|description": "You forgot your ticket and have to pay at the exit gate.",
    "kaiwa_bertemu_teman_stasiun|title": "Meeting an Old Friend at the Station",
    "kaiwa_bertemu_teman_stasiun|description": "You unexpectedly run into an old friend at the station.",
    "kaiwa_nomor_gerbong|title": "Asking the Train Car Number",
    "kaiwa_nomor_gerbong|description": "You ask which car number you should board.",
    "kaiwa_tanya_harga|title": "Asking the Price of an Item",
    "kaiwa_tanya_harga|description": "You ask the price of an item at the store.",
    "kaiwa_coba_baju|title": "Trying on Clothes at the Store",
    "kaiwa_coba_baju|description": "You want to try on clothes before buying.",
    "kaiwa_bayar_kasir|title": "Paying at the Cashier",
    "kaiwa_bayar_kasir|description": "You pay for your purchases at the cashier.",
    "kaiwa_minta_diskon|title": "Asking for a Discount",
    "kaiwa_minta_diskon|description": "You try to haggle over the price at the store.",
    "kaiwa_tukar_barang_rusak|title": "Exchanging a Damaged Item",
    "kaiwa_tukar_barang_rusak|description": "The item you bought turns out to be damaged, and you want to exchange it.",
    "kaiwa_cari_ukuran_pas|title": "Finding the Right Size",
    "kaiwa_cari_ukuran_pas|description": "The clothes you tried on don't quite fit.",
    "kaiwa_bandingkan_barang|title": "Comparing Two Items",
    "kaiwa_bandingkan_barang|description": "You're torn between two items.",
    "kaiwa_tanya_jam_buka_toko|title": "Asking the Store's Opening Hours",
    "kaiwa_tanya_jam_buka_toko|description": "You ask about the store's operating hours.",
    "kaiwa_beli_oleh_oleh|title": "Buying Souvenirs",
    "kaiwa_beli_oleh_oleh|description": "You're looking for souvenirs for your family in Indonesia.",
    "kaiwa_beli_elektronik|title": "Buying Electronics",
    "kaiwa_beli_elektronik|description": "You want to buy new headphones.",
    "kaiwa_cari_barang_rak|title": "Looking for an Item on the Shelf",
    "kaiwa_cari_barang_rak|description": "You're looking for cooking spices at the supermarket.",
    "kaiwa_beli_baju_musim_dingin|title": "Buying Winter Clothes",
    "kaiwa_beli_baju_musim_dingin|description": "You're looking for a warm coat for winter.",
    "kaiwa_tanya_metode_bayar|title": "Asking About Payment Methods",
    "kaiwa_tanya_metode_bayar|description": "You ask what payment methods are available at the register.",
    "kaiwa_beli_sepatu|title": "Buying New Shoes",
    "kaiwa_beli_sepatu|description": "You try on new shoes before buying.",
    "kaiwa_beli_hadiah_teman|title": "Buying a Gift for a Friend",
    "kaiwa_beli_hadiah_teman|description": "You're looking for a gift for your friend.",
    "kaiwa_barang_habis_stok|title": "Asking About an Out-of-Stock Item",
    "kaiwa_barang_habis_stok|description": "The size you're looking for turns out to be out of stock.",
    "kaiwa_gunakan_poin_member|title": "Using Membership Points",
    "kaiwa_gunakan_poin_member|description": "You sign up for a membership points card at the register.",
    "kaiwa_beli_buah_pasar|title": "Buying Fruit at the Market",
    "kaiwa_beli_buah_pasar|description": "You buy fresh fruit at the market.",
    "kaiwa_tanya_garansi|title": "Asking About the Warranty",
    "kaiwa_tanya_garansi|description": "You ask about the warranty period on the electronics you bought.",
    "kaiwa_ambil_di_toko|title": "Shopping Online, Picking Up In-Store",
    "kaiwa_ambil_di_toko|description": "You pick up your online order at the store.",
    "kaiwa_beli_buku_toko|title": "Buying a Book at the Bookstore",
    "kaiwa_beli_buku_toko|description": "You're looking for a Japanese textbook at the bookstore.",
    "kaiwa_kembalikan_barang_refund|title": "Asking How to Return an Item / Get a Refund",
    "kaiwa_kembalikan_barang_refund|description": "You want to return an item because the size doesn't fit.",
    "kaiwa_beli_barang_bekas|title": "Buying Secondhand Items at a Thrift Store",
    "kaiwa_beli_barang_bekas|description": "You're looking for secondhand furniture at a thrift store.",
    "kaiwa_ukuran_baju_anak|title": "Asking About Kids' Clothing Sizes",
    "kaiwa_ukuran_baju_anak|description": "You're looking for kids' clothes in the right size.",
    "kaiwa_beli_alat_sekolah|title": "Buying School Supplies",
    "kaiwa_beli_alat_sekolah|description": "You buy notebooks, pencils, and erasers.",
    "kaiwa_belanja_pasar_malam|title": "Shopping at a Night Market",
    "kaiwa_belanja_pasar_malam|description": "You haggle over the price of a doll at the night market.",
    "kaiwa_produk_ramah_lingkungan|title": "Asking About Eco-Friendly Products",
    "kaiwa_produk_ramah_lingkungan|description": "You're looking for eco-friendly products.",
    "kaiwa_beli_tas_belanja|title": "Buying a Reusable Shopping Bag",
    "kaiwa_beli_tas_belanja|description": "You buy an eco-friendly shopping bag at the register.",
    "kaiwa_cara_pakai_kosmetik|title": "Asking How to Use a Beauty Product",
    "kaiwa_cara_pakai_kosmetik|description": "You ask how to use a new beauty product.",
    "kaiwa_beli_alat_masak|title": "Buying Cookware",
    "kaiwa_beli_alat_masak|description": "You buy a new frying pan at the store.",
    "kaiwa_diskon_akhir_tahun|title": "Asking About Year-End Discounts",
    "kaiwa_diskon_akhir_tahun|description": "You ask the store clerk about the year-end sale schedule.",
    "kaiwa_beli_perhiasan|title": "Buying Jewelry",
    "kaiwa_beli_perhiasan|description": "You buy a ring as a gift.",
    "kaiwa_antre_kasir|title": "Chatting While Queuing at the Cashier",
    "kaiwa_antre_kasir|description": "You chat with someone else while waiting in line at the cashier.",
    "kaiwa_cara_merawat_barang|title": "Asking How to Care for an Item",
    "kaiwa_cara_merawat_barang|description": "You ask how to take care of the new shoes you bought.",
    "kaiwa_beli_bunga|title": "Buying Flowers as a Gift",
    "kaiwa_beli_bunga|description": "You buy roses as a gift for your mother.",
    "kaiwa_ukuran_internasional|title": "Asking About International vs. Japanese Sizes",
    "kaiwa_ukuran_internasional|description": "You ask about the difference between Japanese clothing sizes and your country's.",
    "kaiwa_barang_custom|title": "Ordering a Custom-Made Item",
    "kaiwa_barang_custom|description": "You order an item with a custom name printed on it.",
    "kaiwa_bayar_qr_code|title": "Asking How to Pay With a QR Code",
    "kaiwa_bayar_qr_code|description": "You pay for your purchase by scanning a QR code.",
    "kaiwa_beli_payung_mendadak|title": "Buying an Umbrella Because of Sudden Rain",
    "kaiwa_beli_payung_mendadak|description": "You buy an umbrella because it suddenly starts raining.",
    "kaiwa_sewa_kostum|title": "Renting a Costume for an Event",
    "kaiwa_sewa_kostum|description": "You rent a costume for a Halloween party.",
    "kaiwa_jalan_ke_stasiun|title": "Asking the Way to the Station",
    "kaiwa_jalan_ke_stasiun|description": "You're lost and ask someone on the street for directions to the station.",
    "kaiwa_jalan_ke_toilet|title": "Asking the Way to a Public Restroom",
    "kaiwa_jalan_ke_toilet|description": "You're looking for a public restroom in a tourist area.",
    "kaiwa_tanya_jarak|title": "Asking About the Distance",
    "kaiwa_tanya_jarak|description": "You want to know how far your destination is.",
    "kaiwa_jalan_ke_rumah_sakit|title": "Asking the Way to the Hospital",
    "kaiwa_jalan_ke_rumah_sakit|description": "You ask for directions to the hospital.",
    "kaiwa_tersesat_kota_baru|title": "Getting Lost in a New City",
    "kaiwa_tersesat_kota_baru|description": "You get lost and ask someone on the street for help.",
    "kaiwa_arah_dengan_peta|title": "Asking for Directions Using a Map",
    "kaiwa_arah_dengan_peta|description": "You show a map and ask a staff member for directions.",
    "kaiwa_jalan_ke_supermarket|title": "Asking the Way to the Supermarket",
    "kaiwa_jalan_ke_supermarket|description": "You ask where the nearest supermarket is.",
    "kaiwa_naik_kendaraan_apa|title": "Asking Which Mode of Transport to Take",
    "kaiwa_naik_kendaraan_apa|description": "You're unsure whether to take a bus or a taxi.",
    "kaiwa_jalan_pintas|title": "Asking About a Shortcut",
    "kaiwa_jalan_pintas|description": "You ask if there's a shortcut to your destination.",
    "kaiwa_terima_kasih_arah|title": "Thanking Someone for Directions",
    "kaiwa_terima_kasih_arah|description": "The person who gave you directions makes sure you understood.",
    "kaiwa_jalan_ke_bank|title": "Asking the Way to the Bank",
    "kaiwa_jalan_ke_bank|description": "You ask someone on the street for directions to the bank.",
    "kaiwa_jalan_ke_taman|title": "Asking the Way to the City Park",
    "kaiwa_jalan_ke_taman|description": "You ask for directions to the famous city park.",
    "kaiwa_arah_dengan_landmark|title": "Asking for Directions Using a Landmark",
    "kaiwa_arah_dengan_landmark|description": "You ask for directions using a building as a landmark.",
    "kaiwa_jalan_ke_kantor_polisi|title": "Asking the Way to the Police Station",
    "kaiwa_jalan_ke_kantor_polisi|description": "Your wallet is lost, so you ask for directions to the police box.",
    "kaiwa_arah_malam_hari|title": "Asking for Directions at Night",
    "kaiwa_arah_malam_hari|description": "You ask about how safe the road is at night.",
    "kaiwa_jalan_ditutup|title": "Asking About a Detour Because a Road Is Closed",
    "kaiwa_jalan_ditutup|description": "The road you usually take is currently closed.",
    "kaiwa_tunjukkan_arah_turis|title": "Giving Directions to Another Tourist",
    "kaiwa_tunjukkan_arah_turis|description": "A tourist asks you for directions on the street.",
    "kaiwa_jalan_ke_perpustakaan|title": "Asking the Way to the Library",
    "kaiwa_jalan_ke_perpustakaan|description": "You ask for directions to the city library.",
    "kaiwa_arah_aplikasi_peta|title": "Asking for Directions Using a Phone Map App",
    "kaiwa_arah_aplikasi_peta|description": "You're confused reading the map on your phone and ask for help.",
    "kaiwa_jalan_naik_sepeda|title": "Asking About Cycling Directions",
    "kaiwa_jalan_naik_sepeda|description": "You ask whether your destination can be reached by bicycle.",
    "kaiwa_jalan_ke_kuil|title": "Asking the Way to a Temple/Shrine",
    "kaiwa_jalan_ke_kuil|description": "You ask someone on the street for directions to a temple.",
    "kaiwa_jalan_ke_kolam_renang|title": "Asking the Way to the Swimming Pool",
    "kaiwa_jalan_ke_kolam_renang|description": "You ask for directions to the swimming pool.",
    "kaiwa_jalan_ke_pantai|title": "Asking the Way to the Beach",
    "kaiwa_jalan_ke_pantai|description": "You ask how to get to the beach.",
    "kaiwa_tangga_atau_lift|title": "Asking Whether to Take the Stairs or Elevator",
    "kaiwa_tangga_atau_lift|description": "You ask which is faster, taking the stairs or the elevator.",
    "kaiwa_jalan_ke_toko_oleh_oleh|title": "Asking the Way to a Souvenir Shop",
    "kaiwa_jalan_ke_toko_oleh_oleh|description": "You ask for directions to a souvenir shop.",
    "kaiwa_jarak_dengan_mobil|title": "Asking About Travel Time by Car",
    "kaiwa_jarak_dengan_mobil|description": "You ask how long the trip takes by car.",
    "kaiwa_tersesat_barang_berat|title": "Getting Lost While Carrying Heavy Luggage",
    "kaiwa_tersesat_barang_berat|description": "You get lost while carrying heavy luggage.",
    "kaiwa_jalan_ke_kantor_pemerintah|title": "Asking the Way to a Government Building",
    "kaiwa_jalan_ke_kantor_pemerintah|description": "You ask for directions to city hall.",
    "kaiwa_arah_bawa_anak|title": "Asking for Directions While Bringing a Child",
    "kaiwa_arah_bawa_anak|description": "You're looking for a small park to play at with your child.",
    "kaiwa_jalan_ke_pasar|title": "Asking the Way to a Traditional Market",
    "kaiwa_jalan_ke_pasar|description": "You ask for directions to a traditional market.",
    "kaiwa_jalan_ke_karaoke|title": "Directions to a Karaoke Place",
    "kaiwa_jalan_ke_karaoke|description": "You ask for directions to a karaoke place.",
    "kaiwa_rute_bebas_tangga|title": "Asking for a Stair-Free Route",
    "kaiwa_rute_bebas_tangga|description": "You ask for a route without stairs because you're carrying a large suitcase.",
    "kaiwa_arah_dengan_foto|title": "Asking for Directions by Showing a Photo",
    "kaiwa_arah_dengan_foto|description": "You show a photo of the place you want to go to.",
    "kaiwa_jalan_ke_gym|title": "Asking the Way to the Gym",
    "kaiwa_jalan_ke_gym|description": "You ask for directions to the nearest gym.",
    "kaiwa_salah_arah_gps|title": "Going the Wrong Way Because of a GPS Error",
    "kaiwa_salah_arah_gps|description": "You get lost because the map app on your phone is malfunctioning.",
    "kaiwa_jalan_pulang_pesta|title": "Asking the Way Home from a Party",
    "kaiwa_jalan_pulang_pesta|description": "It's already late at night and you're figuring out how to get home from the party.",
    "kaiwa_arah_ke_teman_sekelas|title": "Asking the Way to a Classmate's House",
    "kaiwa_arah_ke_teman_sekelas|description": "You ask for directions to a classmate's house.",
    "kaiwa_arah_angin_kencang|title": "Asking for Directions in Strong Wind",
    "kaiwa_arah_angin_kencang|description": "You ask for directions while the wind is blowing strongly.",
    "kaiwa_tunjukkan_arah_kurir|title": "Giving Directions to a Delivery Courier",
    "kaiwa_tunjukkan_arah_kurir|description": "A courier asks you for the delivery address.",
    "kaiwa_terima_kasih_diantar|title": "Thanking Someone for Walking You There",
    "kaiwa_terima_kasih_diantar|description": "A kind person walks you directly to your destination.",
    "kaiwa_sapa_guru|title": "Greeting the Teacher in Class",
    "kaiwa_sapa_guru|description": "You greet your teacher in the morning before class starts.",
    "kaiwa_tanya_pr|title": "Asking About Homework",
    "kaiwa_tanya_pr|description": "You ask a friend about today's homework assignment.",
    "kaiwa_pinjam_alat_tulis|title": "Borrowing Stationery",
    "kaiwa_pinjam_alat_tulis|description": "You forgot to bring a pencil and want to borrow one from a friend.",
    "kaiwa_jadwal_pelajaran|title": "Asking About the Class Schedule",
    "kaiwa_jadwal_pelajaran|description": "You ask Dewi about today's class schedule.",
    "kaiwa_izin_toilet|title": "Asking Permission to Use the Restroom",
    "kaiwa_izin_toilet|description": "You ask the teacher for permission to use the restroom.",
    "kaiwa_terlambat_kelas|title": "Arriving Late to Class",
    "kaiwa_terlambat_kelas|description": "You're late to class because the train was delayed.",
    "kaiwa_ajak_belajar_kelompok|title": "Inviting Someone to Study Together",
    "kaiwa_ajak_belajar_kelompok|description": "You invite Rian to study together for the exam.",
    "kaiwa_tanya_nilai_ujian|title": "Asking About Exam Scores",
    "kaiwa_tanya_nilai_ujian|description": "Lisa asks about your exam score.",
    "kaiwa_bolos_sakit|title": "Missing School Due to Illness",
    "kaiwa_bolos_sakit|description": "You call the school to report you're absent due to illness.",
    "kaiwa_pisah_akhir_semester|title": "Parting Ways at the End of the Semester",
    "kaiwa_pisah_akhir_semester|description": "Andi starts a conversation with you about the end of the semester.",
    "kaiwa_ikut_ekstrakurikuler|title": "Joining an Extracurricular Activity",
    "kaiwa_ikut_ekstrakurikuler|description": "You sign up for the art club at school.",
    "kaiwa_tugas_kelompok|title": "Asking About a Group Assignment",
    "kaiwa_tugas_kelompok|description": "You coordinate with a friend about a group presentation.",
    "kaiwa_izin_pulang_cepat|title": "Asking Permission to Leave Early",
    "kaiwa_izin_pulang_cepat|description": "You're feeling unwell and ask permission to leave early.",
    "kaiwa_tanya_ruang_kelas|title": "Asking About the Classroom",
    "kaiwa_tanya_ruang_kelas|description": "You're a new student looking for your classroom.",
    "kaiwa_makan_kantin_sekolah|title": "Having Lunch at the School Cafeteria",
    "kaiwa_makan_kantin_sekolah|description": "You have lunch with a friend at the school cafeteria.",
    "kaiwa_persiapan_ujian_akhir|title": "Preparing for the Final Exam",
    "kaiwa_persiapan_ujian_akhir|description": "You ask about the scope of material for the final exam.",
    "kaiwa_guru_pengganti|title": "Asking About a Substitute Teacher",
    "kaiwa_guru_pengganti|description": "A friend tells you there's a substitute teacher today.",
    "kaiwa_ikut_karyawisata|title": "Joining a School Field Trip",
    "kaiwa_ikut_karyawisata|description": "You ask about the school's field trip plans.",
    "kaiwa_kembalikan_buku_sekolah|title": "Returning a School Library Book",
    "kaiwa_kembalikan_buku_sekolah|description": "You return a borrowed book to the school library.",
    "kaiwa_tugas_piket|title": "Asking About Classroom Cleaning Duty",
    "kaiwa_tugas_piket|description": "You help a friend who's on cleaning duty today.",
    "kaiwa_sapa_teman_sebelum_kelas|title": "Greeting a Friend Before Class Starts",
    "kaiwa_sapa_teman_sebelum_kelas|description": "Your friend greets you before class starts this morning.",
    "kaiwa_tanya_materi_terlewat|title": "Asking About Missed Material",
    "kaiwa_tanya_materi_terlewat|description": "You were absent yesterday and ask about the material you missed.",
    "kaiwa_pinjam_catatan|title": "Borrowing Notes",
    "kaiwa_pinjam_catatan|description": "You borrow class notes from a friend.",
    "kaiwa_study_tour_sehari|title": "Going on a One-Day Field Trip to a Museum",
    "kaiwa_study_tour_sehari|description": "The teacher announces tomorrow's museum visit schedule.",
    "kaiwa_jadwal_ujian_semester|title": "Asking About the Semester Exam Schedule",
    "kaiwa_jadwal_ujian_semester|description": "You ask about the final semester exam schedule.",
    "kaiwa_jadi_ketua_kelas|title": "Becoming Class President",
    "kaiwa_jadi_ketua_kelas|description": "The teacher asks you to be class president this semester.",
    "kaiwa_izin_sakit_saat_kelas|title": "Asking the Teacher for Sick Leave During Class",
    "kaiwa_izin_sakit_saat_kelas|description": "You feel unwell in the middle of class.",
    "kaiwa_ikut_lomba_sekolah|title": "Joining a School Competition",
    "kaiwa_ikut_lomba_sekolah|description": "You sign up for a speech competition at school.",
    "kaiwa_tugas_tambahan|title": "Asking About Extra Homework",
    "kaiwa_tugas_tambahan|description": "You ask if there's any extra homework.",
    "kaiwa_bersih_bersih_kelas|title": "Cleaning the Classroom Together",
    "kaiwa_bersih_bersih_kelas|description": "The whole class works together to clean the classroom.",
    "kaiwa_tanya_nilai_turun|title": "Asking Why Your Grades Dropped",
    "kaiwa_tanya_nilai_turun|description": "The teacher asks why your exam scores have dropped lately.",
    "kaiwa_ikut_klub_debat|title": "Joining the Debate Club",
    "kaiwa_ikut_klub_debat|description": "You sign up for the debate club at school.",
    "kaiwa_loker_sekolah|title": "Asking About the School Locker",
    "kaiwa_loker_sekolah|description": "You ask about your school locker number.",
    "kaiwa_keluar_ekskul|title": "Quitting an Extracurricular Activity",
    "kaiwa_keluar_ekskul|description": "You quit the club to focus on studying.",
    "kaiwa_jenguk_teman_sakit_sekolah|title": "Visiting a Sick Friend at Home",
    "kaiwa_jenguk_teman_sakit_sekolah|description": "You bring homework to the house of a friend who's out sick.",
    "kaiwa_ikut_les_tambahan|title": "Joining Extra Tutoring Classes",
    "kaiwa_ikut_les_tambahan|description": "You sign up with the teacher for extra math tutoring.",
    "kaiwa_siapkan_presentasi|title": "Preparing a Group Presentation",
    "kaiwa_siapkan_presentasi|description": "You and a friend prepare a group presentation together.",
    "kaiwa_aturan_seragam|title": "Asking About School Uniform Rules",
    "kaiwa_aturan_seragam|description": "You ask the teacher about school uniform rules.",
    "kaiwa_rayakan_kelulusan|title": "Celebrating Graduation",
    "kaiwa_rayakan_kelulusan|description": "You and your friends celebrate graduation together.",
    "kaiwa_tukar_kontak_sekelas|title": "Exchanging Contacts With a Classmate",
    "kaiwa_tukar_kontak_sekelas|description": "You exchange contacts with a new classmate.",
    "kaiwa_bicara_cuaca|title": "Talking About the Weather",
    "kaiwa_bicara_cuaca|description": "You make small talk about the weather with a neighbor.",
    "kaiwa_tanya_akhir_pekan|title": "Asking About Weekend Plans",
    "kaiwa_tanya_akhir_pekan|description": "Your friend asks about your weekend plans.",
    "kaiwa_berpamitan|title": "Saying Goodbye",
    "kaiwa_berpamitan|description": "You say goodbye to a friend after running into them on the street.",
    "kaiwa_musim_favorit|title": "Talking About Your Favorite Season",
    "kaiwa_musim_favorit|description": "Mrs. Sato asks your favorite season.",
    "kaiwa_tunggu_bus|title": "Small Talk While Waiting for the Bus",
    "kaiwa_tunggu_bus|description": "You make light conversation with someone while waiting for the bus.",
    "kaiwa_kabar_lama_tidak_bertemu|title": "Catching Up After a Long Time",
    "kaiwa_kabar_lama_tidak_bertemu|description": "You run into Budi, an old friend, after not seeing him for a long time.",
    "kaiwa_rencana_malam_ini|title": "Talking About Tonight's Plans",
    "kaiwa_rencana_malam_ini|description": "Sinta invites you to watch a movie tonight.",
    "kaiwa_basa_basi_pekerjaan_rumah|title": "Small Talk About Household Chores",
    "kaiwa_basa_basi_pekerjaan_rumah|description": "Mrs. Wati, your neighbor, asks what's been keeping you busy lately.",
    "kaiwa_berita_terkini|title": "Talking About Current News",
    "kaiwa_berita_terkini|description": "Doni talks with you about today's weather news.",
    "kaiwa_sapa_tetangga_baru|title": "Greeting a New Neighbor",
    "kaiwa_sapa_tetangga_baru|description": "Mr. Endro, a new neighbor, introduces himself.",
}
