"""
kanji_word_meaning_en.py

Locked source of truth for the English glosses of every kanji entry's
`wordExamples` ("contoh kata") — the `meaningEn` field on
`KanjiWordExample`. apply_kanji_word_meaning_en.py reads this and patches
assets/data/kanji_data.json, so translations live in exactly one place.

Known data quirk: 也 (kanji_ya_n1) lists the word 也 twice in its own
wordExamples, so the dataset has 7,275 examples but only 7,274 distinct
keys — patching that key fills both slots with the same gloss, which is
correct here since both rows are the same word. Worth fixing in
generate_kanji_seed.py if that entry is ever revisited.

Key format: "{kanji_id}|{word}". The kanji id is part of the key because
the same compound can appear under several kanji (一人 sits under both 一
and 人), and each of those slots is patched independently.

Must be re-applied after generate_kanji_seed.py regenerates the dataset,
same as split_kanji_meanings_en.py.

STATUS: N5 done (321/321), N4 done (399/399). N3/N2/N1 pending —
    6,555 glosses left (N3 945, N2 1101, N1 4509), best done one JLPT
    level at a time. Dump the next level's rows with:
        python -c "import json; d=json.load(open('assets/data/kanji_data.json', encoding='utf-8')); [print(f\"{e['id']}|{w['word']} :: {w['meaning']}\") for e in d if e['jlptLevel']=='N4' for w in e['wordExamples']]"
    then translate, append a block below, and run the applier (it prints
    per-level coverage so progress is visible).

Style: translate the Indonesian gloss as it stands — short, no new senses.
"""

WORD_MEANING_EN = {
    # ---------------- N5 ----------------
    "kanji_ichi|一つ": "one (item)",
    "kanji_ichi|一月": "January",
    "kanji_ichi|一人": "one person, alone",
    "kanji_ni|二つ": "two (items)",
    "kanji_ni|二月": "February",
    "kanji_ni|二人": "two people",
    "kanji_san|三つ": "three (items)",
    "kanji_san|三月": "March",
    "kanji_san|三人": "three people",
    "kanji_yon|四月": "April",
    "kanji_yon|四人": "four people",
    "kanji_yon|四つ": "four (items)",
    "kanji_go|五つ": "five (items)",
    "kanji_go|五月": "May",
    "kanji_go|五人": "five people",
    "kanji_roku|六月": "June",
    "kanji_roku|六つ": "six (items)",
    "kanji_roku|六人": "six people",
    "kanji_shichi|七つ": "seven (items)",
    "kanji_shichi|七月": "July",
    "kanji_shichi|七人": "seven people",
    "kanji_hachi|八月": "August",
    "kanji_hachi|八つ": "eight (items)",
    "kanji_hachi|八人": "eight people",
    "kanji_kyuu|九つ": "nine (items)",
    "kanji_kyuu|九月": "September",
    "kanji_kyuu|九人": "nine people",
    "kanji_juu|十日": "the tenth, ten days",
    "kanji_juu|十人": "ten people",
    "kanji_juu|十月": "October",
    "kanji_hito|日本人": "Japanese person",
    "kanji_hito|一人": "one person, alone",
    "kanji_hito|人々": "people",
    "kanji_hi|日曜日": "Sunday",
    "kanji_hi|毎日": "every day",
    "kanji_hi|誕生日": "birthday",
    "kanji_tsuki|月曜日": "Monday",
    "kanji_tsuki|月": "moon",
    "kanji_tsuki|今月": "this month",
    "kanji_yama|富士山": "Mount Fuji",
    "kanji_yama|山": "mountain",
    "kanji_yama|登山": "mountain climbing",
    "kanji_kawa|川": "river",
    "kanji_kawa|小川": "stream",
    "kanji_kawa|川岸": "riverbank",
    "kanji_hyaku|百円": "one hundred yen",
    "kanji_hyaku|百人": "one hundred people",
    "kanji_hyaku|百点": "a perfect score",
    "kanji_sen|千円": "one thousand yen",
    "kanji_sen|千人": "one thousand people",
    "kanji_sen|二千": "two thousand",
    "kanji_man|一万円": "ten thousand yen",
    "kanji_man|万年筆": "fountain pen",
    "kanji_man|十万": "one hundred thousand",
    "kanji_en|円": "yen",
    "kanji_en|百円": "one hundred yen",
    "kanji_en|千円": "one thousand yen",
    "kanji_nen|来年": "next year",
    "kanji_nen|今年": "this year",
    "kanji_nen|毎年": "every year",
    "kanji_ji|時間": "time, hour",
    "kanji_ji|何時": "what time",
    "kanji_ji|時々": "sometimes",
    "kanji_fun|五分": "five minutes",
    "kanji_fun|分かる": "to understand",
    "kanji_fun|半分": "half",
    "kanji_kan|時間": "time",
    "kanji_kan|間": "interval, gap",
    "kanji_kan|一週間": "one week",
    "kanji_shuu|今週": "this week",
    "kanji_shuu|来週": "next week",
    "kanji_shuu|毎週": "every week",
    "kanji_you|曜日": "day of the week",
    "kanji_you|月曜日": "Monday",
    "kanji_you|何曜日": "which day of the week",
    "kanji_ima|今": "now",
    "kanji_ima|今日": "today",
    "kanji_ima|今年": "this year",
    "kanji_han|半分": "half",
    "kanji_han|一時半": "half past one",
    "kanji_han|半年": "half a year",
    "kanji_ki|木曜日": "Thursday",
    "kanji_ki|木": "tree",
    "kanji_ki|大木": "large tree",
    "kanji_hayashi|林": "woods",
    "kanji_hayashi|森林": "forest",
    "kanji_hayashi|山林": "mountain forest",
    "kanji_mori|森": "forest",
    "kanji_mori|森林": "forest",
    "kanji_mori|深い森": "deep forest",
    "kanji_ta|田んぼ": "rice field",
    "kanji_ta|水田": "paddy field",
    "kanji_ta|田植え": "rice planting",
    "kanji_hi2|火曜日": "Tuesday",
    "kanji_hi2|火": "fire",
    "kanji_hi2|花火": "fireworks",
    "kanji_mizu|水曜日": "Wednesday",
    "kanji_mizu|水": "water",
    "kanji_mizu|水泳": "swimming",
    "kanji_tsuchi|土曜日": "Saturday",
    "kanji_tsuchi|土": "soil",
    "kanji_tsuchi|土地": "land, plot",
    "kanji_sora|空": "sky",
    "kanji_sora|空気": "air",
    "kanji_sora|空港": "airport",
    "kanji_ki2|元気": "healthy, energetic",
    "kanji_ki2|天気": "weather",
    "kanji_ki2|気持ち": "feeling",
    "kanji_ame|雨": "rain",
    "kanji_ame|大雨": "heavy rain",
    "kanji_ame|雨天": "rainy weather",
    "kanji_ishi|石": "stone",
    "kanji_ishi|石鹸": "soap",
    "kanji_ishi|宝石": "gemstone",
    "kanji_hana|花": "flower",
    "kanji_hana|花見": "cherry-blossom viewing",
    "kanji_hana|花瓶": "vase",
    "kanji_ko|子供": "child",
    "kanji_ko|女の子": "girl",
    "kanji_ko|男の子": "boy",
    "kanji_onna|女性": "woman",
    "kanji_onna|女の子": "girl",
    "kanji_onna|彼女": "she, girlfriend",
    "kanji_otoko|男性": "man",
    "kanji_otoko|男の子": "boy",
    "kanji_otoko|長男": "eldest son",
    "kanji_na|名前": "name",
    "kanji_na|有名": "famous",
    "kanji_na|名字": "surname",
    "kanji_mae|名前": "name",
    "kanji_mae|前": "front, before",
    "kanji_mae|午前": "morning, a.m.",
    "kanji_gaku|学校": "school",
    "kanji_gaku|学生": "student",
    "kanji_gaku|大学": "university",
    "kanji_sei|学生": "student",
    "kanji_sei|先生": "teacher",
    "kanji_sei|生まれる": "to be born",
    "kanji_saki|先生": "teacher",
    "kanji_saki|先週": "last week",
    "kanji_saki|先に": "beforehand, first",
    "kanji_tomo|友達": "friend",
    "kanji_tomo|親友": "close friend",
    "kanji_tomo|友人": "friend (formal)",
    "kanji_watashi|私": "I, me",
    "kanji_watashi|私立": "private (institution)",
    "kanji_watashi|私達": "we, us",
    "kanji_chichi|父": "my father",
    "kanji_chichi|お父さん": "father (general term)",
    "kanji_chichi|父親": "father",
    "kanji_haha|母": "my mother",
    "kanji_haha|お母さん": "mother (general term)",
    "kanji_haha|母国": "homeland",
    "kanji_me|目": "eye",
    "kanji_me|目的": "purpose",
    "kanji_me|一つ目": "the first one",
    "kanji_kuchi|口": "mouth",
    "kanji_kuchi|入り口": "entrance",
    "kanji_kuchi|人口": "population",
    "kanji_te|手": "hand",
    "kanji_te|上手": "skilled, good at",
    "kanji_te|手紙": "letter",
    "kanji_ashi|足": "foot, leg",
    "kanji_ashi|足りる": "to be enough",
    "kanji_ashi|一足": "one pair (of shoes)",
    "kanji_ue|上": "above, up",
    "kanji_ue|上手": "skilled",
    "kanji_ue|屋上": "rooftop",
    "kanji_shita|下": "below, down",
    "kanji_shita|下手": "unskilled",
    "kanji_shita|地下": "underground",
    "kanji_naka|中": "inside, middle",
    "kanji_naka|中国": "China",
    "kanji_naka|一日中": "all day long",
    "kanji_soto|外": "outside",
    "kanji_soto|外国": "foreign country",
    "kanji_soto|外国人": "foreigner",
    "kanji_hidari|左": "left",
    "kanji_hidari|左手": "left hand",
    "kanji_hidari|左側": "left side",
    "kanji_migi|右": "right",
    "kanji_migi|右手": "right hand",
    "kanji_migi|右側": "right side",
    "kanji_ato|後で": "later",
    "kanji_ato|午後": "afternoon, p.m.",
    "kanji_ato|後ろ": "behind",
    "kanji_higashi|東": "east",
    "kanji_higashi|東京": "Tokyo",
    "kanji_higashi|東口": "east exit",
    "kanji_nishi|西": "west",
    "kanji_nishi|西口": "west exit",
    "kanji_nishi|関西": "the Kansai region",
    "kanji_minami|南": "south",
    "kanji_minami|南口": "south exit",
    "kanji_minami|南国": "southern country",
    "kanji_kita|北": "north",
    "kanji_kita|北海道": "Hokkaido",
    "kanji_kita|北口": "north exit",
    "kanji_iku|行く": "to go",
    "kanji_iku|銀行": "bank",
    "kanji_iku|旅行": "travel",
    "kanji_kuru|来る": "to come",
    "kanji_kuru|来年": "next year",
    "kanji_kuru|来週": "next week",
    "kanji_taberu|食べる": "to eat",
    "kanji_taberu|食事": "a meal",
    "kanji_taberu|朝食": "breakfast",
    "kanji_nomu|飲む": "to drink",
    "kanji_nomu|飲み物": "a drink",
    "kanji_nomu|飲食店": "restaurant, eatery",
    "kanji_miru|見る": "to see",
    "kanji_miru|見学": "study visit",
    "kanji_miru|意見": "opinion",
    "kanji_kiku|聞く": "to hear, to ask",
    "kanji_kiku|新聞": "newspaper",
    "kanji_kiku|聞こえる": "to be audible",
    "kanji_yomu|読む": "to read",
    "kanji_yomu|読書": "reading books",
    "kanji_yomu|音読": "reading aloud",
    "kanji_kaku|書く": "to write",
    "kanji_kaku|辞書": "dictionary",
    "kanji_kaku|図書館": "library",
    "kanji_hanasu|話す": "to speak",
    "kanji_hanasu|電話": "telephone",
    "kanji_hanasu|会話": "conversation",
    "kanji_kau|買う": "to buy",
    "kanji_kau|買い物": "shopping",
    "kanji_kau|購買": "purchasing",
    "kanji_uru|売る": "to sell",
    "kanji_uru|発売": "release for sale",
    "kanji_uru|売店": "kiosk",
    "kanji_tatsu|立つ": "to stand",
    "kanji_tatsu|国立": "national (state-run)",
    "kanji_tatsu|立派": "splendid",
    "kanji_yasumu|休む": "to rest",
    "kanji_yasumu|休み": "holiday, break",
    "kanji_yasumu|休日": "day off",
    "kanji_hairu|入る": "to enter",
    "kanji_hairu|入学": "entering school",
    "kanji_hairu|入り口": "entrance",
    "kanji_deru|出る": "to go out",
    "kanji_deru|出口": "exit",
    "kanji_deru|出発": "departure",
    "kanji_au|会う": "to meet",
    "kanji_au|会議": "meeting",
    "kanji_au|会社": "company",
    "kanji_kou|学校": "school",
    "kanji_kou|校長": "principal",
    "kanji_kou|高校": "high school",
    "kanji_go2|日本語": "Japanese language",
    "kanji_go2|英語": "English language",
    "kanji_go2|単語": "vocabulary word",
    "kanji_bun|文章": "writing, text",
    "kanji_bun|文法": "grammar",
    "kanji_bun|作文": "essay, composition",
    "kanji_ji2|漢字": "kanji",
    "kanji_ji2|文字": "letter, character",
    "kanji_ji2|字": "character",
    "kanji_hon|本": "book",
    "kanji_hon|日本": "Japan",
    "kanji_hon|本当": "true, really",
    "kanji_kuni|国": "country",
    "kanji_kuni|外国": "foreign country",
    "kanji_kuni|中国": "China",
    "kanji_machi|町": "town",
    "kanji_machi|下町": "old downtown area",
    "kanji_machi|町長": "town mayor",
    "kanji_mura|村": "village",
    "kanji_mura|農村": "farming village",
    "kanji_mura|村人": "villager",
    "kanji_eki|駅": "station",
    "kanji_eki|駅員": "station attendant",
    "kanji_eki|駅前": "in front of the station",
    "kanji_mise|店": "shop",
    "kanji_mise|店員": "shop assistant",
    "kanji_mise|喫茶店": "coffee shop",
    "kanji_ie|家": "house",
    "kanji_ie|家族": "family",
    "kanji_ie|家庭": "household",
    "kanji_ookii|大きい": "big",
    "kanji_ookii|大学": "university",
    "kanji_ookii|大切": "important",
    "kanji_chiisai|小さい": "small",
    "kanji_chiisai|小学校": "primary school",
    "kanji_chiisai|小説": "novel",
    "kanji_ooi|多い": "many",
    "kanji_ooi|多分": "probably",
    "kanji_ooi|多数": "a large number",
    "kanji_sukunai|少ない": "few",
    "kanji_sukunai|少し": "a little",
    "kanji_sukunai|少年": "boy, youth",
    "kanji_takai|高い": "tall, expensive",
    "kanji_takai|高校": "high school",
    "kanji_takai|高速": "high speed",
    "kanji_yasui|安い": "cheap",
    "kanji_yasui|安全": "safe",
    "kanji_yasui|不安": "anxious",
    "kanji_atarashii|新しい": "new",
    "kanji_atarashii|新聞": "newspaper",
    "kanji_atarashii|新年": "new year",
    "kanji_furui|古い": "old",
    "kanji_furui|中古": "second-hand",
    "kanji_furui|古本": "used book",
    "kanji_nagai|長い": "long",
    "kanji_nagai|社長": "company president",
    "kanji_nagai|校長": "principal",
    "kanji_shiro|白い": "white",
    "kanji_shiro|白": "the colour white",
    "kanji_shiro|面白い": "interesting, funny",
    "kanji_nani|何": "what",
    "kanji_nani|何時": "what time",
    "kanji_nani|何人": "how many people",
    "kanji_kuruma|車": "car",
    "kanji_kuruma|電車": "train",
    "kanji_kuruma|自動車": "motor vehicle",
    "kanji_den|電車": "train",
    "kanji_den|電話": "telephone",
    "kanji_den|電気": "electricity, light",
    "kanji_michi|道": "road",
    "kanji_michi|道路": "roadway",
    "kanji_michi|北海道": "Hokkaido",

    # ---------------- N4 ----------------
    "kanji_asa|朝": "morning",
    "kanji_asa|朝食": "breakfast",
    "kanji_asa|毎朝": "every morning",
    "kanji_hiru|昼": "daytime, noon",
    "kanji_hiru|昼食": "lunch",
    "kanji_hiru|昼休み": "lunch break",
    "kanji_yoru|夜": "night",
    "kanji_yoru|今夜": "tonight",
    "kanji_yoru|夜中": "midnight",
    "kanji_do|今度": "this time, next time",
    "kanji_do|一度": "once",
    "kanji_do|温度": "temperature",
    "kanji_yuki|雪": "snow",
    "kanji_yuki|大雪": "heavy snow",
    "kanji_yuki|雪国": "snow country",
    "kanji_kaze|風": "wind",
    "kanji_kaze|台風": "typhoon",
    "kanji_kaze|風邪": "a cold",
    "kanji_oto|音": "sound",
    "kanji_oto|音楽": "music",
    "kanji_oto|発音": "pronunciation",
    "kanji_hikari|光": "light",
    "kanji_hikari|日光": "sunlight",
    "kanji_hikari|光る": "to shine",
    "kanji_karada|体": "body",
    "kanji_karada|体育": "physical education",
    "kanji_karada|体重": "body weight",
    "kanji_kokoro|心": "heart, mind",
    "kanji_kokoro|心配": "worry",
    "kanji_kokoro|安心": "relief",
    "kanji_atama|頭": "head",
    "kanji_atama|頭痛": "headache",
    "kanji_atama|石頭": "stubborn person",
    "kanji_yamai|病気": "illness",
    "kanji_yamai|病院": "hospital",
    "kanji_yamai|病人": "sick person",
    "kanji_shinu|死ぬ": "to die",
    "kanji_shinu|死": "death",
    "kanji_shinu|必死": "desperately",
    "kanji_kao|顔": "face",
    "kanji_kao|笑顔": "smiling face",
    "kanji_kao|顔色": "complexion",
    "kanji_koe|声": "voice",
    "kanji_koe|大声": "loud voice",
    "kanji_koe|声優": "voice actor",
    "kanji_imouto|妹": "younger sister",
    "kanji_imouto|妹さん": "someone's younger sister",
    "kanji_imouto|姉妹": "sisters",
    "kanji_otouto|弟": "younger brother",
    "kanji_otouto|弟さん": "someone's younger brother",
    "kanji_otouto|兄弟": "siblings",
    "kanji_ani|兄": "older brother",
    "kanji_ani|お兄さん": "older brother (general term)",
    "kanji_ani|兄弟": "siblings",
    "kanji_ane|姉": "older sister",
    "kanji_ane|お姉さん": "older sister (general term)",
    "kanji_ane|姉妹": "sisters",
    "kanji_nushi|主人": "husband, host",
    "kanji_nushi|主な": "main",
    "kanji_nushi|持ち主": "owner",
    "kanji_mono|医者": "doctor",
    "kanji_mono|若者": "young person",
    "kanji_mono|学者": "scholar",
    "kanji_in|会社員": "company employee",
    "kanji_in|店員": "shop assistant",
    "kanji_in|会員": "member",
    "kanji_tsukau|使う": "to use",
    "kanji_tsukau|使用": "use",
    "kanji_tsukau|大使": "ambassador",
    "kanji_tsukuru|作る": "to make",
    "kanji_tsukuru|作文": "composition",
    "kanji_tsukuru|作品": "a work (of art)",
    "kanji_omou|思う": "to think",
    "kanji_omou|思い出": "memory",
    "kanji_omou|意思": "intention",
    "kanji_shiru|知る": "to know",
    "kanji_shiru|知識": "knowledge",
    "kanji_shiru|知らせる": "to inform",
    "kanji_motsu|持つ": "to hold, to carry",
    "kanji_motsu|気持ち": "feeling",
    "kanji_motsu|持ち物": "belongings",
    "kanji_asobu|遊ぶ": "to play",
    "kanji_asobu|遊園地": "amusement park",
    "kanji_asobu|遊び": "play, game",
    "kanji_hataraku|働く": "to work",
    "kanji_hataraku|労働": "labour",
    "kanji_hataraku|共働き": "both spouses working",
    "kanji_hashiru|走る": "to run",
    "kanji_hashiru|競走": "a race",
    "kanji_hashiru|走者": "runner",
    "kanji_oyogu|泳ぐ": "to swim",
    "kanji_oyogu|水泳": "swimming",
    "kanji_oyogu|平泳ぎ": "breaststroke",
    "kanji_tobu|飛ぶ": "to fly",
    "kanji_tobu|飛行機": "aeroplane",
    "kanji_tobu|飛行場": "airfield",
    "kanji_okuru|送る": "to send, to see off",
    "kanji_okuru|送料": "shipping fee",
    "kanji_okuru|見送る": "to see someone off",
    "kanji_oshieru|教える": "to teach",
    "kanji_oshieru|教室": "classroom",
    "kanji_oshieru|教育": "education",
    "kanji_narau|習う": "to learn",
    "kanji_narau|練習": "practice",
    "kanji_narau|予習": "preparation before class",
    "kanji_oboeru|覚える": "to memorise",
    "kanji_oboeru|覚えている": "to remember",
    "kanji_oboeru|目覚める": "to wake up",
    "kanji_wasureru|忘れる": "to forget",
    "kanji_wasureru|忘れ物": "lost property",
    "kanji_wasureru|物忘れ": "forgetfulness",
    "kanji_kimeru|決める": "to decide",
    "kanji_kimeru|決定": "decision",
    "kanji_kimeru|決して": "never (with negative)",
    "kanji_wakareru|別れる": "to part, to break up",
    "kanji_wakareru|別に": "not particularly",
    "kanji_wakareru|特別": "special",
    "kanji_kawaru|変わる": "to change (intransitive)",
    "kanji_kawaru|変える": "to change (transitive)",
    "kanji_kawaru|大変": "tough, very",
    "kanji_hajimeru|始める": "to start (transitive)",
    "kanji_hajimeru|始まる": "to begin (intransitive)",
    "kanji_hajimeru|開始": "commencement",
    "kanji_owaru|終わる": "to end",
    "kanji_owaru|終電": "last train",
    "kanji_owaru|最終": "final",
    "kanji_hiraku|開く": "to open",
    "kanji_hiraku|開ける": "to open (transitive)",
    "kanji_hiraku|開店": "shop opening",
    "kanji_shimeru|閉じる": "to close",
    "kanji_shimeru|閉める": "to shut",
    "kanji_shimeru|閉店": "shop closing",
    "kanji_atsumaru|集まる": "to gather (intransitive)",
    "kanji_atsumaru|集める": "to collect",
    "kanji_atsumaru|集合": "assembly, gathering",
    "kanji_ugoku|動く": "to move",
    "kanji_ugoku|運動": "exercise",
    "kanji_ugoku|自動": "automatic",
    "kanji_hayai|早い": "early",
    "kanji_hayai|早朝": "early morning",
    "kanji_hayai|早く": "quickly, early",
    "kanji_osoi|遅い": "slow, late",
    "kanji_osoi|遅れる": "to be late",
    "kanji_osoi|遅刻": "lateness",
    "kanji_tsuyoi|強い": "strong",
    "kanji_tsuyoi|勉強": "study",
    "kanji_tsuyoi|強調": "emphasis",
    "kanji_yowai|弱い": "weak",
    "kanji_yowai|弱点": "weak point",
    "kanji_yowai|弱虫": "coward",
    "kanji_omoi|重い": "heavy",
    "kanji_omoi|重要": "important",
    "kanji_omoi|体重": "body weight",
    "kanji_karui|軽い": "light (in weight)",
    "kanji_karui|軽食": "light meal",
    "kanji_karui|気軽": "easy-going",
    "kanji_kurai|暗い": "dark",
    "kanji_kurai|暗記": "memorising by heart",
    "kanji_kurai|真っ暗": "pitch dark",
    "kanji_akarui|明るい": "bright, cheerful",
    "kanji_akarui|説明": "explanation",
    "kanji_akarui|明日": "tomorrow",
    "kanji_fukai|深い": "deep",
    "kanji_fukai|深夜": "late at night",
    "kanji_fukai|深呼吸": "deep breath",
    "kanji_asai|浅い": "shallow",
    "kanji_asai|浅瀬": "shallows",
    "kanji_asai|経験が浅い": "inexperienced",
    "kanji_futoi|太い": "thick, fat",
    "kanji_futoi|太る": "to gain weight",
    "kanji_futoi|丸太": "log",
    "kanji_hosoi|細い": "thin, slender",
    "kanji_hosoi|細かい": "detailed, fine",
    "kanji_hosoi|詳細": "details",
    "kanji_zu|図書館": "library",
    "kanji_zu|地図": "map",
    "kanji_zu|図": "diagram",
    "kanji_i2|意味": "meaning",
    "kanji_i2|意見": "opinion",
    "kanji_i2|注意": "attention, caution",
    "kanji_aji|味": "taste",
    "kanji_aji|意味": "meaning",
    "kanji_aji|趣味": "hobby",
    "kanji_kubaru|配る": "to distribute",
    "kanji_kubaru|心配": "worry",
    "kanji_kubaru|宅配": "home delivery",
    "kanji_kata2|方法": "method",
    "kanji_kata2|使い方": "how to use",
    "kanji_kata2|あの方": "that person (polite)",
    "kanji_shi2|仕事": "work",
    "kanji_shi2|仕方": "way of doing",
    "kanji_shi2|仕える": "to serve",
    "kanji_shitsu|教室": "classroom",
    "kanji_shitsu|図書室": "library room",
    "kanji_shitsu|室内": "indoors",
    "kanji_noru|乗る": "to board, to ride",
    "kanji_noru|乗客": "passenger",
    "kanji_noru|乗り物": "vehicle",
    "kanji_oriru|降りる": "to get off",
    "kanji_oriru|降る": "to fall (rain/snow)",
    "kanji_oriru|乗降": "getting on and off",
    "kanji_tooru|通る": "to pass through",
    "kanji_tooru|通学": "commuting to school",
    "kanji_tooru|交通": "traffic, transport",
    "kanji_suki2|好き": "to like",
    "kanji_suki2|好物": "favourite food",
    "kanji_suki2|大好き": "to love, to really like",
    "kanji_kirai|嫌い": "to dislike",
    "kanji_kirai|嫌がる": "to be reluctant",
    "kanji_kirai|機嫌": "mood",
    "kanji_tanoshii|楽しい": "fun",
    "kanji_tanoshii|音楽": "music",
    "kanji_tanoshii|楽": "easy, comfortable",
    "kanji_aka2|赤い": "red",
    "kanji_aka2|赤": "the colour red",
    "kanji_aka2|赤ちゃん": "baby",
    "kanji_ao|青い": "blue",
    "kanji_ao|青空": "blue sky",
    "kanji_ao|青年": "young man",
    "kanji_kuro|黒い": "black",
    "kanji_kuro|黒板": "blackboard",
    "kanji_kuro|黒字": "surplus, in the black",
    "kanji_mukashi|昔": "long ago",
    "kanji_mukashi|昔話": "folk tale",
    "kanji_mukashi|大昔": "ancient times",
    "kanji_toku|特に": "especially",
    "kanji_toku|特別": "special",
    "kanji_toku|特急": "limited express train",
    "kanji_isogu|急ぐ": "to hurry",
    "kanji_isogu|急に": "suddenly",
    "kanji_isogu|特急": "limited express train",
    "kanji_aru|有名": "famous",
    "kanji_aru|有る": "to exist, to have",
    "kanji_aru|有名人": "celebrity",
    "kanji_nai2|無い": "to not exist",
    "kanji_nai2|無料": "free of charge",
    "kanji_nai2|無理": "impossible, unreasonable",
    "kanji_zen2|全部": "all",
    "kanji_zen2|全然": "not at all",
    "kanji_zen2|全国": "the whole country",
    "kanji_bu|部屋": "room",
    "kanji_bu|全部": "all",
    "kanji_bu|部長": "department head",
    "kanji_chikai|近い": "near",
    "kanji_chikai|近く": "nearby",
    "kanji_chikai|最近": "recently",
    "kanji_tooi|遠い": "far",
    "kanji_tooi|遠足": "school excursion",
    "kanji_tooi|遠慮": "restraint, holding back",
    "kanji_mi2|実は": "actually",
    "kanji_mi2|実際": "reality, actually",
    "kanji_mi2|事実": "fact",
    "kanji_zen3|全然": "not at all",
    "kanji_zen3|自然": "nature",
    "kanji_zen3|当然": "of course",
    "kanji_kyuu2|研究": "research",
    "kanji_kyuu2|研究者": "researcher",
    "kanji_kyuu2|追究": "close investigation",
    "kanji_ken2|研究": "research",
    "kanji_ken2|研修": "training",
    "kanji_ken2|研究室": "laboratory, research room",
    "kanji_ri2|料理": "cooking, dish",
    "kanji_ri2|理由": "reason",
    "kanji_ri2|理解": "understanding",
    "kanji_ka2|教科書": "textbook",
    "kanji_ka2|科学": "science",
    "kanji_ka2|内科": "internal medicine",
    "kanji_ya2|屋根": "roof",
    "kanji_ya2|八百屋": "greengrocer",
    "kanji_ya2|部屋": "room",
    "kanji_dai2|台所": "kitchen",
    "kanji_dai2|一台": "one unit (of machinery)",
    "kanji_dai2|台風": "typhoon",
    "kanji_tokoro|所": "place",
    "kanji_tokoro|場所": "location",
    "kanji_tokoro|台所": "kitchen",
    "kanji_gyou|授業": "lesson, class",
    "kanji_gyou|卒業": "graduation",
    "kanji_gyou|職業": "occupation",
    "kanji_kai2|世界": "world",
    "kanji_kai2|業界": "industry",
    "kanji_kai2|限界": "limit",
    "kanji_kei2|時計": "clock, watch",
    "kanji_kei2|計画": "plan",
    "kanji_kei2|合計": "total",
    "kanji_ga2|映画": "film",
    "kanji_ga2|計画": "plan",
    "kanji_ga2|絵画": "painting",
    "kanji_hin|品物": "goods",
    "kanji_hin|作品": "a work (of art)",
    "kanji_hin|商品": "product",
    "kanji_tateru|建てる": "to build",
    "kanji_tateru|建物": "building",
    "kanji_tateru|建設": "construction",
    "kanji_okiru|起きる": "to get up",
    "kanji_okiru|起こる": "to happen",
    "kanji_okiru|早起き": "getting up early",
    "kanji_neru|寝る": "to sleep",
    "kanji_neru|寝室": "bedroom",
    "kanji_neru|昼寝": "afternoon nap",
    "kanji_kiru2|着る": "to wear",
    "kanji_kiru2|到着": "arrival",
    "kanji_kiru2|着く": "to arrive",
    "kanji_arau|洗う": "to wash",
    "kanji_arau|洗濯": "laundry",
    "kanji_arau|洗面所": "washroom",
    "kanji_tsuzuku|続く": "to continue (intransitive)",
    "kanji_tsuzuku|続ける": "to continue (transitive)",
    "kanji_tsuzuku|継続": "continuation",
    "kanji_wakai|若い": "young",
    "kanji_wakai|若者": "young person",
    "kanji_wakai|若干": "somewhat, a few",
    "kanji_isogashii2|忙しい": "busy",
    "kanji_isogashii2|大忙し": "very busy",
    "kanji_isogashii2|忙しさ": "busyness",
    "kanji_kan2|漢字": "kanji",
    "kanji_kan2|漢方": "traditional Chinese medicine",
    "kanji_kan2|漢語": "Sino-Japanese word",
    "kanji_susumu|進む": "to advance",
    "kanji_susumu|進歩": "progress",
    "kanji_susumu|前進": "moving forward",
    "kanji_modoru|戻る": "to return",
    "kanji_modoru|戻す": "to put back",
    "kanji_modoru|払い戻し": "refund",
    "kanji_sodatsu|育てる": "to raise",
    "kanji_sodatsu|教育": "education",
    "kanji_sodatsu|体育": "physical education",
    "kanji_fuku2|服": "clothes",
    "kanji_fuku2|洋服": "Western clothing",
    "kanji_fuku2|制服": "uniform",
    "kanji_yu2|理由": "reason",
    "kanji_yu2|自由": "freedom",
    "kanji_yu2|由来": "origin",
    "kanji_jibun|自分": "oneself",
    "kanji_jibun|自由": "freedom",
    "kanji_jibun|自動車": "car",
    "kanji_ri3|便利": "convenient",
    "kanji_ri3|利用": "use, utilisation",
    "kanji_ri3|利益": "profit",
    "kanji_you3|使用": "use",
    "kanji_you3|利用": "utilisation",
    "kanji_you3|用事": "errand",
    "kanji_kanashii|悲しい": "sad",
    "kanji_kanashii|悲しみ": "sadness",
    "kanji_kanashii|悲劇": "tragedy",
    "kanji_zoku2|家族": "family",
    "kanji_zoku2|民族": "ethnic group",
    "kanji_zoku2|親族": "relatives",
    "kanji_teki|目的": "purpose",
    "kanji_teki|一般的": "general",
    "kanji_teki|的": "target",
    "kanji_arawasu|表す": "to express",
    "kanji_arawasu|表": "table, chart",
    "kanji_arawasu|発表": "presentation",
    "kanji_arawareru|現れる": "to appear",
    "kanji_arawareru|現在": "the present",
    "kanji_arawareru|表現": "expression",
    "kanji_zai|現在": "the present",
    "kanji_zai|存在": "existence",
    "kanji_zai|在学": "being enrolled at school",
    "kanji_au2|合う": "to match, to fit",
    "kanji_au2|合わせる": "to combine",
    "kanji_au2|都合": "circumstances, convenience",
    "kanji_warui|悪い": "bad",
    "kanji_warui|悪天候": "bad weather",
    "kanji_warui|意地悪": "mean, spiteful",
    "kanji_kurushii|苦しい": "painful, difficult",
    "kanji_kurushii|苦い": "bitter",
    "kanji_kurushii|苦手": "not good at",
    "kanji_kan3|感じる": "to feel",
    "kanji_kan3|感動": "being moved",
    "kanji_kan3|感謝": "gratitude",
    "kanji_shitsu2|質問": "question",
    "kanji_shitsu2|品質": "quality",
    "kanji_shitsu2|性質": "nature, character",
    "kanji_mon2|質問": "question",
    "kanji_mon2|問題": "problem",
    "kanji_mon2|問う": "to ask",
    "kanji_dai3|問題": "problem",
    "kanji_dai3|宿題": "homework",
    "kanji_dai3|話題": "topic",
    "kanji_rei2|例えば": "for example",
    "kanji_rei2|例": "example",
    "kanji_rei2|実例": "concrete example",
    "kanji_kaesu|返す": "to return something",
    "kanji_kaesu|返事": "reply",
    "kanji_kaesu|返答": "answer",
    "kanji_kotaeru|答える": "to answer",
    "kanji_kotaeru|答え": "answer",
    "kanji_kotaeru|返答": "answer",
    "kanji_tadashii|正しい": "correct",
    "kanji_tadashii|正月": "New Year",
    "kanji_tadashii|正直": "honest",
    "kanji_sama|皆様": "everyone (polite)",
    "kanji_sama|様子": "situation, appearance",
    "kanji_sama|同様": "the same",
    "kanji_komaru|困る": "to be troubled",
    "kanji_komaru|困難": "difficulty",
    "kanji_komaru|貧困": "poverty",
}
