"""
kanji_word_meaning_en.py

Locked source of truth for the English glosses of every kanji entry's
`wordExamples` ("contoh kata") — the `meaningEn` field on
`KanjiWordExample`. apply_kanji_word_meaning_en.py reads this and patches
assets/data/kanji_data.json, so translations live in exactly one place.

Known data quirk: 也 (kanji_ya_n1) lists the word 也 twice in its own
wordExamples, so the dataset has 7,275 examples but only 7,274 distinct
keys — patching that key fills both slots with the same gloss, which is
correct here since both rows are the same word. Worth fixing in
generate_kanji_seed.py if that entry is ever revisited.

Key format: "{kanji_id}|{word}". The kanji id is part of the key because
the same compound can appear under several kanji (一人 sits under both 一
and 人), and each of those slots is patched independently.

Must be re-applied after generate_kanji_seed.py regenerates the dataset,
same as split_kanji_meanings_en.py.

STATUS: N5 (321), N4 (399) and N3 (945) done = 1,665/7,274. N2 (1,101)
    and N1 (4,509) pending — 5,609 glosses left, best done one JLPT level
    at a time. Dump the next level's rows with:
        python -c "import json; d=json.load(open('assets/data/kanji_data.json', encoding='utf-8')); [print(f\"{e['id']}|{w['word']} :: {w['meaning']}\") for e in d if e['jlptLevel']=='N4' for w in e['wordExamples']]"
    then translate, append a block below, and run the applier (it prints
    per-level coverage so progress is visible).

Style: translate the Indonesian gloss as it stands — short, no new senses.
"""

WORD_MEANING_EN = {
    # ---------------- N5 ----------------
    "kanji_ichi|一つ": "one (item)",
    "kanji_ichi|一月": "January",
    "kanji_ichi|一人": "one person, alone",
    "kanji_ni|二つ": "two (items)",
    "kanji_ni|二月": "February",
    "kanji_ni|二人": "two people",
    "kanji_san|三つ": "three (items)",
    "kanji_san|三月": "March",
    "kanji_san|三人": "three people",
    "kanji_yon|四月": "April",
    "kanji_yon|四人": "four people",
    "kanji_yon|四つ": "four (items)",
    "kanji_go|五つ": "five (items)",
    "kanji_go|五月": "May",
    "kanji_go|五人": "five people",
    "kanji_roku|六月": "June",
    "kanji_roku|六つ": "six (items)",
    "kanji_roku|六人": "six people",
    "kanji_shichi|七つ": "seven (items)",
    "kanji_shichi|七月": "July",
    "kanji_shichi|七人": "seven people",
    "kanji_hachi|八月": "August",
    "kanji_hachi|八つ": "eight (items)",
    "kanji_hachi|八人": "eight people",
    "kanji_kyuu|九つ": "nine (items)",
    "kanji_kyuu|九月": "September",
    "kanji_kyuu|九人": "nine people",
    "kanji_juu|十日": "the tenth, ten days",
    "kanji_juu|十人": "ten people",
    "kanji_juu|十月": "October",
    "kanji_hito|日本人": "Japanese person",
    "kanji_hito|一人": "one person, alone",
    "kanji_hito|人々": "people",
    "kanji_hi|日曜日": "Sunday",
    "kanji_hi|毎日": "every day",
    "kanji_hi|誕生日": "birthday",
    "kanji_tsuki|月曜日": "Monday",
    "kanji_tsuki|月": "moon",
    "kanji_tsuki|今月": "this month",
    "kanji_yama|富士山": "Mount Fuji",
    "kanji_yama|山": "mountain",
    "kanji_yama|登山": "mountain climbing",
    "kanji_kawa|川": "river",
    "kanji_kawa|小川": "stream",
    "kanji_kawa|川岸": "riverbank",
    "kanji_hyaku|百円": "one hundred yen",
    "kanji_hyaku|百人": "one hundred people",
    "kanji_hyaku|百点": "a perfect score",
    "kanji_sen|千円": "one thousand yen",
    "kanji_sen|千人": "one thousand people",
    "kanji_sen|二千": "two thousand",
    "kanji_man|一万円": "ten thousand yen",
    "kanji_man|万年筆": "fountain pen",
    "kanji_man|十万": "one hundred thousand",
    "kanji_en|円": "yen",
    "kanji_en|百円": "one hundred yen",
    "kanji_en|千円": "one thousand yen",
    "kanji_nen|来年": "next year",
    "kanji_nen|今年": "this year",
    "kanji_nen|毎年": "every year",
    "kanji_ji|時間": "time, hour",
    "kanji_ji|何時": "what time",
    "kanji_ji|時々": "sometimes",
    "kanji_fun|五分": "five minutes",
    "kanji_fun|分かる": "to understand",
    "kanji_fun|半分": "half",
    "kanji_kan|時間": "time",
    "kanji_kan|間": "interval, gap",
    "kanji_kan|一週間": "one week",
    "kanji_shuu|今週": "this week",
    "kanji_shuu|来週": "next week",
    "kanji_shuu|毎週": "every week",
    "kanji_you|曜日": "day of the week",
    "kanji_you|月曜日": "Monday",
    "kanji_you|何曜日": "which day of the week",
    "kanji_ima|今": "now",
    "kanji_ima|今日": "today",
    "kanji_ima|今年": "this year",
    "kanji_han|半分": "half",
    "kanji_han|一時半": "half past one",
    "kanji_han|半年": "half a year",
    "kanji_ki|木曜日": "Thursday",
    "kanji_ki|木": "tree",
    "kanji_ki|大木": "large tree",
    "kanji_hayashi|林": "woods",
    "kanji_hayashi|森林": "forest",
    "kanji_hayashi|山林": "mountain forest",
    "kanji_mori|森": "forest",
    "kanji_mori|森林": "forest",
    "kanji_mori|深い森": "deep forest",
    "kanji_ta|田んぼ": "rice field",
    "kanji_ta|水田": "paddy field",
    "kanji_ta|田植え": "rice planting",
    "kanji_hi2|火曜日": "Tuesday",
    "kanji_hi2|火": "fire",
    "kanji_hi2|花火": "fireworks",
    "kanji_mizu|水曜日": "Wednesday",
    "kanji_mizu|水": "water",
    "kanji_mizu|水泳": "swimming",
    "kanji_tsuchi|土曜日": "Saturday",
    "kanji_tsuchi|土": "soil",
    "kanji_tsuchi|土地": "land, plot",
    "kanji_sora|空": "sky",
    "kanji_sora|空気": "air",
    "kanji_sora|空港": "airport",
    "kanji_ki2|元気": "healthy, energetic",
    "kanji_ki2|天気": "weather",
    "kanji_ki2|気持ち": "feeling",
    "kanji_ame|雨": "rain",
    "kanji_ame|大雨": "heavy rain",
    "kanji_ame|雨天": "rainy weather",
    "kanji_ishi|石": "stone",
    "kanji_ishi|石鹸": "soap",
    "kanji_ishi|宝石": "gemstone",
    "kanji_hana|花": "flower",
    "kanji_hana|花見": "cherry-blossom viewing",
    "kanji_hana|花瓶": "vase",
    "kanji_ko|子供": "child",
    "kanji_ko|女の子": "girl",
    "kanji_ko|男の子": "boy",
    "kanji_onna|女性": "woman",
    "kanji_onna|女の子": "girl",
    "kanji_onna|彼女": "she, girlfriend",
    "kanji_otoko|男性": "man",
    "kanji_otoko|男の子": "boy",
    "kanji_otoko|長男": "eldest son",
    "kanji_na|名前": "name",
    "kanji_na|有名": "famous",
    "kanji_na|名字": "surname",
    "kanji_mae|名前": "name",
    "kanji_mae|前": "front, before",
    "kanji_mae|午前": "morning, a.m.",
    "kanji_gaku|学校": "school",
    "kanji_gaku|学生": "student",
    "kanji_gaku|大学": "university",
    "kanji_sei|学生": "student",
    "kanji_sei|先生": "teacher",
    "kanji_sei|生まれる": "to be born",
    "kanji_saki|先生": "teacher",
    "kanji_saki|先週": "last week",
    "kanji_saki|先に": "beforehand, first",
    "kanji_tomo|友達": "friend",
    "kanji_tomo|親友": "close friend",
    "kanji_tomo|友人": "friend (formal)",
    "kanji_watashi|私": "I, me",
    "kanji_watashi|私立": "private (institution)",
    "kanji_watashi|私達": "we, us",
    "kanji_chichi|父": "my father",
    "kanji_chichi|お父さん": "father (general term)",
    "kanji_chichi|父親": "father",
    "kanji_haha|母": "my mother",
    "kanji_haha|お母さん": "mother (general term)",
    "kanji_haha|母国": "homeland",
    "kanji_me|目": "eye",
    "kanji_me|目的": "purpose",
    "kanji_me|一つ目": "the first one",
    "kanji_kuchi|口": "mouth",
    "kanji_kuchi|入り口": "entrance",
    "kanji_kuchi|人口": "population",
    "kanji_te|手": "hand",
    "kanji_te|上手": "skilled, good at",
    "kanji_te|手紙": "letter",
    "kanji_ashi|足": "foot, leg",
    "kanji_ashi|足りる": "to be enough",
    "kanji_ashi|一足": "one pair (of shoes)",
    "kanji_ue|上": "above, up",
    "kanji_ue|上手": "skilled",
    "kanji_ue|屋上": "rooftop",
    "kanji_shita|下": "below, down",
    "kanji_shita|下手": "unskilled",
    "kanji_shita|地下": "underground",
    "kanji_naka|中": "inside, middle",
    "kanji_naka|中国": "China",
    "kanji_naka|一日中": "all day long",
    "kanji_soto|外": "outside",
    "kanji_soto|外国": "foreign country",
    "kanji_soto|外国人": "foreigner",
    "kanji_hidari|左": "left",
    "kanji_hidari|左手": "left hand",
    "kanji_hidari|左側": "left side",
    "kanji_migi|右": "right",
    "kanji_migi|右手": "right hand",
    "kanji_migi|右側": "right side",
    "kanji_ato|後で": "later",
    "kanji_ato|午後": "afternoon, p.m.",
    "kanji_ato|後ろ": "behind",
    "kanji_higashi|東": "east",
    "kanji_higashi|東京": "Tokyo",
    "kanji_higashi|東口": "east exit",
    "kanji_nishi|西": "west",
    "kanji_nishi|西口": "west exit",
    "kanji_nishi|関西": "the Kansai region",
    "kanji_minami|南": "south",
    "kanji_minami|南口": "south exit",
    "kanji_minami|南国": "southern country",
    "kanji_kita|北": "north",
    "kanji_kita|北海道": "Hokkaido",
    "kanji_kita|北口": "north exit",
    "kanji_iku|行く": "to go",
    "kanji_iku|銀行": "bank",
    "kanji_iku|旅行": "travel",
    "kanji_kuru|来る": "to come",
    "kanji_kuru|来年": "next year",
    "kanji_kuru|来週": "next week",
    "kanji_taberu|食べる": "to eat",
    "kanji_taberu|食事": "a meal",
    "kanji_taberu|朝食": "breakfast",
    "kanji_nomu|飲む": "to drink",
    "kanji_nomu|飲み物": "a drink",
    "kanji_nomu|飲食店": "restaurant, eatery",
    "kanji_miru|見る": "to see",
    "kanji_miru|見学": "study visit",
    "kanji_miru|意見": "opinion",
    "kanji_kiku|聞く": "to hear, to ask",
    "kanji_kiku|新聞": "newspaper",
    "kanji_kiku|聞こえる": "to be audible",
    "kanji_yomu|読む": "to read",
    "kanji_yomu|読書": "reading books",
    "kanji_yomu|音読": "reading aloud",
    "kanji_kaku|書く": "to write",
    "kanji_kaku|辞書": "dictionary",
    "kanji_kaku|図書館": "library",
    "kanji_hanasu|話す": "to speak",
    "kanji_hanasu|電話": "telephone",
    "kanji_hanasu|会話": "conversation",
    "kanji_kau|買う": "to buy",
    "kanji_kau|買い物": "shopping",
    "kanji_kau|購買": "purchasing",
    "kanji_uru|売る": "to sell",
    "kanji_uru|発売": "release for sale",
    "kanji_uru|売店": "kiosk",
    "kanji_tatsu|立つ": "to stand",
    "kanji_tatsu|国立": "national (state-run)",
    "kanji_tatsu|立派": "splendid",
    "kanji_yasumu|休む": "to rest",
    "kanji_yasumu|休み": "holiday, break",
    "kanji_yasumu|休日": "day off",
    "kanji_hairu|入る": "to enter",
    "kanji_hairu|入学": "entering school",
    "kanji_hairu|入り口": "entrance",
    "kanji_deru|出る": "to go out",
    "kanji_deru|出口": "exit",
    "kanji_deru|出発": "departure",
    "kanji_au|会う": "to meet",
    "kanji_au|会議": "meeting",
    "kanji_au|会社": "company",
    "kanji_kou|学校": "school",
    "kanji_kou|校長": "principal",
    "kanji_kou|高校": "high school",
    "kanji_go2|日本語": "Japanese language",
    "kanji_go2|英語": "English language",
    "kanji_go2|単語": "vocabulary word",
    "kanji_bun|文章": "writing, text",
    "kanji_bun|文法": "grammar",
    "kanji_bun|作文": "essay, composition",
    "kanji_ji2|漢字": "kanji",
    "kanji_ji2|文字": "letter, character",
    "kanji_ji2|字": "character",
    "kanji_hon|本": "book",
    "kanji_hon|日本": "Japan",
    "kanji_hon|本当": "true, really",
    "kanji_kuni|国": "country",
    "kanji_kuni|外国": "foreign country",
    "kanji_kuni|中国": "China",
    "kanji_machi|町": "town",
    "kanji_machi|下町": "old downtown area",
    "kanji_machi|町長": "town mayor",
    "kanji_mura|村": "village",
    "kanji_mura|農村": "farming village",
    "kanji_mura|村人": "villager",
    "kanji_eki|駅": "station",
    "kanji_eki|駅員": "station attendant",
    "kanji_eki|駅前": "in front of the station",
    "kanji_mise|店": "shop",
    "kanji_mise|店員": "shop assistant",
    "kanji_mise|喫茶店": "coffee shop",
    "kanji_ie|家": "house",
    "kanji_ie|家族": "family",
    "kanji_ie|家庭": "household",
    "kanji_ookii|大きい": "big",
    "kanji_ookii|大学": "university",
    "kanji_ookii|大切": "important",
    "kanji_chiisai|小さい": "small",
    "kanji_chiisai|小学校": "primary school",
    "kanji_chiisai|小説": "novel",
    "kanji_ooi|多い": "many",
    "kanji_ooi|多分": "probably",
    "kanji_ooi|多数": "a large number",
    "kanji_sukunai|少ない": "few",
    "kanji_sukunai|少し": "a little",
    "kanji_sukunai|少年": "boy, youth",
    "kanji_takai|高い": "tall, expensive",
    "kanji_takai|高校": "high school",
    "kanji_takai|高速": "high speed",
    "kanji_yasui|安い": "cheap",
    "kanji_yasui|安全": "safe",
    "kanji_yasui|不安": "anxious",
    "kanji_atarashii|新しい": "new",
    "kanji_atarashii|新聞": "newspaper",
    "kanji_atarashii|新年": "new year",
    "kanji_furui|古い": "old",
    "kanji_furui|中古": "second-hand",
    "kanji_furui|古本": "used book",
    "kanji_nagai|長い": "long",
    "kanji_nagai|社長": "company president",
    "kanji_nagai|校長": "principal",
    "kanji_shiro|白い": "white",
    "kanji_shiro|白": "the colour white",
    "kanji_shiro|面白い": "interesting, funny",
    "kanji_nani|何": "what",
    "kanji_nani|何時": "what time",
    "kanji_nani|何人": "how many people",
    "kanji_kuruma|車": "car",
    "kanji_kuruma|電車": "train",
    "kanji_kuruma|自動車": "motor vehicle",
    "kanji_den|電車": "train",
    "kanji_den|電話": "telephone",
    "kanji_den|電気": "electricity, light",
    "kanji_michi|道": "road",
    "kanji_michi|道路": "roadway",
    "kanji_michi|北海道": "Hokkaido",

    # ---------------- N4 ----------------
    "kanji_asa|朝": "morning",
    "kanji_asa|朝食": "breakfast",
    "kanji_asa|毎朝": "every morning",
    "kanji_hiru|昼": "daytime, noon",
    "kanji_hiru|昼食": "lunch",
    "kanji_hiru|昼休み": "lunch break",
    "kanji_yoru|夜": "night",
    "kanji_yoru|今夜": "tonight",
    "kanji_yoru|夜中": "midnight",
    "kanji_do|今度": "this time, next time",
    "kanji_do|一度": "once",
    "kanji_do|温度": "temperature",
    "kanji_yuki|雪": "snow",
    "kanji_yuki|大雪": "heavy snow",
    "kanji_yuki|雪国": "snow country",
    "kanji_kaze|風": "wind",
    "kanji_kaze|台風": "typhoon",
    "kanji_kaze|風邪": "a cold",
    "kanji_oto|音": "sound",
    "kanji_oto|音楽": "music",
    "kanji_oto|発音": "pronunciation",
    "kanji_hikari|光": "light",
    "kanji_hikari|日光": "sunlight",
    "kanji_hikari|光る": "to shine",
    "kanji_karada|体": "body",
    "kanji_karada|体育": "physical education",
    "kanji_karada|体重": "body weight",
    "kanji_kokoro|心": "heart, mind",
    "kanji_kokoro|心配": "worry",
    "kanji_kokoro|安心": "relief",
    "kanji_atama|頭": "head",
    "kanji_atama|頭痛": "headache",
    "kanji_atama|石頭": "stubborn person",
    "kanji_yamai|病気": "illness",
    "kanji_yamai|病院": "hospital",
    "kanji_yamai|病人": "sick person",
    "kanji_shinu|死ぬ": "to die",
    "kanji_shinu|死": "death",
    "kanji_shinu|必死": "desperately",
    "kanji_kao|顔": "face",
    "kanji_kao|笑顔": "smiling face",
    "kanji_kao|顔色": "complexion",
    "kanji_koe|声": "voice",
    "kanji_koe|大声": "loud voice",
    "kanji_koe|声優": "voice actor",
    "kanji_imouto|妹": "younger sister",
    "kanji_imouto|妹さん": "someone's younger sister",
    "kanji_imouto|姉妹": "sisters",
    "kanji_otouto|弟": "younger brother",
    "kanji_otouto|弟さん": "someone's younger brother",
    "kanji_otouto|兄弟": "siblings",
    "kanji_ani|兄": "older brother",
    "kanji_ani|お兄さん": "older brother (general term)",
    "kanji_ani|兄弟": "siblings",
    "kanji_ane|姉": "older sister",
    "kanji_ane|お姉さん": "older sister (general term)",
    "kanji_ane|姉妹": "sisters",
    "kanji_nushi|主人": "husband, host",
    "kanji_nushi|主な": "main",
    "kanji_nushi|持ち主": "owner",
    "kanji_mono|医者": "doctor",
    "kanji_mono|若者": "young person",
    "kanji_mono|学者": "scholar",
    "kanji_in|会社員": "company employee",
    "kanji_in|店員": "shop assistant",
    "kanji_in|会員": "member",
    "kanji_tsukau|使う": "to use",
    "kanji_tsukau|使用": "use",
    "kanji_tsukau|大使": "ambassador",
    "kanji_tsukuru|作る": "to make",
    "kanji_tsukuru|作文": "composition",
    "kanji_tsukuru|作品": "a work (of art)",
    "kanji_omou|思う": "to think",
    "kanji_omou|思い出": "memory",
    "kanji_omou|意思": "intention",
    "kanji_shiru|知る": "to know",
    "kanji_shiru|知識": "knowledge",
    "kanji_shiru|知らせる": "to inform",
    "kanji_motsu|持つ": "to hold, to carry",
    "kanji_motsu|気持ち": "feeling",
    "kanji_motsu|持ち物": "belongings",
    "kanji_asobu|遊ぶ": "to play",
    "kanji_asobu|遊園地": "amusement park",
    "kanji_asobu|遊び": "play, game",
    "kanji_hataraku|働く": "to work",
    "kanji_hataraku|労働": "labour",
    "kanji_hataraku|共働き": "both spouses working",
    "kanji_hashiru|走る": "to run",
    "kanji_hashiru|競走": "a race",
    "kanji_hashiru|走者": "runner",
    "kanji_oyogu|泳ぐ": "to swim",
    "kanji_oyogu|水泳": "swimming",
    "kanji_oyogu|平泳ぎ": "breaststroke",
    "kanji_tobu|飛ぶ": "to fly",
    "kanji_tobu|飛行機": "aeroplane",
    "kanji_tobu|飛行場": "airfield",
    "kanji_okuru|送る": "to send, to see off",
    "kanji_okuru|送料": "shipping fee",
    "kanji_okuru|見送る": "to see someone off",
    "kanji_oshieru|教える": "to teach",
    "kanji_oshieru|教室": "classroom",
    "kanji_oshieru|教育": "education",
    "kanji_narau|習う": "to learn",
    "kanji_narau|練習": "practice",
    "kanji_narau|予習": "preparation before class",
    "kanji_oboeru|覚える": "to memorise",
    "kanji_oboeru|覚えている": "to remember",
    "kanji_oboeru|目覚める": "to wake up",
    "kanji_wasureru|忘れる": "to forget",
    "kanji_wasureru|忘れ物": "lost property",
    "kanji_wasureru|物忘れ": "forgetfulness",
    "kanji_kimeru|決める": "to decide",
    "kanji_kimeru|決定": "decision",
    "kanji_kimeru|決して": "never (with negative)",
    "kanji_wakareru|別れる": "to part, to break up",
    "kanji_wakareru|別に": "not particularly",
    "kanji_wakareru|特別": "special",
    "kanji_kawaru|変わる": "to change (intransitive)",
    "kanji_kawaru|変える": "to change (transitive)",
    "kanji_kawaru|大変": "tough, very",
    "kanji_hajimeru|始める": "to start (transitive)",
    "kanji_hajimeru|始まる": "to begin (intransitive)",
    "kanji_hajimeru|開始": "commencement",
    "kanji_owaru|終わる": "to end",
    "kanji_owaru|終電": "last train",
    "kanji_owaru|最終": "final",
    "kanji_hiraku|開く": "to open",
    "kanji_hiraku|開ける": "to open (transitive)",
    "kanji_hiraku|開店": "shop opening",
    "kanji_shimeru|閉じる": "to close",
    "kanji_shimeru|閉める": "to shut",
    "kanji_shimeru|閉店": "shop closing",
    "kanji_atsumaru|集まる": "to gather (intransitive)",
    "kanji_atsumaru|集める": "to collect",
    "kanji_atsumaru|集合": "assembly, gathering",
    "kanji_ugoku|動く": "to move",
    "kanji_ugoku|運動": "exercise",
    "kanji_ugoku|自動": "automatic",
    "kanji_hayai|早い": "early",
    "kanji_hayai|早朝": "early morning",
    "kanji_hayai|早く": "quickly, early",
    "kanji_osoi|遅い": "slow, late",
    "kanji_osoi|遅れる": "to be late",
    "kanji_osoi|遅刻": "lateness",
    "kanji_tsuyoi|強い": "strong",
    "kanji_tsuyoi|勉強": "study",
    "kanji_tsuyoi|強調": "emphasis",
    "kanji_yowai|弱い": "weak",
    "kanji_yowai|弱点": "weak point",
    "kanji_yowai|弱虫": "coward",
    "kanji_omoi|重い": "heavy",
    "kanji_omoi|重要": "important",
    "kanji_omoi|体重": "body weight",
    "kanji_karui|軽い": "light (in weight)",
    "kanji_karui|軽食": "light meal",
    "kanji_karui|気軽": "easy-going",
    "kanji_kurai|暗い": "dark",
    "kanji_kurai|暗記": "memorising by heart",
    "kanji_kurai|真っ暗": "pitch dark",
    "kanji_akarui|明るい": "bright, cheerful",
    "kanji_akarui|説明": "explanation",
    "kanji_akarui|明日": "tomorrow",
    "kanji_fukai|深い": "deep",
    "kanji_fukai|深夜": "late at night",
    "kanji_fukai|深呼吸": "deep breath",
    "kanji_asai|浅い": "shallow",
    "kanji_asai|浅瀬": "shallows",
    "kanji_asai|経験が浅い": "inexperienced",
    "kanji_futoi|太い": "thick, fat",
    "kanji_futoi|太る": "to gain weight",
    "kanji_futoi|丸太": "log",
    "kanji_hosoi|細い": "thin, slender",
    "kanji_hosoi|細かい": "detailed, fine",
    "kanji_hosoi|詳細": "details",
    "kanji_zu|図書館": "library",
    "kanji_zu|地図": "map",
    "kanji_zu|図": "diagram",
    "kanji_i2|意味": "meaning",
    "kanji_i2|意見": "opinion",
    "kanji_i2|注意": "attention, caution",
    "kanji_aji|味": "taste",
    "kanji_aji|意味": "meaning",
    "kanji_aji|趣味": "hobby",
    "kanji_kubaru|配る": "to distribute",
    "kanji_kubaru|心配": "worry",
    "kanji_kubaru|宅配": "home delivery",
    "kanji_kata2|方法": "method",
    "kanji_kata2|使い方": "how to use",
    "kanji_kata2|あの方": "that person (polite)",
    "kanji_shi2|仕事": "work",
    "kanji_shi2|仕方": "way of doing",
    "kanji_shi2|仕える": "to serve",
    "kanji_shitsu|教室": "classroom",
    "kanji_shitsu|図書室": "library room",
    "kanji_shitsu|室内": "indoors",
    "kanji_noru|乗る": "to board, to ride",
    "kanji_noru|乗客": "passenger",
    "kanji_noru|乗り物": "vehicle",
    "kanji_oriru|降りる": "to get off",
    "kanji_oriru|降る": "to fall (rain/snow)",
    "kanji_oriru|乗降": "getting on and off",
    "kanji_tooru|通る": "to pass through",
    "kanji_tooru|通学": "commuting to school",
    "kanji_tooru|交通": "traffic, transport",
    "kanji_suki2|好き": "to like",
    "kanji_suki2|好物": "favourite food",
    "kanji_suki2|大好き": "to love, to really like",
    "kanji_kirai|嫌い": "to dislike",
    "kanji_kirai|嫌がる": "to be reluctant",
    "kanji_kirai|機嫌": "mood",
    "kanji_tanoshii|楽しい": "fun",
    "kanji_tanoshii|音楽": "music",
    "kanji_tanoshii|楽": "easy, comfortable",
    "kanji_aka2|赤い": "red",
    "kanji_aka2|赤": "the colour red",
    "kanji_aka2|赤ちゃん": "baby",
    "kanji_ao|青い": "blue",
    "kanji_ao|青空": "blue sky",
    "kanji_ao|青年": "young man",
    "kanji_kuro|黒い": "black",
    "kanji_kuro|黒板": "blackboard",
    "kanji_kuro|黒字": "surplus, in the black",
    "kanji_mukashi|昔": "long ago",
    "kanji_mukashi|昔話": "folk tale",
    "kanji_mukashi|大昔": "ancient times",
    "kanji_toku|特に": "especially",
    "kanji_toku|特別": "special",
    "kanji_toku|特急": "limited express train",
    "kanji_isogu|急ぐ": "to hurry",
    "kanji_isogu|急に": "suddenly",
    "kanji_isogu|特急": "limited express train",
    "kanji_aru|有名": "famous",
    "kanji_aru|有る": "to exist, to have",
    "kanji_aru|有名人": "celebrity",
    "kanji_nai2|無い": "to not exist",
    "kanji_nai2|無料": "free of charge",
    "kanji_nai2|無理": "impossible, unreasonable",
    "kanji_zen2|全部": "all",
    "kanji_zen2|全然": "not at all",
    "kanji_zen2|全国": "the whole country",
    "kanji_bu|部屋": "room",
    "kanji_bu|全部": "all",
    "kanji_bu|部長": "department head",
    "kanji_chikai|近い": "near",
    "kanji_chikai|近く": "nearby",
    "kanji_chikai|最近": "recently",
    "kanji_tooi|遠い": "far",
    "kanji_tooi|遠足": "school excursion",
    "kanji_tooi|遠慮": "restraint, holding back",
    "kanji_mi2|実は": "actually",
    "kanji_mi2|実際": "reality, actually",
    "kanji_mi2|事実": "fact",
    "kanji_zen3|全然": "not at all",
    "kanji_zen3|自然": "nature",
    "kanji_zen3|当然": "of course",
    "kanji_kyuu2|研究": "research",
    "kanji_kyuu2|研究者": "researcher",
    "kanji_kyuu2|追究": "close investigation",
    "kanji_ken2|研究": "research",
    "kanji_ken2|研修": "training",
    "kanji_ken2|研究室": "laboratory, research room",
    "kanji_ri2|料理": "cooking, dish",
    "kanji_ri2|理由": "reason",
    "kanji_ri2|理解": "understanding",
    "kanji_ka2|教科書": "textbook",
    "kanji_ka2|科学": "science",
    "kanji_ka2|内科": "internal medicine",
    "kanji_ya2|屋根": "roof",
    "kanji_ya2|八百屋": "greengrocer",
    "kanji_ya2|部屋": "room",
    "kanji_dai2|台所": "kitchen",
    "kanji_dai2|一台": "one unit (of machinery)",
    "kanji_dai2|台風": "typhoon",
    "kanji_tokoro|所": "place",
    "kanji_tokoro|場所": "location",
    "kanji_tokoro|台所": "kitchen",
    "kanji_gyou|授業": "lesson, class",
    "kanji_gyou|卒業": "graduation",
    "kanji_gyou|職業": "occupation",
    "kanji_kai2|世界": "world",
    "kanji_kai2|業界": "industry",
    "kanji_kai2|限界": "limit",
    "kanji_kei2|時計": "clock, watch",
    "kanji_kei2|計画": "plan",
    "kanji_kei2|合計": "total",
    "kanji_ga2|映画": "film",
    "kanji_ga2|計画": "plan",
    "kanji_ga2|絵画": "painting",
    "kanji_hin|品物": "goods",
    "kanji_hin|作品": "a work (of art)",
    "kanji_hin|商品": "product",
    "kanji_tateru|建てる": "to build",
    "kanji_tateru|建物": "building",
    "kanji_tateru|建設": "construction",
    "kanji_okiru|起きる": "to get up",
    "kanji_okiru|起こる": "to happen",
    "kanji_okiru|早起き": "getting up early",
    "kanji_neru|寝る": "to sleep",
    "kanji_neru|寝室": "bedroom",
    "kanji_neru|昼寝": "afternoon nap",
    "kanji_kiru2|着る": "to wear",
    "kanji_kiru2|到着": "arrival",
    "kanji_kiru2|着く": "to arrive",
    "kanji_arau|洗う": "to wash",
    "kanji_arau|洗濯": "laundry",
    "kanji_arau|洗面所": "washroom",
    "kanji_tsuzuku|続く": "to continue (intransitive)",
    "kanji_tsuzuku|続ける": "to continue (transitive)",
    "kanji_tsuzuku|継続": "continuation",
    "kanji_wakai|若い": "young",
    "kanji_wakai|若者": "young person",
    "kanji_wakai|若干": "somewhat, a few",
    "kanji_isogashii2|忙しい": "busy",
    "kanji_isogashii2|大忙し": "very busy",
    "kanji_isogashii2|忙しさ": "busyness",
    "kanji_kan2|漢字": "kanji",
    "kanji_kan2|漢方": "traditional Chinese medicine",
    "kanji_kan2|漢語": "Sino-Japanese word",
    "kanji_susumu|進む": "to advance",
    "kanji_susumu|進歩": "progress",
    "kanji_susumu|前進": "moving forward",
    "kanji_modoru|戻る": "to return",
    "kanji_modoru|戻す": "to put back",
    "kanji_modoru|払い戻し": "refund",
    "kanji_sodatsu|育てる": "to raise",
    "kanji_sodatsu|教育": "education",
    "kanji_sodatsu|体育": "physical education",
    "kanji_fuku2|服": "clothes",
    "kanji_fuku2|洋服": "Western clothing",
    "kanji_fuku2|制服": "uniform",
    "kanji_yu2|理由": "reason",
    "kanji_yu2|自由": "freedom",
    "kanji_yu2|由来": "origin",
    "kanji_jibun|自分": "oneself",
    "kanji_jibun|自由": "freedom",
    "kanji_jibun|自動車": "car",
    "kanji_ri3|便利": "convenient",
    "kanji_ri3|利用": "use, utilisation",
    "kanji_ri3|利益": "profit",
    "kanji_you3|使用": "use",
    "kanji_you3|利用": "utilisation",
    "kanji_you3|用事": "errand",
    "kanji_kanashii|悲しい": "sad",
    "kanji_kanashii|悲しみ": "sadness",
    "kanji_kanashii|悲劇": "tragedy",
    "kanji_zoku2|家族": "family",
    "kanji_zoku2|民族": "ethnic group",
    "kanji_zoku2|親族": "relatives",
    "kanji_teki|目的": "purpose",
    "kanji_teki|一般的": "general",
    "kanji_teki|的": "target",
    "kanji_arawasu|表す": "to express",
    "kanji_arawasu|表": "table, chart",
    "kanji_arawasu|発表": "presentation",
    "kanji_arawareru|現れる": "to appear",
    "kanji_arawareru|現在": "the present",
    "kanji_arawareru|表現": "expression",
    "kanji_zai|現在": "the present",
    "kanji_zai|存在": "existence",
    "kanji_zai|在学": "being enrolled at school",
    "kanji_au2|合う": "to match, to fit",
    "kanji_au2|合わせる": "to combine",
    "kanji_au2|都合": "circumstances, convenience",
    "kanji_warui|悪い": "bad",
    "kanji_warui|悪天候": "bad weather",
    "kanji_warui|意地悪": "mean, spiteful",
    "kanji_kurushii|苦しい": "painful, difficult",
    "kanji_kurushii|苦い": "bitter",
    "kanji_kurushii|苦手": "not good at",
    "kanji_kan3|感じる": "to feel",
    "kanji_kan3|感動": "being moved",
    "kanji_kan3|感謝": "gratitude",
    "kanji_shitsu2|質問": "question",
    "kanji_shitsu2|品質": "quality",
    "kanji_shitsu2|性質": "nature, character",
    "kanji_mon2|質問": "question",
    "kanji_mon2|問題": "problem",
    "kanji_mon2|問う": "to ask",
    "kanji_dai3|問題": "problem",
    "kanji_dai3|宿題": "homework",
    "kanji_dai3|話題": "topic",
    "kanji_rei2|例えば": "for example",
    "kanji_rei2|例": "example",
    "kanji_rei2|実例": "concrete example",
    "kanji_kaesu|返す": "to return something",
    "kanji_kaesu|返事": "reply",
    "kanji_kaesu|返答": "answer",
    "kanji_kotaeru|答える": "to answer",
    "kanji_kotaeru|答え": "answer",
    "kanji_kotaeru|返答": "answer",
    "kanji_tadashii|正しい": "correct",
    "kanji_tadashii|正月": "New Year",
    "kanji_tadashii|正直": "honest",
    "kanji_sama|皆様": "everyone (polite)",
    "kanji_sama|様子": "situation, appearance",
    "kanji_sama|同様": "the same",
    "kanji_komaru|困る": "to be troubled",
    "kanji_komaru|困難": "difficulty",
    "kanji_komaru|貧困": "poverty",

    # ---------------- N3 ----------------
    "kanji_sei_n3|政治": "politics",
    "kanji_sei_n3|政府": "government",
    "kanji_sei_n3|行政": "administration",
    "kanji_gi_n3|会議": "meeting",
    "kanji_gi_n3|議論": "debate, discussion",
    "kanji_gi_n3|議員": "assembly member",
    "kanji_min_n3|国民": "citizen",
    "kanji_min_n3|民間": "private sector, civilian",
    "kanji_min_n3|市民": "city resident",
    "kanji_ren_n3|連絡": "contact",
    "kanji_ren_n3|連休": "consecutive holidays",
    "kanji_ren_n3|連れる": "to take (someone) along",
    "kanji_tai_n3|反対": "opposition, opposite",
    "kanji_tai_n3|絶対": "absolute, definitely",
    "kanji_tai_n3|対応": "response, handling",
    "kanji_shi_n3|市場": "market",
    "kanji_shi_n3|市民": "city resident",
    "kanji_shi_n3|都市": "city",
    "kanji_nai_n3|内容": "content",
    "kanji_nai_n3|案内": "guidance, guide",
    "kanji_nai_n3|家内": "my wife",
    "kanji_sou_n3|相談": "consultation",
    "kanji_sou_n3|相手": "the other party, partner",
    "kanji_sou_n3|首相": "prime minister",
    "kanji_tei_n3|予定": "plan, schedule",
    "kanji_tei_n3|決定": "decision",
    "kanji_tei_n3|安定": "stability",
    "kanji_kai_n3|今回": "this time",
    "kanji_kai_n3|回る": "to go around",
    "kanji_kai_n3|一回": "once",
    "kanji_sen_n3|選挙": "election",
    "kanji_sen_n3|選ぶ": "to choose",
    "kanji_sen_n3|選手": "athlete",
    "kanji_bei_n3|米": "rice",
    "kanji_bei_n3|米国": "the United States",
    "kanji_bei_n3|玄米": "brown rice",
    "kanji_kan_n3|関係": "relationship",
    "kanji_kan_n3|関する": "to relate to",
    "kanji_kan_n3|玄関": "entrance hall",
    "kanji_sen2_n3|戦争": "war",
    "kanji_sen2_n3|戦う": "to fight",
    "kanji_sen2_n3|挑戦": "challenge",
    "kanji_kei_n3|経験": "experience",
    "kanji_kei_n3|経済": "economy",
    "kanji_kei_n3|経つ": "to pass (of time)",
    "kanji_sai_n3|最初": "the first, the beginning",
    "kanji_sai_n3|最後": "the last",
    "kanji_sai_n3|最近": "recently",
    "kanji_chou_n3|調べる": "to investigate",
    "kanji_chou_n3|調子": "condition",
    "kanji_chou_n3|調理": "cooking",
    "kanji_ka_n3|変化": "change",
    "kanji_ka_n3|文化": "culture",
    "kanji_ka_n3|化粧": "make-up",
    "kanji_tou_n3|本当": "true, really",
    "kanji_tou_n3|当たる": "to hit, to be correct",
    "kanji_tou_n3|担当": "person in charge",
    "kanji_yaku_n3|約束": "promise",
    "kanji_yaku_n3|予約": "reservation",
    "kanji_yaku_n3|約": "approximately",
    "kanji_shu_n3|首": "neck",
    "kanji_shu_n3|首相": "prime minister",
    "kanji_shu_n3|首都": "capital city",
    "kanji_hou_n3|方法": "method",
    "kanji_hou_n3|法律": "law",
    "kanji_hou_n3|文法": "grammar",
    "kanji_sei2_n3|性格": "personality",
    "kanji_sei2_n3|女性": "woman",
    "kanji_sei2_n3|可能性": "possibility",
    "kanji_you_n3|必要": "necessary",
    "kanji_you_n3|重要": "important",
    "kanji_you_n3|要素": "element",
    "kanji_sei3_n3|制度": "system",
    "kanji_sei3_n3|制服": "uniform",
    "kanji_sei3_n3|制作": "production",
    "kanji_ji_n3|政治": "politics",
    "kanji_ji_n3|治る": "to get better",
    "kanji_ji_n3|治療": "medical treatment",
    "kanji_mu_n3|事務所": "office",
    "kanji_mu_n3|義務": "duty",
    "kanji_mu_n3|勤務": "work, service",
    "kanji_sei4_n3|成功": "success",
    "kanji_sei4_n3|成長": "growth",
    "kanji_sei4_n3|完成": "completion",
    "kanji_ki_n3|時期": "period, time",
    "kanji_ki_n3|期間": "duration",
    "kanji_ki_n3|期待": "expectation",
    "kanji_shu2_n3|取る": "to take",
    "kanji_shu2_n3|受け取る": "to receive",
    "kanji_shu2_n3|取材": "news coverage",
    "kanji_to_n3|都会": "big city",
    "kanji_to_n3|都市": "city",
    "kanji_to_n3|京都": "Kyoto",
    "kanji_wa_n3|平和": "peace",
    "kanji_wa_n3|和食": "Japanese cuisine",
    "kanji_wa_n3|昭和": "the Showa era",
    "kanji_ki2_n3|機会": "opportunity",
    "kanji_ki2_n3|飛行機": "aeroplane",
    "kanji_ki2_n3|機能": "function",
    "kanji_hei_n3|平和": "peace",
    "kanji_hei_n3|平日": "weekday",
    "kanji_hei_n3|平気": "not bothered, fine",
    "kanji_ka2_n3|参加": "participation",
    "kanji_ka2_n3|加える": "to add",
    "kanji_ka2_n3|増加": "increase",
    "kanji_ju_n3|受ける": "to receive",
    "kanji_ju_n3|受付": "reception",
    "kanji_ju_n3|受験": "taking an entrance exam",
    "kanji_suu_n3|数字": "numeral",
    "kanji_suu_n3|数える": "to count",
    "kanji_suu_n3|人数": "number of people",
    "kanji_ki3_n3|日記": "diary",
    "kanji_ki3_n3|記録": "record",
    "kanji_ki3_n3|記憶": "memory",
    "kanji_sho_n3|最初": "the first",
    "kanji_sho_n3|初めて": "for the first time",
    "kanji_sho_n3|初日": "the first day",
    "kanji_shi2_n3|指": "finger",
    "kanji_shi2_n3|指す": "to point at",
    "kanji_shi2_n3|指輪": "ring",
    "kanji_ken_n3|権利": "right (entitlement)",
    "kanji_ken_n3|人権": "human rights",
    "kanji_ken_n3|選挙権": "the right to vote",
    "kanji_shi3_n3|支える": "to support",
    "kanji_shi3_n3|支店": "branch shop",
    "kanji_shi3_n3|支持": "support, backing",
    "kanji_san_n3|出産": "giving birth",
    "kanji_san_n3|生産": "production",
    "kanji_san_n3|特産": "local speciality product",
    "kanji_ten_n3|点数": "score",
    "kanji_ten_n3|弱点": "weak point",
    "kanji_ten_n3|句点": "full stop",
    "kanji_hou2_n3|情報": "information",
    "kanji_hou2_n3|天気予報": "weather forecast",
    "kanji_hou2_n3|報告": "report",
    "kanji_sai2_n3|経済": "economy",
    "kanji_sai2_n3|済む": "to be finished",
    "kanji_sai2_n3|返済": "repayment",
    "kanji_katsu_n3|生活": "daily life",
    "kanji_katsu_n3|活動": "activity",
    "kanji_katsu_n3|活気": "liveliness",
    "kanji_gen_n3|原因": "cause",
    "kanji_gen_n3|原稿": "manuscript",
    "kanji_gen_n3|草原": "grassland",
    "kanji_kyou_n3|共に": "together",
    "kanji_kyou_n3|共通": "common, shared",
    "kanji_kyou_n3|公共": "public",
    "kanji_toku_n3|得る": "to gain",
    "kanji_toku_n3|説得": "persuasion",
    "kanji_toku_n3|得意": "good at, strong point",
    "kanji_kai2_n3|理解": "understanding",
    "kanji_kai2_n3|解決": "solution",
    "kanji_kai2_n3|解く": "to solve, to undo",
    "kanji_kou_n3|交通": "traffic",
    "kanji_kou_n3|交換": "exchange",
    "kanji_kou_n3|交流": "interaction, exchange",
    "kanji_shi4_n3|資料": "materials, documents",
    "kanji_shi4_n3|資金": "funds",
    "kanji_shi4_n3|投資": "investment",
    "kanji_yo_n3|予定": "plan",
    "kanji_yo_n3|予約": "reservation",
    "kanji_yo_n3|予習": "preparation before class",
    "kanji_kou2_n3|方向": "direction",
    "kanji_kou2_n3|向かう": "to head towards",
    "kanji_kou2_n3|向こう": "over there, the other side",
    "kanji_sai3_n3|実際": "actually, reality",
    "kanji_sai3_n3|国際": "international",
    "kanji_sai3_n3|際に": "at the time of",
    "kanji_shou_n3|勝つ": "to win",
    "kanji_shou_n3|優勝": "championship",
    "kanji_shou_n3|勝利": "victory",
    "kanji_men_n3|面白い": "interesting",
    "kanji_men_n3|場面": "scene",
    "kanji_men_n3|面接": "interview",
    "kanji_koku_n3|報告": "report",
    "kanji_koku_n3|広告": "advertisement",
    "kanji_koku_n3|告白": "confession",
    "kanji_han_n3|反対": "opposite",
    "kanji_han_n3|反応": "reaction",
    "kanji_han_n3|反省": "self-reflection",
    "kanji_han2_n3|判断": "judgement",
    "kanji_han2_n3|裁判": "trial",
    "kanji_han2_n3|評判": "reputation",
    "kanji_nin_n3|確認": "confirmation",
    "kanji_nin_n3|認める": "to acknowledge",
    "kanji_nin_n3|承認": "approval",
    "kanji_san2_n3|参加": "participation",
    "kanji_san2_n3|参考": "reference",
    "kanji_san2_n3|参る": "to go, to come (humble)",
    "kanji_so_n3|番組": "TV programme",
    "kanji_so_n3|組む": "to put together",
    "kanji_so_n3|組織": "organisation",
    "kanji_shin_n3|信じる": "to believe",
    "kanji_shin_n3|自信": "self-confidence",
    "kanji_shin_n3|信頼": "trust",
    "kanji_ken2_n3|事件": "incident",
    "kanji_ken2_n3|用件": "business, matter",
    "kanji_ken2_n3|条件": "condition, requirement",
    "kanji_soku_n3|右側": "right side",
    "kanji_soku_n3|側面": "side, aspect",
    "kanji_soku_n3|内側": "inner side",
    "kanji_nin2_n3|責任": "responsibility",
    "kanji_nin2_n3|任せる": "to entrust",
    "kanji_nin2_n3|主任": "person in charge",
    "kanji_in_n3|引く": "to pull",
    "kanji_in_n3|割引": "discount",
    "kanji_in_n3|引っ越し": "moving house",
    "kanji_kyuu_n3|要求": "demand",
    "kanji_kyuu_n3|求める": "to seek, to request",
    "kanji_kyuu_n3|求人": "job vacancy",
    "kanji_ji2_n3|次に": "next",
    "kanji_ji2_n3|次回": "next time",
    "kanji_ji2_n3|目次": "table of contents",
    "kanji_saku_n3|昨日": "yesterday",
    "kanji_saku_n3|昨年": "last year",
    "kanji_saku_n3|昨夜": "last night",
    "kanji_ron_n3|議論": "debate",
    "kanji_ron_n3|論文": "thesis, paper",
    "kanji_ron_n3|結論": "conclusion",
    "kanji_kan2_n3|警官": "police officer",
    "kanji_kan2_n3|官庁": "government agency",
    "kanji_kan2_n3|外交官": "diplomat",
    "kanji_zou_n3|増える": "to increase (intransitive)",
    "kanji_zou_n3|増加": "increase",
    "kanji_zou_n3|増やす": "to increase (transitive)",
    "kanji_kei2_n3|関係": "relationship",
    "kanji_kei2_n3|係員": "attendant",
    "kanji_kei2_n3|受付係": "receptionist",
    "kanji_jou_n3|感情": "emotion",
    "kanji_jou_n3|情報": "information",
    "kanji_jou_n3|友情": "friendship",
    "kanji_tou2_n3|投げる": "to throw",
    "kanji_tou2_n3|投資": "investment",
    "kanji_tou2_n3|投票": "voting",
    "kanji_ji3_n3|指示": "instruction",
    "kanji_ji3_n3|示す": "to show, to indicate",
    "kanji_ji3_n3|展示": "exhibition",
    "kanji_da_n3|打つ": "to hit",
    "kanji_da_n3|打撃": "blow, impact",
    "kanji_da_n3|打ち合わせ": "planning meeting",
    "kanji_choku_n3|直す": "to fix",
    "kanji_choku_n3|正直": "honest",
    "kanji_choku_n3|直接": "direct",
    "kanji_ryou_n3|両方": "both",
    "kanji_ryou_n3|両親": "parents",
    "kanji_ryou_n3|両手": "both hands",
    "kanji_shiki_n3|結婚式": "wedding ceremony",
    "kanji_shiki_n3|卒業式": "graduation ceremony",
    "kanji_shiki_n3|方式": "method, format",
    "kanji_kaku_n3|確認": "confirmation",
    "kanji_kaku_n3|確かに": "certainly",
    "kanji_kaku_n3|正確": "accurate",
    "kanji_ka3_n3|結果": "result",
    "kanji_ka3_n3|果物": "fruit",
    "kanji_ka3_n3|効果": "effect",
    "kanji_you2_n3|内容": "content",
    "kanji_you2_n3|容器": "container",
    "kanji_you2_n3|美容院": "beauty salon",
    "kanji_hitsu_n3|必要": "necessary",
    "kanji_hitsu_n3|必ず": "without fail",
    "kanji_hitsu_n3|必死": "desperately",
    "kanji_en_n3|演技": "acting",
    "kanji_en_n3|講演": "lecture",
    "kanji_en_n3|出演": "appearing (in a show)",
    "kanji_sai4_n3|二十歳": "twenty years old",
    "kanji_sai4_n3|お歳暮": "year-end gift",
    "kanji_sai4_n3|歳月": "years, time passing",
    "kanji_sou2_n3|戦争": "war",
    "kanji_sou2_n3|争う": "to compete, to dispute",
    "kanji_sou2_n3|競争": "competition",
    "kanji_dan_n3|相談": "consultation",
    "kanji_dan_n3|会談": "talks, conference",
    "kanji_dan_n3|冗談": "joke",
    "kanji_nou_n3|可能": "possible",
    "kanji_nou_n3|能力": "ability",
    "kanji_nou_n3|才能": "talent",
    "kanji_i_n3|一位": "first place",
    "kanji_i_n3|地位": "status",
    "kanji_i_n3|単位": "unit, course credit",
    "kanji_chi_n3|置く": "to put",
    "kanji_chi_n3|位置": "position",
    "kanji_chi_n3|装置": "device",
    "kanji_ryuu_n3|流れる": "to flow",
    "kanji_ryuu_n3|交流": "exchange, interaction",
    "kanji_ryuu_n3|流行": "trend, fashion",
    "kanji_kaku2_n3|性格": "personality",
    "kanji_kaku2_n3|価格": "price",
    "kanji_kaku2_n3|合格": "passing (an exam)",
    "kanji_gi2_n3|疑う": "to doubt",
    "kanji_gi2_n3|質疑": "question and answer",
    "kanji_gi2_n3|疑問": "doubt, question",
    "kanji_ka4_n3|過ぎる": "to pass, to be excessive",
    "kanji_ka4_n3|過去": "the past",
    "kanji_ka4_n3|通過": "passing through",
    "kanji_kyoku_n3|郵便局": "post office",
    "kanji_kyoku_n3|薬局": "pharmacy",
    "kanji_kyoku_n3|結局": "in the end",
    "kanji_hou3_n3|放送": "broadcast",
    "kanji_hou3_n3|放す": "to let go",
    "kanji_hou3_n3|解放": "liberation",
    "kanji_jou2_n3|日常": "everyday",
    "kanji_jou2_n3|非常に": "extremely",
    "kanji_jou2_n3|正常": "normal",
    "kanji_jou3_n3|状態": "condition, state",
    "kanji_jou3_n3|年賀状": "New Year's card",
    "kanji_jou3_n3|招待状": "invitation card",
    "kanji_kyuu2_n3|野球": "baseball",
    "kanji_kyuu2_n3|地球": "the Earth",
    "kanji_kyuu2_n3|電球": "light bulb",
    "kanji_shoku_n3|就職": "getting a job",
    "kanji_shoku_n3|職業": "occupation",
    "kanji_shoku_n3|職場": "workplace",
    "kanji_yo2_n3|与える": "to give",
    "kanji_yo2_n3|参与": "participation",
    "kanji_yo2_n3|給与": "salary",
    "kanji_kyou2_n3|子供": "child",
    "kanji_kyou2_n3|提供": "provision",
    "kanji_kyou2_n3|供給": "supply",
    "kanji_yaku2_n3|役に立つ": "to be useful",
    "kanji_yaku2_n3|役者": "actor",
    "kanji_yaku2_n3|役所": "government office",
    "kanji_kou3_n3|構造": "structure",
    "kanji_kou3_n3|構成": "composition",
    "kanji_kou3_n3|結構": "quite good, no thank you",
    "kanji_katsu2_n3|割る": "to divide, to break",
    "kanji_katsu2_n3|役割": "role",
    "kanji_katsu2_n3|割合": "proportion",
    "kanji_hi_n3|費用": "cost",
    "kanji_hi_n3|食費": "food expenses",
    "kanji_hi_n3|消費": "consumption",
    "kanji_fu_n3|付ける": "to attach",
    "kanji_fu_n3|気付く": "to notice",
    "kanji_fu_n3|受付": "reception",
    "kanji_setsu_n3|説明": "explanation",
    "kanji_setsu_n3|小説": "novel",
    "kanji_setsu_n3|伝説": "legend",
    "kanji_nan_n3|難しい": "difficult",
    "kanji_nan_n3|困難": "hardship",
    "kanji_nan_n3|避難": "evacuation",
    "kanji_yuu_n3|優しい": "kind, gentle",
    "kanji_yuu_n3|優勝": "championship",
    "kanji_yuu_n3|優先": "priority",
    "kanji_fu2_n3|夫": "husband",
    "kanji_fu2_n3|夫婦": "married couple",
    "kanji_fu2_n3|大丈夫": "all right, fine",
    "kanji_shuu_n3|収入": "income",
    "kanji_shuu_n3|収める": "to store, to obtain",
    "kanji_shuu_n3|領収書": "receipt",
    "kanji_dan2_n3|断る": "to refuse",
    "kanji_dan2_n3|判断": "judgement",
    "kanji_dan2_n3|油断": "carelessness",
    "kanji_i2_n3|違う": "to differ, to be wrong",
    "kanji_i2_n3|間違い": "mistake",
    "kanji_i2_n3|違反": "violation",
    "kanji_shou2_n3|消す": "to turn off, to erase",
    "kanji_shou2_n3|消える": "to disappear",
    "kanji_shou2_n3|消費": "consumption",
    "kanji_shin2_n3|神様": "god",
    "kanji_shin2_n3|神社": "Shinto shrine",
    "kanji_shin2_n3|精神": "spirit, mind",
    "kanji_ban_n3|番号": "number",
    "kanji_ban_n3|一番": "number one, the most",
    "kanji_ban_n3|番組": "TV programme",
    "kanji_ki4_n3|規則": "rule",
    "kanji_ki4_n3|規模": "scale",
    "kanji_ki4_n3|新規": "new",
    "kanji_jutsu_n3|技術": "technology, technique",
    "kanji_jutsu_n3|手術": "surgery",
    "kanji_jutsu_n3|美術": "fine arts",
    "kanji_bi_n3|準備": "preparation",
    "kanji_bi_n3|備える": "to prepare, to equip",
    "kanji_bi_n3|設備": "facilities",
    "kanji_taku_n3|自宅": "one's own home",
    "kanji_taku_n3|お宅": "your home",
    "kanji_taku_n3|宅配": "home delivery",
    "kanji_gai_n3|被害": "damage",
    "kanji_gai_n3|公害": "pollution",
    "kanji_gai_n3|害虫": "pest insect",
    "kanji_kei3_n3|警察": "police",
    "kanji_kei3_n3|警告": "warning",
    "kanji_kei3_n3|警備": "security",
    "kanji_seki_n3|出席": "attendance",
    "kanji_seki_n3|座席": "seat",
    "kanji_seki_n3|欠席": "absence",
    "kanji_hou4_n3|訪れる": "to visit",
    "kanji_hou4_n3|訪問": "a visit",
    "kanji_hou4_n3|来訪": "a caller's visit",
    "kanji_zan_n3|残る": "to remain",
    "kanji_zan_n3|残念": "what a shame",
    "kanji_zan_n3|残業": "overtime",
    "kanji_sou3_n3|予想": "prediction",
    "kanji_sou3_n3|理想": "ideal",
    "kanji_sou3_n3|感想": "impressions",
    "kanji_nen_n3|残念": "what a shame",
    "kanji_nen_n3|記念": "commemoration",
    "kanji_nen_n3|念のため": "just in case",
    "kanji_jo_n3|助ける": "to help",
    "kanji_jo_n3|助手": "assistant",
    "kanji_jo_n3|援助": "assistance",
    "kanji_rou_n3|苦労": "hardship",
    "kanji_rou_n3|労働": "labour",
    "kanji_rou_n3|疲労": "fatigue",
    "kanji_gen2_n3|限る": "to limit",
    "kanji_gen2_n3|制限": "restriction",
    "kanji_gen2_n3|期限": "deadline",
    "kanji_tsui_n3|追う": "to chase",
    "kanji_tsui_n3|追加": "addition",
    "kanji_tsui_n3|追跡": "pursuit, tracking",
    "kanji_shou3_n3|商品": "product",
    "kanji_shou3_n3|商店": "shop",
    "kanji_shou3_n3|商売": "business, trade",
    "kanji_you3_n3|葉っぱ": "leaf",
    "kanji_you3_n3|紅葉": "autumn leaves",
    "kanji_you3_n3|言葉": "word, language",
    "kanji_den_n3|伝える": "to convey",
    "kanji_den_n3|伝統": "tradition",
    "kanji_den_n3|手伝う": "to help out",
    "kanji_kei4_n3|形": "shape",
    "kanji_kei4_n3|人形": "doll",
    "kanji_kei4_n3|形容詞": "adjective",
    "kanji_kei5_n3|景色": "scenery",
    "kanji_kei5_n3|風景": "landscape",
    "kanji_kei5_n3|光景": "scene, sight",
    "kanji_raku_n3|落ちる": "to fall",
    "kanji_raku_n3|落とす": "to drop",
    "kanji_raku_n3|下落": "decline (in price)",
    "kanji_tai2_n3|退院": "leaving hospital",
    "kanji_tai2_n3|引退": "retirement",
    "kanji_tai2_n3|退屈": "boring",
    "kanji_fu3_n3|負ける": "to lose",
    "kanji_fu3_n3|自負": "self-confidence, pride",
    "kanji_fu3_n3|負担": "burden",
    "kanji_to2_n3|渡る": "to cross",
    "kanji_to2_n3|渡す": "to hand over",
    "kanji_to2_n3|海外渡航": "travelling abroad",
    "kanji_shitsu_n3|失う": "to lose",
    "kanji_shitsu_n3|失敗": "failure",
    "kanji_shitsu_n3|失礼": "excuse me, rudeness",
    "kanji_sa_n3|差": "difference",
    "kanji_sa_n3|時差": "time difference",
    "kanji_sa_n3|差別": "discrimination",
    "kanji_matsu_n3|週末": "weekend",
    "kanji_matsu_n3|月末": "end of the month",
    "kanji_matsu_n3|結末": "ending",
    "kanji_shu3_n3|守る": "to protect",
    "kanji_shu3_n3|留守": "being out",
    "kanji_shu3_n3|保守": "conservative, maintenance",
    "kanji_shu4_n3|種類": "kind, type",
    "kanji_shu4_n3|種": "seed",
    "kanji_shu4_n3|人種": "race (of people)",
    "kanji_bi2_n3|美しい": "beautiful",
    "kanji_bi2_n3|美術館": "art museum",
    "kanji_bi2_n3|美容院": "beauty salon",
    "kanji_mei_n3|命": "life",
    "kanji_mei_n3|生命": "life",
    "kanji_mei_n3|命令": "order, command",
    "kanji_fuku_n3|幸福": "happiness",
    "kanji_fuku_n3|福祉": "welfare",
    "kanji_fuku_n3|祝福": "blessing",
    "kanji_bou_n3|希望": "hope",
    "kanji_bou_n3|望む": "to wish for",
    "kanji_bou_n3|展望": "view, outlook",
    "kanji_hi2_n3|非常に": "extremely",
    "kanji_hi2_n3|非常口": "emergency exit",
    "kanji_hi2_n3|非公開": "not made public",
    "kanji_kan3_n3|観光": "sightseeing",
    "kanji_kan3_n3|観察": "observation",
    "kanji_kan3_n3|観客": "audience",
    "kanji_satsu_n3|警察": "police",
    "kanji_satsu_n3|観察": "observation",
    "kanji_satsu_n3|察する": "to guess, to sense",
    "kanji_dan3_n3|階段": "stairs",
    "kanji_dan3_n3|値段": "price",
    "kanji_dan3_n3|手段": "means, method",
    "kanji_ou_n3|横": "side",
    "kanji_ou_n3|横断歩道": "pedestrian crossing",
    "kanji_ou_n3|横浜": "Yokohama",
    "kanji_shin3_n3|申す": "to say (humble)",
    "kanji_shin3_n3|申し込む": "to apply",
    "kanji_shin3_n3|申請": "application",
    "kanji_zai_n3|財布": "wallet",
    "kanji_zai_n3|財産": "property, assets",
    "kanji_zai_n3|財政": "public finance",
    "kanji_kou4_n3|港": "harbour",
    "kanji_kou4_n3|空港": "airport",
    "kanji_kou4_n3|香港": "Hong Kong",
    "kanji_shiki2_n3|意識": "consciousness",
    "kanji_shiki2_n3|知識": "knowledge",
    "kanji_shiki2_n3|常識": "common sense",
    "kanji_ko2_n3|呼ぶ": "to call",
    "kanji_ko2_n3|呼吸": "breathing",
    "kanji_ko2_n3|呼び出す": "to summon",
    "kanji_tatsu_n3|友達": "friend",
    "kanji_tatsu_n3|達成": "achievement",
    "kanji_tatsu_n3|発達": "development",
    "kanji_ryou2_n3|良い": "good",
    "kanji_ryou2_n3|良心": "conscience",
    "kanji_ryou2_n3|改良": "improvement",
    "kanji_kou5_n3|気候": "climate",
    "kanji_kou5_n3|候補": "candidate",
    "kanji_kou5_n3|天候": "weather",
    "kanji_tei2_n3|程度": "degree, extent",
    "kanji_tei2_n3|先程": "a moment ago",
    "kanji_tei2_n3|過程": "process",
    "kanji_man_n3|満足": "satisfaction",
    "kanji_man_n3|満員": "full, no vacancy",
    "kanji_man_n3|不満": "dissatisfaction",
    "kanji_hai_n3|失敗": "failure",
    "kanji_hai_n3|敗北": "defeat",
    "kanji_hai_n3|勝敗": "victory or defeat",
    "kanji_chi2_n3|値段": "price",
    "kanji_chi2_n3|価値": "value",
    "kanji_chi2_n3|数値": "numerical value",
    "kanji_totsu_n3|突然": "suddenly",
    "kanji_totsu_n3|衝突": "collision",
    "kanji_totsu_n3|突く": "to poke, to thrust",
    "kanji_ro_n3|道路": "road",
    "kanji_ro_n3|通路": "aisle, passage",
    "kanji_ro_n3|線路": "railway track",
    "kanji_seki2_n3|積む": "to stack",
    "kanji_seki2_n3|面積": "area (size)",
    "kanji_seki2_n3|積極的": "proactive",
    "kanji_ta_n3|その他": "the rest, others",
    "kanji_ta_n3|他人": "other people",
    "kanji_ta_n3|他国": "another country",
    "kanji_sho2_n3|処理": "processing, handling",
    "kanji_sho2_n3|対処": "dealing with",
    "kanji_sho2_n3|処方箋": "prescription",
    "kanji_kyaku_n3|お客さん": "customer, guest",
    "kanji_kyaku_n3|観光客": "tourist",
    "kanji_kyaku_n3|乗客": "passenger",
    "kanji_hi3_n3|否定": "denial",
    "kanji_hi3_n3|拒否": "refusal",
    "kanji_hi3_n3|賛否": "for and against",
    "kanji_shi5_n3|医師": "doctor",
    "kanji_shi5_n3|教師": "teacher",
    "kanji_shi5_n3|美容師": "hairdresser",
    "kanji_tou3_n3|登る": "to climb",
    "kanji_tou3_n3|登山": "mountain climbing",
    "kanji_tou3_n3|登録": "registration",
    "kanji_eki_n3|容易": "easy",
    "kanji_eki_n3|貿易": "trade",
    "kanji_eki_n3|安易": "easygoing, simplistic",
    "kanji_soku2_n3|速い": "fast",
    "kanji_soku2_n3|速度": "speed",
    "kanji_soku2_n3|高速道路": "motorway",
    "kanji_son_n3|存在": "existence",
    "kanji_son_n3|存じる": "to know (humble)",
    "kanji_son_n3|保存": "preservation, saving",
    "kanji_satsu2_n3|殺す": "to kill",
    "kanji_satsu2_n3|自殺": "suicide",
    "kanji_satsu2_n3|忙殺": "being swamped with work",
    "kanji_gou_n3|番号": "number",
    "kanji_gou_n3|信号": "traffic light",
    "kanji_gou_n3|号室": "room number",
    "kanji_tan_n3|簡単": "simple",
    "kanji_tan_n3|単語": "vocabulary word",
    "kanji_tan_n3|単純": "simple, uncomplicated",
    "kanji_za_n3|座る": "to sit",
    "kanji_za_n3|座席": "seat",
    "kanji_za_n3|銀座": "Ginza",
    "kanji_ha_n3|破る": "to tear, to break (a rule)",
    "kanji_ha_n3|破壊": "destruction",
    "kanji_ha_n3|突破": "breakthrough",
    "kanji_jo2_n3|除く": "to exclude, to remove",
    "kanji_jo2_n3|掃除": "cleaning",
    "kanji_jo2_n3|解除": "cancellation, release",
    "kanji_kan4_n3|完成": "completion",
    "kanji_kan4_n3|完全": "complete, perfect",
    "kanji_kan4_n3|未完成": "unfinished",
    "kanji_seki3_n3|責任": "responsibility",
    "kanji_seki3_n3|責める": "to blame",
    "kanji_seki3_n3|自責": "self-blame",
    "kanji_ho_n3|捕まえる": "to catch",
    "kanji_ho_n3|逮捕": "arrest",
    "kanji_ho_n3|捕まる": "to be caught",
    "kanji_ki5_n3|危ない": "dangerous",
    "kanji_ki5_n3|危険": "danger",
    "kanji_ki5_n3|危機": "crisis",
    "kanji_kyuu3_n3|給料": "salary",
    "kanji_kyuu3_n3|給食": "school lunch",
    "kanji_kyuu3_n3|支給": "payment, provision",
    "kanji_gei_n3|迎える": "to welcome, to pick up",
    "kanji_gei_n3|歓迎": "welcome",
    "kanji_gei_n3|送迎": "pick-up and drop-off",
    "kanji_en2_n3|公園": "park",
    "kanji_en2_n3|幼稚園": "kindergarten",
    "kanji_en2_n3|動物園": "zoo",
    "kanji_gu_n3|道具": "tool",
    "kanji_gu_n3|家具": "furniture",
    "kanji_gu_n3|文房具": "stationery",
    "kanji_ji4_n3|辞書": "dictionary",
    "kanji_ji4_n3|辞める": "to resign",
    "kanji_ji4_n3|辞退": "declining politely",
    "kanji_in2_n3|原因": "cause",
    "kanji_in2_n3|因る": "to be due to",
    "kanji_in2_n3|要因": "factor",
    "kanji_ba_n3|馬": "horse",
    "kanji_ba_n3|競馬": "horse racing",
    "kanji_ba_n3|乗馬": "horse riding",
    "kanji_ai_n3|愛": "love",
    "kanji_ai_n3|愛する": "to love",
    "kanji_ai_n3|恋愛": "romance",
    "kanji_fu4_n3|豊富": "abundant",
    "kanji_fu4_n3|富士山": "Mount Fuji",
    "kanji_fu4_n3|富む": "to be rich in",
    "kanji_hi4_n3|彼": "he",
    "kanji_hi4_n3|彼女": "she, girlfriend",
    "kanji_hi4_n3|彼氏": "boyfriend",
    "kanji_mi_n3|未来": "the future",
    "kanji_mi_n3|未成年": "a minor (under age)",
    "kanji_mi_n3|未定": "undecided",
    "kanji_bu_n3|舞台": "stage",
    "kanji_bu_n3|舞う": "to dance",
    "kanji_bu_n3|歌舞伎": "kabuki",
    "kanji_bou2_n3|死亡": "death",
    "kanji_bou2_n3|亡くなる": "to pass away",
    "kanji_bou2_n3|亡命": "defection, exile",
    "kanji_rei_n3|冷たい": "cold (to the touch)",
    "kanji_rei_n3|冷蔵庫": "refrigerator",
    "kanji_rei_n3|冷える": "to get cold",
    "kanji_teki_n3|適当": "half-hearted, suitable",
    "kanji_teki_n3|快適": "comfortable",
    "kanji_teki_n3|適切": "appropriate",
    "kanji_fu5_n3|主婦": "housewife",
    "kanji_fu5_n3|夫婦": "married couple",
    "kanji_fu5_n3|婦人": "lady, woman",
    "kanji_ki6_n3|寄る": "to drop by",
    "kanji_ki6_n3|寄付": "donation",
    "kanji_ki6_n3|最寄り": "nearest",
    "kanji_komi_n3|込む": "to be crowded",
    "kanji_komi_n3|申し込む": "to apply",
    "kanji_komi_n3|税込み": "tax included",
    "kanji_rui_n3|種類": "kind, type",
    "kanji_rui_n3|書類": "documents",
    "kanji_rui_n3|人類": "humankind",
    "kanji_yo3_n3|余る": "to be left over",
    "kanji_yo3_n3|余裕": "leeway, spare time",
    "kanji_yo3_n3|余計": "excessive, unnecessary",
    "kanji_ou2_n3|王様": "king",
    "kanji_ou2_n3|女王": "queen",
    "kanji_ou2_n3|王国": "kingdom",
    "kanji_sai5_n3|妻": "my wife",
    "kanji_sai5_n3|夫妻": "husband and wife",
    "kanji_sai5_n3|人妻": "another man's wife",
    "kanji_hai2_n3|背が高い": "tall",
    "kanji_hai2_n3|背中": "back (of the body)",
    "kanji_hai2_n3|背景": "background",
    "kanji_netsu_n3|熱": "fever, heat",
    "kanji_netsu_n3|熱心": "enthusiastic",
    "kanji_netsu_n3|情熱": "passion",
    "kanji_shuku_n3|宿題": "homework",
    "kanji_shuku_n3|宿泊": "lodging",
    "kanji_shuku_n3|民宿": "guest house",
    "kanji_yaku3_n3|薬": "medicine",
    "kanji_yaku3_n3|薬局": "pharmacy",
    "kanji_yaku3_n3|薬剤師": "pharmacist",
    "kanji_ken3_n3|危険": "danger",
    "kanji_ken3_n3|保険": "insurance",
    "kanji_ken3_n3|冒険": "adventure",
    "kanji_rai_n3|頼む": "to ask a favour",
    "kanji_rai_n3|信頼": "trust",
    "kanji_rai_n3|依頼": "request, commission",
    "kanji_sen3_n3|船": "ship",
    "kanji_sen3_n3|船員": "crew member",
    "kanji_sen3_n3|漁船": "fishing boat",
    "kanji_to3_n3|途中": "on the way",
    "kanji_to3_n3|前途": "the future ahead",
    "kanji_to3_n3|使途": "use (of funds)",
    "kanji_kyo_n3|許す": "to allow, to forgive",
    "kanji_kyo_n3|許可": "permission",
    "kanji_kyo_n3|免許": "licence",
    "kanji_batsu_n3|抜く": "to pull out",
    "kanji_batsu_n3|追い抜く": "to overtake",
    "kanji_batsu_n3|抜群": "outstanding",
    "kanji_ben_n3|便利": "convenient",
    "kanji_ben_n3|郵便": "post, mail",
    "kanji_ben_n3|航空便": "airmail",
    "kanji_ryuu2_n3|留学": "studying abroad",
    "kanji_ryuu2_n3|留守": "being out",
    "kanji_ryuu2_n3|留める": "to fasten, to hold",
    "kanji_zai2_n3|犯罪": "crime",
    "kanji_zai2_n3|罪": "sin, guilt",
    "kanji_zai2_n3|無罪": "not guilty",
    "kanji_do_n3|努力": "effort",
    "kanji_do_n3|努める": "to strive",
    "kanji_do_n3|努力家": "hard worker",
    "kanji_sei5_n3|精神": "spirit, mind",
    "kanji_sei5_n3|精一杯": "with all one's might",
    "kanji_sei5_n3|精密": "precision",
    "kanji_san3_n3|散歩": "a walk",
    "kanji_san3_n3|散る": "to scatter, to fall (petals)",
    "kanji_san3_n3|解散": "dissolution, breaking up",
    "kanji_sei6_n3|静かな": "quiet",
    "kanji_sei6_n3|静止": "standing still",
    "kanji_sei6_n3|冷静": "calm, level-headed",
    "kanji_kon_n3|結婚": "marriage",
    "kanji_kon_n3|婚約": "engagement",
    "kanji_kon_n3|離婚": "divorce",
    "kanji_ki7_n3|喜ぶ": "to be delighted",
    "kanji_ki7_n3|喜び": "joy",
    "kanji_ki7_n3|大喜び": "great delight",
    "kanji_fu6_n3|浮く": "to float",
    "kanji_fu6_n3|浮かぶ": "to come to mind, to float",
    "kanji_fu6_n3|浮気": "having an affair",
    "kanji_zetsu_n3|絶対": "absolutely",
    "kanji_zetsu_n3|絶好": "ideal, perfect",
    "kanji_zetsu_n3|絶える": "to cease",
    "kanji_kou6_n3|幸せ": "happy",
    "kanji_kou6_n3|幸福": "happiness",
    "kanji_kou6_n3|不幸": "misfortune",
    "kanji_ou3_n3|押す": "to push",
    "kanji_ou3_n3|押入れ": "built-in closet",
    "kanji_ou3_n3|押収": "seizure, confiscation",
    "kanji_tou4_n3|倒れる": "to fall over",
    "kanji_tou4_n3|倒す": "to knock down, to defeat",
    "kanji_tou4_n3|面倒": "troublesome",
    "kanji_tou5_n3|等しい": "equal",
    "kanji_tou5_n3|平等": "equality",
    "kanji_tou5_n3|一等": "first class, first prize",
    "kanji_rou2_n3|老人": "elderly person",
    "kanji_rou2_n3|老後": "one's old age",
    "kanji_rou2_n3|老化": "ageing",
    "kanji_kyoku2_n3|曲": "song, tune",
    "kanji_kyoku2_n3|曲がる": "to turn, to bend",
    "kanji_kyoku2_n3|作曲": "composing music",
    "kanji_futsu_n3|払う": "to pay",
    "kanji_futsu_n3|支払い": "payment",
    "kanji_futsu_n3|現金払い": "cash payment",
    "kanji_tei3_n3|庭": "garden",
    "kanji_tei3_n3|家庭": "household",
    "kanji_tei3_n3|校庭": "school grounds",
    "kanji_to4_n3|生徒": "pupil",
    "kanji_to4_n3|徒歩": "on foot",
    "kanji_to4_n3|徒然": "idleness, tedium",
    "kanji_kin_n3|勤める": "to work at",
    "kanji_kin_n3|通勤": "commuting",
    "kanji_kin_n3|勤務": "work, duty",
    "kanji_kyo2_n3|居る": "to be, to stay",
    "kanji_kyo2_n3|住居": "residence",
    "kanji_kyo2_n3|居間": "living room",
    "kanji_zatsu_n3|雑誌": "magazine",
    "kanji_zatsu_n3|複雑": "complicated",
    "kanji_zatsu_n3|雑談": "small talk",
    "kanji_shou4_n3|招待": "invitation",
    "kanji_shou4_n3|招く": "to invite",
    "kanji_shou4_n3|招待状": "invitation card",
    "kanji_ketsu_n3|欠席": "absence",
    "kanji_ketsu_n3|欠点": "flaw",
    "kanji_ketsu_n3|欠ける": "to be lacking, to chip",
    "kanji_kou7_n3|変更": "change, alteration",
    "kanji_kou7_n3|更に": "furthermore",
    "kanji_kou7_n3|更新": "renewal, update",
    "kanji_koku2_n3|時刻": "point in time",
    "kanji_koku2_n3|深刻": "serious",
    "kanji_koku2_n3|刻む": "to carve, to chop",
    "kanji_san4_n3|賛成": "agreement",
    "kanji_san4_n3|賞賛": "praise",
    "kanji_san4_n3|協賛": "sponsorship",
    "kanji_hou5_n3|抱く": "to hug",
    "kanji_hou5_n3|抱える": "to hold, to bear",
    "kanji_hou5_n3|辛抱": "patience",
    "kanji_han3_n3|犯人": "culprit",
    "kanji_han3_n3|犯罪": "crime",
    "kanji_han3_n3|犯す": "to commit (an offence)",
    "kanji_kyou3_n3|恐い": "scary",
    "kanji_kyou3_n3|恐ろしい": "terrifying",
    "kanji_kyou3_n3|恐竜": "dinosaur",
    "kanji_soku3_n3|息": "breath",
    "kanji_soku3_n3|息子": "son",
    "kanji_soku3_n3|休息": "rest",
    "kanji_gan_n3|願う": "to wish, to request",
    "kanji_gan_n3|お願い": "a request, please",
    "kanji_gan_n3|願書": "application form",
    "kanji_kai3_n3|絵": "picture",
    "kanji_kai3_n3|絵本": "picture book",
    "kanji_kai3_n3|絵画": "painting",
    "kanji_etsu_n3|越える": "to cross over",
    "kanji_etsu_n3|引っ越し": "moving house",
    "kanji_etsu_n3|追い越す": "to overtake",
    "kanji_yoku_n3|欲しい": "to want",
    "kanji_yoku_n3|意欲": "motivation",
    "kanji_yoku_n3|食欲": "appetite",
    "kanji_tsuu_n3|痛い": "painful",
    "kanji_tsuu_n3|頭痛": "headache",
    "kanji_tsuu_n3|苦痛": "suffering",
    "kanji_shou5_n3|笑う": "to laugh",
    "kanji_shou5_n3|微笑む": "to smile",
    "kanji_shou5_n3|笑顔": "smiling face",
    "kanji_go_n3|お互い": "each other",
    "kanji_go_n3|互いに": "mutually",
    "kanji_go_n3|相互": "reciprocal",
    "kanji_soku4_n3|約束": "promise",
    "kanji_soku4_n3|束": "bundle",
    "kanji_soku4_n3|花束": "bouquet",
    "kanji_ji5_n3|似ている": "to resemble",
    "kanji_ji5_n3|類似": "similarity",
    "kanji_ji5_n3|真似": "imitation",
    "kanji_retsu_n3|列": "row, queue",
    "kanji_retsu_n3|行列": "long queue",
    "kanji_retsu_n3|列車": "train",
    "kanji_tan2_n3|探す": "to look for",
    "kanji_tan2_n3|探検": "exploration",
    "kanji_tan2_n3|探偵": "detective",
    "kanji_tou6_n3|逃げる": "to run away",
    "kanji_tou6_n3|逃避": "escapism, avoidance",
    "kanji_tou6_n3|見逃す": "to overlook, to miss",
    "kanji_mei2_n3|迷う": "to get lost, to hesitate",
    "kanji_mei2_n3|迷子": "lost child",
    "kanji_mei2_n3|迷惑": "nuisance",
    "kanji_mu2_n3|夢": "dream",
    "kanji_mu2_n3|夢見る": "to dream",
    "kanji_mu2_n3|悪夢": "nightmare",
    "kanji_kun_n3|君": "you (familiar)",
    "kanji_kun_n3|君主": "monarch",
    "kanji_kun_n3|諸君": "everyone (addressing a group)",
    "kanji_sho3_n3|一緒に": "together",
    "kanji_sho3_n3|緒": "cord, strap",
    "kanji_sho3_n3|情緒": "emotion, atmosphere",
    "kanji_setsu2_n3|折る": "to fold, to break",
    "kanji_setsu2_n3|骨折": "bone fracture",
    "kanji_setsu2_n3|折り紙": "origami",
    "kanji_sou4_n3|草": "grass",
    "kanji_sou4_n3|草原": "grassland",
    "kanji_sou4_n3|雑草": "weeds",
    "kanji_bo_n3|暮らす": "to live one's life",
    "kanji_bo_n3|暮れる": "to grow dark, to end",
    "kanji_bo_n3|夕暮れ": "dusk",
    "kanji_shu5_n3|お酒": "alcohol",
    "kanji_shu5_n3|酒屋": "liquor shop",
    "kanji_shu5_n3|日本酒": "sake",
    "kanji_sei7_n3|晴れ": "clear weather",
    "kanji_sei7_n3|晴れる": "to clear up",
    "kanji_sei7_n3|快晴": "perfectly clear skies",
    "kanji_kai4_n3|掛ける": "to hang, to put on",
    "kanji_kai4_n3|電話を掛ける": "to make a phone call",
    "kanji_kai4_n3|心掛け": "attitude, mindfulness",
    "kanji_tou7_n3|到着": "arrival",
    "kanji_tou7_n3|到達": "reaching (a goal)",
    "kanji_tou7_n3|殺到": "a rush, a flood (of people)",
    "kanji_tou8_n3|盗む": "to steal",
    "kanji_tou8_n3|盗難": "theft",
    "kanji_tou8_n3|強盗": "robbery",
    "kanji_kyuu4_n3|吸う": "to inhale, to suck",
    "kanji_kyuu4_n3|呼吸": "breathing",
    "kanji_kyuu4_n3|吸収": "absorption",
    "kanji_you4_n3|太陽": "the sun",
    "kanji_you4_n3|陽気": "cheerful",
    "kanji_you4_n3|陽性": "positive (test result)",
    "kanji_go2_n3|御飯": "cooked rice, meal",
    "kanji_go2_n3|御礼": "thanks",
    "kanji_go2_n3|制御": "control",
    "kanji_shi6_n3|歯": "tooth",
    "kanji_shi6_n3|歯医者": "dentist",
    "kanji_shi6_n3|歯磨き": "brushing teeth",
    "kanji_sui_n3|風が吹く": "the wind blows",
    "kanji_sui_n3|吹雪": "snowstorm",
    "kanji_sui_n3|吹く": "to blow",
    "kanji_jou4_n3|娘": "daughter",
    "kanji_jou4_n3|娘さん": "someone's daughter",
    "kanji_jou4_n3|一人娘": "only daughter",
    "kanji_go3_n3|誤解": "misunderstanding",
    "kanji_go3_n3|誤り": "error",
    "kanji_go3_n3|誤る": "to be mistaken",
    "kanji_kan5_n3|慣れる": "to get used to",
    "kanji_kan5_n3|習慣": "habit",
    "kanji_kan5_n3|慣習": "custom",
    "kanji_rei2_n3|お礼": "thanks",
    "kanji_rei2_n3|礼儀": "manners",
    "kanji_rei2_n3|失礼": "excuse me, rudeness",
    "kanji_sou5_n3|窓": "window",
    "kanji_sou5_n3|窓口": "service counter",
    "kanji_sou5_n3|同窓会": "alumni reunion",
    "kanji_hin_n3|貧しい": "poor",
    "kanji_hin_n3|貧困": "poverty",
    "kanji_hin_n3|貧血": "anaemia",
    "kanji_do2_n3|怒る": "to get angry",
    "kanji_do2_n3|怒り": "anger",
    "kanji_do2_n3|怒鳴る": "to yell",
    "kanji_so2_n3|祖父": "grandfather",
    "kanji_so2_n3|祖母": "grandmother",
    "kanji_so2_n3|先祖": "ancestors",
    "kanji_hai3_n3|一杯": "a glassful, full",
    "kanji_hai3_n3|乾杯": "cheers, a toast",
    "kanji_hai3_n3|祝杯": "celebratory drink",
    "kanji_hi5_n3|疲れる": "to get tired",
    "kanji_hi5_n3|疲労": "fatigue",
    "kanji_hi5_n3|疲れ": "tiredness",
    "kanji_kai5_n3|皆さん": "everyone",
    "kanji_kai5_n3|皆": "all",
    "kanji_kai5_n3|皆無": "none at all",
    "kanji_mei3_n3|鳴る": "to ring, to sound",
    "kanji_mei3_n3|鳴く": "to chirp, to bark",
    "kanji_mei3_n3|悲鳴": "a scream",
    "kanji_fuku2_n3|お腹": "stomach",
    "kanji_fuku2_n3|腹が立つ": "to get angry",
    "kanji_fuku2_n3|空腹": "hunger",
    "kanji_en3_n3|煙": "smoke",
    "kanji_en3_n3|煙草": "cigarette",
    "kanji_en3_n3|禁煙": "no smoking",
    "kanji_min2_n3|眠る": "to sleep",
    "kanji_min2_n3|眠い": "sleepy",
    "kanji_min2_n3|睡眠": "sleep",
    "kanji_fu7_n3|怖い": "scary, afraid",
    "kanji_fu7_n3|怖がる": "to be frightened",
    "kanji_fu7_n3|恐怖": "fear",
    "kanji_ji6_n3|耳": "ear",
    "kanji_ji6_n3|耳鼻科": "ear, nose and throat clinic",
    "kanji_ji6_n3|初耳": "news to me",
    "kanji_chou2_n3|頂く": "to receive (humble)",
    "kanji_chou2_n3|頂上": "summit",
    "kanji_chou2_n3|山頂": "mountain peak",
    "kanji_sou6_n3|箱": "box",
    "kanji_sou6_n3|本箱": "bookcase",
    "kanji_sou6_n3|ゴミ箱": "rubbish bin",
    "kanji_ban2_n3|今晩": "tonight",
    "kanji_ban2_n3|晩ご飯": "dinner",
    "kanji_ban2_n3|毎晩": "every night",
    "kanji_kan6_n3|寒い": "cold (weather)",
    "kanji_kan6_n3|寒さ": "the cold",
    "kanji_kan6_n3|悪寒": "chills",
    "kanji_hatsu_n3|髪": "hair",
    "kanji_hatsu_n3|髪型": "hairstyle",
    "kanji_hatsu_n3|白髪": "grey hair",
    "kanji_sai6_n3|天才": "genius",
    "kanji_sai6_n3|才能": "talent",
    "kanji_sai6_n3|二十才": "twenty years old",
    "kanji_ka5_n3|靴": "shoes",
    "kanji_ka5_n3|靴下": "socks",
    "kanji_ka5_n3|運動靴": "trainers, sports shoes",
    "kanji_chi3_n3|恥ずかしい": "embarrassing",
    "kanji_chi3_n3|恥": "shame",
    "kanji_chi3_n3|恥じる": "to feel ashamed",
    "kanji_guu_n3|偶然": "coincidence",
    "kanji_guu_n3|偶数": "even number",
    "kanji_guu_n3|配偶者": "spouse",
    "kanji_i3_n3|偉い": "great, admirable",
    "kanji_i3_n3|偉大": "grand, magnificent",
    "kanji_i3_n3|偉人": "a great figure",
    "kanji_byou_n3|猫": "cat",
    "kanji_byou_n3|子猫": "kitten",
    "kanji_byou_n3|猫舌": "sensitive to hot food",
    "kanji_ki8_n3|幾つ": "how many",
    "kanji_ki8_n3|幾ら": "how much",
    "kanji_ki8_n3|幾何学": "geometry",
}
