"""
kotoba_meaning_en.py

Locked source of truth for Kotoba's English word-meaning translations
(the `meaningEn` field on `KotobaEntry` — see lib/data/models/kotoba_entry.dart
and CLAUDE.md's "Correction, Kotoba only" note under the language-toggle
section for the full story). Same locked-list pattern as
dokkai_lists.py/bunpou_grammar_lists.py: this file is the only place
translations get authored; apply_kotoba_meaning_en.py reads it and
patches the real JSON files, so there's never a second copy to keep in
sync by hand.

STATUS (update this line every time a category is finished):
    Done (43): all of "Alam & Lingkungan" (10) + all of "Makanan &
    Minuman" (7) + all of "Tubuh & Kesehatan" (6) + all of "Tempat &
    Transportasi" (6) + all of "Manusia & Sosial" (6) + 4 of
    "Pendidikan & Pekerjaan" (alat_tulis_sekolah, mata_pelajaran,
    teknologi_gadget, media_hiburan) + 4 of "Waktu & Angka" (musim,
    angka_satuan, warna, bentuk) = 1069/1266 words. Remaining: 2
    categories, 197 words — pekerjaan_kantor (118) and hari_bulan (79).
    Next session: read assets/data/kotoba/pekerjaan_kantor.json and
    hari_bulan.json, translate, add both dicts here, run the applier
    for both, tick both boxes in CLAUDE.md, this reaches 1266/1266 =
    ALL 45 real categories done (konsep_umum stays excluded).
    See CLAUDE.md's Kotoba-localization note for the full per-category
    checklist and the exact workflow to add a new category here.

Structure: one dict per category id, mapping the word's `id` (from that
category's assets/data/kotoba/{category_id}.json) to a short English
gloss — translate what `meaning` already says, don't invent new content.
Keep entries in the same order as the JSON file for easy side-by-side
diffing while authoring.

Cara pakai (nambah kategori baru):
    1. Buka assets/data/kotoba/{category_id}.json, baca tiap `id` + `meaning`.
    2. Tambah dict baru di MEANING_EN, key = category_id, isi id -> english.
    3. Jalankan: python scripts/apply_kotoba_meaning_en.py {category_id}
       (atau tanpa argumen buat proses SEMUA kategori yang ada di dict ini).
    4. Cek output-nya: "Patched N/N" harus match jumlah kata di kategori itu,
       dan tidak ada "GAGAL"/id yang tidak ketemu.
    5. flutter analyze / flutter test, lalu commit.
"""

MEANING_EN: dict[str, dict[str, str]] = {
    "ikan": {
        "kotoba_ikan_maguro": "tuna",
        "kotoba_ikan_sake": "salmon",
        "kotoba_ikan_tai": "red seabream",
        "kotoba_ikan_unagi": "eel",
        "kotoba_ikan_iwashi": "sardine",
        "kotoba_ikan_saba": "mackerel",
        "kotoba_ikan_katsuo": "bonito (skipjack tuna)",
        "kotoba_ikan_fugu": "pufferfish (fugu)",
    },
    "hewan_darat": {
        "kotoba_hewan_darat_inu": "dog",
        "kotoba_hewan_darat_neko": "cat",
        "kotoba_hewan_darat_usagi": "rabbit",
        "kotoba_hewan_darat_zou": "elephant",
        "kotoba_hewan_darat_raion": "lion",
        "kotoba_hewan_darat_tora": "tiger",
        "kotoba_hewan_darat_kuma": "bear",
        "kotoba_hewan_darat_saru": "monkey",
        "kotoba_hewan_darat_uma": "horse",
        "kotoba_hewan_darat_ushi": "cow",
        "kotoba_hewan_darat_buta": "pig",
        "kotoba_hewan_darat_hitsuji": "sheep",
        "kotoba_hewan_darat_panda": "panda",
        "kotoba_hewan_darat_kirin": "giraffe",
        "kotoba_hewan_darat_nezumi": "mouse",
        "kotoba_hewan_darat_shika": "deer",
        "kotoba_hewan_darat_koala": "koala",
        "kotoba_hewan_darat_kame": "turtle",
        "kotoba_hewan_darat_hebi": "snake",
        "kotoba_hewan_darat_kaeru": "frog",
        "kotoba_hewan_darat_risu": "squirrel",
        "kotoba_hewan_darat_ookami": "wolf",
    },
    "burung": {
        "kotoba_burung_tori": "bird",
        "kotoba_burung_niwatori": "chicken",
        "kotoba_burung_ahiru": "duck",
        "kotoba_burung_suzume": "sparrow",
        "kotoba_burung_karasu": "crow",
        "kotoba_burung_hato": "pigeon/dove",
        "kotoba_burung_tsuru": "crane",
        "kotoba_burung_fukurou": "owl",
        "kotoba_burung_taka": "hawk",
        "kotoba_burung_pengin": "penguin",
        "kotoba_burung_hakuchou": "swan",
        "kotoba_burung_kiji": "pheasant (Japan's national bird)",
        "kotoba_burung_inko": "parakeet",
        "kotoba_burung_kodori": "small bird",
    },
    "serangga": {
        "kotoba_serangga_mushi": "insect/bug",
        "kotoba_serangga_chou": "butterfly",
        "kotoba_serangga_hachi": "bee",
        "kotoba_serangga_ari": "ant",
        "kotoba_serangga_ka": "mosquito",
        "kotoba_serangga_hae": "fly",
        "kotoba_serangga_kumo": "spider",
        "kotoba_serangga_tonbo": "dragonfly",
        "kotoba_serangga_semi": "cicada",
        "kotoba_serangga_kabutomushi": "rhinoceros beetle",
        "kotoba_serangga_tentoumushi": "ladybug",
        "kotoba_serangga_batta": "grasshopper",
        "kotoba_serangga_kuwagata": "stag beetle",
    },
    "pohon": {
        "kotoba_pohon_ki": "tree",
        "kotoba_pohon_sakura": "cherry blossom tree",
        "kotoba_pohon_matsu": "pine tree",
        "kotoba_pohon_take": "bamboo",
        "kotoba_pohon_momiji": "maple tree (momiji)",
        "kotoba_pohon_yashi": "palm/coconut tree",
        "kotoba_pohon_ichou": "ginkgo tree",
        "kotoba_pohon_sugi": "Japanese cedar tree",
    },
    "bunga_tanaman": {
        "kotoba_bunga_tanaman_hana": "flower",
        "kotoba_bunga_tanaman_bara": "rose",
        "kotoba_bunga_tanaman_yuri": "lily",
        "kotoba_bunga_tanaman_himawari": "sunflower",
        "kotoba_bunga_tanaman_tanpopo": "dandelion",
        "kotoba_bunga_tanaman_ajisai": "hydrangea",
        "kotoba_bunga_tanaman_sumire": "violet",
        "kotoba_bunga_tanaman_ume": "plum blossom/tree (ume)",
        "kotoba_bunga_tanaman_shokubutsu": "plant",
        "kotoba_bunga_tanaman_kusabana": "flowering plants",
        "kotoba_bunga_tanaman_shibafu": "lawn/turf grass",
    },
    "buah": {
        "kotoba_buah_ringo": "apple",
        "kotoba_buah_banana": "banana",
        "kotoba_buah_mikan": "mandarin orange",
        "kotoba_buah_budou": "grape",
        "kotoba_buah_momo": "peach",
        "kotoba_buah_suika": "watermelon",
        "kotoba_buah_ichigo": "strawberry",
        "kotoba_buah_nashi": "Asian pear",
        "kotoba_buah_kaki": "persimmon",
        "kotoba_buah_remon": "lemon",
        "kotoba_buah_meron": "melon",
        "kotoba_buah_papaiya": "papaya",
        "kotoba_buah_anzu": "apricot",
        "kotoba_buah_sakuranbo": "cherry",
    },
    "sayuran": {
        "kotoba_sayuran_yasai": "vegetable (general)",
        "kotoba_sayuran_ninjin": "carrot",
        "kotoba_sayuran_jagaimo": "potato",
        "kotoba_sayuran_tamanegi": "onion",
        "kotoba_sayuran_kyabetsu": "cabbage",
        "kotoba_sayuran_tomato": "tomato",
        "kotoba_sayuran_kyuuri": "cucumber",
        "kotoba_sayuran_nasu": "eggplant",
        "kotoba_sayuran_daikon": "daikon radish",
        "kotoba_sayuran_hourensou": "spinach",
        "kotoba_sayuran_piiman": "green bell pepper",
        "kotoba_sayuran_renkon": "lotus root",
        "kotoba_sayuran_negi": "green onion/scallion",
        "kotoba_sayuran_ninniku": "garlic",
    },
    "cuaca": {
        "kotoba_cuaca_tenki": "weather",
        "kotoba_cuaca_hare": "sunny/clear",
        "kotoba_cuaca_ame": "rain",
        "kotoba_cuaca_kumori": "cloudy",
        "kotoba_cuaca_yuki": "snow",
        "kotoba_cuaca_kaze": "wind",
        "kotoba_cuaca_kaminari": "thunder/lightning",
        "kotoba_cuaca_kiri": "fog",
        "kotoba_cuaca_taifuu": "typhoon",
        "kotoba_cuaca_niji": "rainbow",
        "kotoba_cuaca_tsuyu": "rainy season (Japan)",
        "kotoba_cuaca_hyou": "hail",
        "kotoba_cuaca_shitsudo": "humidity",
        "kotoba_cuaca_kiatsu": "air pressure",
        "kotoba_cuaca_mousho": "extreme heat",
        "kotoba_cuaca_kanpa": "cold wave",
        "kotoba_cuaca_tenkiyohou": "weather forecast",
        "kotoba_cuaca_aozora": "blue sky",
        "kotoba_cuaca_kansou": "drying/dryness",
        "kotoba_cuaca_kion": "air temperature",
        "kotoba_cuaca_kouon": "high temperature",
        "kotoba_cuaca_nikkou": "sunlight",
        "kotoba_cuaca_kuuki": "air",
    },
    "bencana_alam": {
        "kotoba_bencana_alam_jishin": "earthquake",
        "kotoba_bencana_alam_tsunami": "tsunami",
        "kotoba_bencana_alam_kouzui": "flood",
        "kotoba_bencana_alam_kaji": "fire",
        "kotoba_bencana_alam_funka": "volcanic eruption",
        "kotoba_bencana_alam_teiden": "power outage",
        "kotoba_bencana_alam_kazan": "volcano",
        "kotoba_bencana_alam_hinan": "evacuation",
        "kotoba_bencana_alam_arashi": "storm",
        "kotoba_bencana_alam_bousai": "disaster prevention/mitigation",
        "kotoba_bencana_alam_hinanjo": "evacuation shelter",
        "kotoba_bencana_alam_fukkyuu": "recovery (post-disaster)",
        "kotoba_bencana_alam_houkai": "collapse",
        "kotoba_bencana_alam_hisai": "being disaster-stricken",
        "kotoba_bencana_alam_songai": "damage/loss",
        "kotoba_bencana_alam_kyuujo": "rescue",
        "kotoba_bencana_alam_tatsumaki": "tornado",
        "kotoba_bencana_alam_kasai": "fire (formal term)",
    },
    "makanan_jepang": {
        "kotoba_makanan_jepang_sushi": "sushi",
        "kotoba_makanan_jepang_ramen": "ramen (noodle soup)",
        "kotoba_makanan_jepang_udon": "udon (thick wheat noodles)",
        "kotoba_makanan_jepang_soba": "soba (buckwheat noodles)",
        "kotoba_makanan_jepang_tenpura": "tempura",
        "kotoba_makanan_jepang_sashimi": "sashimi (raw fish)",
        "kotoba_makanan_jepang_onigiri": "rice ball (onigiri)",
        "kotoba_makanan_jepang_misoshiru": "miso soup",
        "kotoba_makanan_jepang_gyouza": "fried dumplings (gyoza)",
        "kotoba_makanan_jepang_okonomiyaki": "okonomiyaki (savory pancake)",
        "kotoba_makanan_jepang_karaage": "Japanese fried chicken",
        "kotoba_makanan_jepang_katsudon": "pork cutlet rice bowl",
        "kotoba_makanan_jepang_nattou": "natto (fermented soybeans)",
        "kotoba_makanan_jepang_takoyaki": "takoyaki (octopus balls)",
        "kotoba_makanan_jepang_yakitori": "grilled chicken skewers",
        "kotoba_makanan_jepang_bentou": "boxed lunch (bento)",
        "kotoba_makanan_jepang_washoku": "Japanese food",
    },
    "makanan_indonesia": {
        "kotoba_makanan_indonesia_nasigoreng": "fried rice",
        "kotoba_makanan_indonesia_miegoreng": "fried noodles",
        "kotoba_makanan_indonesia_sate": "satay",
        "kotoba_makanan_indonesia_gadogado": "gado-gado (vegetable salad with peanut sauce)",
        "kotoba_makanan_indonesia_rendang": "rendang",
        "kotoba_makanan_indonesia_tempe": "tempeh",
        "kotoba_makanan_indonesia_sambal": "chili sauce (sambal)",
    },
    "makanan_barat": {
        "kotoba_makanan_barat_pan": "bread",
        "kotoba_makanan_barat_hanbaagaa": "hamburger",
        "kotoba_makanan_barat_piza": "pizza",
        "kotoba_makanan_barat_pasuta": "pasta",
        "kotoba_makanan_barat_sarada": "salad",
        "kotoba_makanan_barat_suteeki": "steak",
        "kotoba_makanan_barat_suupu": "soup",
        "kotoba_makanan_barat_sandoicchi": "sandwich",
        "kotoba_makanan_barat_omuretsu": "omelet",
        "kotoba_makanan_barat_furaidopoteto": "french fries",
        "kotoba_makanan_barat_chiizu": "cheese",
        "kotoba_makanan_barat_dezaato": "dessert",
        "kotoba_makanan_barat_keeki": "cake",
        "kotoba_makanan_barat_supagetti": "spaghetti",
    },
    "minuman": {
        "kotoba_minuman_mizu": "water",
        "kotoba_minuman_ocha": "Japanese tea",
        "kotoba_minuman_koucha": "black tea",
        "kotoba_minuman_koohii": "coffee",
        "kotoba_minuman_gyuunyuu": "milk",
        "kotoba_minuman_juusu": "juice",
        "kotoba_minuman_koora": "cola",
        "kotoba_minuman_biiru": "beer",
        "kotoba_minuman_nihonshu": "sake (Japanese rice wine)",
        "kotoba_minuman_wain": "wine",
        "kotoba_minuman_tansan": "carbonated/soda drink",
        "kotoba_minuman_mirukutii": "milk tea",
        "kotoba_minuman_inryou": "beverage/drink",
        "kotoba_minuman_aiin": "habitually enjoying a drink",
    },
    "bumbu_rempah": {
        "kotoba_bumbu_rempah_shio": "salt",
        "kotoba_bumbu_rempah_satou": "sugar",
        "kotoba_bumbu_rempah_shouyu": "soy sauce",
        "kotoba_bumbu_rempah_miso": "miso paste",
        "kotoba_bumbu_rempah_su": "vinegar",
        "kotoba_bumbu_rempah_koshou": "pepper",
        "kotoba_bumbu_rempah_abura": "oil",
        "kotoba_bumbu_rempah_shouga": "ginger",
        "kotoba_bumbu_rempah_karashi": "Japanese mustard (karashi)",
        "kotoba_bumbu_rempah_wasabi": "wasabi",
        "kotoba_bumbu_rempah_katsuobushi": "dried bonito flakes",
        "kotoba_bumbu_rempah_mirin": "mirin (sweet cooking sake)",
        "kotoba_bumbu_rempah_choumiryou": "seasoning/condiments",
    },
    "peralatan_masak": {
        "kotoba_peralatan_masak_nabe": "pot",
        "kotoba_peralatan_masak_furaipan": "frying pan",
        "kotoba_peralatan_masak_houchou": "kitchen knife",
        "kotoba_peralatan_masak_manaita": "cutting board",
        "kotoba_peralatan_masak_oobun": "oven",
        "kotoba_peralatan_masak_denshirenji": "microwave",
        "kotoba_peralatan_masak_suihanki": "rice cooker",
        "kotoba_peralatan_masak_oosaji": "tablespoon (measure)",
        "kotoba_peralatan_masak_kosaji": "teaspoon (measure)",
        "kotoba_peralatan_masak_zaru": "colander/strainer",
        "kotoba_peralatan_masak_yakan": "kettle",
        "kotoba_peralatan_masak_sara": "plate",
        "kotoba_peralatan_masak_shokki": "tableware",
        "kotoba_peralatan_masak_youki": "container",
    },
    "cara_memasak": {
        "kotoba_cara_memasak_yaku": "to grill/pan-fry",
        "kotoba_cara_memasak_niru": "to simmer/boil in broth",
        "kotoba_cara_memasak_ageru": "to deep-fry",
        "kotoba_cara_memasak_musu": "to steam",
        "kotoba_cara_memasak_itameru": "to stir-fry",
        "kotoba_cara_memasak_yuderu": "to boil",
        "kotoba_cara_memasak_kiru": "to cut",
        "kotoba_cara_memasak_mazeru": "to mix",
        "kotoba_cara_memasak_tsukuru": "to make (cook)",
        "kotoba_cara_memasak_taku": "to cook rice",
    },
    "anggota_tubuh": {
        "kotoba_anggota_tubuh_atama": "head",
        "kotoba_anggota_tubuh_kao": "face",
        "kotoba_anggota_tubuh_me": "eye",
        "kotoba_anggota_tubuh_hana": "nose",
        "kotoba_anggota_tubuh_mimi": "ear",
        "kotoba_anggota_tubuh_kuchi": "mouth",
        "kotoba_anggota_tubuh_ha": "tooth",
        "kotoba_anggota_tubuh_te": "hand",
        "kotoba_anggota_tubuh_ashi": "leg/foot",
        "kotoba_anggota_tubuh_kubi": "neck",
        "kotoba_anggota_tubuh_kata": "shoulder",
        "kotoba_anggota_tubuh_onaka": "stomach/belly",
        "kotoba_anggota_tubuh_senaka": "back",
        "kotoba_anggota_tubuh_yubi": "finger",
        "kotoba_anggota_tubuh_kami": "hair",
        "kotoba_anggota_tubuh_mune": "chest",
        "kotoba_anggota_tubuh_hiza": "knee",
        "kotoba_anggota_tubuh_shinzou": "heart",
        "kotoba_anggota_tubuh_naizou": "internal organs",
        "kotoba_anggota_tubuh_kinniku": "muscle",
        "kotoba_anggota_tubuh_kansetsu": "joint",
        "kotoba_anggota_tubuh_kekkan": "blood vessel",
        "kotoba_anggota_tubuh_kamigata": "hairstyle",
        "kotoba_anggota_tubuh_shisei": "posture",
        "kotoba_anggota_tubuh_jintai": "human body",
        "kotoba_anggota_tubuh_ashikoshi": "legs and hips",
        "kotoba_anggota_tubuh_ashimoto": "one's step/footing",
        "kotoba_anggota_tubuh_shinchou": "height",
        "kotoba_anggota_tubuh_ashiato": "footprint",
        "kotoba_anggota_tubuh_shiraga": "gray/white hair",
    },
    "penyakit_gejala": {
        "kotoba_penyakit_gejala_kaze": "cold/flu",
        "kotoba_penyakit_gejala_netsu": "fever",
        "kotoba_penyakit_gejala_seki": "cough",
        "kotoba_penyakit_gejala_hanamizu": "runny nose",
        "kotoba_penyakit_gejala_itai": "painful/hurting",
        "kotoba_penyakit_gejala_kega": "injury/wound",
        "kotoba_penyakit_gejala_arerugii": "allergy",
        "kotoba_penyakit_gejala_kafunshou": "hay fever (pollen allergy)",
        "kotoba_penyakit_gejala_geri": "diarrhea",
        "kotoba_penyakit_gejala_memai": "dizziness",
        "kotoba_penyakit_gejala_tsukare": "fatigue/tiredness",
        "kotoba_penyakit_gejala_shindan": "diagnosis",
        "kotoba_penyakit_gejala_kansen": "infection",
        "kotoba_penyakit_gejala_men'eki": "immunity",
        "kotoba_penyakit_gejala_shoujou": "symptom",
        "kotoba_penyakit_gejala_akka": "worsening (of a condition)",
        "kotoba_penyakit_gejala_kaifuku": "recovery",
        "kotoba_penyakit_gejala_chiryou": "treatment",
        "kotoba_penyakit_gejala_yobou": "prevention",
        "kotoba_penyakit_gejala_zutsuu": "headache",
        "kotoba_penyakit_gejala_fukutsuu": "stomachache",
        "kotoba_penyakit_gejala_kossetsu": "bone fracture",
        "kotoba_penyakit_gejala_shukketsu": "bleeding",
        "kotoba_penyakit_gejala_taion": "body temperature",
        "kotoba_penyakit_gejala_hinketsu": "anemia",
        "kotoba_penyakit_gejala_chuudoku": "poisoning",
        "kotoba_penyakit_gejala_mahi": "paralysis/numbness",
        "kotoba_penyakit_gejala_enshou": "inflammation",
        "kotoba_penyakit_gejala_benpi": "constipation",
        "kotoba_penyakit_gejala_shokuyoku": "appetite",
        "kotoba_penyakit_gejala_suimin": "sleep",
        "kotoba_penyakit_gejala_mushiba": "cavity (tooth decay)",
        "kotoba_penyakit_gejala_fushou": "injury",
        "kotoba_penyakit_gejala_hirou": "fatigue",
        "kotoba_penyakit_gejala_guai": "(physical) condition",
    },
    "obat_obatan": {
        "kotoba_obat_obatan_kusuri": "medicine",
        "kotoba_obat_obatan_byouin": "hospital",
        "kotoba_obat_obatan_isha": "doctor",
        "kotoba_obat_obatan_kangoshi": "nurse",
        "kotoba_obat_obatan_yakkyoku": "pharmacy",
        "kotoba_obat_obatan_chuusha": "injection/shot",
        "kotoba_obat_obatan_bansoukou": "bandage (band-aid)",
        "kotoba_obat_obatan_taionkei": "thermometer",
        "kotoba_obat_obatan_masuku": "mask",
        "kotoba_obat_obatan_kenshin": "health checkup",
        "kotoba_obat_obatan_shohou": "prescription",
        "kotoba_obat_obatan_fukusayou": "side effect",
        "kotoba_obat_obatan_fukuyou": "taking (medicine, formal)",
        "kotoba_obat_obatan_masui": "anesthesia",
        "kotoba_obat_obatan_shoudoku": "disinfection",
        "kotoba_obat_obatan_houtai": "bandage",
        "kotoba_obat_obatan_jouzai": "tablet/pill",
        "kotoba_obat_obatan_eiyou": "nutrition",
        "kotoba_obat_obatan_kango": "nursing care",
        "kotoba_obat_obatan_kenkou": "health",
        "kotoba_obat_obatan_kensa": "examination/inspection",
        "kotoba_obat_obatan_shujutsu": "surgery (medical)",
        "kotoba_obat_obatan_kurumaisu": "wheelchair",
        "kotoba_obat_obatan_geka": "surgery (medical field)",
        "kotoba_obat_obatan_naika": "internal medicine (medical field)",
        "kotoba_obat_obatan_yuketsu": "blood transfusion",
        "kotoba_obat_obatan_nyuuin": "hospitalization",
    },
    "olahraga": {
        "kotoba_olahraga_supootsu": "sports",
        "kotoba_olahraga_sakkaa": "soccer/football",
        "kotoba_olahraga_yakyuu": "baseball",
        "kotoba_olahraga_basukettobooru": "basketball",
        "kotoba_olahraga_suiei": "swimming",
        "kotoba_olahraga_tenisu": "tennis",
        "kotoba_olahraga_ranningu": "running",
        "kotoba_olahraga_juudou": "judo",
        "kotoba_olahraga_karate": "karate",
        "kotoba_olahraga_sumou": "sumo",
        "kotoba_olahraga_taisou": "gymnastics/calisthenics",
        "kotoba_olahraga_undou": "exercise/physical activity",
        "kotoba_olahraga_tanren": "(physical/mental) training",
        "kotoba_olahraga_jikyuuryoku": "endurance/stamina",
        "kotoba_olahraga_kinryoku": "muscle strength",
        "kotoba_olahraga_takkyuu": "table tennis",
        "kotoba_olahraga_rikujou": "track and field/athletics",
        "kotoba_olahraga_yuushou": "championship/victory",
        "kotoba_olahraga_shiai": "match/game",
        "kotoba_olahraga_senshu": "athlete/player",
        "kotoba_olahraga_kouhan": "second half",
        "kotoba_olahraga_zenhan": "first half",
        "kotoba_olahraga_tairyoku": "physical strength/stamina",
        "kotoba_olahraga_tozan": "mountain climbing",
        "kotoba_olahraga_taikai": "tournament/competition",
        "kotoba_olahraga_hitteki": "comparable/rivaling",
    },
    "perasaan_emosi": {
        "kotoba_perasaan_emosi_ureshii": "happy/glad",
        "kotoba_perasaan_emosi_kanashii": "sad",
        "kotoba_perasaan_emosi_tanoshii": "fun/enjoyable",
        "kotoba_perasaan_emosi_okoru": "to get angry",
        "kotoba_perasaan_emosi_kowai": "scary/afraid",
        "kotoba_perasaan_emosi_shinpai": "worried/anxious",
        "kotoba_perasaan_emosi_bikkuri": "surprised",
        "kotoba_perasaan_emosi_sabishii": "lonely",
        "kotoba_perasaan_emosi_hazukashii": "embarrassed",
        "kotoba_perasaan_emosi_anshin": "relieved/at ease",
        "kotoba_perasaan_emosi_ando": "relief (formal)",
        "kotoba_perasaan_emosi_douyou": "agitation/shock",
        "kotoba_perasaan_emosi_rakutan": "disappointment/dejection",
        "kotoba_perasaan_emosi_yuuutsu": "gloomy/melancholy",
        "kotoba_perasaan_emosi_kanki": "great joy/elation",
        "kotoba_perasaan_emosi_kinchou": "nervous/tense",
        "kotoba_perasaan_emosi_koufun": "excitement",
        "kotoba_perasaan_emosi_inshou": "impression",
        "kotoba_perasaan_emosi_kangeki": "being deeply moved",
        "kotoba_perasaan_emosi_kanshin": "admiration",
        "kotoba_perasaan_emosi_kansou": "impression/thoughts",
        "kotoba_perasaan_emosi_kandou": "being deeply moved/touched",
        "kotoba_perasaan_emosi_gaman": "patience/endurance",
        "kotoba_perasaan_emosi_kurou": "hardship/hard work",
        "kotoba_perasaan_emosi_jishin": "self-confidence",
        "kotoba_perasaan_emosi_jiman": "pride/boasting",
        "kotoba_perasaan_emosi_sonkei": "respect",
        "kotoba_perasaan_emosi_nattoku": "understanding/being convinced",
        "kotoba_perasaan_emosi_monku": "complaint",
        "kotoba_perasaan_emosi_aijou": "affection/love",
        "kotoba_perasaan_emosi_aichaku": "attachment (emotional)",
        "kotoba_perasaan_emosi_akui": "malice/ill will",
        "kotoba_perasaan_emosi_ishi": "will/determination",
        "kotoba_perasaan_emosi_miryoku": "charm/appeal",
        "kotoba_perasaan_emosi_nesshin": "enthusiasm/eagerness",
        "kotoba_perasaan_emosi_shigeki": "stimulus",
        "kotoba_perasaan_emosi_waruguchi": "badmouthing/gossip",
        "kotoba_perasaan_emosi_binkan": "sensitive",
        "kotoba_perasaan_emosi_bujoku": "insult",
        "kotoba_perasaan_emosi_burei": "rudeness",
        "kotoba_perasaan_emosi_daitan": "bold/daring",
        "kotoba_perasaan_emosi_dokyou": "courage/guts",
        "kotoba_perasaan_emosi_doujou": "sympathy",
        "kotoba_perasaan_emosi_fukushuu": "revenge",
        "kotoba_perasaan_emosi_hairyo": "consideration",
        "kotoba_perasaan_emosi_henken": "prejudice",
        "kotoba_perasaan_emosi_himei": "scream",
        "kotoba_perasaan_emosi_hinan": "criticism/blame",
        "kotoba_perasaan_emosi_hisan": "tragic/miserable",
        "kotoba_perasaan_emosi_honshin": "true feelings",
        "kotoba_perasaan_emosi_jikaku": "self-awareness",
        "kotoba_perasaan_emosi_jounetsu": "passion",
        "kotoba_perasaan_emosi_kakushin": "conviction/certainty",
        "kotoba_perasaan_emosi_ijiwaru": "mean/spiteful",
        "kotoba_perasaan_emosi_kenka": "quarrel/fight",
        "kotoba_perasaan_emosi_kibun": "mood/feeling",
        "kotoba_perasaan_emosi_shinsetsu": "kind",
        "kotoba_perasaan_emosi_teinei": "polite",
        "kotoba_perasaan_emosi_zannen": "unfortunate/regrettable",
    },
    "ekspresi_wajah": {
        "kotoba_ekspresi_wajah_warau": "to laugh/smile",
        "kotoba_ekspresi_wajah_naku": "to cry",
        "kotoba_ekspresi_wajah_hohoemu": "to smile (gently)",
        "kotoba_ekspresi_wajah_odoroku": "to be surprised",
        "kotoba_ekspresi_wajah_mabataki": "blink (of the eyes)",
        "kotoba_ekspresi_wajah_akubi": "to yawn",
        "kotoba_ekspresi_wajah_shikameru": "to grimace/frown",
        "kotoba_ekspresi_wajah_mitsumeru": "to stare/gaze at",
        "kotoba_ekspresi_wajah_egao": "smiling face",
        "kotoba_ekspresi_wajah_bishou": "a smile",
    },
    "ruangan_rumah": {
        "kotoba_ruangan_rumah_heya": "room",
        "kotoba_ruangan_rumah_genkan": "entryway (shoe-removal area)",
        "kotoba_ruangan_rumah_daidokoro": "kitchen",
        "kotoba_ruangan_rumah_ima": "living room",
        "kotoba_ruangan_rumah_shinshitsu": "bedroom",
        "kotoba_ruangan_rumah_toire": "toilet",
        "kotoba_ruangan_rumah_ofuro": "bath(tub)",
        "kotoba_ruangan_rumah_yokushitsu": "bathroom (formal)",
        "kotoba_ruangan_rumah_beranda": "balcony/veranda",
        "kotoba_ruangan_rumah_kaidan": "stairs",
        "kotoba_ruangan_rumah_niwa": "yard/garden",
        "kotoba_ruangan_rumah_senmenjo": "washroom/washstand",
        "kotoba_ruangan_rumah_shako": "garage",
        "kotoba_ruangan_rumah_kadan": "flower bed",
        "kotoba_ruangan_rumah_tenjou": "ceiling",
        "kotoba_ruangan_rumah_yane": "roof",
        "kotoba_ruangan_rumah_rouka": "hallway/corridor",
        "kotoba_ruangan_rumah_shosai": "study/home office",
        "kotoba_ruangan_rumah_geshuku": "boarding house/lodging",
        "kotoba_ruangan_rumah_suidou": "water supply/plumbing",
    },
    "perabot_rumah": {
        "kotoba_perabot_rumah_isu": "chair",
        "kotoba_perabot_rumah_tsukue": "desk",
        "kotoba_perabot_rumah_teeburu": "table",
        "kotoba_perabot_rumah_beddo": "bed",
        "kotoba_perabot_rumah_sofaa": "sofa",
        "kotoba_perabot_rumah_tana": "shelf",
        "kotoba_perabot_rumah_reizouko": "refrigerator",
        "kotoba_perabot_rumah_kagami": "mirror",
        "kotoba_perabot_rumah_kaaten": "curtain",
        "kotoba_perabot_rumah_tansu": "chest of drawers/wardrobe",
        "kotoba_perabot_rumah_denki": "light/electricity",
        "kotoba_perabot_rumah_shuunou": "storage",
        "kotoba_perabot_rumah_kagu": "furniture",
        "kotoba_perabot_rumah_reibou": "air conditioning (cooling)",
        "kotoba_perabot_rumah_danbou": "heating",
        "kotoba_perabot_rumah_kabin": "vase",
        "kotoba_perabot_rumah_denkyuu": "light bulb",
        "kotoba_perabot_rumah_hondana": "bookshelf",
        "kotoba_perabot_rumah_soujiki": "vacuum cleaner",
        "kotoba_perabot_rumah_dentou": "electric light",
        "kotoba_perabot_rumah_futon": "Japanese futon (floor bedding)",
    },
    "bangunan_fasilitas": {
        "kotoba_bangunan_fasilitas_gakkou": "school",
        "kotoba_bangunan_fasilitas_ginkou": "bank",
        "kotoba_bangunan_fasilitas_yuubinkyoku": "post office",
        "kotoba_bangunan_fasilitas_toshokan": "library",
        "kotoba_bangunan_fasilitas_kouen": "(public) park",
        "kotoba_bangunan_fasilitas_suupaa": "supermarket",
        "kotoba_bangunan_fasilitas_depaato": "department store",
        "kotoba_bangunan_fasilitas_eki": "station",
        "kotoba_bangunan_fasilitas_kuukou": "airport",
        "kotoba_bangunan_fasilitas_jinja": "Shinto shrine",
        "kotoba_bangunan_fasilitas_otera": "Buddhist temple",
        "kotoba_bangunan_fasilitas_kensetsu": "construction",
        "kotoba_bangunan_fasilitas_kaichiku": "building renovation",
        "kotoba_bangunan_fasilitas_tekkyo": "demolition/removal",
        "kotoba_bangunan_fasilitas_ritchi": "location (of a business)",
        "kotoba_bangunan_fasilitas_kyoushitsu": "classroom",
        "kotoba_bangunan_fasilitas_ryokan": "traditional Japanese inn",
        "kotoba_bangunan_fasilitas_ekimae": "in front of the station",
        "kotoba_bangunan_fasilitas_kouban": "police box",
        "kotoba_bangunan_fasilitas_doubutsuen": "zoo",
        "kotoba_bangunan_fasilitas_bijutsukan": "art museum/gallery",
        "kotoba_bangunan_fasilitas_hakubutsukan": "museum",
        "kotoba_bangunan_fasilitas_kissaten": "coffee shop/café",
        "kotoba_bangunan_fasilitas_taishikan": "embassy",
        "kotoba_bangunan_fasilitas_saibansho": "courthouse",
        "kotoba_bangunan_fasilitas_yakusho": "government office",
        "kotoba_bangunan_fasilitas_koujou2": "factory",
        "kotoba_bangunan_fasilitas_jimusho": "office",
        "kotoba_bangunan_fasilitas_onsen": "hot spring",
        "kotoba_bangunan_fasilitas_kaijou": "venue opening",
        "kotoba_bangunan_fasilitas_kaiten": "store opening",
        "kotoba_bangunan_fasilitas_kannai": "inside the building",
        "kotoba_bangunan_fasilitas_kenchiku": "architecture/construction",
        "kotoba_bangunan_fasilitas_kouji": "construction project",
        "kotoba_bangunan_fasilitas_jitaku": "one's own home",
        "kotoba_bangunan_fasilitas_setsubi": "facilities/equipment",
        "kotoba_bangunan_fasilitas_souko": "warehouse",
        "kotoba_bangunan_fasilitas_tsuuro": "passage/aisle",
        "kotoba_bangunan_fasilitas_teiin": "capacity (number of people)",
        "kotoba_bangunan_fasilitas_tochi": "land",
        "kotoba_bangunan_fasilitas_baiten": "small stand/kiosk",
        "kotoba_bangunan_fasilitas_madoguchi": "counter/window (service)",
        "kotoba_bangunan_fasilitas_yachin": "rent",
        "kotoba_bangunan_fasilitas_yuusou": "mailing/postal delivery",
        "kotoba_bangunan_fasilitas_shiyakusho": "city hall",
        "kotoba_bangunan_fasilitas_senmonten": "specialty store",
        "kotoba_bangunan_fasilitas_biyouin": "beauty salon",
        "kotoba_bangunan_fasilitas_hoikuen": "daycare center",
        "kotoba_bangunan_fasilitas_ichiba": "market",
        "kotoba_bangunan_fasilitas_nyuujou": "admission/entry",
        "kotoba_bangunan_fasilitas_heisa": "closure (of a place)",
        "kotoba_bangunan_fasilitas_houtei": "courtroom",
        "kotoba_bangunan_fasilitas_deiriguchi": "entrance/exit",
        "kotoba_bangunan_fasilitas_kaikan": "meeting hall/community center",
        "kotoba_bangunan_fasilitas_kousha": "school building",
        "kotoba_bangunan_fasilitas_koutei": "school yard",
        "kotoba_bangunan_fasilitas_machiaishitsu": "waiting room",
        "kotoba_bangunan_fasilitas_miseya": "shop/store",
        "kotoba_bangunan_fasilitas_shoten": "bookstore",
        "kotoba_bangunan_fasilitas_shouten": "shop/store",
        "kotoba_bangunan_fasilitas_sokutatsu": "express mail",
        "kotoba_bangunan_fasilitas_annai": "guidance/information",
        "kotoba_bangunan_fasilitas_chuugakkou": "junior high school",
        "kotoba_bangunan_fasilitas_chuushajou": "parking lot",
        "kotoba_bangunan_fasilitas_hikoujou": "airfield/airport",
        "kotoba_bangunan_fasilitas_kaigishitsu": "meeting room",
        "kotoba_bangunan_fasilitas_kenkyuushitsu": "research room/lab",
        "kotoba_bangunan_fasilitas_koudou": "auditorium/hall",
        "kotoba_bangunan_fasilitas_koukou": "high school",
        "kotoba_bangunan_fasilitas_okujou": "rooftop",
        "kotoba_bangunan_fasilitas_shougakkou": "elementary school",
        "kotoba_bangunan_fasilitas_uketsuke": "reception (desk)",
        "kotoba_bangunan_fasilitas_yoyaku": "reservation",
    },
    "kendaraan": {
        "kotoba_kendaraan_kuruma": "car",
        "kotoba_kendaraan_densha": "(electric) train",
        "kotoba_kendaraan_basu": "bus",
        "kotoba_kendaraan_jitensha": "bicycle",
        "kotoba_kendaraan_hikouki": "airplane",
        "kotoba_kendaraan_fune": "ship/boat",
        "kotoba_kendaraan_takushii": "taxi",
        "kotoba_kendaraan_baiku": "motorcycle",
        "kotoba_kendaraan_shinkansen": "bullet train",
        "kotoba_kendaraan_torakku": "truck",
        "kotoba_kendaraan_unkou": "(transportation) operation/service",
        "kotoba_kendaraan_chien": "delay",
        "kotoba_kendaraan_oufuku": "round trip",
        "kotoba_kendaraan_kippu": "ticket",
        "kotoba_kendaraan_keiyu": "via (a route)",
        "kotoba_kendaraan_koukuu": "aviation",
        "kotoba_kendaraan_koutsuu": "transportation/traffic",
        "kotoba_kendaraan_konzatsu": "congestion/crowding",
        "kotoba_kendaraan_shihatsu": "first departure",
        "kotoba_kendaraan_shanai": "inside the vehicle",
        "kotoba_kendaraan_juutai": "traffic jam",
        "kotoba_kendaraan_jousha": "boarding (a vehicle)",
        "kotoba_kendaraan_teiki": "commuter pass",
        "kotoba_kendaraan_tetsudou": "railway",
        "kotoba_kendaraan_touchaku": "arrival",
        "kotoba_kendaraan_toho": "on foot",
        "kotoba_kendaraan_manin": "full (of passengers)",
        "kotoba_kendaraan_menkyo": "driver's license",
        "kotoba_kendaraan_kaisatsuguchi": "ticket gate",
        "kotoba_kendaraan_kousoku": "high speed",
        "kotoba_kendaraan_sokudo": "speed",
        "kotoba_kendaraan_unten": "driving/operating",
        "kotoba_kendaraan_jouriku": "landing (making landfall)",
        "kotoba_kendaraan_jisoku": "speed per hour",
        "kotoba_kendaraan_kasoku": "acceleration",
        "kotoba_kendaraan_kasokudo": "rate of acceleration",
        "kotoba_kendaraan_sokuryoku": "speed",
        "kotoba_kendaraan_yusou": "transport (of goods)",
        "kotoba_kendaraan_kisha": "(steam) train",
        "kotoba_kendaraan_kyuukou": "express train",
        "kotoba_kendaraan_tokkyuu": "limited express train",
    },
    "arah_lokasi": {
        "kotoba_arah_lokasi_migi": "right",
        "kotoba_arah_lokasi_hidari": "left",
        "kotoba_arah_lokasi_mae": "front",
        "kotoba_arah_lokasi_ushiro": "behind/back",
        "kotoba_arah_lokasi_ue": "above/top",
        "kotoba_arah_lokasi_shita": "below/under",
        "kotoba_arah_lokasi_naka": "inside",
        "kotoba_arah_lokasi_soto": "outside",
        "kotoba_arah_lokasi_tonari": "next to",
        "kotoba_arah_lokasi_chikaku": "nearby",
        "kotoba_arah_lokasi_tooi": "far",
        "kotoba_arah_lokasi_shuuhen": "surrounding area",
        "kotoba_arah_lokasi_fukin": "nearby/vicinity",
        "kotoba_arah_lokasi_houkou": "direction",
        "kotoba_arah_lokasi_chuushin": "center",
        "kotoba_arah_lokasi_ichi": "position/location",
        "kotoba_arah_lokasi_uchigawa": "inner side",
        "kotoba_arah_lokasi_kitagawa": "north side",
        "kotoba_arah_lokasi_kyori": "distance",
        "kotoba_arah_lokasi_kinjo": "neighborhood",
        "kotoba_arah_lokasi_keshiki": "scenery",
        "kotoba_arah_lokasi_kouhou": "rear direction",
        "kotoba_arah_lokasi_shoumen": "front (facing side)",
        "kotoba_arah_lokasi_sotogawa": "outer side",
        "kotoba_arah_lokasi_chika": "underground",
        "kotoba_arah_lokasi_choujou": "summit/peak",
        "kotoba_arah_lokasi_tochuu": "on the way/midway",
        "kotoba_arah_lokasi_hodou": "sidewalk",
        "kotoba_arah_lokasi_chiheisen": "horizon",
        "kotoba_arah_lokasi_sayuu": "left and right",
        "kotoba_arah_lokasi_genchi": "local site/on-site",
        "kotoba_arah_lokasi_haigo": "behind (someone/something)",
        "kotoba_arah_lokasi_jimoto": "one's hometown/local area",
        "kotoba_arah_lokasi_hantou": "peninsula",
        "kotoba_arah_lokasi_namiki": "row of trees",
        "kotoba_arah_lokasi_sekidou": "equator",
        "kotoba_arah_lokasi_basho": "place/location",
        "kotoba_arah_lokasi_kaigan": "coast/beach",
        "kotoba_arah_lokasi_kaijou": "venue",
        "kotoba_arah_lokasi_kougai": "suburb",
    },
    "negara_kota": {
        "kotoba_negara_kota_nihon": "Japan",
        "kotoba_negara_kota_indoneshia": "Indonesia",
        "kotoba_negara_kota_amerika": "America/United States",
        "kotoba_negara_kota_chuugoku": "China",
        "kotoba_negara_kota_kankoku": "South Korea",
        "kotoba_negara_kota_tai": "Thailand",
        "kotoba_negara_kota_toukyou": "Tokyo",
        "kotoba_negara_kota_oosaka": "Osaka",
        "kotoba_negara_kota_jakaruta": "Jakarta",
        "kotoba_negara_kota_bari": "Bali",
        "kotoba_negara_kota_kyouto": "Kyoto",
        "kotoba_negara_kota_gaikoku": "foreign country",
        "kotoba_negara_kota_gaikokujin": "foreigner",
        "kotoba_negara_kota_chuugokugo": "Mandarin Chinese (language)",
        "kotoba_negara_kota_taiwan": "Taiwan",
        "kotoba_negara_kota_nagoya": "Nagoya",
        "kotoba_negara_kota_inaka": "countryside/hometown village",
        "kotoba_negara_kota_kakuchi": "various places/regions",
        "kotoba_negara_kota_kakkoku": "various countries",
        "kotoba_negara_kota_kikoku": "returning to one's home country",
        "kotoba_negara_kota_kokusai": "international",
        "kotoba_negara_kota_shimin": "citizen",
        "kotoba_negara_kota_shusshin": "origin (hometown/country)",
        "kotoba_negara_kota_taizai": "temporary stay",
        "kotoba_negara_kota_tokai": "city/metropolis",
        "kotoba_negara_kota_ijuu": "migration/relocation",
        "kotoba_negara_kota_gaikou": "diplomacy",
        "kotoba_negara_kota_gikai": "parliament/assembly",
        "kotoba_negara_kota_kaigai": "overseas",
        "kotoba_negara_kota_kokka": "state/nation",
        "kotoba_negara_kota_kokkai": "national diet/parliament",
        "kotoba_negara_kota_kokkyou": "national border",
        "kotoba_negara_kota_kokumin": "citizens/people of a nation",
        "kotoba_negara_kota_zenkoku": "nationwide",
        "kotoba_negara_kota_dokusai": "dictatorship",
        "kotoba_negara_kota_doumei": "alliance",
        "kotoba_negara_kota_fuhai": "corruption/decay",
        "kotoba_negara_kota_funsou": "conflict/dispute",
        "kotoba_negara_kota_fuusa": "blockade/lockdown",
        "kotoba_negara_kota_gunji": "military affairs",
        "kotoba_negara_kota_haishi": "abolition",
        "kotoba_negara_kota_hanei": "prosperity",
        "kotoba_negara_kota_hanran": "rebellion",
        "kotoba_negara_kota_imin": "immigrant/immigration",
        "kotoba_negara_kota_jousei": "situation/state of affairs",
        "kotoba_negara_kota_kainyuu": "intervention",
        "kotoba_negara_kota_kokuou": "king",
        "kotoba_negara_kota_kokuritsu": "national (state-run)",
        "kotoba_negara_kota_kokuseki": "nationality/citizenship",
        "kotoba_negara_kota_touyou": "the East (Asia)",
        "kotoba_negara_kota_jinkou": "population",
        "kotoba_negara_kota_seiji": "politics",
        "kotoba_negara_kota_seiyou": "the West",
        "kotoba_negara_kota_sekai": "world",
        "kotoba_negara_kota_sensou": "war",
    },
    "profesi": {
        "kotoba_profesi_sensei": "teacher/professor",
        "kotoba_profesi_gakusei": "student",
        "kotoba_profesi_kaishain": "company employee",
        "kotoba_profesi_keisatsukan": "police officer",
        "kotoba_profesi_shouboushi": "firefighter",
        "kotoba_profesi_ryourinin": "cook/chef",
        "kotoba_profesi_bengoshi": "lawyer",
        "kotoba_profesi_enjinia": "engineer",
        "kotoba_profesi_nouka": "farmer",
        "kotoba_profesi_untenshu": "driver",
        "kotoba_profesi_shufu": "housewife",
        "kotoba_profesi_kashu": "singer",
        "kotoba_profesi_juuji": "engaging in (an occupation)",
        "kotoba_profesi_tekisei": "aptitude (for a job)",
        "kotoba_profesi_tenshoku": "changing jobs",
        "kotoba_profesi_kengyou": "side job",
        "kotoba_profesi_tsuuyaku": "interpreter",
        "kotoba_profesi_juui": "veterinarian",
        "kotoba_profesi_biyoushi": "hairstylist",
        "kotoba_profesi_kisha": "journalist",
        "kotoba_profesi_gaka": "painter",
        "kotoba_profesi_ishi": "doctor (formal term)",
        "kotoba_profesi_koumuin": "civil servant",
        "kotoba_profesi_kyoushi": "teacher (professional term)",
        "kotoba_profesi_kaikeishi": "accountant",
        "kotoba_profesi_yakuzaishi": "pharmacist",
        "kotoba_profesi_kachou": "section chief",
        "kotoba_profesi_keikan": "police officer (address term)",
        "kotoba_profesi_keisatsu": "police (institution)",
        "kotoba_profesi_sakusha": "author",
        "kotoba_profesi_sakka": "writer",
        "kotoba_profesi_shichou": "mayor",
        "kotoba_profesi_tenchou": "store manager",
        "kotoba_profesi_nougyou": "agriculture",
        "kotoba_profesi_gakusha": "scholar",
        "kotoba_profesi_heishi": "soldier",
        "kotoba_profesi_juugyouin": "employee",
        "kotoba_profesi_shikai": "emcee/host",
        "kotoba_profesi_buchou": "department head",
        "kotoba_profesi_dorobou": "thief",
        "kotoba_profesi_haisha": "dentist",
        "kotoba_profesi_kangofu": "nurse (female)",
        "kotoba_profesi_kouchou": "school principal",
        "kotoba_profesi_shachou": "company president",
        "kotoba_profesi_tenin": "shop clerk",
        "kotoba_profesi_tokoya": "barbershop/barber",
    },
    "keluarga_hubungan": {
        "kotoba_keluarga_hubungan_kazoku": "family",
        "kotoba_keluarga_hubungan_chichi": "(my) father",
        "kotoba_keluarga_hubungan_haha": "(my) mother",
        "kotoba_keluarga_hubungan_ani": "(my) older brother",
        "kotoba_keluarga_hubungan_ane": "(my) older sister",
        "kotoba_keluarga_hubungan_otouto": "younger brother",
        "kotoba_keluarga_hubungan_imouto": "younger sister",
        "kotoba_keluarga_hubungan_sofu": "(my) grandfather",
        "kotoba_keluarga_hubungan_sobo": "(my) grandmother",
        "kotoba_keluarga_hubungan_musuko": "(my) son",
        "kotoba_keluarga_hubungan_musume": "(my) daughter",
        "kotoba_keluarga_hubungan_tomodachi": "friend",
        "kotoba_keluarga_hubungan_koibito": "girlfriend/boyfriend",
        "kotoba_keluarga_hubungan_fuufu": "married couple",
        "kotoba_keluarga_hubungan_soen": "estrangement/losing touch",
        "kotoba_keluarga_hubungan_wakai": "reconciliation",
        "kotoba_keluarga_hubungan_danzetsu": "severance (of a relationship)",
        "kotoba_keluarga_hubungan_kyoudai": "siblings (brothers)",
        "kotoba_keluarga_hubungan_shimai": "sisters",
        "kotoba_keluarga_hubungan_ryoushin": "(both) parents",
        "kotoba_keluarga_hubungan_kodomo": "child (general)",
        "kotoba_keluarga_hubungan_otona": "adult",
        "kotoba_keluarga_hubungan_shinseki": "relative",
        "kotoba_keluarga_hubungan_haiguusha": "spouse (legal term)",
        "kotoba_keluarga_hubungan_ketsuen": "blood relation",
        "kotoba_keluarga_hubungan_dokushin": "unmarried/single",
        "kotoba_keluarga_hubungan_oyako": "parent and child",
        "kotoba_keluarga_hubungan_katei": "household/family",
        "kotoba_keluarga_hubungan_kekkon": "marriage",
        "kotoba_keluarga_hubungan_jikka": "parents' home",
        "kotoba_keluarga_hubungan_tanjou": "birth",
        "kotoba_keluarga_hubungan_nakama": "companion/fellow member",
        "kotoba_keluarga_hubungan_yakuwari": "role",
        "kotoba_keluarga_hubungan_yuujou": "friendship",
        "kotoba_keluarga_hubungan_yuujin": "friend (formal term)",
        "kotoba_keluarga_hubungan_wakamono": "young people",
        "kotoba_keluarga_hubungan_sofubo": "grandparents",
        "kotoba_keluarga_hubungan_aishou": "compatibility (between people)",
        "kotoba_keluarga_hubungan_ikuji": "childcare",
        "kotoba_keluarga_hubungan_chichioya": "father (general term)",
        "kotoba_keluarga_hubungan_danshi": "boy/young man",
        "kotoba_keluarga_hubungan_hahaoya": "mother (general term)",
        "kotoba_keluarga_hubungan_ikka": "one family",
        "kotoba_keluarga_hubungan_mikata": "ally/supporter",
        "kotoba_keluarga_hubungan_seinen": "young man/youth",
        "kotoba_keluarga_hubungan_shoujo": "young girl",
        "kotoba_keluarga_hubungan_shounen": "boy/young man",
        "kotoba_keluarga_hubungan_chuujitsu": "loyal/faithful",
        "kotoba_keluarga_hubungan_doushi": "fellow (people)",
        "kotoba_keluarga_hubungan_chounan": "eldest son",
        "kotoba_keluarga_hubungan_fubo": "father and mother",
        "kotoba_keluarga_hubungan_seishounen": "youth/young people",
        "kotoba_keluarga_hubungan_dansei": "man (formal)",
        "kotoba_keluarga_hubungan_kanai": "my wife",
    },
    "pakaian_aksesori": {
        "kotoba_pakaian_aksesori_fuku": "clothing",
        "kotoba_pakaian_aksesori_shatsu": "shirt",
        "kotoba_pakaian_aksesori_zubon": "trousers/pants",
        "kotoba_pakaian_aksesori_sukaato": "skirt",
        "kotoba_pakaian_aksesori_kutsu": "shoes",
        "kotoba_pakaian_aksesori_boushi": "hat",
        "kotoba_pakaian_aksesori_megane": "glasses",
        "kotoba_pakaian_aksesori_tokei": "watch/clock",
        "kotoba_pakaian_aksesori_baggu": "bag",
        "kotoba_pakaian_aksesori_yubiwa": "ring",
        "kotoba_pakaian_aksesori_nekutai": "necktie",
        "kotoba_pakaian_aksesori_kimono": "kimono (traditional Japanese clothing)",
        "kotoba_pakaian_aksesori_saifu": "wallet",
        "kotoba_pakaian_aksesori_kutsushita": "socks",
        "kotoba_pakaian_aksesori_youfuku": "clothing (Western-style)",
        "kotoba_pakaian_aksesori_tebukuro": "gloves",
        "kotoba_pakaian_aksesori_seifuku": "uniform",
        "kotoba_pakaian_aksesori_fukusou": "attire/outfit",
        "kotoba_pakaian_aksesori_furugi": "used/secondhand clothing",
        "kotoba_pakaian_aksesori_udedokei": "wristwatch",
        "kotoba_pakaian_aksesori_ishou": "costume",
        "kotoba_pakaian_aksesori_kakkou": "appearance/look",
        "kotoba_pakaian_aksesori_momen": "cotton",
        "kotoba_pakaian_aksesori_shitagi": "underwear",
    },
    "hobi_aktivitas": {
        "kotoba_hobi_aktivitas_shumi": "hobby",
        "kotoba_hobi_aktivitas_dokusho": "reading (books)",
        "kotoba_hobi_aktivitas_ongaku": "music",
        "kotoba_hobi_aktivitas_eiga": "movie/film",
        "kotoba_hobi_aktivitas_ryokou": "travel/trip",
        "kotoba_hobi_aktivitas_shashin": "photo/photography",
        "kotoba_hobi_aktivitas_e": "picture/drawing",
        "kotoba_hobi_aktivitas_gaadeningu": "gardening",
        "kotoba_hobi_aktivitas_ryouri": "cooking (as a hobby)",
        "kotoba_hobi_aktivitas_geemu": "game",
        "kotoba_hobi_aktivitas_dansu": "dance",
        "kotoba_hobi_aktivitas_kyanpu": "camping",
        "kotoba_hobi_aktivitas_sentaku": "laundry",
        "kotoba_hobi_aktivitas_souji": "cleaning",
        "kotoba_hobi_aktivitas_kaimono": "shopping",
        "kotoba_hobi_aktivitas_sanpo": "(leisurely) walk",
        "kotoba_hobi_aktivitas_bottou": "absorption/immersion (in an activity)",
        "kotoba_hobi_aktivitas_netchuu": "enthusiasm/being absorbed",
        "kotoba_hobi_aktivitas_juujitsu": "fulfillment",
        "kotoba_hobi_aktivitas_hassan": "release/venting (stress)",
        "kotoba_hobi_aktivitas_ensou": "(musical) performance",
        "kotoba_hobi_aktivitas_kaiga": "painting",
        "kotoba_hobi_aktivitas_katsudou": "activity",
        "kotoba_hobi_aktivitas_kankou": "sightseeing",
        "kotoba_hobi_aktivitas_gaishoku": "eating out",
        "kotoba_hobi_aktivitas_gakki": "musical instrument",
        "kotoba_hobi_aktivitas_geijutsu": "art",
        "kotoba_hobi_aktivitas_sakuhin": "a work (of art)",
        "kotoba_hobi_aktivitas_ryuukou": "trend/fashion",
        "kotoba_hobi_aktivitas_tejina": "magic trick",
        "kotoba_hobi_aktivitas_chousen": "challenge",
        "kotoba_hobi_aktivitas_shuuji": "calligraphy",
        "kotoba_hobi_aktivitas_hanami": "cherry blossom viewing",
        "kotoba_hobi_aktivitas_kenbutsu": "sightseeing/looking around",
        "kotoba_hobi_aktivitas_ningyou": "doll",
        "kotoba_hobi_aktivitas_tenrankai": "exhibition",
    },
    "agama_budaya": {
        "kotoba_agama_budaya_shuukyou": "religion",
        "kotoba_agama_budaya_bukkyou": "Buddhism",
        "kotoba_agama_budaya_shintou": "Shinto (Japan's native religion)",
        "kotoba_agama_budaya_isuramukyou": "Islam",
        "kotoba_agama_budaya_kirisutokyou": "Christianity",
        "kotoba_agama_budaya_hinduukyou": "Hinduism",
        "kotoba_agama_budaya_matsuri": "festival",
        "kotoba_agama_budaya_dentou": "tradition",
        "kotoba_agama_budaya_bunka": "culture",
        "kotoba_agama_budaya_reihai": "worship/religious service",
        "kotoba_agama_budaya_keishou": "passing down (tradition/culture)",
        "kotoba_agama_budaya_gishiki": "ceremony/ritual",
        "kotoba_agama_budaya_shinkou": "faith/belief",
        "kotoba_agama_budaya_shuukan": "custom/habit",
        "kotoba_agama_budaya_jigoku": "hell",
        "kotoba_agama_budaya_jiin": "Buddhist temple",
        "kotoba_agama_budaya_kyoukai": "church",
    },
    "perayaan_haribesar": {
        "kotoba_perayaan_haribesar_oshougatsu": "Japanese New Year",
        "kotoba_perayaan_haribesar_tanjoubi": "birthday",
        "kotoba_perayaan_haribesar_kurisumasu": "Christmas",
        "kotoba_perayaan_haribesar_hinamatsuri": "Hina Matsuri (doll festival, March 3)",
        "kotoba_perayaan_haribesar_tanabata": "Tanabata (star festival, July 7)",
        "kotoba_perayaan_haribesar_obon": "Obon (ancestral spirits festival)",
        "kotoba_perayaan_haribesar_kekkonshiki": "wedding ceremony",
        "kotoba_perayaan_haribesar_oiwai": "celebration",
        "kotoba_perayaan_haribesar_hanabi": "fireworks",
        "kotoba_perayaan_haribesar_ramadan": "Ramadan",
        "kotoba_perayaan_haribesar_barentaindee": "Valentine's Day",
        "kotoba_perayaan_haribesar_shukuga": "celebration/congratulations (formal)",
        "kotoba_perayaan_haribesar_kinenbi": "anniversary",
        "kotoba_perayaan_haribesar_seijinshiki": "coming-of-age ceremony",
        "kotoba_perayaan_haribesar_kinen": "commemoration",
        "kotoba_perayaan_haribesar_shoutai": "invitation",
        "kotoba_perayaan_haribesar_enkai": "banquet/party",
        "kotoba_perayaan_haribesar_kaikai": "opening (of an event)",
    },
    "alat_tulis_sekolah": {
        "kotoba_alat_tulis_sekolah_enpitsu": "pencil",
        "kotoba_alat_tulis_sekolah_keshigomu": "eraser",
        "kotoba_alat_tulis_sekolah_nooto": "notebook",
        "kotoba_alat_tulis_sekolah_hon": "book",
        "kotoba_alat_tulis_sekolah_kaban": "school bag",
        "kotoba_alat_tulis_sekolah_hasami": "scissors",
        "kotoba_alat_tulis_sekolah_nori": "glue",
        "kotoba_alat_tulis_sekolah_jougi": "ruler",
        "kotoba_alat_tulis_sekolah_pen": "pen",
        "kotoba_alat_tulis_sekolah_fude": "(calligraphy) brush",
        "kotoba_alat_tulis_sekolah_kokuban": "blackboard",
        "kotoba_alat_tulis_sekolah_kyoukasho": "textbook",
        "kotoba_alat_tulis_sekolah_jisho": "dictionary",
        "kotoba_alat_tulis_sekolah_shukudai": "homework",
        "kotoba_alat_tulis_sekolah_kanji": "kanji character",
        "kotoba_alat_tulis_sekolah_techou": "notebook/planner",
        "kotoba_alat_tulis_sekolah_hyoushi": "(book) cover",
        "kotoba_alat_tulis_sekolah_youshi": "form paper",
        "kotoba_alat_tulis_sekolah_shomotsu": "book (formal term)",
        "kotoba_alat_tulis_sekolah_tosho": "books (collection, formal term)",
        "kotoba_alat_tulis_sekolah_jiten": "dictionary",
    },
    "mata_pelajaran": {
        "kotoba_mata_pelajaran_kokugo": "Japanese language (school subject)",
        "kotoba_mata_pelajaran_suugaku": "mathematics",
        "kotoba_mata_pelajaran_rika": "science",
        "kotoba_mata_pelajaran_shakai": "social studies",
        "kotoba_mata_pelajaran_eigo": "English",
        "kotoba_mata_pelajaran_nihongo": "Japanese language",
        "kotoba_mata_pelajaran_taiiku": "physical education",
        "kotoba_mata_pelajaran_bijutsu": "fine arts",
        "kotoba_mata_pelajaran_rekishi": "history",
        "kotoba_mata_pelajaran_kagaku": "chemistry",
        "kotoba_mata_pelajaran_senkou": "major/specialization",
        "kotoba_mata_pelajaran_rishuu": "taking a course",
        "kotoba_mata_pelajaran_shingaku": "advancing to higher education",
        "kotoba_mata_pelajaran_keizai": "economics",
        "kotoba_mata_pelajaran_butsuri": "physics",
        "kotoba_mata_pelajaran_seibutsu": "biology",
        "kotoba_mata_pelajaran_chiri": "geography",
        "kotoba_mata_pelajaran_rinri": "ethics",
        "kotoba_mata_pelajaran_tetsugaku": "philosophy",
        "kotoba_mata_pelajaran_kateika": "home economics",
        "kotoba_mata_pelajaran_gakubu": "faculty (university)",
        "kotoba_mata_pelajaran_gakki": "semester",
        "kotoba_mata_pelajaran_kiso": "basics/foundation",
        "kotoba_mata_pelajaran_kihon": "basics/fundamentals",
        "kotoba_mata_pelajaran_gengo": "language",
        "kotoba_mata_pelajaran_kouki": "second semester",
        "kotoba_mata_pelajaran_kougi": "(university) lecture",
        "kotoba_mata_pelajaran_goukaku": "passing (an exam)",
        "kotoba_mata_pelajaran_sansuu": "arithmetic",
        "kotoba_mata_pelajaran_shiken": "exam/test",
        "kotoba_mata_pelajaran_shidou": "guidance",
        "kotoba_mata_pelajaran_juken": "taking an exam",
        "kotoba_mata_pelajaran_seikai": "correct answer",
        "kotoba_mata_pelajaran_tango": "vocabulary word",
        "kotoba_mata_pelajaran_tsuugaku": "commuting to school",
        "kotoba_mata_pelajaran_nyuumon": "introduction (to a subject)",
        "kotoba_mata_pelajaran_hatsuon": "pronunciation",
        "kotoba_mata_pelajaran_moji": "letter/character",
        "kotoba_mata_pelajaran_shinnyuusei": "new student",
        "kotoba_mata_pelajaran_daigakuin": "graduate school",
        "kotoba_mata_pelajaran_anki": "memorization",
        "kotoba_mata_pelajaran_chuugaku": "junior high school",
        "kotoba_mata_pelajaran_gakumon": "scholarship/academics",
        "kotoba_mata_pelajaran_gakushuu": "learning/study",
        "kotoba_mata_pelajaran_gogaku": "foreign language study",
        "kotoba_mata_pelajaran_kamoku": "(curriculum) subject",
        "kotoba_mata_pelajaran_ryuugaku": "studying abroad",
        "kotoba_mata_pelajaran_shougakukin": "scholarship (money)",
        "kotoba_mata_pelajaran_jissen": "practice (real application)",
        "kotoba_mata_pelajaran_kadai": "assignment/issue",
        "kotoba_mata_pelajaran_ensoku": "school excursion",
        "kotoba_mata_pelajaran_gakka": "(university) department",
        "kotoba_mata_pelajaran_gakkai": "academic society",
        "kotoba_mata_pelajaran_gakuryoku": "academic ability",
        "kotoba_mata_pelajaran_jishuu": "self-study",
        "kotoba_mata_pelajaran_jisshuu": "practical training",
        "kotoba_mata_pelajaran_kengaku": "observational visit",
        "kotoba_mata_pelajaran_bungaku": "literature",
        "kotoba_mata_pelajaran_bunpou": "grammar",
        "kotoba_mata_pelajaran_daigakusei": "university student",
        "kotoba_mata_pelajaran_fukushuu": "review (of lessons)",
        "kotoba_mata_pelajaran_honyaku": "translation",
        "kotoba_mata_pelajaran_igaku": "medicine (as a field)",
        "kotoba_mata_pelajaran_kaiwa": "conversation",
        "kotoba_mata_pelajaran_kenkyuu": "research",
        "kotoba_mata_pelajaran_kyouiku": "education",
        "kotoba_mata_pelajaran_nyuugaku": "school enrollment",
        "kotoba_mata_pelajaran_sotsugyou": "graduation",
        "kotoba_mata_pelajaran_yoshuu": "preparing before class",
    },
    "teknologi_gadget": {
        "kotoba_teknologi_gadget_konpyuutaa": "computer",
        "kotoba_teknologi_gadget_sumaho": "smartphone",
        "kotoba_teknologi_gadget_keitai": "mobile phone (general term)",
        "kotoba_teknologi_gadget_intaanetto": "internet",
        "kotoba_teknologi_gadget_denwa": "telephone",
        "kotoba_teknologi_gadget_meeru": "email",
        "kotoba_teknologi_gadget_apuri": "app",
        "kotoba_teknologi_gadget_kamera": "camera",
        "kotoba_teknologi_gadget_juuden": "charging (battery)",
        "kotoba_teknologi_gadget_waifai": "wifi",
        "kotoba_teknologi_gadget_kakushin": "innovation",
        "kotoba_teknologi_gadget_fukyuu": "spread/proliferation (of technology)",
        "kotoba_teknologi_gadget_shinka": "evolution/advancement",
        "kotoba_teknologi_gadget_ouyou": "application (of theory)",
        "kotoba_teknologi_gadget_seimitsu": "precision",
        "kotoba_teknologi_gadget_hanyou": "general-purpose/versatile",
        "kotoba_teknologi_gadget_jouhou": "information",
        "kotoba_teknologi_gadget_shori": "processing",
        "kotoba_teknologi_gadget_koushin": "update",
        "kotoba_teknologi_gadget_setsuzoku": "connection",
        "kotoba_teknologi_gadget_gamen": "screen",
        "kotoba_teknologi_gadget_kinou2": "function",
        "kotoba_teknologi_gadget_sousa": "operation",
        "kotoba_teknologi_gadget_tsuushin": "telecommunications",
        "kotoba_teknologi_gadget_tanmatsu": "terminal/device",
        "kotoba_teknologi_gadget_kensaku": "search",
        "kotoba_teknologi_gadget_hozon": "saving (data)",
        "kotoba_teknologi_gadget_kikai": "machine",
        "kotoba_teknologi_gadget_gijutsu": "technology/skill",
        "kotoba_teknologi_gadget_soushin": "sending (data/email)",
        "kotoba_teknologi_gadget_nyuuryoku": "input (data)",
        "kotoba_teknologi_gadget_buhin": "component/part",
        "kotoba_teknologi_gadget_hatsumei": "invention",
        "kotoba_teknologi_gadget_kyouryoku": "powerful/strong",
        "kotoba_teknologi_gadget_gousei": "synthesis/composite",
        "kotoba_teknologi_gadget_kaihatsu": "development",
        "kotoba_teknologi_gadget_denpou": "telegram",
        "kotoba_teknologi_gadget_kagaku": "science",
        "kotoba_teknologi_gadget_koshou": "breakdown (of a machine)",
    },
    "media_hiburan": {
        "kotoba_media_hiburan_terebi": "television",
        "kotoba_media_hiburan_manga": "comic (manga)",
        "kotoba_media_hiburan_anime": "animation (anime)",
        "kotoba_media_hiburan_shinbun": "newspaper",
        "kotoba_media_hiburan_zasshi": "magazine",
        "kotoba_media_hiburan_rajio": "radio",
        "kotoba_media_hiburan_nyuusu": "news",
        "kotoba_media_hiburan_dorama": "TV drama",
        "kotoba_media_hiburan_yuuchuubu": "YouTube",
        "kotoba_media_hiburan_sns": "social media",
        "kotoba_media_hiburan_ken'etsu": "censorship (media/press)",
        "kotoba_media_hiburan_netsuzou": "fabrication (of news)",
        "kotoba_media_hiburan_inpei": "cover-up/concealment (of facts)",
        "kotoba_media_hiburan_okusoku": "speculation/conjecture",
        "kotoba_media_hiburan_rotei": "exposure (of a flaw)",
        "kotoba_media_hiburan_koukoku": "advertisement",
        "kotoba_media_hiburan_housou": "broadcast",
        "kotoba_media_hiburan_haishin": "streaming/distribution (of content)",
        "kotoba_media_hiburan_eizou": "video footage/visual",
        "kotoba_media_hiburan_kiji": "(news) article",
        "kotoba_media_hiburan_genkou": "manuscript/draft",
        "kotoba_media_hiburan_senden": "advertising/promotion",
        "kotoba_media_hiburan_toujou": "appearance/entrance",
        "kotoba_media_hiburan_monogatari": "story/tale",
        "kotoba_media_hiburan_shuukan": "weekly publication",
        "kotoba_media_hiburan_shasetsu": "editorial (newspaper)",
        "kotoba_media_hiburan_bangumi": "(TV/radio) program",
        "kotoba_media_hiburan_shousetsu": "novel",
    },
    "musim": {
        "kotoba_musim_haru": "spring",
        "kotoba_musim_natsu": "summer",
        "kotoba_musim_aki": "autumn/fall",
        "kotoba_musim_fuyu": "winter",
        "kotoba_musim_kisetsu": "season (general term)",
    },
    "angka_satuan": {
        "kotoba_angka_satuan_ichi": "one (1)",
        "kotoba_angka_satuan_ni": "two (2)",
        "kotoba_angka_satuan_san": "three (3)",
        "kotoba_angka_satuan_yon": "four (4)",
        "kotoba_angka_satuan_go": "five (5)",
        "kotoba_angka_satuan_roku": "six (6)",
        "kotoba_angka_satuan_nana": "seven (7)",
        "kotoba_angka_satuan_hachi": "eight (8)",
        "kotoba_angka_satuan_kyuu": "nine (9)",
        "kotoba_angka_satuan_juu": "ten (10)",
        "kotoba_angka_satuan_hyaku": "hundred (100)",
        "kotoba_angka_satuan_sen": "thousand (1,000)",
        "kotoba_angka_satuan_ichiman": "ten thousand (10,000)",
        "kotoba_angka_satuan_suuji": "number/digit",
        "kotoba_angka_satuan_ninzuu": "number of people",
        "kotoba_angka_satuan_fukusuu": "multiple/plural",
        "kotoba_angka_satuan_ninzuubun": "enough for the number of people",
        "kotoba_angka_satuan_kahansuu": "majority (more than half)",
        "kotoba_angka_satuan_ijou": "or more/above",
        "kotoba_angka_satuan_ika": "or less/below",
    },
    "warna": {
        "kotoba_warna_akai": "red",
        "kotoba_warna_aoi": "blue",
        "kotoba_warna_kiiroi": "yellow",
        "kotoba_warna_midori": "green",
        "kotoba_warna_shiroi": "white",
        "kotoba_warna_kuroi": "black",
        "kotoba_warna_chairo": "brown",
        "kotoba_warna_murasaki": "purple",
        "kotoba_warna_pinku": "pink",
        "kotoba_warna_orenji": "orange",
        "kotoba_warna_haiiro": "gray",
    },
    "bentuk": {
        "kotoba_bentuk_maru": "circle",
        "kotoba_bentuk_shikaku": "square",
        "kotoba_bentuk_sankaku": "triangle",
        "kotoba_bentuk_hoshi": "star (shape)",
        "kotoba_bentuk_haato": "heart (shape)",
        "kotoba_bentuk_katachi": "shape (general term)",
        "kotoba_bentuk_chouhoukei": "rectangle",
        "kotoba_bentuk_daen": "ellipse/oval",
        "kotoba_bentuk_enshuu": "circumference",
        "kotoba_bentuk_hankei": "radius",
    },
    # Add the next category here, e.g.:
    # "pekerjaan_kantor": {
    #     "kotoba_pekerjaan_kantor_...": "...",
    # },
}
