"""
particle_meaning_en.py

Locked source of truth for the English translations of Particle module
content: ParticleEntry.overviewEn, ParticleFunction.titleEn/explanationEn,
SentenceExample.translationEn, ClozeExample.translationEn.
apply_particle_meaning_en.py reads this and patches assets/data/particle_data.json,
so translations live in exactly one place.

Key format (four content kinds share one dict, disambiguated by suffix):
    "{entry_id}|overview"                -> the particle's overview prose
    "{entry_id}|{function_id}|title"     -> a function's title
    "{entry_id}|{function_id}|explanation" -> a function's explanation prose
    "{entry_id}|{function_id}|se{i}"     -> the i-th (0-based) sentenceExample's
                                             translation
    "{entry_id}|{function_id}|cloze{i}"  -> the i-th (0-based) clozeExample's
                                             translation

STATUS: DONE. All 311/311 fields translated (25 overviews, 48 titles,
48 explanations, 144 sentence examples, 46 cloze examples), in one pass
since the whole module is only 25 particles / 48 functions — far smaller
than Kaiwa, so no batch-dump-uniq pipeline was needed, just one direct
pass through the dump.
"""

PARTICLE_MEANING_EN = {
    "particle_ga|overview": "A particle that marks the sentence's subject, either to introduce new information or as the object of certain feeling/ability verbs.",
    "particle_ga|ga_subject|title": "Marks the sentence's subject (especially new information)",
    "particle_ga|ga_subject|explanation": "が marks the sentence's subject, especially when that subject is new information not mentioned before, or when specifically identifying WHO/WHAT does something (answering questions like 'who ~?'). Unlike は, which marks an already-known/discussed topic, が highlights the subject itself.",
    "particle_ga|ga_subject|se0": "There's a cat outside the window.",
    "particle_ga|ga_subject|se1": "Who came?",
    "particle_ga|ga_subject|se2": "It's raining.",
    "particle_ga|ga_subject|cloze0": "There's a cat outside the window.",
    "particle_ga|ga_feeling_ability|title": "Object of feeling/ability/desire verbs and adjectives",
    "particle_ga|ga_feeling_ability|explanation": "が also marks the object of certain verbs/adjectives expressing feeling, ability, or desire — such as わかる (understand), できる (can do), ほしい (want a thing), 好き/嫌い (like/dislike), and 上手/下手 (good/bad at) — even though it functions like an 'object' in meaning, the particle used is still が, not を.",
    "particle_ga|ga_feeling_ability|se0": "I understand Japanese.",
    "particle_ga|ga_feeling_ability|se1": "I want water.",
    "particle_ga|ga_feeling_ability|se2": "She's good at singing.",
    "particle_ga|ga_feeling_ability|cloze0": "I understand Japanese.",
    "particle_o|overview": "A particle that marks the direct object of a transitive verb, and also a place passed through or departed from during movement.",
    "particle_o|o_direct_object|title": "Marks the direct object",
    "particle_o|o_direct_object|explanation": "を marks the direct object of a transitive verb — the thing directly receiving the verb's action.",
    "particle_o|o_direct_object|se0": "I read a book.",
    "particle_o|o_direct_object|se1": "I drink coffee.",
    "particle_o|o_direct_object|se2": "I do my homework.",
    "particle_o|o_direct_object|cloze0": "I read a book.",
    "particle_o|o_path|title": "A place passed through or departed from (movement)",
    "particle_o|o_path|explanation": "を also marks a place passed through or departed from while moving — used with verbs like 出る (exit), 降りる (get off), 歩く (walk), 渡る (cross), and 通る (pass through).",
    "particle_o|o_path|se0": "I leave the house.",
    "particle_o|o_path|se1": "I cross the bridge.",
    "particle_o|o_path|se2": "I get off the bus.",
    "particle_o|o_path|cloze0": "I cross the bridge.",
    "particle_ni|overview": "One of the most versatile particles in Japanese — it marks the location of existence, a destination, a specific time, a recipient, or the agent in a passive sentence, depending on the verb's context.",
    "particle_ni|ni_location|title": "Location of existence",
    "particle_ni|ni_location|explanation": "に marks the location where something/someone exists, used with existence verbs like いる (for living things) and ある (for inanimate objects), as well as 住む (live/reside).",
    "particle_ni|ni_location|se0": "I live in Tokyo.",
    "particle_ni|ni_location|se1": "There's a book on the table.",
    "particle_ni|ni_location|se2": "There's a cat in the park.",
    "particle_ni|ni_location|cloze0": "I live in Tokyo.",
    "particle_ni|ni_direction|title": "Direction/destination of movement",
    "particle_ni|ni_direction|explanation": "に marks the destination of movement, used with motion verbs like 行く (go), 来る (come), and 帰る (return home). へ can often be used interchangeably here with the exact same meaning, especially to emphasize the direction of travel.",
    "particle_ni|ni_direction|se0": "I go to school.",
    "particle_ni|ni_direction|se1": "My friend comes to my house.",
    "particle_ni|ni_direction|se2": "I go home at 7.",
    "particle_ni|ni_time|title": "Specific time",
    "particle_ni|ni_time|explanation": "に marks a specific point in time — an hour, day, date, or year. It's not used for relative time expressions like 今日 (today), 明日 (tomorrow), or きのう (yesterday), which stand alone without a particle.",
    "particle_ni|ni_time|se0": "I wake up at 7.",
    "particle_ni|ni_time|se1": "There's an exam on Monday.",
    "particle_ni|ni_time|se2": "I was born in 2010.",
    "particle_ni|ni_time|cloze0": "I wake up at 7.",
    "particle_ni|ni_recipient|title": "Recipient / indirect object",
    "particle_ni|ni_recipient|explanation": "に marks the recipient of an action — the person targeted by verbs like あげる (give), もらう (receive from), 言う (say to), and 送る (send).",
    "particle_ni|ni_recipient|se0": "I write a letter to my friend.",
    "particle_ni|ni_recipient|se1": "I give a gift to my teacher.",
    "particle_ni|ni_recipient|se2": "I call my mother.",
    "particle_ni|ni_recipient|cloze0": "I call my mother.",
    "particle_ni|ni_passive_agent|title": "Agent in a passive sentence",
    "particle_ni|ni_passive_agent|explanation": "に marks the doer/agent in a passive sentence — who performs the action on the sentence's subject.",
    "particle_ni|ni_passive_agent|se0": "I was praised by my teacher.",
    "particle_ni|ni_passive_agent|se1": "I was bitten by a dog.",
    "particle_ni|ni_passive_agent|se2": "My book was taken by my older brother.",
    "particle_ni|ni_passive_agent|cloze0": "I was praised by my teacher.",
    "particle_de|overview": "A particle that marks the location where an action takes place, the means/method of doing something, the cause, or the total scope/quantity — different from に, which marks the location of existence (not an action).",
    "particle_de|de_location_action|title": "Location where an action takes place",
    "particle_de|de_location_action|explanation": "で marks the place where an action/activity takes place — unlike に, which marks a passive location of existence (with いる/ある), で is used with action verbs like 勉強する (study), 働く (work), and 遊ぶ (play).",
    "particle_de|de_location_action|se0": "I study at the library.",
    "particle_de|de_location_action|se1": "I play at the park.",
    "particle_de|de_location_action|se2": "I work at the office.",
    "particle_de|de_location_action|cloze0": "I study at the library.",
    "particle_de|de_means|title": "Means/method/tool",
    "particle_de|de_means|explanation": "で marks the tool, means, or method of doing something.",
    "particle_de|de_means|se0": "I go by bus.",
    "particle_de|de_means|se1": "I write with a pen.",
    "particle_de|de_means|se2": "I eat with chopsticks.",
    "particle_de|de_means|cloze0": "I write with a pen.",
    "particle_de|de_cause|title": "Cause/reason",
    "particle_de|de_cause|explanation": "で marks the cause or reason for an event, especially when that cause is a single noun (not a full clause — から/ので is used for that).",
    "particle_de|de_cause|se0": "I'm off because I'm sick.",
    "particle_de|de_cause|se1": "The train stopped because of the typhoon.",
    "particle_de|de_cause|se2": "The road is jammed because of an accident.",
    "particle_de|de_cause|cloze0": "I'm off because I'm sick.",
    "particle_de|de_scope_total|title": "Total scope or quantity",
    "particle_de|de_scope_total|explanation": "で also marks the scope (within a certain span) or the total overall quantity — fixed patterns like 全部で (all together), 一人で (alone), and N日で (within N days).",
    "particle_de|de_scope_total|se0": "It's 1000 yen in total.",
    "particle_de|de_scope_total|se1": "It's done within 3 days.",
    "particle_de|de_scope_total|se2": "I go alone.",
    "particle_de|de_scope_total|cloze0": "It's 1000 yen in total.",
    "particle_to|overview": "A particle that marks the person accompanying an action ('together with'), direct/indirect quotation, connects nouns ('and', a complete list), and an automatic condition.",
    "particle_to|to_with|title": "'Together with' (comitative particle)",
    "particle_to|to_with|explanation": "と marks the person accompanying/doing something together with the subject.",
    "particle_to|to_with|se0": "I watch a movie with my friend.",
    "particle_to|to_with|se1": "I travel together with my family.",
    "particle_to|to_with|se2": "I talk with them.",
    "particle_to|to_with|cloze0": "I watch a movie with my friend.",
    "particle_to|to_quotative|title": "Quotation marker ('that ~')",
    "particle_to|to_quotative|explanation": "と marks the content of a direct or indirect quotation, used before verbs like 言う (say), 思う (think), and 聞く (hear).",
    "particle_to|to_quotative|se0": "I think it'll rain tomorrow.",
    "particle_to|to_quotative|se1": "She said, \"I'll go.\"",
    "particle_to|to_quotative|se2": "I heard there's a party.",
    "particle_to|to_quotative|cloze0": "I think it'll rain tomorrow.",
    "particle_to|to_listing|title": "Connecting nouns ('and', a complete list)",
    "particle_to|to_listing|explanation": "と connects two or more nouns as a COMPLETE list (every item is mentioned) — unlike や, which implies a PARTIAL list (there are other items not mentioned).",
    "particle_to|to_listing|se0": "I bought apples and bananas.",
    "particle_to|to_listing|se1": "There's my father and mother.",
    "particle_to|to_listing|se2": "I keep a dog and a cat.",
    "particle_to|to_listing|cloze0": "I bought apples and bananas.",
    "particle_to|to_conditional|title": "Automatic condition ('if...then always')",
    "particle_to|to_conditional|explanation": "と states a condition whose result happens automatically/certainly — suited to natural laws, habits, or directions, but it CANNOT be used for invitations, commands, or requests in the resulting clause.",
    "particle_to|to_conditional|se0": "When spring comes, cherry blossoms bloom.",
    "particle_to|to_conditional|se1": "If you press this button, the door opens.",
    "particle_to|to_conditional|se2": "If you turn right, there's a station.",
    "particle_to|to_conditional|cloze0": "When spring comes, cherry blossoms bloom.",
    "particle_e|overview": "A directional particle that emphasizes the direction of travel toward a place — similar to に's direction function, but へ feels more focused on the DIRECTION of travel than a specific DESTINATION POINT, and is commonly used on letter addresses.",
    "particle_e|e_direction|title": "Destination direction (emphasizing the direction of travel)",
    "particle_e|e_direction|explanation": "へ marks the direction of movement, with emphasis on the DIRECTION of travel itself, not a specific destination point. In many everyday sentences へ can be swapped with に's direction function with an identical meaning — the difference is much more noticeable in formal/written style (e.g. letter addresses, 'To ~へ') than in ordinary conversation.",
    "particle_e|e_direction|se0": "I'm heading toward Tokyo.",
    "particle_e|e_direction|se1": "To: Mr. Tanaka (letter opening)",
    "particle_e|e_direction|se2": "I move forward toward the south.",
    "particle_kara|overview": "A particle that marks a starting point (place or time), a cause/reason, or the original material when its form changes completely.",
    "particle_kara|kara_starting_point|title": "Starting point (place/time)",
    "particle_kara|kara_starting_point|explanation": "から marks a starting point — either a place (where a journey begins) or a time (when something starts). Often paired with まで to mark the end point.",
    "particle_kara|kara_starting_point|se0": "I walk from home to the station.",
    "particle_kara|kara_starting_point|se1": "It starts from 9 o'clock.",
    "particle_kara|kara_starting_point|se2": "I start working from next week.",
    "particle_kara|kara_starting_point|cloze0": "It starts from 9 o'clock.",
    "particle_kara|kara_reason|title": "Cause/reason (after a clause)",
    "particle_kara|kara_reason|explanation": "から marks a cause/reason, used after a complete clause (a verb/adjective in plain or polite form) — unlike で, which can only be used after a single noun as a cause.",
    "particle_kara|kara_reason|se0": "Since I'm tired, I'll rest.",
    "particle_kara|kara_reason|se1": "Since there's no time, let's hurry.",
    "particle_kara|kara_reason|se2": "Since it's dangerous, please be careful.",
    "particle_kara|kara_reason|cloze0": "Since I'm tired, I'll rest.",
    "particle_kara|kara_material_source|title": "Original material (form changes completely)",
    "particle_kara|kara_material_source|explanation": "から marks the original material when its form changes completely into something different — unlike で, which is used for material whose original form is still visible/recognizable.",
    "particle_kara|kara_material_source|se0": "Sake is made from rice.",
    "particle_kara|kara_material_source|se1": "Grapes become wine.",
    "particle_kara|kara_material_source|se2": "Cheese is made from milk.",
    "particle_kara|kara_material_source|cloze0": "Sake is made from rice.",
    "particle_made|overview": "A particle that marks an ending point (place or time) — the natural counterpart of から.",
    "particle_made|made_ending_point|title": "Ending point (place/time)",
    "particle_made|made_ending_point|explanation": "まで marks an ending point — the final destination of a journey, or the time something ends. Often paired with から.",
    "particle_made|made_ending_point|se0": "I walk as far as the station.",
    "particle_made|made_ending_point|se1": "I work until 5 o'clock.",
    "particle_made|made_ending_point|se2": "There's only 1 week left until summer vacation.",
    "particle_made|made_ending_point|cloze0": "I work until 5 o'clock.",
    "particle_no|overview": "A versatile particle that connects two nouns (possession/description), replaces a noun already clear from context, and functions as a casual sentence-final question particle.",
    "particle_no|no_possessive|title": "Possession / connecting nouns",
    "particle_no|no_possessive|explanation": "の connects two nouns, usually expressing possession (noun A belongs to/relates to noun B) or description (noun A is a type/category of noun B).",
    "particle_no|no_possessive|se0": "This is my book.",
    "particle_no|no_possessive|se1": "I'm a Japanese teacher.",
    "particle_no|no_possessive|se2": "That university's library is big.",
    "particle_no|no_possessive|cloze0": "This is my book.",
    "particle_no|no_nominalizer|title": "Replacing a noun ('the one that ~')",
    "particle_no|no_nominalizer|explanation": "の replaces a noun already clear from context, similar to 'the one that ~' in English — used after an adjective or descriptive phrase to avoid repeating the noun.",
    "particle_no|no_nominalizer|se0": "Please give me the red one.",
    "particle_no|no_nominalizer|se1": "This one is mine.",
    "particle_no|no_nominalizer|se2": "I like the big one.",
    "particle_no|no_nominalizer|cloze0": "Please give me the red one.",
    "particle_no|no_casual_question|title": "Casual sentence-final question particle",
    "particle_no|no_casual_question|explanation": "の at the end of a sentence (with a rising intonation) functions as a casual question particle, similar to か but more relaxed, and often used in everyday conversation, especially by women or in familiar settings.",
    "particle_no|no_casual_question|se0": "Where are you going?",
    "particle_no|no_casual_question|se1": "What are you eating?",
    "particle_no|no_casual_question|se2": "Are you okay?",
    "particle_no|no_casual_question|cloze0": "Where are you going?",
    "particle_wa|overview": "A particle that marks the sentence's topic (what's being talked about), and is also used to express a contrast between two things.",
    "particle_wa|wa_topic|title": "Marks the sentence's topic",
    "particle_wa|wa_topic|explanation": "は marks the sentence's topic — the thing being talked about, usually information already known/mentioned before. Unlike が, which highlights the SUBJECT (often new info), は highlights WHAT is being discussed.",
    "particle_wa|wa_topic|se0": "I am a university student.",
    "particle_wa|wa_topic|se1": "This is a book.",
    "particle_wa|wa_topic|se2": "Tokyo is a big city.",
    "particle_wa|wa_topic|cloze0": "I am a university student.",
    "particle_wa|wa_contrast|title": "Expressing contrast",
    "particle_wa|wa_contrast|explanation": "は is also used to emphasize a contrast between two things, usually by mentioning both sides in one sentence or consecutive sentences.",
    "particle_wa|wa_contrast|se0": "I like fish, but I don't like meat.",
    "particle_wa|wa_contrast|se1": "I can speak English, but I can't speak French.",
    "particle_wa|wa_contrast|se2": "It's cold today, but it might be warm tomorrow.",
    "particle_wa|wa_contrast|cloze0": "I like fish, but I don't like meat.",
    "particle_mo|overview": "A particle meaning 'also/too', emphasizing a surprisingly large amount, or (with a question word + negative form) expressing 'not a single one'.",
    "particle_mo|mo_also|title": "'Also/too' (adding something the same)",
    "particle_mo|mo_also|explanation": "も replaces は/が/を to express 'also/too' — this subject/topic is the same as what was mentioned before.",
    "particle_mo|mo_also|se0": "I'm also a university student.",
    "particle_mo|mo_also|se1": "They'll come too.",
    "particle_mo|mo_also|se2": "This is good too.",
    "particle_mo|mo_also|cloze0": "I'm also a university student.",
    "particle_mo|mo_emphasis_quantity|title": "Emphasizing a surprising quantity/degree",
    "particle_mo|mo_emphasis_quantity|explanation": "も after a number/quantity emphasizes that the amount feels large/surprising to the speaker — similar to 'as much as' or 'even' in English.",
    "particle_mo|mo_emphasis_quantity|se0": "I waited as long as 3 hours!",
    "particle_mo|mo_emphasis_quantity|se1": "I ate as many as 10 pieces!",
    "particle_mo|mo_emphasis_quantity|se2": "It costs as much as 10,000 yen!",
    "particle_mo|mo_emphasis_quantity|cloze0": "I waited as long as 3 hours!",
    "particle_mo|mo_double_negative|title": "'Not a single one' (question word + も + negative)",
    "particle_mo|mo_double_negative|explanation": "A question word (だれ/なに/どこ) + も, followed by a negative form, expresses total negation — 'not a single one/not at all'.",
    "particle_mo|mo_double_negative|se0": "Not a single person came.",
    "particle_mo|mo_double_negative|se1": "I didn't eat anything.",
    "particle_mo|mo_double_negative|se2": "I didn't go anywhere.",
    "particle_mo|mo_double_negative|cloze0": "Not a single person came.",
    "particle_shika|overview": "A particle meaning 'only' that must be followed by a negative form, giving the impression of 'only ~ (and that's not enough/lacking)'.",
    "particle_shika|shika_only_negative|title": "'Only' (must take negative form)",
    "particle_shika|shika_only_negative|explanation": "しか is always followed by a negative predicate, giving the nuance that the amount/choice feels lacking or insufficient — unlike だけ, which is neutral and can be used in both positive and negative sentences.",
    "particle_shika|shika_only_negative|se0": "I only have 1000 yen (and that's not enough).",
    "particle_shika|shika_only_negative|se1": "I only understand this (nothing else).",
    "particle_shika|shika_only_negative|se2": "I only eat vegetables (nothing else).",
    "particle_shika|shika_only_negative|cloze0": "I only have 1000 yen (and that's not enough).",
    "particle_dake|overview": "A neutral particle meaning 'only' — can be used in both positive and negative sentences, without the sense of lacking that しか carries.",
    "particle_dake|dake_only_neutral|title": "'Only' (neutral)",
    "particle_dake|dake_only_neutral|explanation": "だけ expresses 'only/just' neutrally, without the sense of insufficiency that しか carries — it can be freely used in both positive and negative sentences.",
    "particle_dake|dake_only_neutral|se0": "Just this is enough.",
    "particle_dake|dake_only_neutral|se1": "I'm only off on Saturdays.",
    "particle_dake|dake_only_neutral|se2": "I only eat a little.",
    "particle_dake|dake_only_neutral|cloze0": "I'm only off on Saturdays.",
    "particle_kurai|overview": "A particle marking an approximate amount or degree ('about/roughly') — also often pronounced/written ぐらい, especially after a word ending in a voiced sound.",
    "particle_kurai|kurai_approximation|title": "Approximate amount/degree",
    "particle_kurai|kurai_approximation|explanation": "くらい (or ぐらい) marks that the stated amount/time is an approximation, not an exact number.",
    "particle_kurai|kurai_approximation|se0": "I waited about 10 minutes.",
    "particle_kurai|kurai_approximation|se1": "It takes roughly 1 hour.",
    "particle_kurai|kurai_approximation|se2": "About 100 people came.",
    "particle_kurai|kurai_approximation|cloze0": "I waited about 10 minutes.",
    "particle_bakari|overview": "A particle emphasizing an excessive proportion ('nothing but, only that') with a somewhat negative nuance, or (after the ~た verb form) expressing an action that just finished.",
    "particle_bakari|bakari_excessive_proportion|title": "'Nothing but' (excessive proportion)",
    "particle_bakari|bakari_excessive_proportion|explanation": "ばかり emphasizes that someone does/uses something excessively or constantly, usually with a somewhat critical nuance.",
    "particle_bakari|bakari_excessive_proportion|se0": "He does nothing but play games.",
    "particle_bakari|bakari_excessive_proportion|se1": "Please don't eat nothing but snacks.",
    "particle_bakari|bakari_excessive_proportion|se2": "She does nothing but complain.",
    "particle_bakari|bakari_excessive_proportion|cloze0": "He does nothing but play games.",
    "particle_bakari|bakari_just_happened|title": "'Just now' (V-た + ばかり)",
    "particle_bakari|bakari_just_happened|explanation": "The ~た verb form + ばかり expresses that an action just finished being done.",
    "particle_bakari|bakari_just_happened|se0": "I just arrived.",
    "particle_bakari|bakari_just_happened|se1": "I just woke up.",
    "particle_bakari|bakari_just_happened|se2": "I just bought this book.",
    "particle_bakari|bakari_just_happened|cloze0": "I just arrived.",
    "particle_demo|overview": "A particle emphasizing an extreme example ('even') or offering one of several unspecified options ('~ or something like that'). Different from the conjunction でも ('but') that stands alone at the start of a sentence — that's not a particle, so it isn't covered here.",
    "particle_demo|demo_even|title": "'Even' (emphasizing an extreme example)",
    "particle_demo|demo_even|explanation": "Noun + でも emphasizes that the mentioned example is an extreme case — if even that applies, other things surely apply too.",
    "particle_demo|demo_even|se0": "Even a small child can do it.",
    "particle_demo|demo_even|se1": "Even a teacher doesn't understand some things.",
    "particle_demo|demo_even|se2": "Even I sometimes make mistakes.",
    "particle_demo|demo_even|cloze0": "Even a small child can do it.",
    "particle_demo|demo_or_something|title": "'~ or something like that' (offering one option)",
    "particle_demo|demo_or_something|explanation": "Noun + でも offers one example as one of several unspecified options, often used to casually invite someone.",
    "particle_demo|demo_or_something|se0": "Want some tea or something?",
    "particle_demo|demo_or_something|se1": "Let's watch a movie or something.",
    "particle_demo|demo_or_something|se2": "I'll rest while listening to music or something.",
    "particle_demo|demo_or_something|cloze0": "Want some tea or something?",
    "particle_ya|overview": "A particle that connects nouns as a PARTIAL list (incomplete, implying there are other items) — the contrasting counterpart of と, which implies a complete list.",
    "particle_ya|ya_partial_listing|title": "'And' (partial, incomplete list)",
    "particle_ya|ya_partial_listing|explanation": "や connects nouns as representative examples — implying there are other items not mentioned, unlike と, which implies every item has been mentioned.",
    "particle_ya|ya_partial_listing|se0": "There's a book, a notebook, and other things on the table.",
    "particle_ya|ya_partial_listing|se1": "I like apples, bananas, and things like that.",
    "particle_ya|ya_partial_listing|se2": "There's a dog, a cat, and other animals in the park.",
    "particle_ya|ya_partial_listing|cloze0": "There's a book, a notebook, and other things on the table.",
    "particle_ka|overview": "A sentence-final question particle (neutral/formal register), and also an 'or' particle when listing options.",
    "particle_ka|ka_question|title": "Formal sentence-final question particle",
    "particle_ka|ka_question|explanation": "か at the end of a sentence marks it as a question, whether yes/no or a question word question — a neutral register, suitable to use with anyone.",
    "particle_ka|ka_question|se0": "How are you?",
    "particle_ka|ka_question|se1": "What's this?",
    "particle_ka|ka_question|se2": "Will you come tomorrow?",
    "particle_ka|ka_question|cloze0": "How are you?",
    "particle_ka|ka_question|cloze1": "What's this?",
    "particle_ka|ka_or|title": "'~ or ~' (listing options)",
    "particle_ka|ka_or|explanation": "か between two nouns/clauses expresses an 'or' choice.",
    "particle_ka|ka_or|se0": "I want to keep a dog or a cat.",
    "particle_ka|ka_or|se1": "Please give me coffee or tea.",
    "particle_ka|ka_or|se2": "I'll go on Saturday or Sunday.",
    "particle_ka|ka_or|cloze0": "I want to keep a dog or a cat.",
    "particle_ka|ka_or|cloze1": "Please give me coffee or tea.",
    "particle_ne|overview": "A particle asking for agreement or confirmation from the listener — similar to 'right?' in English.",
    "particle_ne|ne_agreement|title": "Asking for agreement/confirmation",
    "particle_ne|ne_agreement|explanation": "ね at the end of a sentence invites the listener to agree or confirm, often used when sharing the same feeling/observation.",
    "particle_ne|ne_agreement|se0": "Nice weather, isn't it?",
    "particle_ne|ne_agreement|se1": "This song is good, isn't it?",
    "particle_ne|ne_agreement|se2": "Tiring, right?",
    "particle_ne|ne_agreement|cloze0": "Nice weather, isn't it?",
    "particle_ne|ne_agreement|cloze1": "Tiring, right?",
    "particle_yo|overview": "A particle that asserts or informs, especially something the listener may not know yet — similar to '...you know!' in English.",
    "particle_yo|yo_informing|title": "Asserting/informing new information",
    "particle_yo|yo_informing|explanation": "よ at the end of a sentence emphasizes that the speaker is telling the listener something they may not know — unlike ね, which invites agreement on something ALREADY mutually known.",
    "particle_yo|yo_informing|se0": "It's already 7 o'clock, you know!",
    "particle_yo|yo_informing|se1": "This restaurant is good, you know!",
    "particle_yo|yo_informing|se2": "That's dangerous, you know!",
    "particle_yo|yo_informing|cloze0": "It's already 7 o'clock, you know!",
    "particle_yo|yo_informing|cloze1": "That's dangerous, you know!",
    "particle_na|overview": "A casual/blunt prohibition particle (dictionary-form verb + な), and also a casual, masculine-leaning assertion similar to ね/よ but blunter.",
    "particle_na|na_prohibition|title": "Casual prohibition ('don't ~!')",
    "particle_na|na_prohibition|explanation": "Dictionary-form verb + な is a direct and blunt prohibition — much harsher than ~ないでください, suited for close friends or urgent situations, not for someone you should show respect to.",
    "particle_na|na_prohibition|se0": "Don't worry!",
    "particle_na|na_prohibition|se1": "Don't go!",
    "particle_na|na_prohibition|se2": "Don't touch!",
    "particle_na|na_prohibition|cloze0": "Don't worry!",
    "particle_na|na_prohibition|cloze1": "Don't touch!",
    "particle_na|na_casual_emphasis|title": "Casual, masculine-leaning assertion",
    "particle_na|na_casual_emphasis|explanation": "な can also assert the speaker's own feeling, similar to ね's function but feeling blunter/more masculine — the choice of な here is purely a matter of speech register (not a translatable meaning difference), so this function isn't used for quiz questions.",
    "particle_na|na_casual_emphasis|se0": "That's tiring, isn't it.",
    "particle_na|na_casual_emphasis|se1": "That's really heavy rain, isn't it.",
    "particle_na|na_casual_emphasis|se2": "That makes me miss it, doesn't it.",
    "particle_wa2|overview": "A soft assertion particle traditionally associated with a feminine speech style.",
    "particle_wa2|wa2_feminine_emphasis|title": "Soft assertion, feminine speech style",
    "particle_wa2|wa2_feminine_emphasis|explanation": "わ at the end of a sentence gives a soft, assertive impression, traditionally associated with women's speech style. Since what sets it apart is purely the speaker's register/gender (not the sentence's meaning), this function isn't used for quiz questions — there's no way to translate it differently from a neutral equivalent like よ/ね.",
    "particle_wa2|wa2_feminine_emphasis|se0": "That's really nice.",
    "particle_wa2|wa2_feminine_emphasis|se1": "I'll head home first.",
    "particle_wa2|wa2_feminine_emphasis|se2": "I think so too.",
    "particle_zo|overview": "A strongly assertive particle with a masculine, rough nuance, often used talking to oneself or to close friends.",
    "particle_zo|zo_masculine_emphasis|title": "Strong assertion, masculine speech style",
    "particle_zo|zo_masculine_emphasis|explanation": "ぞ at the end of a sentence asserts something strongly, with a rough/masculine nuance — commonly used when talking to oneself (e.g. psyching yourself up) or with very close friends. Same as わ, what sets it apart is purely the speaker's register, so this function isn't used for quiz questions.",
    "particle_zo|zo_masculine_emphasis|se0": "Let's go!",
    "particle_zo|zo_masculine_emphasis|se1": "Alright, let's get it done!",
    "particle_zo|zo_masculine_emphasis|se2": "I won't lose!",
    "particle_ze|overview": "A casual, masculine-leaning assertion particle, similar to ぞ but feeling a bit more relaxed/friendly, commonly used with close friends.",
    "particle_ze|ze_casual_masculine_emphasis|title": "Casual assertion, casual masculine speech style",
    "particle_ze|ze_casual_masculine_emphasis|explanation": "ぜ asserts something in a relaxed, familiar tone, masculine-leaning but friendlier/less rough than ぞ — commonly used when inviting a close friend. What sets it apart is purely the speaker's register, so this function isn't used for quiz questions.",
    "particle_ze|ze_casual_masculine_emphasis|se0": "Let's do our best!",
    "particle_ze|ze_casual_masculine_emphasis|se1": "Let's go.",
    "particle_ze|ze_casual_masculine_emphasis|se2": "Let's enjoy it!",
    "particle_sa|overview": "A casual assertion particle, often masculine-leaning, asserting something as if it's obvious/natural.",
    "particle_sa|sa_casual_assertion|title": "Casual assertion, asserting the obvious",
    "particle_sa|sa_casual_assertion|explanation": "さ at the end of a sentence asserts something in a relaxed tone, as if it's already obvious/natural and not worth overthinking. What sets it apart is purely the speaker's register, so this function isn't used for quiz questions.",
    "particle_sa|sa_casual_assertion|se0": "Relax, it's fine.",
    "particle_sa|sa_casual_assertion|se1": "It's easy.",
    "particle_sa|sa_casual_assertion|se2": "That's just how it is.",
}
